### ISSUE TITLE
Penance (s2) set bonus bug

### ISSUE THREAD

**Issue by Lujansh** [Duskhaven/Bug-Reports#1003]
The warrior 5p bonus from s2 dps set doesn't reduce Whirlwind rage cost by 10 as stated, it's reduced by 5, resulting in a total of 20 rage cost (down from 25)

![image](https://user-images.githubusercontent.com/76747701/232251245-9321a3b1-f9ec-44a6-ab2d-21013cc0bded.png)

**Comment by Duskhaven** [comment]
Update your patch
