### ISSUE TITLE
Death Knight starting zone

### ISSUE THREAD

**Issue by Viertis** [Duskhaven/Bug-Reports#1012]
Soul Feast Quest. If you die and are spawned are the near by GY you can kill the wandering souls outside but you cannot loot them. The game is reading that they are too far away. Also you cannot get back into the Crypt at this time either making it where you cannot move forward with the DK.

**Comment by Duskhaven** [comment]
The Quest can be done at a later point, you have to use the Death Gate to complete the DK Questline.
