### ISSUE TITLE
Mythic+ is Inconvenient, QOL suggestion

### ISSUE THREAD

**Issue by MichaelCrow** [Duskhaven/Bug-Reports#1013]
When you complete a mythic plus, you get phased back to the original dungeon, this is very inconvenient and shitty if you plan on doing more mythics in the same dungeon or your hearthstone is on cooldown. So I propose on mythic+ turn ins, it teleports you outside of the instance you're currently in or spawns portals to stormwind and orgrimmar by the font gameobject. 

This will make it where you dont need to hearth or run out of dungeons everytime you want to do another mythic or worse, if everyone leaves the group after 1 minute you get bugged out because it continuously teleports you to the graveyard even while you're alive.

**Comment by Duskhaven** [comment]
This belongs in the suggestion channel on discord.
