### ISSUE TITLE
improved tracking

### ISSUE THREAD

**Issue by koskeer** [Duskhaven/Bug-Reports#1015]
hunters improved tracking talent says it gives 5% dmg on the types listed above
it doesnt seem to work 
does it increase the dmg on the specific type that i have selected or on all of the types listed on the description

**Comment by yoyosan** [comment]
@Duskhaven can you please clarify this since it's close to impossible to test.

**Comment by Duskhaven** [comment]
It only increases the damage against the tracked type.

Ex. 5% increased damage to giants if you attack one, but not to other creature types
