### ISSUE TITLE
Natural Protection & Dreamgrove's Blessing bugged.

### ISSUE THREAD

**Issue by Kebful** [Duskhaven/Bug-Reports#1017]
https://vimeo.com/818045068

Natural protection and Dreamgrove's blessing aren't working correctly. it only procs on other targets via healing touch and even then, the buff only applies to yourself.  When targeting yourself it applies from both healing touch and regrowth. 

I think Dreamgrove's blessing is broken because from the way it words the buff natural protection should be applied to the target affected by healing touch and regrowth and as shown above in the video it does not apply to anyone but yourself. 

-Submission by Snooze

**Comment by Duskhaven** [comment]
Talent doesnt exist anymore.
