### ISSUE TITLE
Transcendence set (T2 Priest original) 5set doesn't work  (mana restore)

### ISSUE THREAD

**Issue by Shadzer** [Duskhaven/Bug-Reports#1019]
The 5set for Transcendence set states: 
1. When struck in melee there is a 50% chance you will Fade for 4 sec
2. Your spells have a Chance to grant 120 mana

The first part works when you get hit. I have raided and spammed heals over 3 hours and I haven't gotten a single mana proc from this set. Can't find anything in the logs or in my Mana restored meters.

![image](https://user-images.githubusercontent.com/129836951/232398068-1f7f6219-7129-4cc5-bccb-f7d1f2beda30.png)

**Comment by Duskhaven** [comment]
The mana restore only works for damaging spells

**Comment by Shadzer** [comment]
> 

If it only works for damaging spells, make it work for healing spells as well please.
