### ISSUE TITLE
Report 5 bonus tier cloth caster S2 and some feedback.

### ISSUE THREAD

**Issue by Elylenai** [Duskhaven/Bug-Reports#1023]
Hello, ty for your time.

Bug:
The demonfang tier (not the S2 one) 4 bonus works 50%. It procs 15SP (10s) also but I've never seen it proc a single time. Maybe monk dps proc it? If it works well, it just has a low % or it doesn't even displays in buff section.

Feedback:
The S2 tier mage feels very underwhelming. 35SP for 15s on mana gem usage would be better in the first tier, and the haste one would be better in S2 one (just saying). I consider 4% haste on proc to be better than plain SP.
Also, the S2 mage tier bonus (5 parts) is just plain crit chance while other classes get:
- Mana cost reduction of SB by 15%. 
- 5% increased dmg by chance (proc). proc'd by inmolate and unstable afflix.
- PW:S grants 26sp 5s
- SW:P grants 35sp for the next skill.
Mages: Plain crit chance, and not even specified (I think its 5% crit). For a 5 tier bonus it feels very underwhelming.

T2 8bonus set: Frostbolt and fireball procs it, but for arcane, arcane missiles? That's kinda unfair. Hard hitting arcane missiles procs by chance. And the 8bonus set procs by chance too. Fire and frost will proc 8 bonus set easier than arcane. I hope you have it in mind too.

I have 3 M+ S2 token which I don't use because the conqueror token set is way better despite S2 set having better stats. I think it should be the other way around but maybe I'm mistaken because balance issues in high end.

I hope you consider it and if you don't, can you explain how does S2 M+ token set is balanced for mages, please?

Again, tyvm for your time and good job.

**Comment by Chromie-the-gnome** [comment]
If you tested the +8 s2 set, 3 set is actually 225 spellpower, not 35.
Its still a super underhwelming set.  Considering it has no  hit and less spellpower than raid pieces making it ass for mage.

I do agree t2 8bonus set guts arcane, but that 8bonus set is not something you really go for since it has an ICD (Unless its taken out here)

Also 5 crit  is a great bonus, just locked under a 5 set on a really bad set.

**Comment by Elylenai** [comment]
> If you tested the +8 s2 set, 3 set is actually 225 spellpower, not 35. Its still a super underhwelming set. Considering it has no hit and less spellpower than raid pieces making it ass for mage.
> _I think you didn't read or you did a speedrun, which makes communication incomplete. 3 set of S2, NOT T2, is 35SP on mana gem usage. I repeat, S2, NOT T2._ 
> I do agree t2 8bonus set guts arcane, but that 8bonus set is not something you really go for since it has an ICD (Unless its taken out here)
> _It's obv arcane gets hindered by having a chance on arcane missiles (you can't even 5/5 MISSILE barrage unless you sacrifice damage or haste talents)._
> Also 5 crit is a great bonus, just locked under a 5 set on a really bad set.
> _It is a great bonus, for a 3 set piece of S2, not for a 5 set piece of S2. Conq. tokens have way better bonuses than S2+ tier and that feels weird._
