### ISSUE TITLE
Blizzard Cast Cut Short

### ISSUE THREAD

**Issue by Kesrai** [Duskhaven/Bug-Reports#1024]
I've been noticing that when I'm casting blizzard the cast is cut short randomly and I'm not moving or taking damage. I believe there is correlation with Paladin's Sanctified Consecration, because I see that appear on my screen and then my blizzard cast is cut short.

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/922
