### ISSUE TITLE
I got phased into the normal Black Temple raid as DH

### ISSUE THREAD

**Issue by GhostBE2003** [Duskhaven/Bug-Reports#1027]
So i got inside Black Temple with everything being blocked off as it should be, but then i abandoned a M+ quest and it phased me inside the actual raid, i can see illidari blood lords and can attack them 
![proof 2](https://user-images.githubusercontent.com/131063948/232618770-3bd5fafb-c5e9-4f78-b893-87d9f228618d.PNG)
![proof 3](https://user-images.githubusercontent.com/131063948/232618822-53326056-d940-45c2-b395-0f4c5ec8f493.PNG)
![proof](https://user-images.githubusercontent.com/131063948/232618848-4ed57f89-d0d0-416f-8a1b-976f30c5cd33.PNG)

**Comment by Duskhaven** [comment]
Relogging phases you back.
