### ISSUE TITLE
Arcane Potency Talent Bug

### ISSUE THREAD

**Issue by Sokks-Sturges** [Duskhaven/Bug-Reports#1031]
![image](https://user-images.githubusercontent.com/127478138/232702244-c752af48-5c29-402c-8c07-150abd325b13.png)
Pic 1 Ref: Arcane Blast, a spell currently not granting Arcane Potency when Clearcasting is granted.

![image](https://user-images.githubusercontent.com/127478138/232702615-c7273173-e763-4bd3-8e23-3587912d52ce.png)
Pic 2 Ref: Arcane Missiles, a spell currently granting Arcane Potency when Clearcasting is granted as intended.

Arcane Potency is the talent in the Arcane Tree that grants an additional 30% critical strike chance on the next spell after gaining Clearcasting or gaining Presence of Mind. At the moment the talent is bugged to only grant the buff when certain Spells grant the Clearcasting buff state.

Spells tested that **do not** grant Arcane Potency when giving Clearcasting:

• Arcane Explosion
• Flamestrike
• Frost Nova
• Arcane Blast
• Scorch

Spells tested that correctly grant Arcane Potency when Clearcasting is granted:

• Blizzard
• Arcane Missiles
• Ice Lance
• Frostbolt
• Frostfire Bolt 
• Fireball

**Comment by Duskhaven** [comment]
Fixed.
