### ISSUE TITLE
High Justice Grimstone disappears after first set of adds

### ISSUE THREAD

**Issue by zahoogaming** [Duskhaven/Bug-Reports#1034]
Hey I tried to solo BRD to farm savage gladiator chest, the event starts normally and High Justice Grimstone walks up to the first door and releases the first set of adds but once I kill them he walks up to a second door giving his speech about how I though I was done already but he never opens the second door for the boss to show up

**Comment by Duskhaven** [comment]
Killing the adds too fast causes it to happen sometimes.
