### ISSUE TITLE
Arcanite dragonling doesn't attack targets reliably and doesn't cast its two abilities

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1035]
Arcanite dragonling (summon of the engineering trinket) is not casting its abilities Flame Breath and Flame Buffet.

Also, it is very hard getting it to attack something at all. It ignores target dummies completely.

Finally, it doesnt show it's damage both in meters or as scrolling text. It is missing the "guardian of xxx".

**Comment by Duskhaven** [comment]
The Dragonling now correctly uses his abilities.
