### ISSUE TITLE
Penance S2 set bonus 5/5 broken for warriors.

### ISSUE THREAD

**Issue by Eccies** [Duskhaven/Bug-Reports#1037]
The S2 Penance set says :

5/5 set bonus : Whirlwind cost reduced by 10 rage.

In reality it reduces Whirlwind cost by 5 after equipping it. 
![image](https://user-images.githubusercontent.com/87206308/232802597-faf7b915-906f-4846-99e8-dc16c517ef2f.png)

**Comment by Duskhaven** [comment]
Tooltip is updated to the correct value after patch update
