### ISSUE TITLE
Charger Mount Cost is still 261g for human paladins

### ISSUE THREAD

**Issue by TechBlue0625** [Duskhaven/Bug-Reports#1038]
There was a post about two weeks ago that said that the charger mount was "fixed", but I still had to buy the 100% mount riding (255g) and the mount which was 261g. Am I going to be able to get my gold back since this error was never fixed? Character name is HolyPally

Old "closed" Post below:
https://github.com/Duskhaven/Bug-Reports/issues/583#event-8905574433

**Comment by Kebful** [comment]
![image](https://user-images.githubusercontent.com/127319823/232818511-060cb284-e0d5-4e95-a9ee-6dfbe4887f2f.png)
Issue was resolved on server restart.

**Comment by TechBlue0625** [comment]
Shouldn't that have been fixed three weeks ago when they said that they would fix this issue? I would love my gold back 253g is a good amount of gold especially in vanilla.
