### ISSUE TITLE
Black Screen Fullscreen

### ISSUE THREAD

**Issue by Svare94** [Duskhaven/Bug-Reports#1040]
Hi i tried to go windowed mode ingame, didnt work just got a black screen, reopened the game, and now it just stayes black until i put it in windowed but then i just get a crash ingame instead.

**Comment by Feardonald** [comment]
This is not a server related bug.

Known issue for all wotlk 3.3.5a clients.

Go to your WTF folder > Open Config > Add these lines SET gxWindow "1" SET gxMaximize "1"
