### ISSUE TITLE
T2 Warrior set bonus is not working as intended 

### ISSUE THREAD

**Issue by Eccies** [Duskhaven/Bug-Reports#1043]
The Warrior T2 Set bonus for 2/8 , is supposed to add 14 expertise rating.

it only show + 14 expertise , and it doesn't add up properly somehow. 

Seems like the +14 expertise gives less than 14 expertise raiting.

**Comment by Feardonald** [comment]
The conversion for expertise isn't 1 to 1.

The 2set is giving 17 expertise rating = +6 expertise > 1.50%
**EDIT:** We're actually gaining 3 expertise rating too much.

Similar as with defense rating where the conversion isn't 1 to 1.

Best Regards
Genjuro

**Comment by Feardonald** [comment]
All though the set bonus set does say Expertise, not Expertise Rating.

I could be wrong, depending on what Noxx intended.

**Comment by Duskhaven** [comment]
Genjuro explained how Expertise is handled.

**Comment by Eccies** [comment]
Indeed but that doesn't fix the issue : 
 I am litterally taking off 14 expertise rating ( ring ) , and adding 5  exp rating ( bracer t2 ) + 14 exp ( t2 set bonus ) 

14 expertise rating < 5 expertise rating + 14 expertise

Am i wrong ?

**Comment by Dova14** [comment]
Tier 2 set bonus is Expertise rating, not raw expertise.  as genjuro explained.

**Comment by Eccies** [comment]
Even then i should get more : i took off 14 expertise rating from a ring, and added 14 +5  exp rating from t2 bracers and boots 
How do i end up with less expertise then ? 

IS 14 higher than 19 ? 

Is Math off or i am have error ?

**Comment by Eccies** [comment]
I will just forfeit to the idea that it might be a visual bug

**Comment by LVCJS** [comment]
Unequip all your T2 pieces and reequip them. You most likely had a duplicate set that you unequipped, but until you fully unequip the 2set bonus, you won't get those bonuses. Not sure if this is what you're referring to exactly as your explanations are a bit over the place, but try this and see if it fixes your missing expertise.

**Comment by Eccies** [comment]
Expertise is broken.

**Comment by Wheemix** [comment]
Is it intended behaviour for S2 3/5 bonus to not stack with T2 2/8 bonus that both give +14 expertise rating per tooltip or +17 expertise rating in reality? Because that is not obvious at all, I expected them to stack.
