### ISSUE TITLE
Strathholm undead RDF queue gave my entire party dungeon delver debuff

### ISSUE THREAD

**Issue by Dwordis** [Duskhaven/Bug-Reports#1044]
![image](https://user-images.githubusercontent.com/48196367/232878934-6ff82a25-1f3b-4e34-8ced-1a54fb81708e.png)

**Comment by Dwordis** [comment]
also it states that it reduces exp gains by 40% but thats a lie. I was getting 20ish exp a kill now without the debuff im getting 150ish. Does that sound like 40%?

**Comment by Duskhaven** [comment]
Make sure to not queue for specific

**Comment by Dwordis** [comment]
Bro you didnt evem read the title... We queued RDF
