### ISSUE TITLE
Clamette Magnifique putting all vendor water on 1 min cd

### ISSUE THREAD

**Issue by Aquarion-Duskhaven** [Duskhaven/Bug-Reports#1045]
As title says, Clamette Magnifique is putting all vendor water on 1 min cd.

Very annoying during raids.
Tested with Refreshing Spring Water, Ice Cold Milk, Melon Juice, Sweet Nectar, Morning Glory Dew, Filtered Draenic Water.

Haven't tested with Conjured Mage Water, or Conjured table food/water.

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/640
