### ISSUE TITLE
Strathholm undead RDF queue gave my entire party dungeon delver debuff

### ISSUE THREAD

**Issue by Dwordis** [Duskhaven/Bug-Reports#1047]
Reopening because you guys dont read titles.
![image](https://user-images.githubusercontent.com/48196367/232883979-c476ba21-3214-441e-945d-dddb33f2ffde.png)

**Comment by Duskhaven** [comment]
I assume you or someone else of a higher level tped in and out. This always happens. Using it when turning in Quests doesnt reduce quest xp tho.
