### ISSUE TITLE
Troll Boomkin form Still bugged 

### ISSUE THREAD

**Issue by LetThemCook69** [Duskhaven/Bug-Reports#1059]
i submitted a bug report last week regarding the "new" troll boomkin form overwriting the trial of cenarius moonkin form 
and the fact the troll boomkin form  lacks basically all proper animations

Was told in reply it would be fixed this patch update
it is still yet to be fixed

like why even bother putting custom boomkin transmog forms in the game if they don't work properly?

the only way to actually be in the celestial form is through phasing/zoning, and i would prefer to be in this form rather than the troll boomkin form that's missing 90% of its animations

**Comment by Duskhaven** [comment]
The Troll form will no longer overwrite the trial one after restart
