### ISSUE TITLE
Priest Spell Ranks are downgrades

### ISSUE THREAD

**Issue by Gregie** [Duskhaven/Bug-Reports#106]
Power Word Shield Rank 7 is better than 8 and 9.
Prayer of Healing Rank 2 is better than 3.
All I've seen so far.

**Comment by Duskhaven** [comment]
Values are fixed (These are updated visually in the Description with the next Patch update)

**Comment by Gregie** [comment]
Greater Heal Rank 3 is better than rank 5 now. have cast and confirmed this.
