### ISSUE TITLE
Shaman's Strike of the Windlord appears to be bugged and no longer scaling with attack power.

### ISSUE THREAD

**Issue by Samhydeftw** [Duskhaven/Bug-Reports#1060]
I recently noticed how bad Strike of the windlord is now. Using Hand of Rag it's non critting for roughly 295-300 damage... this used to be one of my highest performing spells when it comes to AOE and now it's roughly 4-5% of my overall dps which is terrible. There were no change logs that mentioned this (that I saw) and nobody in the shaman class discussion thread seemed to be aware or know why it was underperforming. This has completely nerfed my aoe dps by a substantial margin. In it's current form I do better dps with a 1h + shield in Stonewarden form which seems unfair/unintentional.

**Comment by Kimiky** [comment]
Can confirm, SotW does like 80% less damage.

**Comment by Duskhaven** [comment]
It dealt more damage then intended (Included in the bugfix changelog)

**Comment by Samhydeftw** [comment]
This completely neuters enhance shaman aoe dps but if it's intended it's intended i suppose. Ty for the clarification. I don't see the reasoning when Enhance dps (aoe specifically) is mid-tier at best. Monks/Dks/Warriors/Hunters all outperform prior to the nerf. This seems heavy handed.
