### ISSUE TITLE
Affliction talent Eradication is providing haste, not casting speed.

### ISSUE THREAD

**Issue by Reoreyh** [Duskhaven/Bug-Reports#1066]
Incorrect. Proved myself wrong.

**Comment by Reoreyh** [comment]
Nevermind. Eradication is decreasing the duration of CoA.

**Comment by Duskhaven** [comment]
Intended. https://www.mmo-champion.com/threads/685719-Eradication-amp-Glyph-of-Quick-amp-Decay

Offers more insight to the spell
