### ISSUE TITLE
Felguard Bladestorm doesn't activate if Felguard doesn't have enough mana

### ISSUE THREAD

**Issue by Krzywomordy** [Duskhaven/Bug-Reports#1067]
![obraz](https://user-images.githubusercontent.com/50958510/233137894-d255c3dc-11ea-4c7e-a16e-5fe613fa00f1.png)
Demonic Empowerment doesn't make your Felguard use Bladestorm & Chaos Nova if he doesn't have enough mana (even tho bladestorm itself doesn't use any of felguard's mana)

**Comment by Duskhaven** [comment]
Cannot replicate
