### ISSUE TITLE
Rank 2: Plainsrunning (ID 81141) - Not Applying 90% Movement Speed

### ISSUE THREAD

**Issue by Scarlessfate** [Duskhaven/Bug-Reports#1068]
Level 40 version of Plainsrunning is currently not applying the 90% Movement Speed as mentioned in the tooltip. This makes it worse than it's prior rank. 
![bf86af2cc94e78c3fac1ecdfc07e86cc](https://user-images.githubusercontent.com/131289921/233145923-41a10ee0-15cd-4fda-b235-17a298a46577.png)
![image](https://user-images.githubusercontent.com/131289921/233146087-3ec411ae-76a2-4093-b78a-d0baa2e3e9c3.png)

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/873
