### ISSUE TITLE
Lava lash only hits with one weapon

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#1072]
Even with flameshock up, it only hits with one weapon unlike what the tooltip says
![image](https://user-images.githubusercontent.com/93952514/233148870-240b25f4-eca5-4fcc-9990-9ec1e399787c.png)
![image](https://user-images.githubusercontent.com/93952514/233150444-417e2711-492e-4379-a0e4-c78e4eaeb884.png)
18 casts, 18 hits.  0 Mh hits

**Comment by Dova14** [comment]
Is it like fixed now? or what as it still only hits with one weapon

**Comment by Duskhaven** [comment]
> Is it like fixed now? or what as it still only hits with one weapon

It does hit with both weapons, the second hit is the fire blast.

**Comment by Dova14** [comment]
> > Is it like fixed now? or what as it still only hits with one weapon
> 
> It does hit with both weapons, the second hit is the fire blast.

Please rephrase the change then, as hitting with Fire blast isnt the same thing as hitting with both weapons.  Its very misleading as Hitting with Two weapons and hitting with one weapon + fire blast are two very different things especially for enhance
