### ISSUE TITLE
Got killed by horde 

### ISSUE THREAD

**Issue by haptschi** [Duskhaven/Bug-Reports#1073]
I was at Scarlet Monastary and got killed in front of the Dungeon entrance from a Horde mage. Look in the chat.
![WoWScrnShot_041923_201205](https://user-images.githubusercontent.com/131296809/233165693-e237ae0a-1b51-4b6a-982e-12138b1ca612.jpg)

**Comment by Duskhaven** [comment]
This report belongs in a ticket
