### ISSUE TITLE
Quest not working - Abyssal Contacts

### ISSUE THREAD

**Issue by RealSkyRipper** [Duskhaven/Bug-Reports#1074]
The following quest [Abyssal Contacts](https://www.wowhead.com/wotlk/quest=8361/abyssal-contacts) does not work, also any quest with the same mechanic does not work.

[Video of how the quest i suppose to be like](https://www.youtube.com/watch?v=gvC3zsnVnic)

**Comment by Duskhaven** [comment]
The Quest is not available until shortly before AQ releases.
