### ISSUE TITLE
Crusader Aura (newly added aura)

### ISSUE THREAD

**Issue by LVCJS** [Duskhaven/Bug-Reports#1076]
Hi,

Crusader Aura cannot currently be learned by Tauren Paladins.
Unsure if this is an oversight or if the aura was not properly applied to the trainers after server restart.
Would appreciate this being fixed, as this is a useful aura for us that you've just recently added.

Thank you very much.

**Comment by Duskhaven** [comment]
Fixed after restart

**Comment by elbrando91** [comment]
same for belfs btw
