### ISSUE TITLE
High Priest Thekal (HC)

### ISSUE THREAD

**Issue by Lujansh** [Duskhaven/Bug-Reports#1078]
Not going to discuss if it's overtuned or not, just the ability tooltips are wrong or missleading.

Choking cloud states it ticks every 1s but the actual dmg is dealt every 0.5s.

Crushing leap indicates a minimum range of 10yds, but it can stomp right under herself, on top of that the knockback effect is not working.

![image](https://user-images.githubusercontent.com/76747701/233189392-a33c44da-eae2-40b9-b32b-e74ba7620c87.png)
![image](https://user-images.githubusercontent.com/76747701/233189471-6e1fadde-1fc9-4846-8adb-263a955bba08.png)
(can't provide a death log to choking cloud due to being a monkey and resetting details before any fight)

**Comment by Duskhaven** [comment]
Fixed after restart.
