### ISSUE TITLE
halbert of smiting proc rate is bugged - totaly broken - FIX ASAP

### ISSUE THREAD

**Issue by RoFlNagII** [Duskhaven/Bug-Reports#1081]
![image](https://user-images.githubusercontent.com/79908620/233202058-6336a74e-956b-489e-a616-ed7fbd96985c.png)
proc rate totaly busted

**Comment by RoFlNagII** [comment]
6k st dmg...

**Comment by RoFlNagII** [comment]
![image](https://user-images.githubusercontent.com/79908620/233207839-02ab4855-8185-4454-af5a-ef9b63e8c4d9.png)

**Comment by Duskhaven** [comment]
Fixed after restart. Proc is disbled for now.
