### ISSUE TITLE
Demonic Empowerment

### ISSUE THREAD

**Issue by Ashaemage** [Duskhaven/Bug-Reports#1087]
Demon Empowerment does not cause the felguard to do his AoE attack when used while an imp from Imp Gang is also summoned.

**Comment by Kromster** [comment]
Works for me make sure you have the updated patch Z
![WoWScrnShot_042023_182347](https://user-images.githubusercontent.com/57280869/233305990-437eb250-f458-4fe1-8d6a-7ba63aebacf3.jpg)
