### ISSUE TITLE
Thunderfury bugged on Demon Hunter

### ISSUE THREAD

**Issue by Khano11** [Duskhaven/Bug-Reports#1090]
Thunderfury damage proc is bugged while playing Demon hunter. I think it's because the change to poisons. The proc damage is only 1 while in demon hunter stance.

**Comment by Duskhaven** [comment]
Intended

**Comment by xnexodus** [comment]
Why making it intended? so only 3 Broken classes will be using it (pala,Warrior,Hunter). Paladin with DW with Thunderfury makes TF do almost 800dps almost by itself with Haste stacking. Give DH some kind of opinion or make the glaives better..

**Comment by Khano11** [comment]
Why was darkmoon fair trinket fixed then?
