### ISSUE TITLE
T2 Shaman Elemental Set Bonus only gives Spell Haste

### ISSUE THREAD

**Issue by plasma-93** [Duskhaven/Bug-Reports#1101]
![image](https://user-images.githubusercontent.com/38546519/233497995-421b705f-dc03-4b53-954d-dbb9874eb322.png)
![image](https://user-images.githubusercontent.com/38546519/233498105-c571ced3-f4b3-4c81-b4cf-14f9d8c3b8c4.png)
![image](https://user-images.githubusercontent.com/38546519/233498136-5b3ebad0-d05d-4b64-a3c3-86cfc4208ea1.png)

I just spent 2 tokens for these because it says "Increases Haste by 30", but it does not give Haste, it gives Spell Haste. I am very sad, this is a bug either in the set bonus wording or in bonus it gives

:(

**Comment by Duskhaven** [comment]
Intended. Most caster stat bonuses from sets only apply for their intended spec
