### ISSUE TITLE
Felstriker appears to be not working correctly.

### ISSUE THREAD

**Issue by Samhydeftw** [Duskhaven/Bug-Reports#1102]
The tooltip states "All attacks are guaranteed to land and will be critical strikes." yet skills like Firestorm kick are not critting while i have 124% crit chance. It doesn't say "All physical/melee attacks will land and crit". Why does this crit buff not affect spells? Crit rating is universal in WOTLK so it should just be granting 100% crit for 3 seconds to all attacks.

**Comment by Duskhaven** [comment]
Intended. It's only for melee+ranged attacks 

![image](https://user-images.githubusercontent.com/123925176/233499900-2ff30f92-f90a-4b16-87dd-512e100f5409.png)
