### ISSUE TITLE
Monk's Scarlet Set (T1) is currently broken for DPS stance.

### ISSUE THREAD

**Issue by Samhydeftw** [Duskhaven/Bug-Reports#1105]
I was asked to post this issue here by Kebful. The set is just titled "Scarlet boots" not "Scarlet boots (Tank)". The descriptions of the set bonus insinuates that it would work for either monk stance. This is misleading. Can this be fixed or can i have a refund of my Scarlet items so I can get the prophecy dps (smite set) version. I have tested it on the target dummies and the set bonuses do not activate until I switch to tank stance.

**Comment by Duskhaven** [comment]
Tank Set bonuses only work while in their corresponding stance for Monks and DH's

**Comment by Samhydeftw** [comment]
The bonuses that weren't working were not tank related...Jab striking a second time for 25% damage and fire damage on jabs after fist of the tiger is not tank oriented.
