### ISSUE TITLE
Warrior Shield Bash

### ISSUE THREAD

**Issue by SpookyTookyOG** [Duskhaven/Bug-Reports#1109]
Warriors ability Shield Bash had its damage component removed. This must have been a recent update oversight. While leveling this spell correctly had it's damage.

**Comment by Duskhaven** [comment]
![image](https://user-images.githubusercontent.com/123925176/233810595-5411cd2c-7f82-433f-b851-49f9adb498d5.png)

According to this source Shield Bash does not deal damage in the 3.3.5 client.

**Comment by SpookyTookyOG** [comment]
![Shield Bash](https://user-images.githubusercontent.com/131320189/233813442-26041d30-047c-4fbc-8417-c62c1a5efb46.png)
Here is the clip from the patch notes on 3.0.2. If this is the patch to be referenced. The wiki page on the shield bash spell itself references this change incorrectly. This would have been done in later patches where lower leveling was of no importance. Until talents unlock Shield Slam. This spell was and is a solid addition to tanking rotations as it does not list it's armour negating damage. The damage was small mind you. but still worth leaving in. 

For this server. I don't believe there would be any negative impact for re-adding the damage. This would allow lower level tanks another threat option. And i do hear a lot of war tanks with issues at max lvl.
