### ISSUE TITLE
Flight from Stormwind to Menethil Harbour is bugged

### ISSUE THREAD

**Issue by Schmitlab** [Duskhaven/Bug-Reports#111]
Everytime i use the flightpath in stormwind to fly to Menethil Harbour the Gryphon flies through the Dun Morough mountain passed Menethil up to Arathi and then flies all the way BACK to Ironforge back through the mountain again and finally lands in Menethil

**Comment by Duskhaven** [comment]
Duplicate Issue, please refer to https://github.com/Duskhaven/Bug-Reports/issues/17
