### ISSUE TITLE
T2 3 set bonus conflicts with T1 2 set bonus for mage.

### ISSUE THREAD

**Issue by Tyrannus97** [Duskhaven/Bug-Reports#1110]
Hello,
I'm a mage and I recently acquired the 3 set of T2 together with my 2 set of T1 plus my glyph of molten armor should give me a total of 70% spirit to crit chance conversion but as you can see the spell says it gives only 55% so it is missing 15% meaning my new T2 set bonus does not work because it is the same as the T1 one, could you please fix this?

![Schermopname (76)](https://user-images.githubusercontent.com/131414797/233511757-56f0763a-c534-475e-b96a-f321ba3cc339.png)
![Schermopname (77)](https://user-images.githubusercontent.com/131414797/233511767-8610d3d2-e525-43a8-8958-41a1bea76ea3.png)
![Schermopname (78)](https://user-images.githubusercontent.com/131414797/233511781-5f47039c-a212-4119-887a-7c1f8364ae5e.png)
![Schermopname (79)](https://user-images.githubusercontent.com/131414797/233511791-68a6cf17-34fa-4b3f-adcc-a4a8cc54078b.png)
![Schermopname (80)](https://user-images.githubusercontent.com/131414797/233511804-713a5182-f91b-4e5b-a893-8357725e3d3a.png)

**Comment by Duskhaven** [comment]
The same set bonuses do not stack.
