### ISSUE TITLE
Hard mode death on server shut down or crash

### ISSUE THREAD

**Issue by StarMountains** [Duskhaven/Bug-Reports#1111]
I was in doing the hard mode challenge for the third time this last time what a shaman. While on a quest (shadow pendant) inside a mage tower near top I  engaged with five mobs and handle them without a problem. Then I came across three more mobs when I noticed that the mobs were no longer interacting with my character. A few moments later the login screen appeared, indicating the server had shut down/crashed.  I went on discord soon after and saw people complaining that the server was shut down so I took a brake. I logged back on an hour later and I found my character in the graveyard.
This is happened to me twice once on my warrior, which I deleted in the second time on my shaman, which frustrated me enough to put in this ticket.
I uploaded my summary report on the line that reads Total Death it shows I have 2 death which is not true. This
![B854B627-5471-43DC-B93C-97AB164CED14](https://user-images.githubusercontent.com/131421387/233531808-074b0909-1a9b-4095-8f9f-e4abee5da0ba.gif)
 is my first death with us character.

**Comment by Duskhaven** [comment]
This does not belong in the bug report section.
