### ISSUE TITLE
T1 prophecy priest 5 piece bonus is not working

### ISSUE THREAD

**Issue by Altair484** [Duskhaven/Bug-Reports#1113]
The 28 critical strike rating are not granted when all the required pieces are equiped :( 

4/8 T1 without +5 piece bonus = 12.50% crit
![image](https://user-images.githubusercontent.com/15770932/233579704-39189aaa-a009-4582-ae3f-97b56e8c2f0b.png)

5/8 T1 with + 5 piece bonus = 12.83% crit 
![image](https://user-images.githubusercontent.com/15770932/233580064-dd3d39bd-9bae-42f9-96da-7769bd713ef2.png)

Expected behaviour : 

When 5/8 T1 is equiped  the critical score should be around 14.50% 

Thanks again for the server, and everything that you are doing for us <3

**Comment by Duskhaven** [comment]
Cannot replicate 

Without 
![image](https://user-images.githubusercontent.com/123925176/233737301-42375ac1-5165-45c4-ac93-a74992e566fa.png)

With Set Bonus
![image](https://user-images.githubusercontent.com/123925176/233737329-1a0ffb11-0d39-4c16-98c1-d365285fd84d.png)
