### ISSUE TITLE
S2 Ruby Plate Teir Set

### ISSUE THREAD

**Issue by Hammyys** [Duskhaven/Bug-Reports#1116]
the 5th set as it displays it supposed to reduce the Cooldown of Shield block ability by 10 seconds while the actual Cooldown is only reduced by 3 seconds, I passed all my T2 items just to be able to obtain S2 Tank items. Kindly fix the Cooldown reduction at S2 Tier set.

side notes: yes I have my patch Z updated... and the gear is so underwhelming after the nerf.

**Comment by Duskhaven** [comment]
Set Tooltip is changed with the next patch update.
