### ISSUE TITLE
Dying in the DH Starter Quest Area

### ISSUE THREAD

**Issue by TwoSnaksz** [Duskhaven/Bug-Reports#112]
May of had some fun jumping off the edge of the Mardum and died as a result.
Clicked release but was instantly resurrected beyond the tunnel where the Fel Guard is. Meaning I couldn't get back in due to the invisible wall. Fortunately I managed to get back to Azeroth but I still have a quest to do in there albeit the final one.

Its not much of a bug report but can respawn point be moved inside the enclosed area? If not, enclose the spawn point so that it looks like part of the cave.

Alternatively set the DH npc in Org/SW to be able to tp you back to Mardum if the final quest hasn't been completed.

**Comment by Duskhaven** [comment]
This is now fixed.
