### ISSUE TITLE
Enhancement Shaman Toughness Visual bug

### ISSUE THREAD

**Issue by Trentmahalla** [Duskhaven/Bug-Reports#1121]
When at 5 points the toughness talent says that it is giving 5% stamina
![image](https://user-images.githubusercontent.com/47612241/233707776-ea9f0558-5559-4afd-a68d-4fd43bd2add9.png)

When it should be giving 10% stamina because one point into it is a 2% stamina increase
![image](https://user-images.githubusercontent.com/47612241/233707943-fb606ed6-d84b-4c2e-ae7b-a667749e67f0.png)

**Comment by Duskhaven** [comment]
The stamina is intended to be only 5% at max rank. Rank 1 tooltip will be updated with the next patch.
