### ISSUE TITLE
T1 4 set DH

### ISSUE THREAD

**Issue by Kreindal** [Duskhaven/Bug-Reports#1122]
I found mistake on T1 4 set says Demonic Tatoos and when you equip 4 set T1 for Rouges that bonus not working when you are TANK it wont regen until you proc it to activate and also t2 bonus 8 set is not good at all you cant Tank as Metamophis perma its only for 20 sec to pls change that to Demonic Tattoos otherwise its very useless honestly

-Azeroth

**Comment by Duskhaven** [comment]
Fixed after restart
