### ISSUE TITLE
Talisman of Troll Divinity not working with direct heals. (Druid)

### ISSUE THREAD

**Issue by Trommerwow** [Duskhaven/Bug-Reports#1123]
"Use: For the next 20 sec, your direct heals increase healing received by their target by up to 58.  This effect lasts 10 sec and stacks up to 5 times. (2 Min Cooldown)"

Name: Tomtes 
Class: Druid 
Race: Worgen
Discord: Trommer#9234

I activated the trinket and used all my direct healing spells (Healing Touch, Regrowth, and Tranquility). No stacks were gained.
I tried restoration, balance, and naked, but still not working.

Thanks for giving this a look. You're awesome!

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/610
