### ISSUE TITLE
Frost Death Knight's "Shattering Cold"

### ISSUE THREAD

**Issue by Halnasman** [Duskhaven/Bug-Reports#1124]
Shattering cold is proccing by nearby death knights without being in combat or a party. I was standing near my friend teaching them dk and they were proccing Shattering Cold without me being in a party with them nor with me hitting any buttons. Just standing near them. Hope this helps!
   -Halnasman/Haln/Halnisme

**Comment by Duskhaven** [comment]
Fixed after restart
