### ISSUE TITLE
Spirit Weapons not giving Tank Monk parry chance

### ISSUE THREAD

**Issue by xbadturtlex** [Duskhaven/Bug-Reports#1131]
As said in the title, my parry chance on my Monk is 0%, surprisingly enough when I hover over the stat it then says I have a 14% chance to parry, but after exensive testing I cannot get my character to parry. I don't believe this is intended and seems to be a big issue for monk tanks

**Comment by eMalum** [comment]
Priests have a hard cap of 0% parry chance. 

![image_2023-04-26_162322337](https://user-images.githubusercontent.com/85034251/234693673-68a2e68e-2c79-4ad7-84eb-c4c616d3dda1.png)
Screenshot courtesy of Iridi on Discord. They were able to change the parry cap on their personal server.

**Comment by drivenx** [comment]
gib parry
