### ISSUE TITLE
Human feral cat model (not worgen) + Joyous Journeys (Buff)

### ISSUE THREAD

**Issue by Xenbiotic** [Duskhaven/Bug-Reports#1140]
When I relog in cat form it twists my model.
First relog makes my model into 1 or 0 pixels (drinking anything that makes you smaller does the same thing aka noggenfogger)
Second relog made my feral cat model both backwards and upside down
Getting in and out of cat form fixes this but thought I'd bring it up regardless.
Getting into cat form I'm super huge but quickly scale down to normal size.
My suggestion on a quick fix is giving Human druid the Worgen druid cat model. (They aren't the same)
I got human druid from faction change.

Joyous Journeys Refreshes too often, in the screenshot where my model is hidden "Ihatehealing" has made 2 potions and it proc's twice before the second one was made. This might be making lag

![upsidedowncat1](https://user-images.githubusercontent.com/67262624/233800237-4b752aa0-4311-449a-bb53-e0ba58b52307.png)
![upsidedowncat2](https://user-images.githubusercontent.com/67262624/233800294-fdc6356e-9fe0-4952-8387-ad5779268f15.png)

**Comment by Duskhaven** [comment]
Fixed after restart
