### ISSUE TITLE
Wildfire Infusion Survival Hunter Talent

### ISSUE THREAD

**Issue by Davaerst** [Duskhaven/Bug-Reports#1141]
The hunter survival tree talent called 'Wildfire Infusion' can't be learned because it needs a point in 'Improved Stings' which it only states when linking the talent. 'Improved Stings' requires 15 points in the Marksmanship tree, and should therefor probably not be a requirement for the Wildfire Infusion talent.

When looking at the talent in the tree:
![image](https://user-images.githubusercontent.com/36208013/233805705-42b84df0-6ddd-421e-8ca2-d7c6c105d937.png)

When linked, the talent even shows as the Marksmanship talent:
![image](https://user-images.githubusercontent.com/36208013/233805669-bc8beb63-322a-42ff-8fbc-07a137a0fa0d.png)

**Comment by Duskhaven** [comment]
Fixed with the next patch update
