### ISSUE TITLE
Frost Armor + Frost Warding talent visual bug

### ISSUE THREAD

**Issue by ImYoinks** [Duskhaven/Bug-Reports#1144]
Frost Armor buff tooltip shows original value instead of the increased one. For example when using a tier 2 Frost Armor and 2 points in the Frost Warding talent, the buff shows +110 Armor when it should be +165. Does not affect your actual armor value though, that value is correct.

**Comment by Duskhaven** [comment]
Thats the case for most talents, the increased values are not shown on the buff list near the minimap.
