### ISSUE TITLE
Hunter's T2 last set bonus is not proccing off melee attacks

### ISSUE THREAD

**Issue by Congroo24** [Duskhaven/Bug-Reports#1147]
As the title says. Even though the 350 AP debuff procs off range attacks, it doesn't with melee attacks.

**Comment by M0tke** [comment]
Adding on to this, even when it does proc from ranged attacks it only increases ranged attack power but the set bonus says melee and ranged attack power.

**Comment by Duskhaven** [comment]
Fixed.
