### ISSUE TITLE
Balance Druid Talent - Earthweaver

### ISSUE THREAD

**Issue by kasumee** [Duskhaven/Bug-Reports#1149]
Since the recent change to the "Shoot Thorns" portion of Wrath to not be counted as a melee attack, it not does not have the correct crit damage. Whereas it was 2x crit dmg before, it is now 1.5x and not benefiting from Vengeance. Pretty sizeable nerf, and I cant imagine Vengeance not affecting it is intended.

**Comment by Duskhaven** [comment]
Fixed after restart
