### ISSUE TITLE
Multiple NPC's in Steelgrill's Depot, Dun Morogh

### ISSUE THREAD

**Issue by Davaerst** [Duskhaven/Bug-Reports#1151]
There are 2 Captain Tread Sparknozzle's right next to eachother, giving the same quests, basically just mirror images.
And the Drill Sergeant Steamcrank right by them shouldn't be there either, he is already standing over by the recruits and shouting at them.
![WoWScrnShot_042323_085352](https://user-images.githubusercontent.com/36208013/233824902-41c3064f-84d0-451a-ac49-603dc4dc429e.jpg)

**Comment by Duskhaven** [comment]
Fixed.
