### ISSUE TITLE
Hunter Marksman Talent Bugged

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#1153]
Talent : Rapid Recuparation is not granting any mana reg when you gain Rapid Killing effect.
 
Rapid Killing effect is triggered by the Talent Rapid Killing.

Piercing Shots : It doesnt stack after a crit and only refreshes the debuff.

Improved Steady Shot : The buff doesnt increase damage of Aimed , Chimera, Arcane Shot as stated

**Comment by Duskhaven** [comment]
Cannot replicate
