### ISSUE TITLE
Master of Elements not giving spell hit

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#1156]
Hello Noxx!
The Fire Mage talent, Master of Elements is currently not giving 6% hit. (Also tooltip still showing 3%)

Tested with 11% hit on my gear and spells missed.

Would love it fixed, thank you!
![image](https://user-images.githubusercontent.com/31871078/233855481-1db31515-f4a6-4222-931c-ba3004fdc799.png)
![image](https://user-images.githubusercontent.com/31871078/233855496-9a76a34a-fd93-4d23-88b7-30e8050272d0.png)

**Comment by Chromie-the-gnome** [comment]
![image](https://user-images.githubusercontent.com/31871078/233855579-4970ea37-f138-4a78-9dcd-fb9e95ce898d.png)
Tested after with 13% spellhit and no spells missed.

**Comment by Duskhaven** [comment]
Fixed
