### ISSUE TITLE
Essence of the Windlord

### ISSUE THREAD

**Issue by Saphix16** [Duskhaven/Bug-Reports#1161]
Currently shamans gain a buff from using Strike of the Windlord called Essence of the Windlord. This buff however does not have any value to the shaman as the buff is related to hunter abilites and spells. 

![essence](https://user-images.githubusercontent.com/131386548/233862654-be2e3b9c-8542-46c5-b08c-b445c2724eda.png)

**Comment by Duskhaven** [comment]
Visual Tooltip is updated with the next patch.
