### ISSUE TITLE
Soul Feast quest npcs do damage to all nearby players in massive radius

### ISSUE THREAD

**Issue by B00M5T1CK** [Duskhaven/Bug-Reports#1163]
I just started a death knight and was trying to do the Soul Feast quest.

I saw someone else fighting a harvested soul at the same time I was and noticed my health was dropping very quickly.
After observing and making another character to replicate the issue, it appears that Harvested Soul enemies will hit all players in a massive area with no visual indication other than the damage being taken. This only comes from their attacks, corruption that they put on players is isolated to the person with corruption.

To replicate: Create a death knight character and stand near the harvested souls. Wait for another death knight to enter combat and keep track of health and distance from the other death knight.

Please let me know if any further information is needed/helpful

**Comment by Duskhaven** [comment]
Fixed after restart
