### ISSUE TITLE
Crusader Strike And Divine Storm Crits From Off-Hand Not Applying Righteous Vengeance

### ISSUE THREAD

**Issue by YoshGit** [Duskhaven/Bug-Reports#1169]
Attached screenshots demonstrate instances of MH registering as a regular hit and OH registering as a crit but Righteous Vengeance not being applied

Evidence:
![DS](https://user-images.githubusercontent.com/12674486/233904421-2d0747ba-77a5-47e4-af33-76b2717242e6.png)
![CS](https://user-images.githubusercontent.com/12674486/233905127-a8eef731-5c99-46da-905f-480115f649ca.png)

**Comment by Duskhaven** [comment]
Fixed after restart
