### ISSUE TITLE
Battle Chicken Not Casting Chicken Fury

### ISSUE THREAD

**Issue by YoshGit** [Duskhaven/Bug-Reports#1170]
Battle Chicken from trinket Gnomish Battle Chicken should have a chance on hit to cast Chicken Fury

https://www.wowhead.com/wotlk/npc=8836/battle-chicken#abilities;mode:n10
https://www.wowhead.com/wotlk/spell=13168/chicken-fury

**Comment by Duskhaven** [comment]
Fixed after restart
