### ISSUE TITLE
Hunter Marksman Talent bugged

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#1173]
"Talent : Rapid Recuparation is not granting any mana reg when you gain Rapid Killing effect.

Rapid Killing effect is triggered by the Talent Rapid Killing."

To replicate this bug, have Rapid Killing and Rapid Recuparation talented as Hunter marksman.
Then you need to kill a mob close to the lv60 level range.

Now what should appear on your character is the "Rapid Killing" buff for 20 secs.
During this time frame you should receive 2% Mana reg every 3 secs.

And that is the issue there is no mana reg buff appearing.

**Comment by Duskhaven** [comment]
Works as intended. 

![image](https://user-images.githubusercontent.com/123925176/233919631-b7985cd7-0c1d-445a-8f19-38fec481b13e.png)

**Comment by Colette00** [comment]
Doesnt work for me i dont know how you gain mana from rapid recuperation.
Any idea how you fixed it? Do i need to patch the game? As stated im still not getting any mana reg from rapid recuperation during Rapid killing.

This is exactly what the talent Rapid Recuperation states:

"You gain 4 % of your mana every 3 secs while under the effect of Rapid Fire. and you gain 2% of your mana every 2 secs for 6 secs when you gain Rapid Killing."

The second part of this Talent isnt showing up for me.
If you fixed it please put that in the changelog.
