### ISSUE TITLE
Mobs south of Stromgarde Keep

### ISSUE THREAD

**Issue by Aurekaa** [Duskhaven/Bug-Reports#118]
The ogres in Arathi, south of Stromgarde Keep, fly 30 feet when you agro them until you somehow kill them (impossible for melee) or you go below 20% where they jankily teleport back down to kill you.
![WoWScrnShot_031123_061020](https://user-images.githubusercontent.com/127609126/224489688-826c8fc9-99a5-4888-a4d8-11153f20a0f7.jpg)
![WoWScrnShot_031123_061135](https://user-images.githubusercontent.com/127609126/224489689-140ddde8-b4c7-4f4b-8a5b-857cc786e8fa.jpg)

**Comment by Duskhaven** [comment]
Fixed.
