### ISSUE TITLE
Warblade of the Hakkari applies Ursoc's Ferocity & Frost Presence on equip.

### ISSUE THREAD

**Issue by Kebful** [Duskhaven/Bug-Reports#1180]
Dual Equipping Warblade of the Hakkari applies the following auras.

- Frost Presence
- Ursoc's Ferocity (which turns you into bear form)

Item IDs for Hakkari
19865     - Heroic
19866     - Heroic

57138     - Normal 
57139     - Normal

**Comment by Duskhaven** [comment]
Fixed
