### ISSUE TITLE
ERROR #134 (0x85100086) Fatal Condition

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1184]
![image](https://user-images.githubusercontent.com/131197913/234126108-8e6d9fb9-6fe8-4c87-9ffb-aeb2ba131838.png)

Submitting this issue on behalf of character name "Ashwindcoyot"

They advised, "my blood elf was in Silvermoon using the teleporter that teleports to Undercity. I clicked it, I could see the loading art for Undercity, and the error screen comes up afterwards."

Ashwindcoyot goes on to say that, "I was playing with my husband who used the same teleport a second ahead of me and went through just fine."

Attached the screenshot they provided of the issue. 

Thank you

**Comment by Duskhaven** [comment]
This belongs in Discord
