### ISSUE TITLE
Demon Hunter Fel Rush + Blade Dance Interaction Bug

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1194]
Fel Rush states:  "_Your Next Chaos Strike deals damage twice. Your next Blade Dance increases your Health by 6% for 20 seconds_"

But the buff Infernal Armor which is applied after using Blade dance increases the HP only for 5 seconds.

Current behavior:
- Infernal Armor lasts for 5 seconds

Expected behavior:
- Infernal Armor lasts for 20 seconds

There is also a typo there. There should be a dot after "20 seconds"

**Comment by Duskhaven** [comment]
Fixed after restart
