### ISSUE TITLE
Demon Hunter Fel Rush Chaos Strike Damage Twice OR Blande Dance Bug 

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1195]
Fel Rush states: "Your Next Chaos Strike deals damage twice. Your next Blade Dance increases your Health by 6% for 20 seconds"

However, when you activate Fel Rush you get the Demon's Mark which is consumed after using either Chaos Strike OR Blade Dance. That means that you only get either the double damage on chaos strike OR the increased health from Blade Dance but never both.

Current behavior:
- Demon's Mark is consumed after using either Chaos Strike or Blade Dance

Expected behavior:
- Two buffs where one is consumed after using Chaos Strike and one after using Blade Dance

**Comment by Duskhaven** [comment]
Intended
