### ISSUE TITLE
Demon Hunter Blade Dance Dodge Chance or  Attack Speed Buff Bug

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1196]
Blade Dance states: "_Blade Dance grants 15% Dodge Chance for 10 seconds if used during Metamorphosis or 30% additional Attack Speed._"

Expected behavior:
- 30% increased Attack Speed when **not in** Metamorphosis  
- 15% increased Dodge Rate when **in** Metamorphosis  

Current behavior: 
- 30% increased Attack Speed AND 15% increased Dodge Rate when **in** Metamorphosis  
- Nothing when **not in** Metamorphosis

**Comment by Duskhaven** [comment]
Intended
