### ISSUE TITLE
Alterac valley honor gear

### ISSUE THREAD

**Issue by Holyshirtpro** [Duskhaven/Bug-Reports#1205]
Sent in a ticket was told to post it here instead. All the alterac valley honor gear is 25k honor which is lich king levels of honor. Back in the day one of the bis dps rings was don julios band and was 5k honor and is even 5k honor according to your custom atlas loot.  Before warmode was removed I managed to farm 9k honor from that and brawlers guild.  And i went to go get don julios and was appalled by the 25k honor requirement. Not sure if there is a rework in place but 25k honor is almost impossible on this server. is there some sort of change in place or is this a bug where the honor req are way to high

**Comment by Duskhaven** [comment]
Intended.
