### ISSUE TITLE
Weapon DPS Greataxe of the Warrior (S2) 

### ISSUE THREAD

**Issue by BugSquisher9000** [Duskhaven/Bug-Reports#1208]
Greataxe of the Warrior has a ilvl 73 with 64.6 dps. However Zin'rohk, Destroyers of Worlds (Heroic) Has a ilvl 73 with 77.8 dps. Both weapon have 3.80 speed. Either you adjust ilvl back to 68 or you fix the low and high end dmg on Greataxe which match it's ilvl.

![image](https://user-images.githubusercontent.com/131832227/234439770-efcee2e8-91e0-497f-beec-1a498283deec.png)

![image](https://user-images.githubusercontent.com/131832227/234439893-fb58c27a-4439-4f56-a811-37a49c0ec4cb.png)

**Comment by Duskhaven** [comment]
Ilvl of HC Weapons dropped from Hakkar has been increased.
