### ISSUE TITLE
Demon Hunter Threat 

### ISSUE THREAD

**Issue by BugSquisher9000** [Duskhaven/Bug-Reports#1209]
Im told rogue threat works like this. Warrior generates 100% threat from every ability in non defensive stance and rogue generates 80% threat from their abilities. Even with a threat modified by 110% that will still be only 190% threat. While bear, warrior and paladin have 300% threat modifier in their respective form and buff.
Shaman and monk threat is also very much close to 300%
This explain very much for me why DH can’t push threat enough when you have dps pushing 2.5k dps
In tank stance you do avg 1,1k dps
That is a threat generate of 1980 close to 2k tps

Take a example as it was stated in DH subforum in discord - A Feral bear did as same avg dps as DH tank which was 1,1k dps. DH will do 1980 tps, the feral bear however is doing 3300 tps. And user said it felt like he was 30-50% higher than him. 

The solution I can see is that you buff DH tank stance from 110% to 220% to match 80% threat that rogues generate. 

Source: https://www.wowhead.com/classic/guide/threat-overview-classic-wow#threat-modifier-abilities-and-values-rogue.

**Comment by Duskhaven** [comment]
Generated threat has been increased after restart
