### ISSUE TITLE
Improved Stormstrike Mana return lower than intended

### ISSUE THREAD

**Issue by randomknight** [Duskhaven/Bug-Reports#121]
The Enhancement Shaman talent Improved Stormstrike currently only returns the original 20% of base mana as it does on regular wrath clients as opposed to whatever increased value it should have according to the Class Changes listed on the website. 
![image](https://user-images.githubusercontent.com/56983190/224506818-6634e352-5b8b-4972-b7a3-dd79de959bfe.png)

**Comment by Duskhaven** [comment]
This was an oversight from the old Realm. It has been removed from the Website.
