### ISSUE TITLE
DH new demon form

### ISSUE THREAD

**Issue by Daziod** [Duskhaven/Bug-Reports#1213]
![WoWScrnShot_042623_183725](https://user-images.githubusercontent.com/119414336/234550845-13d0011b-6e62-4c68-9634-271c48795d91.jpg)
The New DH demon form is bugged i dont see any new Form im just a green thingy with a glaive, I also update my Patch Z using Launcer

**Comment by chtheiss** [comment]
I encountered the same issue. 
Gif:
![DH_form_bug](https://user-images.githubusercontent.com/24509495/234552741-114ea769-56c1-41cd-8ab5-92a2b72f1b9c.gif)

**Comment by RealSkyRipper** [comment]
![image](https://user-images.githubusercontent.com/131196964/234553335-7b80d295-8700-4e63-bdb8-00ed40b80d23.png)

same
