### ISSUE TITLE
[Priest] Shadowy Tome has no effect

### ISSUE THREAD

**Issue by Netherborne** [Duskhaven/Bug-Reports#122]
The Shadowy Tome talent does not work.

**Comment by Duskhaven** [comment]
Works fine for me. Without Talent: 
![image](https://user-images.githubusercontent.com/123925176/224512775-1db17249-a3ce-4bb1-8927-70fe5e4af7f9.png)


With Talent: 
![image](https://user-images.githubusercontent.com/123925176/224512796-545f227b-0b09-40bd-8a51-f1bfc7871677.png)

**Comment by Netherborne** [comment]
![image](https://user-images.githubusercontent.com/18594410/224513974-70fa20e6-a6a2-4c80-a293-3cafed4fded8.png)
![image](https://user-images.githubusercontent.com/18594410/224513977-262f9e43-3ba8-475a-ae92-bf5d23ca16b3.png)
![image](https://user-images.githubusercontent.com/18594410/224513981-330608dc-9181-4e5c-a400-de8026b1db30.png)
No effect at all for me

**Comment by kiriaziskokkinos** [comment]
maybe it only works at higher ranks of mind flay?

**Comment by Netherborne** [comment]
@Duskhaven doesnt affect any of my mind flay ranks. does it require haste gear to take effect?

**Comment by Netherborne** [comment]
It turns out the effect gets removed shortly after logging in. 

https://user-images.githubusercontent.com/18594410/224514953-9c9e65f0-bc2c-4e6b-bb3d-62da9fdf101d.mp4

**Comment by Netherborne** [comment]
it started working again when i leveled to 52. 
it wasnt working from the moment i learned it (around 36 iirc?) until now.

**Comment by Netherborne** [comment]
it's back to not applying for me @lvl 60 idk whats going on
