### ISSUE TITLE
Demon Hunter Chaos Nova Damage Reduction Debuff only lasts for 5 seconds instead of 10

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1220]
Chaos Nova states: "reduces the Damage of affected Targets by 5% for 10 seconds"

Current Behavior:
- The damage reduction debuff lasts for 5 seconds (might be a copy paste error from the 5%)

Expected Behavior:
-  The damage reduction debuff lasts for 10 seconds

**Comment by Duskhaven** [comment]
Duration reduced to 5 seconds in the Tooltip with the next patch.
