### ISSUE TITLE
Demon Hunter Teleport to Council Icon changes based icon on previous page

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1221]
Current Behavior (See Images):
- The skill "Teleport to Council" has the icon of whichever skill is at the same position one page before it in the spellbook

Expected Behavior:
- The skill "Teleport to Council" has its own Icon

![image](https://user-images.githubusercontent.com/24509495/234653303-7ddba369-16b3-41b5-bdd8-fdd3fef9f09b.png)
![image](https://user-images.githubusercontent.com/24509495/234653350-a74ed4f5-17f2-49fe-9b86-6598b0f9ff18.png)

**Comment by Duskhaven** [comment]
Fixed with the next patch update
