### ISSUE TITLE
Demon Hunter Chaos Nova and Immolation Aura Require an Attackable Target to be Used

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1222]
As far as I know, there are no other AOEs or Auras that require a target to be used (except Seed of Corruption for obvious reasons) so I would assume this to be a bug for these two skills.

Current Behavior:
- Chaos Nova and Immolation Aura require an attackable target to be used

Expected Behavior:
- Chaos Nova and Immolation Aura can be cast without a target selected

**Comment by Duskhaven** [comment]
Intended
