### ISSUE TITLE
Demon Hunter Blade Dance does not provide 15% chance dodge but 200 dodge rating before DR instead

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1227]
Blade Dance states: "_Blade Dance grants 15% Dodge Chance for 10 seconds_"

which is similar to e.g. Evasion ("Increases the rogue's dodge change by 50%) or Ghostly Strike ("increases your chance to dodge by 15%). Both Evasion and Ghostly Strike add their chance after DR is calculated. So you end up with exactly 50% or 15% dodge chance in both cases. Blade Dance instead of granting its buff in the same way gives 200 dodge rating instead (see images below). This is added before DR. So the resulting dodge change increase is somewhere around 8-11% depending on your gear.

Current Behavior:
- Blade Dance dodge buffs gives 200 dodge rating
 
Expected Behavior:
- Blade Dance dodge buff increases your chance to dodge by 15% similar to Evasion or Ghostly Strike.

Evasion Buff for reference (37.76% -> 87.76% dodge chance):
![image](https://user-images.githubusercontent.com/24509495/234687377-bb57e654-d7fc-4fc9-a066-8ffca7056ec6.png)

Without Blade Dance Buff:
![image](https://user-images.githubusercontent.com/24509495/234685456-3d1cea62-b2eb-4a6d-ac8e-d3b9937f358d.png)

With Blade Dance Buff:
![image](https://user-images.githubusercontent.com/24509495/234685338-ffb7515e-ea29-418b-943b-e443d7016450.png)

**Comment by Duskhaven** [comment]
Changed to % based after restart
