### ISSUE TITLE
Demon Hunter Glaive Throw Threat Bug in Tank Stance

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1228]
Glaive Throw states: "_Generates additional Threat as a Tank_"

Current Behavior:
- Glaive Throw generates the same amount of threat regardless of stance (Fel Infusion or Demonic Tattoos)

Expected Behavior:
- Glaive Throw generates for threat in tank stance (Demonic Tattoos) than in DPS stance (Fel Infusion)

**Comment by Duskhaven** [comment]
Fixed after restart
