### ISSUE TITLE
Power Word: shield Wrong ToolTip and has a Weird bug?

### ISSUE THREAD

**Issue by WiseWolfHolo123** [Duskhaven/Bug-Reports#123]
As in the Titel, there are two things right now with Power word shield,
![Desktop_230311_2104](https://user-images.githubusercontent.com/75774869/224511157-5d444998-e323-402d-b0f0-dcb9796002ec.jpg)
Rank 8 shows 370 "Shield" and upon using PWS, it was also with rank 7 the case before learning Rank 8. it also seems like that every attack that enemys do to you, will be a "miss" While still taking Absorb away from your PWS

https://user-images.githubusercontent.com/75774869/224511187-b644b11d-0de2-4010-b52f-657752b39204.mp4

**Comment by Duskhaven** [comment]
Fixed with the restart.
