### ISSUE TITLE
S1 Set (Bluefang) 2-Set Bonus not giving Hit Rating

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1231]
Bluefang 2-Set Bonus states: "_Hit rating increased by 20_"

Current Behavior
- Hit Rating is not increased from the 2-set bonus when 2 or more pieces of the Bluefang set are equipped

Expected Behavior:
- Hit Rating is increased by 20 when 2 or more pieces of the Bluefang set are equipped

Example:
80 Hit Rating with only gloves equipped:
![image](https://user-images.githubusercontent.com/24509495/234694230-b7b26a02-dbb2-4c4f-b587-5358ee148ffe.png)

91 Hit Rating with gloves and legs equipped (11 from the legs itself are applied) but 20 from the set bonus are missing:
![image](https://user-images.githubusercontent.com/24509495/234694461-0d1eb5e9-94fd-4dc9-a18e-0ee491e825e9.png)

**Comment by Duskhaven** [comment]
Cannot replicate
