### ISSUE TITLE
Demon Hunter damage scaling seems to be nerfed?

### ISSUE THREAD

**Issue by Khano11** [Duskhaven/Bug-Reports#1232]
Not sure if this is a bug or what but about a week ago or so demon hunters damage dropped heavily and are no longer close to being competitive with other classes. Chaos strike went from 2k crits to under 1k. Having better scaling on abilities like chaos strike scaling with weapon damage would go far. In the current state its better to stack spell power for damage then attack power because everything does fire damage

**Comment by xAzeroth** [comment]
it will be fixed after restart for sure someone already post this one
