### ISSUE TITLE
Molten Core (HC) - Majordomo: Loot Chest

### ISSUE THREAD

**Issue by Xenbiotic** [Duskhaven/Bug-Reports#1233]
His chest despawns very fast. I lost a item because everyone passed and I was AFK, the heroic corehround tooth for my toon Awoo is just gone, vanished into nothing. I wasn't AFK long either

Suggestion: Make loot drop off domo himself or make the chest last longer
How to recreate: Kill domo on heroic on default loot type, open the chest, pass on everything then wait

**Comment by Duskhaven** [comment]
Duration increased by 50 seconds.
