### ISSUE TITLE
Mage - Master of Elements Talent

### ISSUE THREAD

**Issue by Ezi66** [Duskhaven/Bug-Reports#1240]
The talent "Master of Elements" was never updated. According to Changelog post on 18.04.2023 by Qtips; 

Fire Mage
- Master of Elements now grants 2% spell hit chance per point, up from 1%.

This change was never implemented as the talent still only gives 1% per point. 
I opened a ticket in game and was informed that this is indeed a "bug" by Game Master "Dava" and to please report it here to be fixed.

**Comment by Duskhaven** [comment]
This only applies visually, description will be changed with the next patch update
