### ISSUE TITLE
My scrap bullet does 300% damage instead of double on crit

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1246]
Ok this is a weird one.

Ive been pulling some ridiculous numbers on raids lately, and when I checked, my scrap bullet was critting for 2k while normal hits are 600-700 (this is on SV, so not crit modifiers)

Ive commented it with other tinkers and apparently it is only happening to me. Also I am able to use arcane shot for some reason?

So yeah, before tinker catches a nerf I would like to surrender myself to the authorities :(

**Comment by Duskhaven** [comment]
Fixed
