### ISSUE TITLE
Normal Vaelstrasz Loot is Bugged

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#1250]
Hello team!
As others have already said, Vaelstrasz in normal BWL keeps dropping always the same loot.

In our guild it's been dropping the exact same items all the time, and it's already became a meme but it sucks to gear up like this.
Is there any chance this can be looked at?
Thank you!

**Comment by Chromie-the-gnome** [comment]
Bump!

**Comment by Duskhaven** [comment]
Fixed
