### ISSUE TITLE
Neutral NPCs in-game put you into combat upon login

### ISSUE THREAD

**Issue by AmistadeGG** [Duskhaven/Bug-Reports#1253]
There are a few places in-game, that put you in combat upon the login of your character. When you log-in, you see few damage markers (even tho, you don't do anything, since it happens the second you see in-game screen) and it puts you in combat. It breaks few addons and raid menu by doing so, because combat appears before addons load is my guess, which is the main reason im reporting this. You can leave the combat by going far away from the spot it happened, but you can't mount(since combat bug). One of the spot in SW will be in attachment picture.

EDIT: Most of Neutral (yellow name) mobs puts you in combat upon login (does fantom damage); NPCs in SW prison does the same for example.

![image](https://user-images.githubusercontent.com/131989916/234909869-58f3d7d4-6d0f-4682-98f6-b0abedff5365.png)

**Comment by Duskhaven** [comment]
Fixed after restart
