### ISSUE TITLE
Skinning Vile'rel

### ISSUE THREAD

**Issue by Kemokid420** [Duskhaven/Bug-Reports#1256]
you can skin Vile'rel of the Seven, in BRD
idk if thats intended
a dead humanoid, got a black dragonscale

on the screen sadly doenst show the skinning symbole

**Comment by Kemokid420** [comment]
![WoWScrnShot_042723_214321](https://user-images.githubusercontent.com/131711367/234975436-0774e0e7-4d80-4ce9-aa25-ebfcb55cc02a.jpg)

**Comment by Duskhaven** [comment]
Fixed
