### ISSUE TITLE
Melee Trials of Cenarias

### ISSUE THREAD

**Issue by Zikareous** [Duskhaven/Bug-Reports#1258]
When taking the quest and entering the trial for melee, none of the NPCs will do anything. I have to pull the boss to the npcs then they will react, however even standing there not doing anything they won't taunt or do what they are supposed to causing me to get 4 shot by the boss. 

Also NPCs don't immediately reset on failure. Not sure if that's intended or not.

**Comment by Duskhaven** [comment]
Intended, mobs only attack if they are near xavius.

NPC's only reset if you reset your lockout.
