### ISSUE TITLE
[Mage] Fire Blast Rank 7 Bug

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#126]
I don´t get the 20% increased Fire Critchance, when I cast the max rank Fire Blast like the tooltip shows.

**Comment by Duskhaven** [comment]
Fire Blast only grants crit if you are a Fire Mage.

**Comment by Flex13** [comment]
One of my Specs is fire. I have dual spec. Still no 20% crit. Is the 20% fire crit bound to a specific talent that i didnt skilled/maxed out?

**Comment by Flex13** [comment]
![image](https://user-images.githubusercontent.com/127632931/224531856-c291a58f-f3b2-4105-8504-f308786a48a6.png)
