### ISSUE TITLE
Swift Zulian Tiger HC size and seat

### ISSUE THREAD

**Issue by Minearm** [Duskhaven/Bug-Reports#1260]
It seems that HC Zulian Tiger is somewhat smaller than the normal version. But could be race difference, I don't have a way to compare since most people don't have it yet. Though my comparison was me with HC mount (night elf) vs gnome with normal mount, and the gnome had the bigger one. 
The night elf model also sinks into the tiger, both legs and arms.

Model issue: 
![image](https://user-images.githubusercontent.com/129947503/235081484-1af002d8-2440-4618-a19e-a5232a72ca00.png)

Size difference: 
![image](https://user-images.githubusercontent.com/129947503/235081542-11bf3450-f52f-40bb-b8ae-001987e322ed.png)

**Comment by Duskhaven** [comment]
Gnomes have bigger mounts.
