### ISSUE TITLE
Chaos Strike critical modifiers

### ISSUE THREAD

**Issue by Minearm** [Duskhaven/Bug-Reports#1262]
It seems Chaos Strike got changed from 200% crit damage to 150% sometimes during the last few days, since you changed/is changing it from Fire to actual "chaos damage" maybe this was an unintended change? It also seem to be critting based on spell crit rather than melee crit at the moment.

**Comment by Khano11** [comment]
Can confirm. few weeks ago chaos strike with my gear would crit for 2k damage. Now its crit damage is 900.

**Comment by Duskhaven** [comment]
Fixed after restart
