### ISSUE TITLE
Hardcore Challenge Showing Ironman Challenge Debuff

### ISSUE THREAD

**Issue by wonderduck234** [Duskhaven/Bug-Reports#127]
Have created a character twice and joined the hardcore challenge and it is showing the Ironman Challenge Debuff and it seems XP/Reputation is reduced as well.

**Comment by Duskhaven** [comment]
This is intended. By attempting the HC Challenge your XP is automatically lowered by 50%, the Reputation is not decreased and is just a visual bug.
