### ISSUE TITLE
DH new mitigation have a proc bug

### ISSUE THREAD

**Issue by Drazkanil** [Duskhaven/Bug-Reports#1270]
when you enter metamorphosis form, you don't get savage defense again, unless you enter metamorphosis again, but out of it you don't go back to activate this passive.

**Comment by 0Ezic0** [comment]
Tested.
1) You trigger Savage defense every white (auto attack) crit.
2) Its re-activated each crit.
3) Works in Meta.
4) After Meta ends you no longer can proc this buff like ever again.
5) After Meta ends you need to clicking off Demonic Tattoos and than entering Tank stance again will allow you to get the procs again. (this needs to be fixed)

**Comment by Duskhaven** [comment]
Fixed
