### ISSUE TITLE
T2 8 set Bonus For Enhancement Shaman Tank doesn't work

### ISSUE THREAD

**Issue by Obleh** [Duskhaven/Bug-Reports#1272]
I'm not getting the 15% Block Rating, not getting the "Lesser Earth Shield" and I have no clue how Elemental Bulwark is supposed to "Interact" with my Maelstrom Stacks. It deals the exact same amount of damage regardless of having zero or 5 stacks of Maelstrom, and does not consume them if this was the intended way of having it work. I would very much prefer it not consuming Maelstrom stacks as there are very good uses for it outside of Elemental Bulwark, but I would take the survivability of it while tanking for sure.

Suggestion: NOT PART OF THE BUG. I would like for you to consider doing something like you did for demon hunter, for shamans with damage reduction based on AP, currently the only thing we have to mitigate magic damage is the absorb provided by Stoneclaw Totem, and while this is alright for the purpose, it just doesn't provide that much cover from being comboed by overlapping skills in Heroic content. If not maybe consider adding something like Elemental Warding from the Elemental tree into some of the talents in Enhancement, you could also potentially add it to the first of row of enhancement since there is not many options for Shaman Tanks anyways and it is a talent that is completely skipped in Elemental anyways.

**Comment by Obleh** [comment]
Also 6 piece T2 is not giving the 10% Increased Health when you use Shamanistic Rage

**Comment by Duskhaven** [comment]
Fixed after restart
