### ISSUE TITLE
Demon Hunter Fury Stacks Internal Cooldown

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#1274]
Having an invisible internal cooldown on fury stacks of 3 seconds makes playing around fury stacks very awkward, especially with Glaive Throw no longer being on GCD.

Current behavior:
- Getting a fury stack from Chaos Strike or Glaive Throw has an internal cooldown of 3 seconds

Expected behavior:
- No internal CD on fury stacks

**Comment by Duskhaven** [comment]
Intended
