### ISSUE TITLE
tinker dungeon problem?

### ISSUE THREAD

**Issue by Sumsura** [Duskhaven/Bug-Reports#1278]
I wanted to run gnomeregan on my gnome tinker so i chose to use the dungeon finder to specifically find a group. After finding one and transporting to the dungeon i found myself in the instanced version tinkers warp to to learn the abilities not the actual dungeon. i tried to teleport out and back in many times. Strangely i could see the party on the map but i could not interact with them. o still got EXP and could roll on drops but it felt wrong so i left the group. I would love to run gnomeregan but i am unable to at this moment.

**Comment by Duskhaven** [comment]
Refer to https://github.com/Duskhaven/Bug-Reports/issues/35
