### ISSUE TITLE
Teaching of the Monastery: Tank

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#1280]
'Teachings of the Monastery: Tank' gets locked after putting 2/2 into the Discipline Talent 'Grace' - the player gets the "You can't do that yet" error message. TotM:DPS works just fine.

**Comment by harukaze3** [comment]
Putting only one point in Grace fixes this temporarily.

> Haru

**Comment by Duskhaven** [comment]
Intended
