### ISSUE TITLE
Postmaster only recoveres 1 satchel of helpful good

### ISSUE THREAD

**Issue by Kremdes** [Duskhaven/Bug-Reports#1281]
when you have full bags finishing a dungeon, the postmaster only send you 1 satchel of helpful goodsinstead of the 2 listed in teh RDF tool

**Comment by Duskhaven** [comment]
Cannot replicate

**Comment by DuskhavenPlayer** [comment]
I've experienced the same issue two times now. Bags full and once out of dungeon and checking mailbox, postmaster only sent me one satchel and not two.

**Comment by Kremdes** [comment]
yep, when you finish RDF and dont have free bagspace, only 1 satchel is send to you via postmaster
