### ISSUE TITLE
Judgement Belt (Retribution) Drop Rate is Bugged

### ISSUE THREAD

**Issue by plasma-93** [Duskhaven/Bug-Reports#1291]
We do a LOT of raids, and we have dropped the ret belt about 90% of the times we kill the bird in ED, or Vael. 

I'm not exaggerating with 90%, it's like 14/15 since we noticed the trend atm, it's insane lol

**Comment by Duskhaven** [comment]
Fixed

**Comment by Xenbiotic** [comment]
Can confirm fixed, much hype
