### ISSUE TITLE
Postmaster Malown doesn't spawn after opening the 3rd mailbox

### ISSUE THREAD

**Issue by Tegas** [Duskhaven/Bug-Reports#1295]
I've tried this a couple times now. According to the wowhead guide, you kill the Courier and he drops 3 keys. You open the 3 mailboxes and the postmaster is supposed to spawn. But the third mailbox just spawns another set of 3 Undead Postmen. 

reference info:
https://www.wowhead.com/classic/guide/stratholme-live-dungeon-strategy-wow-classic#postmaster-malown

**Comment by Duskhaven** [comment]
Fixed
