### ISSUE TITLE
Mux's quality goods did not contain any goblin rocket fuel

### ISSUE THREAD

**Issue by Tegas** [Duskhaven/Bug-Reports#1296]
I've been working on the t0.5 quest line and noticed that the bag you get as part of the chain "The Ectoplasmic Distiller" did not give me the 8 goblin rocket fuel that it was supposed to.

https://www.wowhead.com/classic/quest=8921/the-ectoplasmic-distiller

https://www.wowhead.com/classic/item=22320/muxs-quality-goods#contains

**Comment by Duskhaven** [comment]
Cannot replicate

![image](https://user-images.githubusercontent.com/123925176/236006209-f6b1aac0-71d5-49bf-827a-9e0ab8b36911.png)
