### ISSUE TITLE
[Shaman Spell] Storm Cloud

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#13]
Character Name: Magni
Screenshot/Video: Not needed.
Issue: The spell Storm Cloud shows Target Too Low Level error whenever you try to cast it on a friendly player and can only be casted on yourself. Not what the spell tooltip says at all.

**Comment by Frauce** [comment]
Can confirm. I had to write a macro to target myself for this spell and it is not random but targeted.

**Comment by Duskhaven** [comment]
Storm Cloud is only castable on yourself until Level 60, this will be added into the Description with a future patch.
