### ISSUE TITLE
Cloak of shadows gcd

### ISSUE THREAD

**Issue by Novawins** [Duskhaven/Bug-Reports#1301]
99.999% sure cloak of shadows "rogue" shouldnt be on gcd. so there is that.. can it be fixxed (if it isnt the 0.001% ofc )

**Comment by Duskhaven** [comment]
Intended 
![image](https://user-images.githubusercontent.com/123925176/236005541-27f2ea8f-f4c2-47af-85b3-9f4ce56158e8.png)
