### ISSUE TITLE
Death knight T1 2 piece bonus not working

### ISSUE THREAD

**Issue by oniichan123** [Duskhaven/Bug-Reports#1304]
Death knight T1 set bonus (of Might) states " Gain 4% increased damage whenever your runes are on cooldown" But you never get the bonus damage when runes are on cooldown, nothing procs, checked damage manually and it doesnt increase also.

**Comment by Duskhaven** [comment]
Cannot replicate

**Comment by Trommerwow** [comment]
> 
@Duskhaven 
It can be replicated. Blood Strike will activate the T1 2 piece bonus, but not Pestilence or Blood Boil. Here is some image proof. First image I use Bloodstrike, which works just fine. 
In the second image, I use Pestilence, which doesn't work. 
![Blood Strike](https://user-images.githubusercontent.com/131488756/236020882-472f3619-5aba-40b8-9d1a-4ce04cb1423a.jpg)
![Pestilence](https://user-images.githubusercontent.com/131488756/236020897-a3128f71-fb87-4514-a5f0-36c6fb9b7d06.jpg)


The addon I use for my Runes is called Magic Runes.
