### ISSUE TITLE
Piercing Jab

### ISSUE THREAD

**Issue by dariumz** [Duskhaven/Bug-Reports#131]
Piercing Jab doesn't seem to apply it's damage over time effect (Eye of the Tiger) all the time. When fighting regular mobs, I have noticed it's lacking, but when I went to fight a target dummy too high for me to hit, it did apply the damage over time effect.

Lacking this effect not only means lower damage output, but also the heal mentioned in the tooltip of Piercing Jab is also not happening.

**Comment by Duskhaven** [comment]
Eye of the Tiger is not available until a certain Level is reached.

**Comment by dariumz** [comment]
Thanks for the reply, tho it seems to be based on the mob you attack, moreso than your personal level?

Would it be possible to clarify such things either on the class change page, or through the tooltips, tho I get some of the ingame tool tips are getting lengthy.

Thanks for the quick responds and awesome work.
