### ISSUE TITLE
Zeal affected by spell hit?

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#1314]
![image](https://user-images.githubusercontent.com/31871078/235925607-65467a48-feba-4585-bdce-33d7a8447cd9.png)
As shown in the picture, im way above over the hit cap for 2h and special melee attacks and there's a MISS on the Zeal hit there.
![image](https://user-images.githubusercontent.com/31871078/235925764-e3b2fa55-76ed-43ae-b0be-7c5af32da6fd.png)
Same shown on the consecration ability (But that might be cause that IS affected by spell hit? idk)

Total melee hit: 12.30% (10.30% from gear + 2% from Radiance Aura)
Total Spell Hit: 14.88% (12.88% from gear + 2% from Radiance Aura)

**Comment by Duskhaven** [comment]
Intended.
