### ISSUE TITLE
Base T1 for shamans is available to be purchased for Hydraxian Sigils, but paladin base T1 is NOT available

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#1317]
Base T1 for shamans is available to be purchased for Hydraxian Sigils, but paladin base T1 is NOT available

**Comment by moonfirespammer** [comment]
Druids also unavailable - only shamans can buy them as of now.

**Comment by Duskhaven** [comment]
Intended. Druid and Paladin's have received a custom version for the healing role.

**Comment by moonfirespammer** [comment]
There are specific use cases for the base T1 set as well. Could you please give us the option the purchase T1 base as well?
