### ISSUE TITLE
Spectral Tiger & Elite Greatwyrm tooltips

### ISSUE THREAD

**Issue by Paltanei** [Duskhaven/Bug-Reports#1321]
Hey !

The tooltip of the Spectral tiger goes wrong.
In retail bc / wrath , we have 2 types of spectral tiger 

Spectral Tiger : 60% https://www.wowhead.com/tbc/item=33224/reins-of-the-spectral-tiger
Swift Spectral Tiger : 100% https://www.wowhead.com/tbc/item=33225/reins-of-the-swift-spectral-tiger

So, here the tooltip displays the wrong thing

Same thing for Elite Greatwyrm , tooltip display 60% and not 100% with the max comp

But the ingame move speed is good ( 100% with max comp )

https://gyazo.com/a4ab62a6533c09da32dda0b239005f9e
https://gyazo.com/fdc451b7beb5269a5b2885247fbabd02
https://gyazo.com/c95e2bda70491d1aeba4acf81c27145b

**Comment by Duskhaven** [comment]
Intended. Tooltips are not adjusted when your riding skill is increased
