### ISSUE TITLE
Lupine Horror +8

### ISSUE THREAD

**Issue by HemorrhageOOK** [Duskhaven/Bug-Reports#1326]
Lupine Horror +8 from Shadowfang Keep +8 seems to have an issue with its "Thunderclap" ability. This ability is routinely 1-shotting non-tanks with its Thunderclap ability, and doing exceedingly more damage than is shown in Combat Log. As a DK Tank with 8k+ HP and 10k Armor, this ability is even nearly 1 shotting me through defensives.

In weeks prior, I have completed SFK 8s as a DPS and a Tank, and these Lupine Horrors have never been an issue like they are now.

**Comment by Duskhaven** [comment]
Fixed
