### ISSUE TITLE
Razormaw Quest incompletable

### ISSUE THREAD

**Issue by jtstansberry** [Duskhaven/Bug-Reports#1327]
In the quest Razormaw on Wyrmscar Island in Bloodmyst Isle, throwing the dragon bones on the pyre does not summon Razormaw. Razormaw can be seen stationary, flying above the island. The correct behavior would be that Razormaw flies around and toward Talon Stand (the mountain top on the island) until he eventually approaches the pyre where the player can begin the fight.

**Comment by Duskhaven** [comment]
Walking towards his direction starts his movement.
