### ISSUE TITLE
Repair Bots unable to be placed

### ISSUE THREAD

**Issue by EsmerZinnia** [Duskhaven/Bug-Reports#1334]
Whenever I, night elf demon hunter, attempt to place down a repair bot in Stratholme or Eastern Plaguelands my character will get stuck in the summoning animation and nothing will happen. I can press escape to get out of it. No item is consumed, no bot is summoned.
I've seen another player, human death knight, place a bot in Stormwind with no issue.

**Comment by Duskhaven** [comment]
Cannot replicate
