### ISSUE TITLE
Arcerus: The Ebon Hold Teleporter is not working (Death Knight)

### ISSUE THREAD

**Issue by Trommerwow** [Duskhaven/Bug-Reports#1335]
I tried standing in different spots, jumping, and praying. No dice. Dks can't reach the other room.
![tp not working](https://user-images.githubusercontent.com/131488756/236329819-ebcc15ea-cc5c-4c87-adb2-d9ac83f258b9.jpg)

**Comment by Duskhaven** [comment]
Fixed
