### ISSUE TITLE
DE doesn't work properly on demo warlock.

### ISSUE THREAD

**Issue by Leffany** [Duskhaven/Bug-Reports#1336]
"Demonic Empowerment has received an additional Effect: When used on your Felguard your Felguard will whirl around over 8 seconds dealing damage and additional chaos damage every second for 8 seconds" this doesn't work anymore after restart.

**Comment by Carrek** [comment]
now it doesn't even spin

**Comment by Duskhaven** [comment]
Fixed. The Spell has been redesigned as a solution.

Your Demonic Empowerment now causes your Felguard to have 50% increased Attack speed, causes his auto-attacks to deal additional Fire damage to nearby enemies, and his Cleave emits a Chaos Nova for the duration.
