### ISSUE TITLE
Heal not scaling with Spellpower

### ISSUE THREAD

**Issue by Vyntoras** [Duskhaven/Bug-Reports#1337]
None of the ranks of Heal scale with any amount of spellpower. Tested it on 800, still heals the base amount.

**Comment by Duskhaven** [comment]
This is intended. Some lower ranked Skills receive less SP scaling the higher your Level is.

Both tested with 2000 SP

1. Level 60
2. Level 39
![image](https://user-images.githubusercontent.com/123925176/236582694-866b7ce9-dccd-458a-9c57-ad0122ccbcca.png)
![image](https://user-images.githubusercontent.com/123925176/236582741-d3b6c212-aac6-4267-a3cf-85d912d47637.png)
