### ISSUE TITLE
Cant logon to any toon on the server keeps crashing

### ISSUE THREAD

**Issue by Agibaan** [Duskhaven/Bug-Reports#134]
I cant log on to any toon on the server I first made a tinker got through the tinker starting stuff to level 6 and tried to port to SW it then crashed in the middle of loading and now I cant load onto any toon on the server even if I make a new toon in game tinker name is Blinkerton

**Comment by Duskhaven** [comment]
Please follow the instructions on Discord, your files are most likely not located where they should be.

**Comment by Agibaan** [comment]
> Please follow the instructions on Discord, your files are most likely not located where they should be.

it work till i use the portal from the gnome starting zone its now giving me a error code #134 (0x85100086) fatal condition

**Comment by Agibaan** [comment]
> Please follow the instructions on Discord, your files are most likely not located where they should be.

i remade my tinker the issue is zoning into SW i try make other races and they log in until i made a human they wont login ether
