### ISSUE TITLE
Iron Man experience

### ISSUE THREAD

**Issue by Walami** [Duskhaven/Bug-Reports#1346]
If you are doing the iron man challange, you only get 25% XP not 50%. It deducts 50% from debuff and after that another 50% from the trinket.
Quest text said it gives 80 XP,  and it only gave 20.
Not sure if this is on purpose or by mistake.

**Comment by Duskhaven** [comment]
Using the Trinket during the HC Challenge reduces your XP by an additional 50%.

**Comment by Walami** [comment]
Okay, but there is no indication that XP is reduced in HC Challange. If I take off the trinket I lose the Iron Man challange debuff.
