### ISSUE TITLE
Monk tank stance not usable with 2/2 Grace

### ISSUE THREAD

**Issue by zypr** [Duskhaven/Bug-Reports#1347]
Hey team,

I discovered yesterday that the monk tank stance is not usable when taking 2/2 points of the Grace talent in the discipline tree. The monk DPS stance is still working. If I try to cast the tank stance, it just says "You can't do that right now." I unlearned the talents and put only one point in Grace, and the tank stance is now working. However, after adding the second point in Grace, it stops being usable.

Thanks for your hard work, and have a nice day!

**Comment by Duskhaven** [comment]
Fixed after restart
