### ISSUE TITLE
blackrock Upper city flame aggro

### ISSUE THREAD

**Issue by Chachisoothe** [Duskhaven/Bug-Reports#135]
the statues in the elemental boss before the emperor of the dark iron left me and my party in a state of aggro, first we thought it was the dark iron in the other room but after the 2nd attempt i believe it to be the flames from the statues, i've seen at least one statues continue to spew flames even after we left the room, vanish and feign death wasn't able to drop the aggro

**Comment by Duskhaven** [comment]
This is now fixed.
