### ISSUE TITLE
Mortal shots from Marksmanship tree stopped working (again!)

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1353]
Abilities ive tested it with: Aimed shot, Chimera shot, Scrap Bullet, Rapid Shot, Wild Quiver

**Comment by GoldWarr** [comment]
same here, aint working since the core update yesterday, the increases crit damage ratio of 30% does not seem to apply.
a normal Arcane Shot that dealt 1,7k befor the update now deals regulary 1,3-1,4k.
This has been tested on dummies yesterday.
