### ISSUE TITLE
Tinker - MG-X2 Turret: Unable to loot mobs after use

### ISSUE THREAD

**Issue by Ashundoktur** [Duskhaven/Bug-Reports#1368]
After using the MG-X2 Turret I am unable to loot mobs that it has attacked. It almost acts like the turret is a separate entity to me, "tagging" it to itself, shows the mob is still tagged by me.

**Comment by Duskhaven** [comment]
Intended on 3.3.5. The same behavior applies to Demons and Pets. If your Pet dealt too much damage or you didnt attack the creature it cant be looted.
