### ISSUE TITLE
Rogue assass new talent bug

### ISSUE THREAD

**Issue by LemsibakZak** [Duskhaven/Bug-Reports#137]
Leeching scoundrel does nothing.
Another rogue also told me that internal bleeding doesn't work, not sure about it though.

**Comment by SI7D** [comment]
adding to this, the leaching scoundrel not working properly. Currently using any of the deadly poisons does not give a passive buff.

**Comment by Duskhaven** [comment]
Leeching Scoundrel now works correctly after the restart.
