### ISSUE TITLE
Yebb Neblegear doenst have the quest [More Glowing Scorpid Blood] - Darkmoon Faire

### ISSUE THREAD

**Issue by IvanIvanov1699** [Duskhaven/Bug-Reports#1372]
The Darkmoon Faire NPC Yebb Neblegear doesnt have the repeatable quest [More Glowing Scorpid Blood] for turning in Glowing Scorpid Blood after the first normal quest turn in.

**Comment by Duskhaven** [comment]
You need atleast 5500 Reputation to accept the repeatable Quests
