### ISSUE TITLE
Impact talent dosent work on mage

### ISSUE THREAD

**Issue by Swiisha** [Duskhaven/Bug-Reports#1376]
Hello, i have an issue where the talent Impact from Mage dosent work ,the talents says that when you proc the Impact ur next  fire blast gonna stun the enemy 100% well it dosent do anything the talent procs and appears like it works but it never dose the stun !

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/1089
