### ISSUE TITLE
Warpwood Pod bugged in Diremaul East.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1381]
This Warpwood pod is mainly used to gather Runn Tum Tube in Diremaul East.
Issue is nothing happens when you click on them.

There is no other way to gather this ingridient to make the Runn Tum Tuber Suprise cooking Dish.

Also seems like some of them spawn **unlimited** amounts of invisible mobs, this could be abused to lag the server.

**Comment by Duskhaven** [comment]
Spawn bug has been fixed. Runn Tum Tuber can also drop from Pusillin and the imp mobs.
