### ISSUE TITLE
Shatterspear Troll's are no longer attackable as an Alliance Player

### ISSUE THREAD

**Issue by Heldojin** [Duskhaven/Bug-Reports#1383]
Those Trolls are normaly Yellow to alliance Player and Green to Horde Players. This was one of the Best farming Spots for Alliance, cause they are kinda hidden and got a good Respawn Rate. They only went Friendly for Alliance after Cataclysm happend. 
Please make them Neutral again.

**Comment by Duskhaven** [comment]
Intended
