### ISSUE TITLE
Stuck in warmode/PvP, found the culprit

### ISSUE THREAD

**Issue by ihugyourmom** [Duskhaven/Bug-Reports#1391]
Issue: I enabled warmode, and after that got stuck in pvp. Couldnt log out without a timer, no rest in cities etc.. So after trying a lot of things, and making 2 tickets which also resulted in nothing.

Fix:
I seems that the issue are group quests, maybe of pvp nature?
For me the problem was solved when i abandoned : King of the Gordok
which is a quest from Dire Maul (tribute run)

After a logout i now get rest in cities, and no log out timer aka fixed!

Thought:
It might be a direct issue with that quest, or just the nature of said quest. since we are xfaction, it might put us in pvp mode or smth.

credit: Vigorcheck, for vital information <3

**Comment by Duskhaven** [comment]
Fixed. The Quest no longer flags you for PvP.
