### ISSUE TITLE
Tauren Plainsrunning Rank 2

### ISSUE THREAD

**Issue by Davaerst** [Duskhaven/Bug-Reports#1392]
Plainsrunning Rank 2 tooltip states it can be cast while moving, but it can't.
Tooltip also says movement speed is increased by 90%, however the actual buff says 100%
![image](https://user-images.githubusercontent.com/36208013/236685733-c0078aac-b67d-4bce-9c60-86c907ae5832.png)
![image](https://user-images.githubusercontent.com/36208013/236685753-483f421c-4ad6-497d-8233-8d6115b41932.png)

**Comment by Duskhaven** [comment]
Tooltip is corrected with the upcoming patch
