### ISSUE TITLE
DH Fury stacks seem to have a internal cooldown. Don't know if it is intendet

### ISSUE THREAD

**Issue by Fixi555** [Duskhaven/Bug-Reports#1393]
so basicly if i use glavetrhow thats off gcd and felrush i only get 1 Fruy stack. I tested pure Chaosstriking after that and it seems that only ever second chaosstrike gives you 1 stack of fury, I don't know if that was a intendet choice but fury should get +1 stack by yousing any DH ability right?

**Comment by Duskhaven** [comment]
Fury stacks have a intended 2.5 sec ICD.
