### ISSUE TITLE
Glyph of Inner Fire

### ISSUE THREAD

**Issue by SylvieDuskhaven** [Duskhaven/Bug-Reports#140]
Attempting to use this Glyph fails with the error message "That Glyph is already inscribed in your spellbook."

I'm aware that the glyphs is passively active while talented+ in monk stance.

I feel like there should something perhaps in the tooltip that would dissuade people from buying/making this glyph.
Or maybe even just removing it entirely?

**Comment by Duskhaven** [comment]
The Glyph has been removed.
