### ISSUE TITLE
T1 Giantstalker Hunter 5 Set Bonus Lone Wolf

### ISSUE THREAD

**Issue by BugSquisher9000** [Duskhaven/Bug-Reports#1402]
This is not working correctly, Im not getting the extra 3% dmg.

With 3% extra from Lone Wolf should grant me wep min dmg by 540 and max wep dmg by 660.

![image](https://user-images.githubusercontent.com/131832227/236802895-8ebcd5af-fa2e-4047-8cf2-c056239a459e.png)
![image](https://user-images.githubusercontent.com/131832227/236802992-eb4715a2-0820-48e8-9f51-4bc3c027a1af.png)

**Comment by Duskhaven** [comment]
Fixed after restart
