### ISSUE TITLE
Poisonous Shots - MM talent

### ISSUE THREAD

**Issue by BugSquisher9000** [Duskhaven/Bug-Reports#1403]
Does not deal 10% dmg as tooltip says, looks like fixed dmg. 

![image](https://user-images.githubusercontent.com/131832227/236804059-6ec9f304-f2f2-4734-a9e3-b3d2bc1cf694.png)
![image](https://user-images.githubusercontent.com/131832227/236804444-03a00d1f-fe7e-421b-946d-7ccbb056f1b5.png)

**Comment by Duskhaven** [comment]
Fixed
