### ISSUE TITLE
Steady Shot

### ISSUE THREAD

**Issue by BugSquisher9000** [Duskhaven/Bug-Reports#1406]
To make Ranged hunter QoL for this V+ is too make steady shot usable while moving.

**Comment by Heldojin** [comment]
What has that to do with a Bug Report?

**Comment by BugSquisher9000** [comment]
> What has that to do with a Bug Report?

Better to write a suggestion here than on discord that is filled with bias idiots who downvotes anything that is not related to Shaman or Druid

**Comment by Duskhaven** [comment]
Belongs in the suggestion channel
