### ISSUE TITLE
Disengage

### ISSUE THREAD

**Issue by BugSquisher9000** [Duskhaven/Bug-Reports#1408]
Disengage has a GCD which it should not have.

https://wotlk.evowow.com/?spell=781

**Comment by Duskhaven** [comment]
Intended, so melee hunters cannot spam disengange during the harpoon buff.

**Comment by BugSquisher9000** [comment]
> Intended, so melee hunters cannot spam disengange during the harpoon buff.

But then make it so they have a 1 cd when in aspect of the beast. You're punishing us who play Ranged Hunter since we also Trapweave, and have to wait for a gcd just makes it that disengage is a useless ability as it is faster to run out to 5 yard
