### ISSUE TITLE
Field Duty bugging out

### ISSUE THREAD

**Issue by Vyntoras** [Duskhaven/Bug-Reports#1415]
The assignments from the quest "Field Duty" are bugging out like crazy. After taking 2 combat assignments I cannot open anymore. Whenever I try to open a new assignment the item just disappears out of my inventory. Sometimes just nothing happens and then it says "Already looted" without getting an item. The latter problem happened to me on a Logistics Assignment too.

Long story short, I can't get more Combat Assignments to even be able to work towards the final item which I'm grinding for. Tried to do the first 4 quests, hoping I could get new ones, but it still disappears.

The same problems I had with Combat Assignments also happens with Tactical Assignments. The ledgers disappearing instead of dropping any quests.

**Comment by Vyntoras** [comment]
This also happens on Tactical & Logistical Followup Assignments.

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/623
