### ISSUE TITLE
Fel Energy/DH stance not giving damage increase

### ISSUE THREAD

**Issue by FerisRogue2** [Duskhaven/Bug-Reports#1422]
The tooltip states that it grants a flat 3% damage increase, but is actually giving +3% crit chance (which on average is half of the dmg increase that it's claiming it gives you).

**Comment by FerisRogue2** [comment]
![WoWScrnShot_050823_183221](https://user-images.githubusercontent.com/132957172/236955530-4e312435-08be-425c-9e1c-3c3623b67867.jpg)
![WoWScrnShot_050823_183246](https://user-images.githubusercontent.com/132957172/236955533-14d4d380-c238-4581-b642-3adc9ddeadcb.jpg)
Screenshots. No gear/talent changes

**Comment by Duskhaven** [comment]
Cannot replicate. 3% from Fel Energy, 5% from Stance.

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/520c9da4-b65b-4156-bbcc-52b9a8030254)
