### ISSUE TITLE
Aspect of the Hawk bug

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1427]
Issue is Aspect of the Hawk (Rank 7) should grant as tooltip mentions 150 AP.
But in reality you only get 120 AP.

**Comment by Duskhaven** [comment]
Its not supposed to grant 150 AP 

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/a59a4c55-f9aa-45c8-9494-906615638bc2)
