### ISSUE TITLE
Assasination DH Abuse

### ISSUE THREAD

**Issue by xnexodus** [Duskhaven/Bug-Reports#1440]
Saw alot of Assasination Rogues abusing DH abilitys, If you dont Talent Focused Attacks you can be in the DH stance and will be able to Use alot of DH abilitys and go out of the Stance and pump 4k DPS meanwhile being in Methamorphosis or Blade dance.

**Comment by xnexodus** [comment]
Make it something like wear one Glaive to let the stance turned on and if theres no more Glaives Equipped turn the stance off

**Comment by Duskhaven** [comment]
Fixed.
