### ISSUE TITLE
Quest: The Grimtotem Weapon

### ISSUE THREAD

**Issue by mjako81** [Duskhaven/Bug-Reports#1443]
The totem that needs to be put down for the quest doesn't work.
When I try putting the totem down close to a crocolisk, the crocolisk destroys the totem before I can do anything.
When I attack the crocolisk and then put down the totem before killing the crocolisk it doesn't count towards the quest.
When I put the totem down away from the crocolisk and then attack and kite the crocolisk to the totem, the kill doesn't count towards the quest.
I tried these several times and it never worked.

**Comment by Duskhaven** [comment]
Fixed
