### ISSUE TITLE
Dancing Rune Blade 

### ISSUE THREAD

**Issue by Logan6969** [Duskhaven/Bug-Reports#1446]
Dancing rune blade does not attack my target which whom I'm attacking.  Also does not attack target dummies when its suppose to.  Rune blade/Wep skill is suppose to mimic your Death knights Damage.   It also is a main part of the blood dk dps rotation. so that's 3-5% dmg loss.

**Comment by Duskhaven** [comment]
The Rune Blade does not work on training dummies/neutral mobs.

**Comment by KreepAK** [comment]
> The Rune Blade does not work on training dummies/neutral mobs.

Tested that in duel. Not working. Please reopen the ticket or should I create a new one?
