### ISSUE TITLE
(Druid) Blessing of Elune should apply a copy of your Rejuvenation, but it doesn't.

### ISSUE THREAD

**Issue by Trommerwow** [Duskhaven/Bug-Reports#1448]
Awesome spell, but it's not working as intended. Tooltip says it casts a copy of your Rejuvenation, but it casts a weaker hot instead. Here is some testing I did that proves that the heal copy isn't actually Rejuvenation, resulting in a MUCH weaker heal.

The copy can't be consumed with Swiftmend.
The copy has a shorter duration and total "ticks" than normal rejuv. 11 sec and 4 ticks (should be 15 sec and 5 ticks before haste) This suggests that the first tick is skipped somehow.
The copy doesn't benefit from haste as the normal rejuv does. With +17% haste, it still has 11 sec duration.
The copy doesn't gain +healing from Idol of Rejuvenation (+50 Spell Power to Rejuvenation).
The copy can't be crit with m+ S2 2 set bonus.

As the screenshot shows, this adds up to a heal that heals for less than half of a normal Rejuvenation.

Thanks for looking into this!

![Blessing of Elune bug](https://github.com/Duskhaven/Bug-Reports/assets/131488756/00d68f75-5d7c-4976-b341-681a9472590f)

**Comment by Duskhaven** [comment]
SP scaling has been increased to make up for the missing synergies.

**Comment by Trommerwow** [comment]
> SP scaling has been increased to make up for the missing synergies.

@Duskhaven Awesome! Thanks for the quick response. If I may be so bold, what's the reason for not making it a true copy of a normal Rejuvenation? I'm mostly sad that it doesn't proc Revitalize. :(
