### ISSUE TITLE
Frost DK buffs

### ISSUE THREAD

**Issue by Serial9** [Duskhaven/Bug-Reports#1450]
The buffs to Frost DKs doesnt seem to be right, atleast from me and some other DKs, pretty much nothing changed damage wise, so doesnt seem right.

Obliterate etc. is exact same crits as before buff

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/429ede1b-fbe5-478c-b092-402e2be34cf9)
