### ISSUE TITLE
Tinker: Tier 1 8 piece set bonus doesnt work

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1458]

**Comment by Duskhaven** [comment]
Cannot replicate. 10% hit is correctly given during Machine Gun 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/5a4617c4-2606-436b-a52e-26320e4ea09c)

**Comment by ghost** [comment]
That is the thing, you get that extra 100 rating even if you dont have it equipped, assumed it was another "shadow change" for all tinkers regardless of gear
