### ISSUE TITLE
All shaman tier 2 is just terrible...

### ISSUE THREAD

**Issue by slaptime2** [Duskhaven/Bug-Reports#1463]
I am not sure if this has been looked into. 

Elemental shaman tier 2 - Extremely bad set bonuses that legit offer nothing in comparison other lower tiers and mythic+ set bonuses. The gear has less stats than Mythic 2-6+, Mythic+8, tier 1 gear. - As a Elemental shaman you legit only want the 2 pieces for the 30haste as all other lesser sets are easier to get tier gear is better and the bonuses are also better. I have 8 pieces of this gear from offspec rolls and I legit refuse to even attempt elemental spec as the gear is so bad the bonuses are not fun at all.

Enhancement shaman tier 2 - Not only do the set bonuses do not even work the AP, Hit and Crit lower than t1 and mythic gear. The only thing this has better than other pieces of gear is the pure stats. As a enhancement shaman you legit only want the 2 pieces for the expertise as all other easier to get tier gear is better and the bonuses are also better. I have 4 pieces and every enhance I have spoken to who has the 8 piece has swapped of it due to it being broken and terrible.

Resto Shaman tier 2 - Resto gear overshadowed by t1 set bonus and stats and Mythic+8 gear. Even the stats are lower on some items. The set bonus is also worse than legit all other tier gear in the game. - Compare this to any other set bonuses as stats and you'll see the issue.

It comes to a point where you dont run any tier 2 except for 2 pieces. As a shaman is feels extremely unrewarding seeing everyone else get extreme healing/tank and dps increases from the more tier 2 they equip. I want to equipping and unlocking of new bonuses as fun but right now you have legit no reason to try to get any additional tier pieces from BWL or Ony as it offers a ton more to other classes.

**Comment by Duskhaven** [comment]
Belongs in suggestions
