### ISSUE TITLE
Point of No Escape off-hand hits with Raptor Strike and Mongoose bite doesn't work

### ISSUE THREAD

**Issue by Machanu** [Duskhaven/Bug-Reports#1467]
Tested with both 1/2 and 2/2 talent points, the talent Point of No Escape does not do additional damage when using Mongoose Bite or Raptor Strike, neither as white hits, additional damage on the ability itself, or a seperate off-hand proc.

Can't say if the crit bonus is active, but it doesn't give any indication.

**Comment by Duskhaven** [comment]
Cannot replicate
