### ISSUE TITLE
Tinkerer can learn hunter abilities they can't use and more

### ISSUE THREAD

**Issue by xzores** [Duskhaven/Bug-Reports#1470]
Tinkerer can learn hunter abilities they can't use, but they can use some of them like:
Hunter's mark.
Concusion blow
Viper sting
Scropid sting
Distracting shot
Wing clip

But I can't seem to use anything else.
This seems very bugged as why would you only be able to use some of them and not all? It should state what you can and can't use.

Furthermore here are some other weird stuff with tinkerer:
In the survival tree you don't benefit from spending talents points, but you need to get to the next tier.
There are no new abilities from level 44 to 60...
You can learn aspects but not use them, this means that aspects will show besides modify scrap gun and there is no way to remove them after learning them.
The "engineering" icon sometimes seems to change or become invisible.

Solution:
Make savage strikes apply to electrified baton.
Make Entrapment apply to frost grenade.
Make T.N.T apply to Scrap bullet.
Allow usage of aspects? or do not allow learning them.

I wanna end this by saying that Tinkerer is a awesome class love the semi-melee aspect of the class, but the "modify scrap fun" seems out of place as I never use it because it disallows using scrap gun, but there is a long CD on "load of scrap". So there is a long time where I can't use any abilities.
I also feel like placing a turret should replace the existing one instead of failing, as I sometimes want to place a new turret before doing my combo. I can do it by dismissing the pet.

**Comment by Duskhaven** [comment]
Intended
