### ISSUE TITLE
Reset talents as a 2H Enhancement Shaman and Poof!, Strike of the Windlord doesn't work anymore.

### ISSUE THREAD

**Issue by ratmoman** [Duskhaven/Bug-Reports#1477]
Was working fine prior to this, now when the ability is clicked it displays the error message : You can't do that yet. What can be done?

**Comment by DrexOtter** [comment]
This happened to me once. Double check that you have 3/3 points in Anticipation, as Storm Infuser seems to be required to use that ability.

**Comment by ratmoman** [comment]
Ghasp! You're right, when respeccing I failed to allocate enough points into that talent. Mark this as solved. Thanks!!
