### ISSUE TITLE
"Favor for Krazek" Quest is uncompletable

### ISSUE THREAD

**Issue by ExonHUN** [Duskhaven/Bug-Reports#1480]
I didnt have mining, so I bought the **Lesser Bloodstone Ores** off of the auction house.
I have no clue why _Krazek_ does not accept it, I do be having the same anmount.
Altho the quest indicator shows it to be completed.

![WoWScrnShot_051123_110652](https://github.com/Duskhaven/Bug-Reports/assets/59777466/62262745-b7c0-41b7-b4e7-66012ec91341)

**Comment by ExonHUN** [comment]
Update: I can complete the quest, if I have more than 4, but it will only take 4 bloodstones.

**Comment by Duskhaven** [comment]
Cannot replicate
