### ISSUE TITLE
(Shaman) Master Enhancer Talent Not Removing the Bonus When Buff is Replaced

### ISSUE THREAD

**Issue by DrexOtter** [Duskhaven/Bug-Reports#1483]
So as the title says, when you have Master Enhancer, you gain bonuses depending on the type of weapon buff you apply. When you apply Windfury Weapon you gain 3% haste. When you cast Flametongue Weapon you gain 3% crit.

That all works fine, but the problem is those bonuses never go away even after they are removed. So you can cast Flametongue on your weapon, then cast Windfury on that same weapon and get the bonuses of both, so 3% haste and 3% crit. These stay that way until you log out and back on.

I didn't try this with Frostbrand but it probably will work for that as well.

**Comment by Duskhaven** [comment]
Fixed
