### ISSUE TITLE
Dancing Rune Weapon is not doing dmg to the enemy target.

### ISSUE THREAD

**Issue by KreepAK** [Duskhaven/Bug-Reports#1484]
Dancing rune weapon (DRW - Last talent in DK Blood talent tree) is not doing dmg when summoned. Tested in duels and hostile mobs. Previously tested on target dummies but found that DRW is not working on dummies for some reason. Weapon is not doing dmg.

Also, pls check this issue https://github.com/Duskhaven/Bug-Reports/issues/1010 

There are multiple tickets that are being closed without a fix with the same comment "It is working on hostile mobs and not working on target dummies and neutral mobs" - but this is false. DRW is NOT WORKING on any type of targets.

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/f6c00061-d9b4-43ec-b171-458b6acf0c04)


Damage is just not shown on DPS addons
