### ISSUE TITLE
Champion's Battlegear Quest and items are bugged.

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#1485]
1. This quest is supposed to be repeatable - unfortunately there's no repeatable option after the quest is done.
https://www.wowhead.com/classic/quest=8573/champions-battlegear#comments
Check comments - many have verified this quest is repeatable.

2. item "Wrath of Cenarius" is currently bugged and not proccing the spellpower increase at all.

**Comment by Duskhaven** [comment]
Items and Quests related to the AQ phase are disabled until it is active.
