### ISSUE TITLE
Protection Warrior Scale. 

### ISSUE THREAD

**Issue by HelloItsKay** [Duskhaven/Bug-Reports#1486]
Hello, the issue  I find with the Protection Warrior class is kinda disturbing honestly. It comes from the fact that there are no block-value stats in the game.   But the class itself scales with it.  And since such stats do not exist, later into the game the class falls off a lot compared to other classes.  Told to GM days ago about it, he told me not to worry about because in CLASSIC, the more defence raising i have more block  value i will have . I was like this is the biggest bulshit i have ever heard but i will test it out, so i bought every available  item with defence raiting i could get my hands of and start testing. It turned out the average damage of the abilities that scale with block  value were the same. So i started to ask people that play in the server as TANK spec  that invested time, to check for myself if it is worhted invest in warrior. All 10+ people  all doing M+ and Raids told me to reroll warrior because it feels weak, cant AOE, lack of damage  etc etc told me to roll  other class such as paladin or druid :))) So in conclusion i would say that in my oppinion the lack of block value makes the class dogshit...
There are so many things that makes him scale with block value such as enchants for shield, Talents, abilities that if you rip block value it off the class feels bad... Take a look into that issue, if you want make tests yourself. 

Also someting else out of the topic...i notice that Demon Hunters hit for 4 000 Damage Critical  with Chaos Strike at level 57.
I will ask you if it is normal, compared to 800-1200 crits to other classes. The guy with the same gear were having single target damage as if the tank + 2 other DPS classes  without overexadurateing

**Comment by Duskhaven** [comment]
Belongs in the suggestion channel
