### ISSUE TITLE
Dreamwing S2 Set Bonus

### ISSUE THREAD

**Issue by Huntereye1** [Duskhaven/Bug-Reports#1491]
The 5 Set bonus for Rapid fire bonus is bugged, its not reducing Rapid fire Cooldown by 2m anymore instead its reducing it now by 30 seconds now. There was no Changelog Regarding this change, and the tooltip has not been updated.

**Comment by Duskhaven** [comment]
Tooltip will be updated with the next patch.

**Comment by Huntereye1** [comment]
so after the MM nerf additonal nerf? thats not cool. atleast revert the 5% dmg nerf then... it was the only way MM was Viable for ST.
