### ISSUE TITLE
Hunter: The Marksmanship aura nerf is of 6% in game instead of 5%

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1506]
![imagen](https://github.com/Duskhaven/Bug-Reports/assets/131160108/6a9d2e8c-3b4d-458f-96aa-df1e2500e6b5)

**Comment by Robustencio** [comment]
![imagen](https://github.com/Duskhaven/Bug-Reports/assets/131160108/d042efbe-537c-4dc6-bc29-a251a79adef1)
