### ISSUE TITLE
Extremely low heal by Shadowstrike Heroic version

### ISSUE THREAD

**Issue by Girlslera** [Duskhaven/Bug-Reports#1510]
Its not fair giving that weapon tiny lifesteal by Void Drain specially if me compare this effect to Drain Life of normal version 
[https://i.imgur.com/U14GndO.png](url)
[https://i.imgur.com/5zFI3PY.png](url)
[https://i.imgur.com/hi83yjR.png](url)
[https://i.imgur.com/VF04XUG.png](url)

**Comment by Girlslera** [comment]
Almost a tenfold difference

**Comment by Duskhaven** [comment]
Intended. The passive effect is completely different from the normal version and buffs your damage
