### ISSUE TITLE
Flask of Relentless Assault is available to players (TBC flask)

### ISSUE THREAD

**Issue by GodKingKaiser** [Duskhaven/Bug-Reports#1525]
Currently there is few posts of Flask of Relentless assault (for 999g) by Bankofawoo.
This flask is a TBC item made with Fel Lotus, Mana Thistle and Terocones, all TBC items.
Unless it's bought from some vendors (doubtful), this person has managed to get into Outlands and actually farm herbs.
![relentless flask](https://github.com/Duskhaven/Bug-Reports/assets/86673617/8e52f4f8-9ac1-470c-9ea7-d52dbd817053)

**Comment by Duskhaven** [comment]
Fixed after restart. Recipe cannot be learned and the mats have been removed from the Darkmoon Faire.

**Comment by Xenbiotic** [comment]
yes was from Darkmoon Faire. The NPC was already removed altogether. I'm Awoo. I'm hunter/druid I can't go to outlands if I wanted
