### ISSUE TITLE
Deadmines does not consistently give the end of dungeon reward.

### ISSUE THREAD

**Issue by Wasilewskiii** [Duskhaven/Bug-Reports#153]
When queuing for a random dungeon and getting into Deadmines, the end of dungeon experience and reward is not consistently rewarded. I haven't received it two out of three times so far. It only worked once, and of course, it also didn't work for the other members in the group.

**Comment by Wasilewskiii** [comment]
Oh, and also, in one of the two runs that didn´t reward anything, the last boss spawned a second time after he was killed. Also the aggro range in this dungeon seems way off.

**Comment by Duskhaven** [comment]
This is fixed after the restart.
