### ISSUE TITLE
Using Demonic Rune puts Healthstone on a shared, 15-minute cooldown

### ISSUE THREAD

**Issue by numbchuck** [Duskhaven/Bug-Reports#1533]
Using Demonic Rune puts Healthstone on a shared, 13-minute cooldown.
This includes both Major (1200hp, 1 charge) and Master (1700hp, 3 charges) Healthstones.

Proof is attached in screenshots:
![1](https://github.com/Duskhaven/Bug-Reports/assets/22568293/1a80cb8f-c958-4b85-bed7-403911a12cae)
![2](https://github.com/Duskhaven/Bug-Reports/assets/22568293/801698ef-4bdf-4f4c-ba98-54a8eed5fcce)
![3](https://github.com/Duskhaven/Bug-Reports/assets/22568293/d8754e79-2ba1-4b74-aa21-ffa781b47837)

**Comment by Duskhaven** [comment]
Seems to be intended

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/3e6db3f0-89b5-43ed-ba83-f38c302b163d)

**Comment by eMalum** [comment]
They share a cooldown but it is not intended to force Healthstone to share the 15-minute Demonic Rune cooldown.

When you use a Demonic Rune, it should put Healthstone on a 2-minute cooldown while the Demonic Rune is put on a 15-minute cooldown.
