### ISSUE TITLE
Defense Rating on Bane Broadsword & Bulwark Necklace

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1534]
This may just be a visual glitch, but the defense rating on the character stats doesn't match what the items say. 

Stats show 7 defense being added instead of 11 

![11 defense rating between these items](https://github.com/Duskhaven/Bug-Reports/assets/131197913/f401f2a6-d99a-4603-b403-7792a5a4a9c6)

![only 7 defense rating being added](https://github.com/Duskhaven/Bug-Reports/assets/131197913/e7795ecb-c1fb-4589-88cb-9bccb3760204)

**Comment by eMalum** [comment]
Defense Rating is used to calculate Defense, they are not the same stat.

1.5 Defense Rating @ 60 = 1 Defense

Mouse over your Defense stat to see the stat breakdown. 11/1.5 = 7.33
