### ISSUE TITLE
Tinker: Some instant abilities can miss if used during or immediately after Machine Gun

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#1535]
Tested with: Aimed Shot, Chimaera Shot, Explosive Shot, Black Arrow, Cursed Arrow*.

Target: Heroic Training Dummy. 
Hit rating: 138

Miss chance is fairly small. Nowhere near -50% accuracy that mg shots suffer.

*Cursed arrow applies the debuff every time but the frost arrow (damage portion) can miss.

**Comment by Duskhaven** [comment]
Intended
