### ISSUE TITLE
Using the Twillight Acolyte set (3) doesn't provide the aura

### ISSUE THREAD

**Issue by numbchuck** [Duskhaven/Bug-Reports#1536]
Using the Twillight Acolyte set (3) obtained from Silithus Twillight mobs doesn't provide the aura required to proceed with the quest Abyssal contacts (summon elemental and kill it for for Abyssal Crest item drop)

![1 1](https://github.com/Duskhaven/Bug-Reports/assets/22568293/ab5656ad-2e2d-4209-88b4-141da8d08116)

**Comment by Duskhaven** [comment]
The Stones have been disabled until the AQ Pre-Event
