### ISSUE TITLE
hunter pets not getting hit/exp rating from the hunter

### ISSUE THREAD

**Issue by tornadax** [Duskhaven/Bug-Reports#1537]
hunter pets should not miss or get dodged if you have ranged hit cap, but my pet is missing 16% of its attacks even when i have 68 hit rating
![WoWScrnShot_051423_232044](https://github.com/Duskhaven/Bug-Reports/assets/133617411/c60e0cd2-d24f-4113-90c2-3f867407d013)

**Comment by GoldWarr** [comment]
same here, this and other reasons of course´might be the reason why ranged Beastmaster falls so far behind the Survival /Marksman Hunter.
