### ISSUE TITLE
Worgen(Human) Druid Visual Glitch

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#154]
Switching to Cat form as a Worgen Druid downscales the player model for a brief moment. Logging out while being in Cat form continues to try downscaling the player model, where the scale reaches negative values. This inverts the character model, and continues backwards-scaling it indefinitely, making the character model reach ridiculous sizes and potentially lagging out the server.

**Comment by Duskhaven** [comment]
Fixed after restart
