### ISSUE TITLE
horde quest able to be accepted by alliance.

### ISSUE THREAD

**Issue by Thickoatmeals** [Duskhaven/Bug-Reports#1540]
![image](https://github.com/Duskhaven/Bug-Reports/assets/129557110/421d04c6-037d-419f-810a-e584af057d87)
Quest title: Past Endeavors in Winterspring

**Comment by Duskhaven** [comment]
Seems to have changed with TBC

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/8c56dd27-8de7-4023-b931-011bb8f22d7f)
