### ISSUE TITLE
Going through TBC/Outland portal (Could be gamebreaking)

### ISSUE THREAD

**Issue by StepheTheBugmaster** [Duskhaven/Bug-Reports#1545]
I found a way to pass the Invisible TBC portal wall. The player can go through it but the Booty Bay teleport prevention works. The bug is possible because of the Mount I'm using into the videos. The mount have smaller hitbox than the Draenei itself so when I dismount the character bugs into the wall.
I promised to report the bug so here we are :

The Bug : 
https://www.youtube.com/watch?v=Y9cjxxH4yBo&ab_channel=Stephe

How the Bug works : 
https://www.youtube.com/watch?v=qyUG_54bdYs&ab_channel=Stephe

**Comment by Duskhaven** [comment]
Fixed.
