### ISSUE TITLE
Scarlet will not working with Power Infusion for Monks, making PI useless

### ISSUE THREAD

**Issue by TheScarletCrusade** [Duskhaven/Bug-Reports#1549]
Using doesn't increase our haste to make our weapons hit faster. I even tried with a slow staff to see if it was a "hidden stat" but no.

https://cdn.discordapp.com/attachments/823579799028105236/1107718103904817302/image.png

Please fix this for monks, PI is useless for us

**Comment by Duskhaven** [comment]
Cannot replicate
Without PI 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/44690487-10fc-49ae-bdf8-5216f733b837)

With PI
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/bba866f0-13e3-4c65-b6e9-a6374e6d3292)
