### ISSUE TITLE
Tank Shaman Elemental Bulwark Doesn't scale with Stormstrike

### ISSUE THREAD

**Issue by Trentmahalla** [Duskhaven/Bug-Reports#1555]
Currently Elemental Bulwark does not gain any extra nature damage from the stormstrike debuff.
# Without Stormstrike Debuff Damage
![NoStormStrikeEleBulwark](https://github.com/Duskhaven/Bug-Reports/assets/47612241/5930b1f8-2686-4f70-8f7f-7f955aca3d0e)
# With Stormstrike Debuff Damage
![StormStrikeEleBulwark](https://github.com/Duskhaven/Bug-Reports/assets/47612241/734e3b42-fa38-4688-84ff-8373e8a6f84c)

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/1287
