### ISSUE TITLE
Halberd of Smiting with warriors Titans Grip bugged

### ISSUE THREAD

**Issue by MasterFlomaster** [Duskhaven/Bug-Reports#1556]
Can equip Halberd of Smiting (Heroic) only with one-handed weapon in offhand or a shiled, but cant equip second two-handed weapon as Titans Grip said.
![ddd](https://github.com/Duskhaven/Bug-Reports/assets/1233408/1ff07fdc-9987-47dc-ba56-cab04be743bd)

**Comment by Duskhaven** [comment]
Polearms are not intended to work with Titan's Grip
