### ISSUE TITLE
Warrior SMF new crit buff not stacking to 5

### ISSUE THREAD

**Issue by Eccies** [Duskhaven/Bug-Reports#1557]
Tooltip says ( bloodsurge 3/3 ) : Your autos have a chance to hurl your weapons at up to 3 enemies. Dealing 20% weapon dmg and grant 1% crit chance for each application , stackable up to 5 times. 

I've only seen it stacking to 3 times so far.

**Comment by Duskhaven** [comment]
Fixed after restart
