### ISSUE TITLE
Troll weapon skill - Bows

### ISSUE THREAD

**Issue by RosyGames** [Duskhaven/Bug-Reports#1560]
Troll start out with no weapon skill in bow weapons, despite having bow weapons specialization.

**Comment by Duskhaven** [comment]
Intended 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/59298c23-496c-472c-844a-b7f1a0e8cdf1)
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/eb8a3f32-c484-441d-89d4-175bbdcd4c0f)
