### ISSUE TITLE
Hunter pet doesn't strike an additional target with Frenzy Talent.

### ISSUE THREAD

**Issue by Trommerwow** [Duskhaven/Bug-Reports#1567]
![WoWScrnShot_051623_165156](https://github.com/Duskhaven/Bug-Reports/assets/131488756/689e2269-882c-4671-b4fd-42dfccde178c)
![WoWScrnShot_051623_165240](https://github.com/Duskhaven/Bug-Reports/assets/131488756/e42e7f41-0a93-4986-8bc0-832d4a7f829e)

Thanks for looking into this!

edit: To my knowledge, my pet has only gained the "Sweeping Strikes" buff once, and it was with a group in SM. So it's definitely in the game, just bugged.

After further testing, it seems to be RDF related.

**Comment by Duskhaven** [comment]
Only works for ranged BM Hunter.

**Comment by Trommerwow** [comment]
@Duskhaven Unless it's bugged, I think you're wrong. The aspect of the Beast never mentions anything about this restriction, and neither does Frenzy. In fact, (and I'm sorry melee hunters), the talent DOES work for melee. I've got proof. Sure it stops working from time to time, but pet death often restores this feature. That's not a strike for my argument, the talent is bugged and you know it.

![Skärmklipp1](https://github.com/Duskhaven/Bug-Reports/assets/131488756/c012649e-94f6-48d4-b601-aa11e1897eee)

![WoWScrnShot_052323_094525](https://github.com/Duskhaven/Bug-Reports/assets/131488756/d0f7559f-ff40-49f5-a299-3fd2a12ce5d8)

If you want to give more power to ranged BM Hunter, awesome! I'm sure they need it. But please don't push an issue to the side and pretend it's our fault for misinterpreting.
