### ISSUE TITLE
Hunter Talent "Mortal Shot" bugged.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1575]
This bug has been reported 2 times but i understand that certian bugs have prior above others, take your time you are doing an awesome job and people appreciate you not enough sadly.

Hunter abilities not getting "Mortal Shot" talent bonus : Arcane Shot, Aimed Shot, Serpent Sting, Chimera Shot , Rapid Shot, Volley, Multi-shot, Kill Shot, Explosive Shot and more.
(source wowhead)
https://www.wowhead.com/wotlk/spell=19490/mortal-shots

I have added link for you to check which skills the Hunter talent "Mortal Shot" modifies.

**Comment by Duskhaven** [comment]
cannot replicate.
