### ISSUE TITLE
Dragonstalker's 5p set bonus seems to not work

### ISSUE THREAD

**Issue by gargolMM** [Duskhaven/Bug-Reports#1578]
Tooltip says "Lone Wolf grants an additional 3% Damage" but it does not seem like lone wolf is receiving this benefit.

**Comment by GoldWarr** [comment]
Yeah got the same issue too, lone wolf buff or even the character window doesnt take T2 5P bonus into account.

**Comment by Duskhaven** [comment]
Fixed after restart
