### ISSUE TITLE
Dragonstalker's 3p set bonus giving bonus damage to serpent sting

### ISSUE THREAD

**Issue by gargolMM** [Duskhaven/Bug-Reports#1579]
The Dragonstalker's 3p set bonus seemingly is giving about a 30% dmg boost to serpent sting but the tooltip is not mentioning anything about this. 

If you unequip dragonstalker 3p and instead equip the Dremwing (S2) 3p set (which should give the 30% serpent sting dmg bonus according to the tooltip) and then equip the dragonstalker 3p once again the bonus damage to serpent sting disappears until you relog then it's there again.

**Comment by Duskhaven** [comment]
Fixed
