### ISSUE TITLE
Deflection does not provide 3% melee hit

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#1582]
I have 8.80% hit chance and talented into Deflection which the talent provides 3% and that gives me a total of 11.80% hit chance, but my melee attacks still miss on bosses.

**Comment by CovexVortex** [comment]
Are you Survival or Beast Mastery?

**Comment by nboytcl** [comment]
I'm Tinker.

**Comment by Robusten** [comment]
Dual wield?
