### ISSUE TITLE
Blood DK , Blood feast Custom talent

### ISSUE THREAD

**Issue by Huntereye1** [Duskhaven/Bug-Reports#1587]
The Custom talent Blood Feast currently doesnt scale with Anything, it allways does 300 Damage when the worms explode. Tested with 1k AP and 2k AP and both the healing and damage remains the same.

**Comment by Duskhaven** [comment]
Fixed

**Comment by Huntereye1** [comment]
@Duskhaven  The fix didnt worked, no changes in numbers regardless of AP.
