### ISSUE TITLE
SFM fury bug. New ability only stacks up to 3

### ISSUE THREAD

**Issue by Brinksteam** [Duskhaven/Bug-Reports#1596]
Your auto-attacks have a chance to hurl your Weapons at up to 3 enemies infront of you, dealing 20% Weapon Damage and grants 1% crit chance for each application, stackable up to 5 times this doesn't stack to 5 times only stacks to 3 and it doesnt heal
You are healed for a small amount when this effect triggers.

**Comment by Duskhaven** [comment]
Fixed after restart
