### ISSUE TITLE
Getting redoubt procs as stone warden shaman

### ISSUE THREAD

**Issue by EndingInfinity** [Duskhaven/Bug-Reports#16]
sometimes on my stone warden i get the redoubt proc buff from paladin tank tree. you can see the buff on my buff bar in the picture
![wow_owdblaDKLr](https://user-images.githubusercontent.com/127152963/223238866-c1985f8c-dcfe-4ead-a7a1-7ba72c970d49.jpg)

**Comment by Frauce** [comment]
Can confirm this happens for my shaman with Stone Warden as well

**Comment by Duskhaven** [comment]
Tank Shamans have many passives which are not included in the Skill. 
This Info will be added in a later patch.
