### ISSUE TITLE
Worgen: Darkflight and Every Man for Himself

### ISSUE THREAD

**Issue by KoireThePriest** [Duskhaven/Bug-Reports#1601]
When I log on my worgen hunter I noticed that sometimes darkflight doesnt show up in my buffs, it can be fixed with casting Running Wild or Altered Form. But the main bug is that, when the buff is missing, I can cast human racial Every Man for Himself. Macro with /cancelaura darkflight allows worgen to use human racial/s (not sure about spirit and sword/mace expertise)

**Comment by Duskhaven** [comment]
Fixed
