### ISSUE TITLE
Rake rank 4 bugged

### ISSUE THREAD

**Issue by Helltul** [Duskhaven/Bug-Reports#1602]
Cannot use on large number of targets combat log says invalid target.
Seems to be that every mob under lvl 48 is an invalid target. 
lvl 48 Rabid blisterpaw I could cast rake on but not a lvl 47

**Comment by Aquarion-Duskhaven** [comment]
Having same issue aswell.
Anything lvl 47 and under cannot use ability.
Attacking Trolls in Hinterlands, lvl 48 is fine, anything else, says invalid target.

**Comment by Duskhaven** [comment]
Fixed
