### ISSUE TITLE
Mortal Shot talent not working right on Hunter Abilities.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1603]
As title says, its honestly vital talent skill for ranged hunters please could this be looked at?

I checked back how it could be possible to replicate the bug hopefully.

all ranged hunter skills befor there max rank seem to be buffed with Mortal Shot but not there last rank.
(example Aimed Shot 5 is fine but Aimed Shot 6 has no mortal shot buff)

Also a check on details dps addon showed that Mortal Shot when it "works" does not grant 30% when 5/5 points.
Its around 10-15% for all ranged abilities this takes even talent based skills into account.
(example Wild Quiver , Piercing Shot, Poisones Arrow hunter talents.)
this makes ranged marksman coupled with the 6% nerf  they got prior even worse compared to other classes.

by checking all ranks of the hunter skill it do be clear to see what abilities benefits from Mortal Shot and what not. 
i recommend using details for that if nessary i can send you my own details logs for that.

**Comment by Duskhaven** [comment]
Mortal Shots only affects the talents/skills below. 

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/cb0eb682-cbb7-438b-91cc-f52ed3018fd8)
