### ISSUE TITLE
Demon hunter quest "Combat practice" is bugging

### ISSUE THREAD

**Issue by Torenix** [Duskhaven/Bug-Reports#1604]
Hi,

Demon hunter "Combat practice" quest says that I have to duel other demon hunters and I should type "ready" emote to start it. 
Well I did type /ready and they do turn yellow and soon disappearing, but I cant spar with them. 

And yes I did equip those war glaives and learned those skills.. Did I miss something?

Can you help me?

Thanks in advance :)

**Comment by Duskhaven** [comment]
Cannot replicate. You can attack the NPC after typing /ready
