### ISSUE TITLE
DH T1 2-set and T2 3-set bonus dont stack

### ISSUE THREAD

**Issue by MasterFlomaster** [Duskhaven/Bug-Reports#1610]
I equiped 2 pieces of T1 Rogue set, and 3 pieces of T2 as a DH, but the 15% dot-damage debuff from Chaos strike apllied only once, and it said its T1-set bonus damage. I tried to equip only T2 3-set, its working alone, but tooltip says its T1-set bonus damage. I wear 5 diffrent slots, and getting only 1 tier bonus. Seems bug, because I can wear T1 2-set, and for example Mythic 2-set and get from 4 pieces 2 set bonuses, but thats what I cant do with T1 and T2, yet it has the same effect, should be stackable I guess. Same is for shield applied after Fel Rush as DH tank. Im getting only 1 buff instead of 2 while wearing T1 and T2 set bonuses.

**Comment by Duskhaven** [comment]
Intended
