### ISSUE TITLE
Shaman Totems and Pets. Issues with Base Functionality and Inheritance. 

### ISSUE THREAD

**Issue by plasma-93** [Duskhaven/Bug-Reports#1617]
### **Spirit Wolves** 
Does not inherit the shamans Melee Hit Rating as they should, or any inheritance at all. They also have no expertise, while they should have capped expertise by default based on testing in WotLK Classic, and from Elitist Jerks back in vanilla. Additionally the Wolves should be able to crit, in testing I have only ever seen them crit if the target is debuffed with a crit chance debuff etc. They should critically strike around 10% of the tim, as per vanilla, and classic wow. 
![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/c555e4c2-a49c-4f6a-ae56-058c5fbe491e)
![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/5ca21d70-d7d0-4bdb-9aec-1e1dabbea124)

### **Magma Totem** 
Doesn't inherit Fire Spell Critical Strike Chance, or Spell Hit Rating from the shaman. 
Additionally, Magma Totem should put the player in combat with the enemy it is hitting, but it does not.
![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/9951fae3-3878-4d21-840d-dddc5ad5a14f)

### **Searing Totem** 
Like Magma Totem does not inherit Fire Spell Critical Strike Chance, or Spell Hit Rating. 
It also does not put the target enemy in combat with the Shaman, though this maters less for searing totem because it won't hit anything you aren't hitting anyways. 
![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/1720a97e-55e8-4ab6-8f59-9e48a25b5160)

### **Earthbind Totem** 
Does not inherit the Shamans Spell Hit Chance, leading to situations where it is cast, and then nothing is slowed  and people die in dungeons or while aoe farming as ele shaman. 
![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/4ab6c726-cccc-48c6-9387-2379b708e267)

### **Grounding Totem**
I would just say that the totem does not work at all on this server. Maybe it works in some places, but I've never noticed it working. This is a big part of Shaman Utility and very frustrating. It doesn't work on Mind Blasts in HC Nefarian, it doesn't work on Shadow Bolts on NM Nefarian. Doesn't seem to catch any of the targetted spells in MC either, like shadowbolts or immolates. Tried using it in dungeons to catch caster spells for a bit, I think it worked once, but it also might have just been random targeted, not sure.

**Comment by plasma-93** [comment]
https://github.com/asido/TrinityCore/commit/8bf6fac32431b5215f445d7a4e24b207eaa98b9b#diff-0d2a44370e18523042eca998013bf68fa21f38524f406c0ccdfd557f62342a30 found this implementation from a fork of trinitycore if it helps. It's over 10 years old though lol. Might be a similar issue of the shamans stats simply not being retrieved for the spells cast by the totem.

**Comment by Duskhaven** [comment]
Fixed after restart
