### ISSUE TITLE
Thekal´s Grasp Fist Weapon Set effect bugged.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1627]
Hey Dev Team,

Thekals Grasp set effect very rarely procs, my hunch is its because it only counts weapon auto attacks.
The issue is the set effect states that it proccs from every sort of damage be it ablitly , skills, passives or talent based skills.
Its a darn hard weapon set to get, would be huge if you guys could help this but take your time.

P:S: i forgot to add that the holding and fighting animation for this weapon fist set are bugged and dont show up properly.

**Comment by Duskhaven** [comment]
Effect only triggers from physical meele+ranged abilities and auto attacks.
Procrate increased to 2% to make it more useful.
