### ISSUE TITLE
Thirst for Blood worgen racial not working!!!!!!

### ISSUE THREAD

**Issue by zahoogaming** [Duskhaven/Bug-Reports#1630]
Thirst for Blood used to give a stacking damage buff and heal when you kill a mob that gives xp but it does nothing atm. I specidically leveled a fresh worgen warrior to 10 on a new account to test and never got the buff after killing a mob. This happened to my other characters who are worgen as well. Also if I cancel the worgen speed aura I can use Every Man For Himself human racial for some reason.

**Comment by zahoogaming** [comment]
ok so I just tested a worgen druid, leveled it to 10 and as I predicted druids do get Thirst a for Blood buff because as of may 13th they learn worgen passives automatically, however there is no damage modifier neither for mele nor for spell. And if you level another class as a worgen and learn spells from the book that racial doesn't work for you, you don't even get the buff nor a heal. So the problem with that Tinker/Druid update is messing up with a spell learnt from a book by other classes.

**Comment by zahoogaming** [comment]
If there is no better solution I'd suggest make all the characters who are worgen learn the racials automatically at lvl 10 instead of the books and apply the same for existing 60 worgens so that they can at least benefit from the heal on kills

**Comment by Duskhaven** [comment]
Fixed. Make sure to relog.

**Comment by zahoogaming** [comment]
I do get the buff now but the damage modifier isn't there, tested on my lvl 13 warrior without taste for blood - 44 mele damage on mob and with 2 stacks of taste for blood same 44 damage on the mob of the same level. Also for warriors it used to work a bit differently (not sure if it was intended or not) but instead of instant heal after the kill I'd get a stack of "second wind" heal over time effect instead but now it's just "Swift Hand of Justice" instant heal in combat log.
