### ISSUE TITLE
Elemental Shaman Tier 2 Set bonus

### ISSUE THREAD

**Issue by Babygrim** [Duskhaven/Bug-Reports#1632]
2-item tier 2 elemental shaman set bonus only applies to spell haste (gives only 30 spell haste), and doesn't give any melee haste.

Shaman always was kind of hybrid support/dps class that you could gear up, pretty much, any way you wanted. And so currently I am testing out Spellhancement build, considering that we have 51 talent point, we are limited by only 1 tree of skills, meaning I can't go into elemental tree, which already reduces dmg by a good chunk. So. having set bonus stats apply as it was intended in a first place, would be nice

**Comment by Duskhaven** [comment]
Tooltip adjusted with the next patch update
