### ISSUE TITLE
Dreadwake mount giving 100% movespeed if no Riding skill is learned yet.

### ISSUE THREAD

**Issue by Saecret** [Duskhaven/Bug-Reports#1634]
I've tested the new mount Dreadwake, and if you use it starting at lvl 8, and did not do the mount quest yet, and learned 75 riding, it defaults to 100% movespeed version. I suppose this is not the intended behaviour. It works as normal and reverts to 60% speed mount after learning 75 riding skill though.

**Comment by Duskhaven** [comment]
Fixed
