### ISSUE TITLE
Heroic BWL Trinkets

### ISSUE THREAD

**Issue by Ramz1991x** [Duskhaven/Bug-Reports#1636]
Hello,

Some of us don't understand why Heroic Trinkets like Rejuv Gem and Nelth Tear both BIS for Healers and Casters seem to have a close to 100% drop rate yet Heroic DFT is 2-5% according to Noxx himself. Can you give any reasoning as to why that is? Most of the raids are half melee and half caster/healer. The last group gets all of their bis trinkets in 2/3 runs max, yet melee struggle to even see a Heroic DFT drop after 3 full months of clearing Heroic BWL.

If you could just explain as to why melee have to suffer for eternity and healers + casters get their bis trinkets for free basically I and many others would like to know.

Thanks! :-)

**Comment by Duskhaven** [comment]
Belongs in the suggestion channel
