### ISSUE TITLE
Predator's Craving talent only triggering after using Cat's "Savage Roar"

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1638]
In my testing the only time I could trigger Predator's Craving was using 1 ability: Savage Roar

It wasn't triggered by Bear's Maul or any other Cat finishing move (Rip, Ferocious Bite, Maim) except Savage Roar 

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/388945bc-1224-430d-9a78-deee059c6276)

**Comment by Duskhaven** [comment]
Cannot replicate
