### ISSUE TITLE
Protection Pally - Holy Power not working with this specific set of talents

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1640]
This is the only combination of talents in my testing that is causing the problem:
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/ef391731-04e8-49b0-8ed6-cca790997ec8)

Issue: Holy Power not happening after using Hammer of the Righteous, so Shield of Righteous not usable 

Here are 5 other talent combinations I tested where this issue does _not_ happen:
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/2586eece-10ed-4dde-b3ab-dd8b271385c2)

**Comment by ryanportfolio** [comment]
Here's another talent combination that causes Hammer of the Righteous to not provide any Holy Power

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/fcc2f244-832b-4e26-8f17-296de90f02d6)

**Comment by asdfasqw** [comment]
Might be Divine Plea I don't use that in my builds tbf i think its just hammer of righteousness thats directly causing the issue thou cause sometimes you generate holy power sometimes you don't

**Comment by Duskhaven** [comment]
Fixed
