### ISSUE TITLE
Phase 128 on login

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1644]
Character "Ordommick" was having this happen along with a few others I've talked with. 

Every time on login, they would be in phase 128. 

I'm guessing one of their quests was causing the issue, though I'm not sure which one. Here's the quests they had when the issue was happening: 

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/0363f027-62aa-4724-87e0-081c7366e0f9)

I think it was either related to Undercity or Tirisfal Glades. 

Everyone who has reported this issue has been Undead.

**Comment by Duskhaven** [comment]
Related to "Lordaeron's Last Stand" Quest must be abandoned or the whole Questline completed to return to the normal Tirisfal.
