### ISSUE TITLE
Damage x95%

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1645]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/818a5ebd-c1fb-4dbd-ac3b-2ee588d3e984)
(no items were equipped)
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/f6013006-5f14-4d50-acfa-cf3972b5224a)

This player has their damage negatively modified for some reason

**Comment by ryanportfolio** [comment]
Update: after adding the Sanctified Retribution talent, the issue went away

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/55a7732a-85a2-4575-adb6-a406a9070692)

**Comment by Duskhaven** [comment]
Intended. Ret's got a Aura Damage reduction/increase along with other classes based on performance.
