### ISSUE TITLE
Issue with quest "The Grimtotem Weapon"

### ISSUE THREAD

**Issue by Silfarnos** [Duskhaven/Bug-Reports#1647]
I have been trying to do "The Grimtotem Weapon" in Dustwallow marsh, but it seems to be impossible to get quest progress currently:

The quest indicates that you need to kill two kinds of mobs near a Captured Totem, an item you can use to summon a friendly, stationnary totem with the same name. The mobs are named Mottled Drywallow Crocolisks and Drywallow Daggermaws.

The issue is that i have killed many of the two kinds of mobs each time after putting down my totem, and even tho they died just next to the totem and way before the totem expired, i couldn't get any progress.
I then filed an in game ticket and interacted with the moderator Epicly, that performed some tests themselves and confirmed that this was most likely a bug, so i'm reporting it here.

Hope you can find a fix for it :D

Have a nice evening.

**Comment by Duskhaven** [comment]
Fixed
