### ISSUE TITLE
Beastial Wrath Glyph is bugged.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1649]
The Glyph doesn not reduce Beastial Wrath by 20 seconds.
I made sure to be ranged and not have Beast aspect on me, still nothing changed and it still stays on 56 secs for me.

Normaly its 1.33 m but im a beastmaster and got the talent "Longevity" that reduces BW, Intdimidation and Pet special skills by 30%.

So a BM hunter + Glyph should have 36 secs cooldown on Beastial Wrath.

**Comment by Duskhaven** [comment]
Cannot replicate

With Glyph
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/62c08142-bac7-4b23-8e18-22f24c10671d)

With Glyph+Talent
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/49c2a5ba-906c-4f6d-95e5-ddf4b25ee538)
