### ISSUE TITLE
Frenzy- BM talent Max Rank Bug

### ISSUE THREAD

**Issue by Enigmaticresolve** [Duskhaven/Bug-Reports#1651]
The BM talent Frenzy is not providing the sweeping strikes additional damage buff to pets when the talent is at rank 5. In an instance earlier my pet did not proc a single sweeping strike even though it crit multiple times, whereas another hunter with rank 4/5 had their pet proc sweeping strikes. I’ve tested it on dummy and pet is only receiving the frenzy buff only.

**Comment by Duskhaven** [comment]
Only works for ranged BM Hunter.
