### ISSUE TITLE
Gordunni Cobolt Quest

### ISSUE THREAD

**Issue by BerserkerFury** [Duskhaven/Bug-Reports#1656]
Hello there , the quest above is not working. You do get the item in ur intentory to start diggng, but there are no piles of cobolt ( they should be with a blue aura ) in the specific zone at the ogre's ... 

![image](https://github.com/Duskhaven/Bug-Reports/assets/83886596/f40b9f57-6db8-46bf-b6f0-85ffc121de4e)

**Comment by Duskhaven** [comment]
Fixed
