### ISSUE TITLE
Twilight Geolord's Rewarding Incorrect Amount of Rep

### ISSUE THREAD

**Issue by plasma-93** [Duskhaven/Bug-Reports#1664]
Twilight Geolord's reward 2 rep instead of 10.

https://www.wowhead.com/wotlk/npc=11881/twilight-geolord
![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/2606c4c7-75f7-455f-ad6a-72b7ec99f5cf)

**Comment by Duskhaven** [comment]
Fixed
