### ISSUE TITLE
Fire blast crit but no ignite ??

### ISSUE THREAD

**Issue by HelloItsKay** [Duskhaven/Bug-Reports#1666]
![image](https://github.com/Duskhaven/Bug-Reports/assets/77486531/b7a878aa-d106-438a-ae3b-e687541d9a07)
![image](https://github.com/Duskhaven/Bug-Reports/assets/77486531/bbf5b21b-47b9-4d09-9516-61c59f3e27ca)

as you  can see from the image the critical didn't prock  ignite despite its  talented on 2/5, but fire ball does prock it 

If that is an issue probably will be a good idea to check if ignite at all works as intended, does it stack, or override the current damage with the new one

**Comment by Duskhaven** [comment]
Intended. Fire blast has been reworked and does not proc Ignite
