### ISSUE TITLE
New head enchantment AQ Invasion

### ISSUE THREAD

**Issue by Lunalesta** [Duskhaven/Bug-Reports#1672]
The head enchantment is sold for lvl 60, but is not active until lvl 70.
![Vendor](https://github.com/Duskhaven/Bug-Reports/assets/134546953/17516f69-e780-4deb-8c02-d4f4067ea3d9)
![enchant](https://github.com/Duskhaven/Bug-Reports/assets/134546953/ad3dff0b-dade-42fc-9c99-00939f9842df)

**Comment by Duskhaven** [comment]
Fixed (Visual Issue will be resolved with the next patch update)
