### ISSUE TITLE
Darkshore 2 Invasion Quest

### ISSUE THREAD

**Issue by KirkM411** [Duskhaven/Bug-Reports#1677]
Quest is showing that 9 of the same commander needs to be killed rather than 9 invader mobs. It isn't just a typo though and actually requires you to kill the commander 9 times before it is complete. 
![image](https://github.com/Duskhaven/Bug-Reports/assets/134551867/5c0b329a-d8b8-418d-9745-4bf175e0f27d)

**Comment by Duskhaven** [comment]
Close and reopen your game
