### ISSUE TITLE
Alliance Bards are Missing custom mount 

### ISSUE THREAD

**Issue by oniichan123** [Duskhaven/Bug-Reports#1680]
Undead Bards get there own custom mounts, Alliance doesnt get anything, This isnt quite fair for the players who wanted dwarf bards. Is this just a mistake and Alliance bards are going to get a mount also?

**Comment by Duskhaven** [comment]
Alliance Bards have a longer questline as compensation.

**Comment by oniichan123** [comment]
How is that compenstation??? A mount doesnt equal more quests? Thats unfair

**Comment by oniichan123** [comment]
The questline is confusing anyway for alliance it bugs and doesnt port when it should and Ports when it shouldnt. Theres no Map objectives, its kinda favoritism to only give horde a mount that alliance counterpart cant have, It's being Lazy tbh you coulda just given both factions the same mount.

**Comment by Duskhaven** [comment]
They will receive a new unique mount in the following days.
