### ISSUE TITLE
The Path of the Righteous - Quest Unavailable

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1683]
Quest giver has a grey ! for "The Path of the Righteous" even when the prerequisites are completed
https://www.wowhead.com/wotlk/quest=8301/the-path-of-the-righteous
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/4115a41a-ccd2-4aa8-b614-eb903c185742)

**Comment by ryanportfolio** [comment]
Update: Even if "The Path of the Righteous" quest is manually completed, it can't be turned in

**Comment by ryanportfolio** [comment]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/286caa5d-bc79-4894-9d1b-421176351250)

**Comment by Duskhaven** [comment]
Fixed
