### ISSUE TITLE
Bard , Anthem of Glory

### ISSUE THREAD

**Issue by Huntereye1** [Duskhaven/Bug-Reports#1686]
This ability currently only increases spell crit chance. while stated it should increase meele crit Chance.  See screenshots

![WoWScrnShot_052523_143531](https://github.com/Duskhaven/Bug-Reports/assets/109392926/84d38c77-8069-474c-8186-195417a42fa4)
![WoWScrnShot_052523_143527](https://github.com/Duskhaven/Bug-Reports/assets/109392926/53132dd8-60b9-4261-a802-ef3af7a03203)

**Comment by Duskhaven** [comment]
Tooltip changed with the next patch update
