### ISSUE TITLE
Corrupet Saber Quest in Felwood

### ISSUE THREAD

**Issue by BerserkerFury** [Duskhaven/Bug-Reports#1687]
After taking the cat in the box at the speicifc location, it transforms into the corrupted saber but it gets stuck from there, i walked all the way back to the quest giver and it didnt accept me having the cat next to me, or bringing it back as the quest is saying. Quest bug in short ...

![image](https://github.com/Duskhaven/Bug-Reports/assets/83886596/a0430c73-1dcc-4791-b79d-bdc28f9f084d)

**Comment by Duskhaven** [comment]
Fixed
