### ISSUE TITLE
VIsual bug in jinthalor

### ISSUE THREAD

**Issue by iraizo** [Duskhaven/Bug-Reports#169]
mob/player flickering

![image](https://user-images.githubusercontent.com/35413558/224572353-5891bd39-66b7-4a0c-a6c4-efc9126646ff.png)

**Comment by Duskhaven** [comment]
Please refer to this existing List https://github.com/Duskhaven/Bug-Reports/issues/3

**Comment by iraizo** [comment]
> Please refer to this existing List #3

My bad!
