### ISSUE TITLE
Step Up Your Performance (26840)

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1693]
Dwarf Druid reported not being able to turn in quest ID 26840 after successfully killing Wrath of Azshara: 

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/2ed87882-ae13-4af0-acd7-ba9229e42a2a)
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/bd90f9d1-e7d6-413d-bcad-5aab03232692)

**Comment by Duskhaven** [comment]
Fixed
