### ISSUE TITLE
Wrath of Cenarius ring - No procs on paladin abilities

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#1695]
It simply is not proccing on any paladin abilities.

**Comment by moonfirespammer** [comment]
Hi any update on this?

**Comment by Duskhaven** [comment]
Only procs on pure magic attacks 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/252c8ba2-856b-4ffb-accb-5804b0ad8615)
