### ISSUE TITLE
Preserver's Cudgel - Increases SP by 40 instead of 56

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1698]
Item 25836 is only providing 40 SP instead of 56 per the tooltip

With no items equipped: spell power is 73
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/0a237644-9686-407a-820f-0cb6969b8eee)

With only the mace equipped: spell power is 113
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/6e0e0acf-be32-42aa-ac04-b56aacca7697)

**Comment by Duskhaven** [comment]
Tooltip adjusted
