### ISSUE TITLE
Flightpath IF to Menethil Harbor

### ISSUE THREAD

**Issue by sarkonthedad** [Duskhaven/Bug-Reports#17]
While taking the flightpath from Ironforge to Menethil Harbor it took me to the IF airfield than reversed, flew out to Hillsbrad/Arathi Highlands and then turned back flew through the world and around to the actual landing point in Menethil. Have now checked to see if this happened again and can confirm has happened 2 of 2 times.
![WoWScrnShot_030623_153746](https://user-images.githubusercontent.com/127152922/223239181-ebfa7d7a-5ca2-448f-b402-f892d2d90f2f.jpg)
![WoWScrnShot_030623_153749](https://user-images.githubusercontent.com/127152922/223239189-ce0dd581-1b3d-4803-9388-d1c5ca64f9b6.jpg)
![WoWScrnShot_030623_154016](https://user-images.githubusercontent.com/127152922/223239194-c607052f-cd01-430b-889c-36b6824f5a12.jpg)

**Comment by Duskhaven** [comment]
This is now fixed.
