### ISSUE TITLE
Tinkerer Quest bugs if anyone else tries to do it at the same time.

### ISSUE THREAD

**Issue by dmjohn0x** [Duskhaven/Bug-Reports#175]
The quest where you follow a robot to cleanse the entrance of Gnomeragan for tinkerer bugs if someone else tries to do it at the same time. I got teleported inside before getting credit for protecting my robot, before getting completion credit. I tried dropping the quest and hearthing out to try again, but I wasnt allowed to pick up the quest again, so it bricked my character and i was forced to delete it and try again.

**Comment by Duskhaven** [comment]
All players which are near the Trogg when it dies now get kill credit. Fixed.
