### ISSUE TITLE
Blue Scepter Shard not dropping from Maws (The Wrath of Neptulon)

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1754]
Similar to https://github.com/Duskhaven/Bug-Reports/issues/1694

The quest item (21137) is not in the loot after boss is defeated for quest 8729

https://www.wowhead.com/wotlk/quest=8729/the-wrath-of-neptulon

**Comment by Duskhaven** [comment]
cannot replicate
