### ISSUE TITLE
Song of Celerity - mana regen

### ISSUE THREAD

**Issue by dreammerko** [Duskhaven/Bug-Reports#1757]
Bard gets addition mana regen from Song of Celerity but the tooltip doesn´t say so

**Comment by dreammerko** [comment]
I was at 2/3 talents Dreamstate in Hymn of Valor (it did increase my mana regen), I added 1 point to 3/3, it worked, then switched to Song of Celerity and back to Valor and my mana regen was down again

**Comment by Duskhaven** [comment]
Fixed after restart
