### ISSUE TITLE
Watcher's Cowl - 26 SP instead of 42

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1758]
Similar to https://github.com/Duskhaven/Bug-Reports/issues/1698 

Item 29174 from Carapace Quartermaster is only providing 26 SP

SP with no items on:
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/76e2d8c0-4d66-4e68-a3ad-858f78edd922)

SP with just Cowl on:
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/8be6ffd9-1567-4105-b390-6ce8ca04cadc)

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/fc24cb66-0c36-4c19-ba2a-924bcafc0f6f)

**Comment by Duskhaven** [comment]
Tooltip adjusted
