### ISSUE TITLE
Rest and Relaxation - combat bugging

### ISSUE THREAD

**Issue by dreammerko** [Duskhaven/Bug-Reports#1759]
In some dungeons with friendly/neutral/even Red mobs Rest and Relaxation seems to make you stay in combat since it affects those too.

Second problem: Rest and Relaxation makes you get insta aggro from mobs your team member encountered (just as healing would), if this is intentional not really worth using between pulls.

Third suggestion: too long duration, would be awesome if bard could move at 50% speed at time of channeling this. Would make it atleast a bit more usable

**Comment by Duskhaven** [comment]
Fixed
