### ISSUE TITLE
Lone Wolf (T2) is being applied as a buff to other players

### ISSUE THREAD

**Issue by CovexVortex** [Duskhaven/Bug-Reports#1760]
When a hunter with the T2 5p stands on another player, they gain a buff called Lone Wolf (T2) doing what the set bonus is also doing to the hunter player
https://cdn.discordapp.com/attachments/1083160728082595920/1111542980512333834/ju78i8.png

**Comment by Xenbiotic** [comment]
Can confirm
![ju78i8](https://github.com/Duskhaven/Bug-Reports/assets/67262624/185dd7f8-491f-471f-bd72-b1cdc2166751)

**Comment by Duskhaven** [comment]
Fixed after restart
