### ISSUE TITLE
Head of the Broodlord Lashlayer not dropping

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1771]
Similar to https://github.com/Duskhaven/Bug-Reports/issues/1754 and https://github.com/Duskhaven/Bug-Reports/issues/1694

Item 20383 is not dropping after defeating Broodlord Lashlayer when on quest 8288 

https://www.wowhead.com/classic/quest=8288/only-one-may-rise

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/1d56a2cf-abac-4a26-811a-e359ce85e34f)
