### ISSUE TITLE
Marli's Touch Wand - no range

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1773]
Item 57132 can only be used if you're _very_ close to the mob, basically right next to it

Anything more than that will cause the wand to not be usable as seen in the below screenshot

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/b95865c7-688d-4af6-97da-5e005ba3cb61)

**Comment by Duskhaven** [comment]
Fixed after restart
