### ISSUE TITLE
improved virtuoso talent bug

### ISSUE THREAD

**Issue by Drazkanil** [Duskhaven/Bug-Reports#1774]
the haste seems to be bug, doesnt affect any spell and even when all the stacks doenst work

**Comment by Duskhaven** [comment]
Cannot replicate

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/92cf198d-40a7-43a6-8a96-67ab43d1da1d)
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/6780cffe-cf47-4a02-a0ee-18bfddbc940b)
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/41979913-308b-4108-accf-6b585e78840e)


1. without
2. with 1 stack
3. with 3 stacks
