### ISSUE TITLE
Greater Heal ranks are non sequential.

### ISSUE THREAD

**Issue by JustOneSparrow** [Duskhaven/Bug-Reports#1776]
Greater Heal Rank 5 heals lower than Rank 3 and Rank 4, Currently Rank 4 is healing the most. 

<img width="297" alt="Wow_A0U05Chcmu" src="https://github.com/Duskhaven/Bug-Reports/assets/58004776/aafe6d07-1d0b-4884-a57e-3a6266a58d8e">
<img width="305" alt="Wow_U3HDhTJpha" src="https://github.com/Duskhaven/Bug-Reports/assets/58004776/373201a7-40bd-424b-a7bf-9a6e4d5de03a">
<img width="294" alt="Wow_X15uLGSLpO" src="https://github.com/Duskhaven/Bug-Reports/assets/58004776/6275fa0e-1b15-4f9a-96a0-b40b167ddc45">

**Comment by Duskhaven** [comment]
Fixed after restart
