### ISSUE TITLE
Bard: Motif of Focus / Moonfire Dot

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#1777]
![image](https://github.com/Duskhaven/Bug-Reports/assets/127632931/00c21451-b820-41c7-af69-c6afd3eaa500)

Motif of Focus does not give the highest rank of moonfire / power chord virtuoso the ability to stack 3 times the highest rank but instead creates a new debuff slot which stacks the rank 1 moonfire debuff up to 3 times. ^^ I´m playing undead if dwarf does not have this issue

**Comment by Duskhaven** [comment]
Fixed
