### ISSUE TITLE
Arcanite dragonling (engineering trinket): Is not being treated as a guardian, and is missing levels

### ISSUE THREAD

**Issue by Robusten** [Duskhaven/Bug-Reports#1783]
This means that it will attack opposite faction raid members, can be attacked by them, and will die instantly.

Also gnomish battle chicken gets level 73 from extra tinker engineering skill. Dragonling is missing this.

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/1319
