### ISSUE TITLE
Unable to turn in with 999 Silithid Fragments

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1787]
Player attempted to turn in a Qiraji Invasion quest but received this error message:

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/31af17e2-fc2f-437c-b39f-be89cb59c1d9)

Had 999 of item 57929 in inventory 

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/2c9c4fa3-faf3-4203-a185-fe0d10155fd9)

**Comment by Duskhaven** [comment]
Fixed after restart
