### ISSUE TITLE
Frost Mage's 'Glacial Spike' and 'Snowstorm' talents are incapable of critting. 'Glacial Spike' also isn't reset by the 'Cold Snap' talent.

### ISSUE THREAD

**Issue by Scoliox** [Duskhaven/Bug-Reports#179]
Use 'Glacial Spike' while having Fingers of Frost up, or set your spell crit chance to 100% I guess, to replicate the issue. 'Snowstorm' has an extremely low crit chance and seems to be unaffected by Fingers of Frost + Shatter combo.

Side note: 'Glacial Spike' is too RNG and difficult to pull off due to its requirement of needing to have both Brain Freeze and Fingers of Frost procs active. You end up having to hold on to your Brain Freeze proc but if you get a single Brain Freeze proc refresh, you end up losing more damage trying to meet the requirements to cast 'Glacial Spike' than you'd gain from using it. Either break out the requirement, or put the talent lower into the Frost tree so that you can take Deep Freeze alongside it as currently Deep Freeze is a more consistent choice than 'Glacial Spike' is, thanks to Deep Freeze being capable of critting (or freezing a target for Ice Lance spam) as well as being reset by Cold Snap.

**Comment by Duskhaven** [comment]
Glacial Spike no longer requires Fingers of Frost or Brain Freeze to cast after the restart.

**Comment by Scoliox** [comment]
Unfortunately the crit bugs seem to still be live. That's Glacial Spike's (as well as Snowstorm's) biggest issue at the moment while it has to compete with Deep Freeze on the same talent row. For single target, Deep Freeze can be reset by Cold Snap and is able to crit up to 5-6k against stun-immune targets (bosses pretty much) consistently thanks to FoF increasing its crit chance by 50%, or enable the usage of 2-3 Ice Lances (hitting 2k each) into a frozen target; which is the same amount of damage Glacial Spike does on 2 targets non-crit.

https://imgur.com/a/9uqRv2x - Used Glacial Spike only while under the effects of Fingers of Frost for the +50% crit chance amp. It also seems like Glacial Spike isn't affected by the talent 'Ice Shards' (increases Frost crit damage by 100%) as it only crits for 40%~ extra damage, not double, when it does crit. 

I think the real bugs here are Glacial Spike and Snowstorm not being a part of 'Fingers of Frost', 'Shatter',  and 'Ice Shards' their affected abilities. Could also be because Glacial Spike is listed under the General spellbook and not under any of the spec based spellbooks and that therefore it isn't seen as an actual mage ability? I did also test Glacial Spike on targets affected by Frost Nova which should also trigger Shatter's 50% increased crit chance bonus but it didn't work on those targets either which makes me think the ability is simply not flagged as a (frost) mage ability and therefore not affected by any of the mage talents. The 'Lonely Winter' ability for example does affect Glacial Spike's damage which I think is a general +15% increase to any Frost damage you do.

I'd still love to see Deep Freeze and Glacial Spike be on separate talent rows if possible, with Glacial Spike dealing reduced damage against players as a compensation nerf for PvP if the crit bug is ever fixed. Deep Freeze is a really fun ability to use in PvE due to how oomphy it hits and how you can use it back to back with Cold Snap. It also has uses in M+ and enables Frost mages to assist in stopping mob casts, which is something it currently really lacks relative to other specs.
