### ISSUE TITLE
Darkmoon Card: Maelstrom not proccing

### ISSUE THREAD

**Issue by ZaiDaDK** [Duskhaven/Bug-Reports#1791]
I sat afk and auto attacked a training dummy for around 360 auto attacks and the trinket did not proc a single time, I also tested it in my secondary spec and dual wielding for about 400 auto attacks and still no procs. Image link for proof https://imgur.com/FLMmsWg

Edit: Over 2000 melee attacks, no proc at all, https://imgur.com/a/hB2EBOG . Final image is for proof that the proc does exist on damage meters. I have reason to believe it is a problem with death knight. My friends playing hunter, druid, and paladin can all proc the trinket just fine, I can not. I have tried every presence, both of my specs to see if it was a talent, dual wield, 2 handing, no weapon equipped at all, equipping the trinket in the other trinket slot, making sure my game is completely up to date, using a previous version of patches, hitting npcs that are not a training dummy, hitting real players,,,, just about everything I could possibly think of and I am the only one unable to proc the item.

**Comment by Duskhaven** [comment]
Intended for DK's
