### ISSUE TITLE
falling through the floor and dying on hardmode

### ISSUE THREAD

**Issue by Kingdomofwar** [Duskhaven/Bug-Reports#1796]
I fell through the floor and died on hardmode while charging a mob. 

See attach photos I'm under Stromgarde Keep

![Screenshot 2023-05-27 182418](https://github.com/Duskhaven/Bug-Reports/assets/129566771/a62b4353-c20e-4dbb-933c-d9aa3dad36d9)
![Screenshot 2023-05-27 182500](https://github.com/Duskhaven/Bug-Reports/assets/129566771/b8cb9086-b9e6-4c81-9e72-0957168676d2)
![Screenshot 2023-05-27 182605](https://github.com/Duskhaven/Bug-Reports/assets/129566771/95777755-1084-48db-b905-a02c9f689e55)

**Comment by ryanportfolio** [comment]
Hey @Kingdomofwar this death will be excused, please submit an in-game ticket when you have a moment
