### ISSUE TITLE
bards can't roll on cloth and almost all leather drops are melee

### ISSUE THREAD

**Issue by pokeslog** [Duskhaven/Bug-Reports#1797]
Let bards roll on cloth drops in RFD, or give them a melee spec.    ALL leather drops in ALL dungeons are agi/str.    This was not thought out.   As it stands, their talent tree is screwed with many mooncrap junk not working for bard, the spells learned don't scale well (eg have multiple levels), and we have no third option for spec.   ALL OTHER CLASSES have 3 trees to chose from.  Bards have 2.. one of which is extremely weak.

**Comment by Duskhaven** [comment]
Belongs in the suggestion forum
