### ISSUE TITLE
Mage Fire Talent "Volatile Detonation"

### ISSUE THREAD

**Issue by paladin2080** [Duskhaven/Bug-Reports#18]
The 6 second burn effect is not working but the Hotstreak does work

**Comment by Duskhaven** [comment]
The Burn effect is visible on the ground, and is not applied as a DoT on enemies.

**Comment by paladin2080** [comment]
although its a flamestrike effect, it does not always proc

**Comment by Cavol315** [comment]
It does dmg only if you don't move during Blast Wave cast
