### ISSUE TITLE
Deafening Screech- Bard

### ISSUE THREAD

**Issue by Enigmaticresolve** [Duskhaven/Bug-Reports#1800]
Casting Deafening Screech while Virtuoso is active provides the animation of the target being "scared" and silenced, however they are not stunned and still are able to perform attacks. I think it's only granting the silence and not the stun when compared to how Coda of Cowardice works and grants 2 separate debuffs, 1 for the normal cast and the 2nd for the virtuoso cast.

**Comment by Duskhaven** [comment]
Fixed after restart
