### ISSUE TITLE
Dark Moon Faire not giving proper reputation

### ISSUE THREAD

**Issue by Thickoatmeals** [Duskhaven/Bug-Reports#1803]
As stated above, we are receiving only 14 rep per turn in when it should be 50 rep per Rogue deck. As well as 140 rep instead of 500 per Epic card deck turn in. Anyway we could fix this before the next time the faire comes?

**Comment by Duskhaven** [comment]
Duplicate, refer to https://github.com/Duskhaven/Bug-Reports/issues/1528
