### ISSUE TITLE
Demons don't inherit hit chance from master

### ISSUE THREAD

**Issue by Krzywomordy** [Duskhaven/Bug-Reports#1811]
Even tho I'm at almost 17% hit chance from hit rating alone
![obraz](https://github.com/Duskhaven/Bug-Reports/assets/50958510/7b046869-ec5e-45ed-9101-0bb43d4425d5)
my demons don't inherit any of that hit chance. 
My spells - no misses
![obraz](https://github.com/Duskhaven/Bug-Reports/assets/50958510/c33cd4e0-bfba-4e65-bb1a-8f6898cf4bd5)
Wild imps' Searing pain:
![obraz](https://github.com/Duskhaven/Bug-Reports/assets/50958510/62e5be37-a5c8-4dcc-9a1a-7d5fd171e599)
Felguard's attacks:
![obraz](https://github.com/Duskhaven/Bug-Reports/assets/50958510/89cc28eb-6bf4-4f5a-8c68-e9d7f32d62bb)

**Comment by Duskhaven** [comment]
Fixed
