### ISSUE TITLE
Blacksmith recipe being learnt in Player spellbook

### ISSUE THREAD

**Issue by kylejessetaylor** [Duskhaven/Bug-Reports#1818]
The recipe "Runed Copper Bracers" which can be learnt via BS trainer, doesn't populate in the BS menu, but instead shows under the General tab in the spellbook.

Img link: https://imgur.com/a/HrrSe3s

**Comment by Duskhaven** [comment]
Duplicate Issue, refer to https://github.com/Duskhaven/Bug-Reports/issues/218
