### ISSUE TITLE
Dwarfs are light rays 

### ISSUE THREAD

**Issue by Verplexa** [Duskhaven/Bug-Reports#1819]
This only happens with the Dwarf race and if I try to click on undead in the creator screen my game instantly crashes.
![72A16508-7015-411F-9469-9FEECC33E5FC](https://github.com/Duskhaven/Bug-Reports/assets/135031242/ff581409-38bb-477e-8925-70eb472a4471)

**Comment by ryanportfolio** [comment]
@Verplexa this is due to using incompatible patches in the Data folder

See this guide to make HD patches compatible: https://docs.google.com/document/d/1ylN2hidUWzzLMoI4eJqdQ1axceVKOkSfHGyvjV9K8i4/edit?usp=sharing
