### ISSUE TITLE
Empyrean Demolisher on-hit effect not working

### ISSUE THREAD

**Issue by FedeMontanari** [Duskhaven/Bug-Reports#182]
Weapon's haste on-hit proc effect isn't working at all.

Did multiple tries on dummies both dry (only white hits) and doing normal rotation for about 10-12 mins each and got absolutely no procs at all.

In case it was a visual effect where the buff didnt show on the buffs bar for some reason I still tracked the swing speed for both weapons and it didnt change either.

Couldn't test if it's an issue with the spell itself because the only other weapon sharing it (ID 21165) is the crafted TBC epic 1h mace.

**Comment by FedeMontanari** [comment]
Tried tracking the buff with [Skada](https://github.com/bkader/Skada-WoTLK) too but in a 15 minutes long sample (with only white swings) it didnt proc once.

This was an afk test so I wasnt able to check the swing speed to confirm if the stat is applying without the buff, but my guess is probably not.

**Comment by Duskhaven** [comment]
Works fine here. Some skills/procs might not trigger on Dummies for some reason.

![image](https://user-images.githubusercontent.com/123925176/224907020-5991ec27-d37e-4cff-85f2-eafd43b0becf.png)
