### ISSUE TITLE
Quel'Serrar Armor percentage

### ISSUE THREAD

**Issue by Andromira** [Duskhaven/Bug-Reports#1823]
![image](https://github.com/Duskhaven/Bug-Reports/assets/24929645/35101b96-d304-4670-8ab0-9670a6027787)
![image](https://github.com/Duskhaven/Bug-Reports/assets/24929645/ffeedc9f-89dd-4d5a-8e62-8c12a03acf7c)

the 300 additional armor for Quel'Serrar is only adding a .72% to my DK mitigation. That seems very low.

**Comment by Duskhaven** [comment]
Armor is affected by diminishing returns
