### ISSUE TITLE
Anthem of Defiance- Intended or Bug?

### ISSUE THREAD

**Issue by Enigmaticresolve** [Duskhaven/Bug-Reports#1833]
I am unsure if this is intended or a bug, due to lack of information, but Anthem of Defiance does not stack with other Auras/buffs that provide 60 resistance. In fact, what is odd is that according to the description it should provide 60 resistance to all schools, but it's actually providing 61 resistance. So, when you use Anthem of Defiance while another "resistance" aura is active, it only provides 1 additional resistance (Which the formula is 1 resistance per level = 60 at 60, not 61). Considering most raids and resist buffs/damage output of mobs, I don't think being unable to stack is intentional. It's a free cost, uses a GCD, and a 30 second CD for an unintended 1 additional resistance on top of resistance buffs. For these reasons, I believe this is a bug.

**Comment by Duskhaven** [comment]
Intended
