### ISSUE TITLE
Hunter T1 5P set effect is bugged and not working.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1834]
Hey Dev Team!

to verify this T1 5P set effect is not working, a full T1 set was compared with full T2 set it was clear to see that T1 set effect is not working.

Unless.... the Hunter T1 5P set effect is tied / binded to the Lone wolf talent all the way down the survival hunter tree.

As BM hunter this a problem because they dont invest into the survival talent tree.

**Comment by Duskhaven** [comment]
Only works with Lone Wolf.

**Comment by GoldWarr** [comment]
May ask if you guys mean the survival talent Lone Wolf or the normal Lone Wolf buff?
