### ISSUE TITLE
Savage Gladiator 3 set bonus not working with Shaman's Stone Warden

### ISSUE THREAD

**Issue by Yamato154** [Duskhaven/Bug-Reports#1838]
At level 60 and equipped with a shield and no other + defense rating items, defense is at 364.

When equipping 3 pieces of the Savage Gladiator set, defense is at 364.

When combining 3 pieces of Savage Gladiator with a shield defense rating is at 364.

Taking off a piece of Savage gladiator while still equipped with a shield defense gets lowered to 300.

Taking off the shield while still equipped with 3 pieces of Savage Gladiator, defense gets lowered to 300.

So it appears the bonus does not stack if you have a shield equipped and if you take off the set piece or the shield, you lose the bonus the other gives as well.

**Comment by Duskhaven** [comment]
Fixed after restart
