### ISSUE TITLE
Aspect of the Beast: Reduces Melee DPS ?

### ISSUE THREAD

**Issue by Naarujuana** [Duskhaven/Bug-Reports#1841]
Unsure if this is a tooltip error or what, but somethings not clicking with Aspect of the Beast.
My DPS in both BM and SV will drop by about 30-50, spec dependent, when I toggle on AotB.
Didn't notice it prior to today. My AP does go up, but in-game tooltip shows it as a 18% dps loss when AotB is toggled on.

**Comment by Duskhaven** [comment]
Fixed
