### ISSUE TITLE
Ashenvale simply doesn't work.

### ISSUE THREAD

**Issue by ClubEar99** [Duskhaven/Bug-Reports#1844]
No NPCs are spawning in Ashenvale except custom quest givers and including the flightmaster. This started at the time of the qiraji event and hasn't gone away. I expirienced some weirdness with it while leveling: the satyr enemies just didn't exist. But now there is not a single non-custom-quest giving NPC, gathering node, or anything else. I would really like this to be resolved, especially for the qiraji quests.

**Comment by Duskhaven** [comment]
You have to finish/abandon the custom Questline to get phased to the normal version again
