### ISSUE TITLE
Paladin Base T1 unobtainable 

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#1847]
With the changes to hydraxian sigils , the base Lawbringer set is now UNOBTAINABLE. In 6 weeks it has not dropped at all from the MCH mc and ac I do weekly, and u can't trade insigils or raider marks for them. I suspect they were removed from the drop table entirely. 

Please let us trade sigils and marks for base Lawbringer (NOT holy, ret, pro, but BASE)

**Comment by Duskhaven** [comment]
Added
