### ISSUE TITLE
Rogue Talent Gloomblade not working.

### ISSUE THREAD

**Issue by bowzef** [Duskhaven/Bug-Reports#185]
The DPS doesn't scale correctly, it doesn't hit twice like the tool-tip says, and Damage bonus is awful.
Had level 60 also try and figure it out and they said it doesn't scale at 60 either.

I went to a dummy and for about 40mins trying figure out what it does, it does a debuff on the mob "Chance to critically hit with spells  increased by 5%"

Not useful debuff- could be a tooltip issue though.

Suggestion 
Make it so its hemorrhage hits twice with a shadow bolt or some shadow base spell, that then hits for 15% of the total damage you done(Example hemorrhage 300+300 melee damage + 90 Shadow damage, make it scale off your melee damage, so harder you hit the more shadow damage it can do ) and remove spell crit and add melee crit with Spell power bonus on next Gloomstrike attack so that spell power bonus can apply to the Shadow damage part.

**Comment by Duskhaven** [comment]
The scaling has now been increased massively.
