### ISSUE TITLE
Whitemane in Cathedral won't die

### ISSUE THREAD

**Issue by Xenbiotic** [Duskhaven/Bug-Reports#1853]
Shaman Searing Totem (and maybe Magma Totem) interrupts Whitemane's resurrection spell on Mograine. Bricking the fight as she won't die and won't resurrect Mograine in order to drop her unkillable flag. Dots like _Rend_ for example doesn't interrupt her I believe.

![yuukiki8u87](https://github.com/Duskhaven/Bug-Reports/assets/67262624/72236a9f-4575-4a04-b306-d8743addaf57)

**Comment by Duskhaven** [comment]
Fixed after  restart
