### ISSUE TITLE
Files corrupted issue

### ISSUE THREAD

**Issue by daniel-nunes-03** [Duskhaven/Bug-Reports#1857]
![imagem](https://github.com/Duskhaven/Bug-Reports/assets/132585776/d3ffaa6d-e2fe-49e2-a8ef-c52e5d6a9d87)

Following the discord guide, my friend downloaded "https://wowdl.net/client/3.3.5a-win-us" present in the client instalation guide (text channel #how-to-connect) and downloaded the launcher, following the instructions step by step.

Unfortunately, an error still occurs after executing the launcher and installing the files needed to run duskhaven. When he tries to enter WoW, an error occurs saying "Your login interface files are corrupt. Please reinstall the game".

**Comment by ryanportfolio** [comment]
@Maxjoni if using the launcher > go into launcher settings > wow.exe fix

to do this manually: delete the wow.exe in your client folder and replace it with custom one: https://drive.google.com/file/d/1lUn8BRpoomqBnKL9FGXDFNei2YWwYNL-/view?usp=sharing

**Comment by daniel-nunes-03** [comment]
It worked, thank you!
