### ISSUE TITLE
Enigma Circlet - being sold twice from Azenel

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1858]
Item 21347 is being sold by Azenel for a Chestguard of the Vanquished Defender as well as Vek'nilash's Circlet

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/5e48ba11-baaf-41c9-a069-33e6c6a26745)

**Comment by Duskhaven** [comment]
Intended, they can be bought with either a circlet or set token.
