### ISSUE TITLE
[AQ40] Bug Trio - Kri Venom

### ISSUE THREAD

**Issue by Hyperbearr** [Duskhaven/Bug-Reports#1863]
Lord Kri of the Bug Trio encounter in AQ40 drops his poison pool as expected, however it visually doesn't match the area it hits and currently globals melee dps. This visual issue either needs to be fixed or the damage of the area of effect needs to be scaled down so that it can be played around.

**Comment by Duskhaven** [comment]
Damage and tick rate lowered by 25%
