### ISSUE TITLE
[AQ40] Twin Emperors - Unbalancing Strike

### ISSUE THREAD

**Issue by Hyperbearr** [Duskhaven/Bug-Reports#1867]
Currently unbalancing strike on the Twin Emperor encounter is overtuned, hitting fully geared tanks (both Prot Warrior and Bear Druid) for over 15k damage after mitigation, this needs to be reduced for the encounter to be played as intended.

**Comment by Duskhaven** [comment]
Damage lowered by 30% and has received a cast time after restart.
