### ISSUE TITLE
Secrets of Karazhan - quest reward

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1881]
When picking up the quest it shows that a Token of the Forgotten Vanquisher will be rewarded
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/f54e0b33-3f61-4994-8e3d-02df2dde7c82)

However once the quest is in the log that changes to 3 Mark of the Raider
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/bc16d961-53d4-4f89-ab0a-04bcdc63a512)

**Comment by Duskhaven** [comment]
Closing and reopening the game fixes this issue
