### ISSUE TITLE
Season 2 Expertise Rating set bonus does not stack with Tier 2 Expertise Rating set bonus

### ISSUE THREAD

**Issue by KreepAK** [Duskhaven/Bug-Reports#1885]
Penance, Season2, 3 piece set bonus has +14 Expertise Rating, which DOES NOT stack with Death Knight/Warrior Tier 2, Wrath (DPS), 2 piece set bonus, which also has +14 Expertise Rating.

When equipped alone, both sets work fine. So basically, if I want to equip both sets to get expertise boost, I will get only 1 bonus from one of the sets (depends what was equipped first).

**Comment by Duskhaven** [comment]
Intended
