### ISSUE TITLE
Azenel does not have proper stock

### ISSUE THREAD

**Issue by Yuther2010** [Duskhaven/Bug-Reports#1891]
for druid hunter and those folks, they have available to them the pants by using the skin of the great sandworm and the helmet using vek'lor's diadem without the quest but for mages warriors and the like they only have the helmet available using Vek'nilash's circlet. Are one half of the classes supposed to have more available to them than the other half?

**Comment by Yuther2010** [comment]
For reference, I saw this while on a mage

**Comment by Duskhaven** [comment]
There are 2 Skin and Circlet Items, each of them require different Classes to turn in.
Missing legs for the skin exchange have been added for Rogue, Priest and Mages
