### ISSUE TITLE
Enchant Cloak - Subtletly

### ISSUE THREAD

**Issue by Vyntoras** [Duskhaven/Bug-Reports#1892]
It requires TBC mats like Greater Planar Essence and Primal Shadow. 
I don't have the other enchants yet but they may also have such problems, please check!

**Comment by ryanportfolio** [comment]
This enchant also has the same issue -

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/ff33b0f7-7837-4864-8b23-31ff8968862e)

**Comment by Duskhaven** [comment]
Mats changed to Vanilla with the next patch update
