### ISSUE TITLE
[Important] AQ40 Upgraded Illidari Warglaive - 'disable' DH spells

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1893]
There's an error of "that item is not a valid target" when trying to enchant them 

Equipping these will also cause DH abilities to not work:
https://media.discordapp.net/attachments/1104614467767128064/1115520274662694974/World_of_Warcraft_2023-06-06_00-58-32.mp4

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/7338b755-e5e8-48e8-8c46-6d98ec10027e)
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/73d220bc-ca61-40d2-8ea3-10fe6321a5be)

These are the upgraded versions from AQ40

**Comment by ryanportfolio** [comment]
**Update**: They can both be equipped now, however the 1.6 speed can only be equipped in the main hand 

the error when trying to enchant is also present 
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/52e258c6-e5a5-42f0-9abe-886300d4195b)

**Comment by ryanportfolio** [comment]
_Equipping these will also cause DH abilities to not work as seen in the videos:_

https://media.discordapp.net/attachments/1104614467767128064/1115520274662694974/World_of_Warcraft_2023-06-06_00-58-32.mp4

https://media.discordapp.net/attachments/1104614467767128064/1115520272884305980/World_of_Warcraft_2023-06-06_00-55-56.mp4

**Comment by AntoTKO** [comment]
Also want to add that the 2.6 speed weapon cannot be placed in the main hand slot either.

**Comment by AntoTKO** [comment]
Also adding that the equip effect doesnt proc:
![image](https://github.com/Duskhaven/Bug-Reports/assets/133019013/a2263efb-1aed-4450-9d8a-a34788e1ee13)

**Comment by Duskhaven** [comment]
Requires a patch update that will release later today

**Comment by Obleh** [comment]
So you also can't use Double Jump and Chaos Strike in tank stance while having the new Warglaives equipped.
