### ISSUE TITLE
Paladin 2.5 - 2 set bonus

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1894]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/3b992c46-d6f5-4935-b37d-632f2749b2da)

When the targeted player receives Beacon of Light, the 3% health bonus is applied to the paladin who cast the Beacon of Light - not the target

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/f41a4cd5-60c7-4f87-96e7-df2393eda325)
not applied to target

**Comment by Duskhaven** [comment]
Fixed after restart
