### ISSUE TITLE
C'Thun's Digestive Acid dot stays permanently on pet

### ISSUE THREAD

**Issue by Congroo24** [Duskhaven/Bug-Reports#1896]
The dot stays after raid. I can't get rid of it by dismissing or sacrificing pet.
![image](https://github.com/Duskhaven/Bug-Reports/assets/131566445/6d17b65e-0bf0-49fb-adf8-e9a921170acb)
Furthermore, pets can't live during this fight as they always get this debuff, resulting in them dieing all the time.

**Comment by Duskhaven** [comment]
Fixed after restart
