### ISSUE TITLE
A Pawn on the Eternal Board - quest won't complete

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1897]
Quest 8519 - after accepting and experiencing the event/story, it doesn't complete itself.

It was reported that, "The different dragons came but the Qiraji weren't there (or not visible for me), Staghelm showed up and left again and then nothing happened"

https://www.wowhead.com/classic/quest=8519/a-pawn-on-the-eternal-board

**Comment by Duskhaven** [comment]
Fixed
