### ISSUE TITLE
Joining LFG different phase with partial clear

### ISSUE THREAD

**Issue by Frauce** [Duskhaven/Bug-Reports#19]
Character Name: Frauce
Zone/Area: Blackfathom Deeps
Screenshot/Video: None taken
Issue: 
When joining a dungeon, at least with the LFG tool, if you join in when the dungeon is partially completed you will be in a different phase and nothing will have been cleared. If you attempt to teleport out of the dungeon and back in you will then be at the front of the dungeon and nothing will still be cleared. A fresh looking dungeon. 

A note here is that when you initially join in everyone's health is 1/1 until you relog and then it goes back to normal.

**Comment by Duskhaven** [comment]
Cannot replicate
