### ISSUE TITLE
Warlock T2.5 2/4 bonus set doesn't work for demolock

### ISSUE THREAD

**Issue by Congroo24** [Duskhaven/Bug-Reports#1900]
There is no 10% dmg increase buff on the pet after using DE, and another imp doesn't appear.
![image](https://github.com/Duskhaven/Bug-Reports/assets/131566445/105841ab-b904-41e2-8b84-e7ec3934a3f2)
Furthermore, DE is already summoning an imp on proc without the tier bonus. So if the bonus doesn't summon a 2nd imp, it is irrelevant.

**Comment by Duskhaven** [comment]
Fixed
