### ISSUE TITLE
Hunter 2.5 set bugged

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1901]
the 2P set effect for marksman is impossible to keep up it only last 4-5 secs .

And poisoned shots can only be procced with Aimed Shot, Arcane Shot and Steady Shot.

A marksman hunter uses mainly Aimed Shot and Arcane Shot as there stable skills.

its very difficult to keep any stacks and even focusing they fall of to quickly.

Can the other 2P effect be changed to Explosion Shot / Chimera Shot?
its sort of not really great to see this Set being busted for ranged surv hunter and almost useless for marksman.

**Comment by Duskhaven** [comment]
Duration increased after restart
