### ISSUE TITLE
Cannot Double Jump or Chaos Strike in DH Tank Form when I don't have two glaives equipped.

### ISSUE THREAD

**Issue by harrisonzalman** [Duskhaven/Bug-Reports#1903]
This just started happening and I'm not sure why. I have fresh 60 version of glaive MH equipped, flurry axe OH and noticed when I go into DH Tank form I can't double jump or chaos strike. When I go back into DH DPS form, I can still use both. 

I played around with different weapon configurations to see when it happens. If I equip a glaive into OH (so glaive MH and OH) I can double jump/chaos strike in DPS tank form again. But any OH that I put in besides a glaive (including no OH) and I can't double jump or chaos strike again.

Relogging/refreshing does not fix this issue. I also asked a bunch of other DH to try and they don't see this issue.

Char name is Haroldstab if you have any questions.

**Comment by Duskhaven** [comment]
Intended. Most abilities only work with 2 glaives equipped.
