### ISSUE TITLE
Hunter Damage showing x99%

### ISSUE THREAD

**Issue by teaiwen** [Duskhaven/Bug-Reports#1904]
i hope this isnt something that is already addressed. While in marksman spec, not sure if it applies to all specs at the moment, i noticed the damage under ranged and melee with a pet out shows in red with x99%. With pet dismissed and lone wolf applied the damage is green with x123%. but that doesnt make sense as lone wolf is +25% dmg, so 99 +25 should be 124%. but the x99% with a pet out doesnt make sense to me either as it seems we are losing 1% of damage for some reason?

**Comment by GoldWarr** [comment]
Oh i might know but another dev from the game dev team can make sure if im right.

Hunter marksman specc got nerfed a few patches ago, this is why you see red minus number on your stat window.
