### ISSUE TITLE
Twin Emps Portal + Twin Emps Door

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1907]
This portal gets **very** easily 'stuck' in phase -1 

In majority of cases the portal will not be visible 

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/5ed3a8f5-6464-40e1-87fc-3fff19a29f59)

I know it was mentioned that "if it's not there its probably been over 1 day since you've killed them" - but it's going to be normal to take multiple days, and there have been reports of it going back into phase -1 even on the same day. 

---

As for the Twin Emps door, this is confirmed to close itself every time after a C'Thun wipe, making it impossible to get through without intervention. 

And potentially a wipe before C'Thun as well.

**Comment by Wheemix** [comment]
We killed both Emps and Cthun in the same raid today and never saw any portal in the first place. So we could not tell whether it never spawned or simply despawned very shortly after...
