### ISSUE TITLE
[Warrior] SMF movespeed

### ISSUE THREAD

**Issue by Wheemix** [Duskhaven/Bug-Reports#1908]
As per the tooltip, SMF is supposed to give 10% movespeed, however using a Weakaura that shows my current movespeed I can see that it only gives 8%. 

Secondly, and here I am not sure if this is intended or not, but this 8% increase does not stack with minor speed enchant on boots, either is giving 108% total speed by itself.

**Comment by Duskhaven** [comment]
Speed increased to 10% after restart
