### ISSUE TITLE
Secrets of Karazhan - "Duplicate Item Found"

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1909]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/91ea378d-9e01-48f7-b896-7d85efd61ceb)

The quest can't be turned in due to already having item 24490 (The Master's Key)

An easy workaround, but there will be confusion when someone tries to turn the quest in unless they know to delete the key to be able to get a new one

**Comment by Duskhaven** [comment]
Fixed after restart
