### ISSUE TITLE
Arms T2.5 4set Not working

### ISSUE THREAD

**Issue by Hansson921** [Duskhaven/Bug-Reports#1916]
The arms 4set bonus is not working properly, The shockwaves from bladestorm cause 200 noncrit 300 crits which is quite lackluster, And the 2% crit that's supposed to stack 8 Times and last for 12 seconds dosen't stack And It dosen't last for 12 seconds, It dosen't even show up as a buff, It does give you 2% crit for the duration of the bladestorm Which lasts  6 seconds. 

This should probably be adressed That's it for me

**Comment by Duskhaven** [comment]
Crit stacks properly after restart
