### ISSUE TITLE
Poisoned Shot Talent is bugged

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1918]
Hello Dev Team,

Talent is not adding the 10% additional damage as stated , it seems to be 2-3%.

Example is my current Aimed Shot it hits for 3,3k Crit but poisoned shot only grants 113 dgm.

**Comment by Duskhaven** [comment]
Fixed after restart. Talent does 40% Weapon Damage, not based on the Arcane or Steady Shot.
