### ISSUE TITLE
Demon hunter tier 2.5 2/4 set bonus crit chance

### ISSUE THREAD

**Issue by 42343243242** [Duskhaven/Bug-Reports#1928]
Not sure if it's intended or not, but the crit chance of the elemental seems to be extremely low or nonexistent, as seen on these screenshots from hitting the Expert's Training Dummy
![Screenshot_286](https://github.com/Duskhaven/Bug-Reports/assets/129960795/1a1ccde7-34fb-4061-851d-1e58fbb5e900)
![Screenshot_285](https://github.com/Duskhaven/Bug-Reports/assets/129960795/57c159e5-738d-4e36-981f-548639af0aef)
![Screenshot_287](https://github.com/Duskhaven/Bug-Reports/assets/129960795/feb8b899-58e9-41fc-8b5f-52c6daf86d9e)

**Comment by Duskhaven** [comment]
Intended
