### ISSUE TITLE
Tinker Rocket Launcher does not grant buff.

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#1931]
Tooltip states that Rocket Launcher provides 2% crit and hast and stack up to 5x.   According to my test, it does not stack up to 5x and also it does not grant 2% crit and hast.
![With_Rocket_Launcher_Buff](https://github.com/Duskhaven/Bug-Reports/assets/127713434/7ec40dbd-0a9f-4488-a429-a0b8cb5f35f8)
![Without_Rocket_Launcher_buff](https://github.com/Duskhaven/Bug-Reports/assets/127713434/3a9252a2-4584-4bdd-b6a5-fc89f349be8a)

**Comment by Duskhaven** [comment]
Tooltip adjusted with the next patch
