### ISSUE TITLE
STOP TOUCHING Demon Hunters

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#1934]
Chaos strike DPS very hellish geared  have now 700 chaos strike with new glaives and old BWL glaives 696 Chaos strike  
before updates and resets  Chaos strike was around 800 -900  

STOP doing stealth nerfs and give back Chaos strike to at least  1k when we are fully t2 and geared as hell

**Comment by 42343243242** [comment]
t2.5 set bonuses are bad as well (haven't seen 4/4 yet but i assume it's bad)

**Comment by xAzeroth** [comment]
we dont have  Tank gear  like   " equip  dodge rating , parry  at all "   defense just nothing copy paste  retail t2.5 and new set bonuses wich doing more  dps than tank
