### ISSUE TITLE
Hunter T2 3pc and 5pc bonus does not provide dmg bonus

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#1941]
Hunter T2 3pc bonus does not provide 5% dmg when scrap gun is modified.  According to my test.  Scrap bullet does the same dmg with or without scrap gun been modified.  Also, T2 5pc does not provide additional 3% dmg to lone wolf.

![WoWScrnShot_060923_223040](https://github.com/Duskhaven/Bug-Reports/assets/127713434/a8e8c2b6-e49b-4b9f-b85d-df3caeb26371)
![WoWScrnShot_060923_223201](https://github.com/Duskhaven/Bug-Reports/assets/127713434/0c906c4c-c5a3-4714-bbca-3cffddec3abb)

**Comment by Duskhaven** [comment]
Fixed after restart
