### ISSUE TITLE
Demon Hunter 2.5 -- 4 Set Issue

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1942]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/3a7b1e2e-6ac0-4f68-bb5b-d3e34d559ba0)
video of the issue: https://media.discordapp.net/attachments/1104614467767128064/1116937114630750238/World_of_Warcraft_2023-06-09_22-47-57.mp4

https://cdn.discordapp.com/attachments/1104614467767128064/1116944771299151902/World_of_Warcraft_2023-06-09_23-18-07.mp4

- The demon is not able to be killed by party members
- When the demon dies, it doesn't do any damage
- 5% increased damage or 6% health doesn't appear to be working 
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/e69f062a-9c7a-4a6f-8be5-eca5db6e2560)

**Comment by AntoTKO** [comment]
Can confirm, mob stays as a guardian, sits there. Doesnt despawn. Cant kill doesnt explode for dmg etc. Doesnt provide Health or DPS increase

**Comment by AntoTKO** [comment]
[World of Warcraft 2023-06-09 22-56-58.zip](https://github.com/Duskhaven/Bug-Reports/files/11711486/World.of.Warcraft.2023-06-09.22-56-58.zip)

**Comment by AntoTKO** [comment]
[World of Warcraft 2023-06-09 23-18-07.zip](https://github.com/Duskhaven/Bug-Reports/files/11711490/World.of.Warcraft.2023-06-09.23-18-07.zip)

**Comment by Duskhaven** [comment]
Fixed
