### ISSUE TITLE
AQ40 - No Scarab Coffers.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1946]
There are no Scarab Coffers inside AQ40 making it impossible for people to use there Scarab Keys they obtain by killing mobs inside AQ40.

Those Scarab Coffers are essntiel to get  AQ40 Idols and Scarabs.

**Comment by Duskhaven** [comment]
Coffers have been added at following blizzlike locations. (Location taken from wowhead)

![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/ee675331-38e8-4654-b877-5a533a27d299)
