### ISSUE TITLE
New Aimed Shot issue (MM Hunter)

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#1948]
Aimed Shot being cast can be interrupted and delayed if the Hunter receives any damage.

Also there is no Talent that can help stop any delays to Aimed Shot being cast like Steady Shot got .( Focus Aim)

Is that intended? If not my suggestion to help with this issue is to give the already existing Talent " Focused Aim " the option to take Aimed Shot into account as well.

Or add it to the Talent Skill Aimed Shot itself.

**Comment by Duskhaven** [comment]
Can no longer be interrupted when receiving damage after restart
