### ISSUE TITLE
Bard Bugged S2 Setboni 3/5

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#1949]
Hi
The 3piece set bonus for balance bard is bugged. It´s not increasing the rift damage by 10%, when target is debuffed by power chord - virtuoso as shown in the tooltip.
But the "Dot can crit" - Part works fine.
Greetings

![image](https://github.com/Duskhaven/Bug-Reports/assets/127632931/13e8f34a-1183-4e05-b2e6-53615b4c897b)

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/1849
