### ISSUE TITLE
DPS STANCE and Tank Stance Demon Hunter

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#1954]
DPS STANCE and Tank Stance sometimes droping in raids and in M+ runs 
not sure what skills doing that to drop it

**Comment by Duskhaven** [comment]
Intended when using Talents that are too deep in the Assa or Sub tree

**Comment by xAzeroth** [comment]
let me post my talent for Tank and tell me if you see "TOO DEEP " Assa or Sub tree 

![image](https://github.com/Duskhaven/Bug-Reports/assets/132115122/dd054d5c-c501-4348-ad6e-03e5cc87ef5c)
![image](https://github.com/Duskhaven/Bug-Reports/assets/132115122/4dbc384d-a62f-4673-b6e4-03b2a6baece9)
![image](https://github.com/Duskhaven/Bug-Reports/assets/132115122/a02f172c-ccb7-4145-aa9c-d5abcf85a911)

Now tell me where is my mistake
