### ISSUE TITLE
Tinker Jet Pack bugged

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#1955]
Tinker Jet Pack does not provide immunity to fear, stun, silence, interrupt.  Also, it does not provide 30% dmg reduction.
![WoWScrnShot_061023_192655](https://github.com/Duskhaven/Bug-Reports/assets/127713434/6eeaa680-71c9-4625-8e8f-0d435e2e617c)

**Comment by Duskhaven** [comment]
Fixed after restart
