### ISSUE TITLE
The Prophet Skeram - Arcane Blast (normal mode)

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1956]
The arcane explosion is hitting raid wide. Usually clones are separated so that part of the raid doesn't get hit by this.

This arcane explosion can't be outranged, and due to the frequency of its casts + infinite range + all players affected, this causes it to be extremely difficult to heal through. 

Please consider making this ability capped to a radius of 30 yards (this is what it's supposed to be per https://www.wowhead.com/classic/spell=26192/arcane-explosion)

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/c66e68c8-1bc6-4bdd-98f7-fe7570493212)

**Comment by Duskhaven** [comment]
Radius is already set to 30 yards
