### ISSUE TITLE
Resto Bard "Coda of Cowardice" doesn´t increase damage taken

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#1960]
![image](https://github.com/Duskhaven/Bug-Reports/assets/127632931/23ffa89d-3a92-4a92-a554-3f397b66091a)

Debuff is correctly applied to enemies, but does not increase the damage taken. I only tested for magic damage.

**Comment by Duskhaven** [comment]
Fixed after restart
