### ISSUE TITLE
Tinker T2 is still bugged

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#1963]
I previously submitted a ticket (1941 now closed with reply "Fixed after restart".  I believe the server was restarted many times since).  The bug is still not fixed.  As I stated before in my previously ticket, T2 3pc bonus does not provide 5% dmg when scrap gun was modified.  According to me tests, scrap bullet still does the same amount of dmg with or without scrap gun been modified.  Also, T2 5pc still does not provide additional 3% dmg to long wolf.
![WoWScrnShot_061123_105311](https://github.com/Duskhaven/Bug-Reports/assets/127713434/44ff4a95-ab41-4f5a-80d2-9d24f52c812b)
![WoWScrnShot_061123_105154](https://github.com/Duskhaven/Bug-Reports/assets/127713434/b62885bc-c0d1-4135-8634-f2cf669f9aa4)

**Comment by Duskhaven** [comment]
Lone Wolf only works for hunters
