### ISSUE TITLE
Druid (Feral) T2.5 Chest missing expertise

### ISSUE THREAD

**Issue by FatherSylla** [Duskhaven/Bug-Reports#1964]
All 2.5 items have slightly upgraded stat tables from t2, with the exception of the Genesis (Feral) chest, which is missing expertise, making it impossible to test the set without dropping the expertise cap. This seems like it was overlooked - please add the expertise on the chestpiece :) 

![2023-06-10 (2)](https://github.com/Duskhaven/Bug-Reports/assets/136253714/c498be88-29f9-4ca9-9c76-bb101a6d9156)

**Comment by Duskhaven** [comment]
Fixed after restart
