### ISSUE TITLE
No Arena Points being given 

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1965]
After confirmed wins in the Arena, no Arena Points were rewarded

No honor points were given either

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/e79e876b-d8e6-46f7-ab25-a5fd5160b4dd)

**Comment by Duskhaven** [comment]
Arena Points are given each week, refer to 

https://wowwiki-archive.fandom.com/wiki/Arena_point
