### ISSUE TITLE
Warrior battle stance not giving bonus Armor Penatration

### ISSUE THREAD

**Issue by rborrowman** [Duskhaven/Bug-Reports#1966]
![battle stance](https://github.com/Duskhaven/Bug-Reports/assets/129297908/c7935cae-b71e-4efa-9c0b-6b75b92a5f47)
![berserker stance](https://github.com/Duskhaven/Bug-Reports/assets/129297908/45bbad62-248f-4855-89aa-948c44226d73)

**Comment by Duskhaven** [comment]
Armor Pen gained from Talents/Stances is not shown in the char stat sheet.
