### ISSUE TITLE
Warrior 2 piece T1 not giving armor penatration bonus.

### ISSUE THREAD

**Issue by rborrowman** [Duskhaven/Bug-Reports#1967]
![2P T1](https://github.com/Duskhaven/Bug-Reports/assets/129297908/95e1c9c2-3766-49f0-9ec9-e17c057bd235)
![T1 Bracer](https://github.com/Duskhaven/Bug-Reports/assets/129297908/dfe8f1a3-5ff3-477f-b12a-ec872a3d4e1c)
![T1 chest](https://github.com/Duskhaven/Bug-Reports/assets/129297908/2a7b5191-b6b0-4797-a158-486cb4b617e9)

**Comment by Duskhaven** [comment]
Armor Pen gained from Talents/Stances is not shown in the char stat sheet.
