### ISSUE TITLE
Warlock tier 2.5 set Bug

### ISSUE THREAD

**Issue by Tatya97** [Duskhaven/Bug-Reports#1970]
Can you please fix the tier set for Warlocks.
- The 2-set bonus in the 2.5 tier for locks doesn't work for demonology, there is no increase in damage for Felguard by 10% or the imp gang additional proc.
- The 4-set bonus for affliction Lock summons the pet but it does not apply any of the dots it should be doing.
![lock bug](https://github.com/Duskhaven/Bug-Reports/assets/127970258/fc63263e-0b69-4303-b091-3d8ddb4f46a1)

**Comment by Duskhaven** [comment]
Darkglare is now casting the correct spells
