### ISSUE TITLE
The Wrath of Neptulon Quest Item not Dropping

### ISSUE THREAD

**Issue by plasma-93** [Duskhaven/Bug-Reports#1974]
I killed Maws after summoning him with the Arcanite Buoy as the quest demands, did not get a Blue Scepter Shard :(

![image](https://github.com/Duskhaven/Bug-Reports/assets/38546519/806c2702-9c94-4e59-ad02-239ff578c321)

**Comment by plasma-93** [comment]
I would do it again to test, but it kinda costs a fuck ton of gold lol

**Comment by Duskhaven** [comment]
Fixed
