### ISSUE TITLE
Demon of the Twisting Nether

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1975]
As a followup to https://github.com/Duskhaven/Bug-Reports/issues/1942

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/c5cea79a-b7cf-413d-970b-ae7e5245b03d)

Party members are not able to attack the demon

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/5360f202-0c26-475c-9794-4dbf6b06ab98)

**Comment by Duskhaven** [comment]
Any spell from players that is cast near the Demon makes him die shortly afterwards while in combat, visual issue.
