### ISSUE TITLE
Rogues Deck - Reputation Amount

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#1976]
Quest 12517 is rewarding less reputation than it should at level 60 
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/5c23ac9b-146b-4e42-ad4d-a71b76dc12e4)

Intended amount:
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/6c3bdc94-32d9-4237-85aa-a36cd7bb5d56)

**Comment by Duskhaven** [comment]
Fixed
