### ISSUE TITLE
Fire mage 2.5 p2/p4 need clarification or fixing

### ISSUE THREAD

**Issue by Yuther2010** [Duskhaven/Bug-Reports#1977]
The 2p for the fire mage portion states "Your Pyroblast causes the target to take an additional 5% fire damage and the enemy burns for additional damage while Hot Streak is consumed" The 2p dot does not always apply once hot streak is consumed and either a fix or % chance label would be appreciated. The 4p states "Your Hot Streak now guarentees your Pyroblast to be a critical strike." This effect does not occur in conjunction with Blast Wave and the Hot Streak granted by Volatile Detonation

**Comment by Duskhaven** [comment]
Cannot replicate. 2p always procs with Pyroblast and 4p Only triggers from the talented version of Hot Streak, not the one gained from Volatile Detonation.
