### ISSUE TITLE
Logout not Instant in Stormwind

### ISSUE THREAD

**Issue by PSIN-dev** [Duskhaven/Bug-Reports#198]
Takes a full 20 seconds to logout in every area of Stormwind I have personally tried it in.

**Comment by PSIN-dev** [comment]
Seems to be instant in the park

**Comment by PSIN-dev** [comment]
I figured it out, Warmode is what causes you to be unable to instantly logout.

**Comment by Yurimir** [comment]
Same, WM causes it not to be instant in Orgrimmar as well.
