### ISSUE TITLE
Arms 4set still not working

### ISSUE THREAD

**Issue by Hansson921** [Duskhaven/Bug-Reports#1980]
Hi Again
Now we do get a buff but it only triggers from the first bladestorm hit, not the third, not the second etc. And It dosen't stack, In fact, The buff has no text at all except "Arms 4/4 Shockwave Crit" And It only grants 2% crit and Dosen't stack until 16%. 

The Icon changes and copies another buff instead of haveing its own Icon.

And Now the shockwave only does 100 dmg extra which seems extremely low. For a 4set bonus.

**Comment by Duskhaven** [comment]
Buff now correctly stacks
