### ISSUE TITLE
Tanking Necklaces are not appropriately statted.

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#1983]
![image](https://github.com/Duskhaven/Bug-Reports/assets/52112645/6ac241f7-cfaf-4ab9-9bdc-54fb354f6ea3)

The necklace from ZGH has the highest ilvl (as it should, given the raid is hardest) but is inferior to the one from MCH. 

The one from Kara is also badly statted and could do with an ilvl/stat bump.

**Comment by Duskhaven** [comment]
Items adjusted after restart
