### ISSUE TITLE
Death Knight Tier 2.5 set bonuses NOT WORKING and VISUALLY BUGGED

### ISSUE THREAD

**Issue by BettyEvil** [Duskhaven/Bug-Reports#1986]
Death Knight Tier 2.5 set does not work properly. First off it puts a debuff on target dummies and trash pulls and this is the first issue. the debuff plague strike puts on targets is a icon that has Featherfalling....and it says DK 2/4 unh pestules with no value change. It always stays at this debuff and this tooltip no matter how many plaguestrikes you do. 

the other issue is there is no indicator that you are gaining 1% increased shadow damage stacking up to 5 times when popping this debuff.

3rd issue is that this ability is not proccing on Raid Bosses.

**Comment by Duskhaven** [comment]
Pustule has to be popped with death coil to deal damage. Immune issue against raid bosses is fixed after restart

**Comment by BettyEvil** [comment]
i know its not popping with death coil. its why i even made this post
