### ISSUE TITLE
Fire Mage 2.5 not working properly

### ISSUE THREAD

**Issue by Yuther2010** [Duskhaven/Bug-Reports#1987]
The dot that is applied once hot streak has been consumed via the 2p does not apply in two circumstances: 1. You are too far away, which is very common if the mage has Flame Throwing talented and common at max range. 2. the target has not received damage from the mage prior to the pyroblast cast. This is possible if the mage decided to start the fight with an out of range Blast Wave in an attempt to start the fight off with pyroblast or swapping to a different target once hot streak has already been gained. In addition, the 4p guaranteed critical strike is still set at 4 seconds while hot streak is a 9 second duration. This is an issue when you have bosses that have reflect phases where the mage has to hold the pyroblast for 5 seconds and loses the guaranteed crit or even if the mage has to move during those 4 seconds. If it's intended to have a shorter timer then additional text would be appreciated.

**Comment by Yuther2010** [comment]
Please let me know if additional information is necessary

**Comment by Duskhaven** [comment]
Range increased after restart.
