### ISSUE TITLE
Eranikus +8 one-shots

### ISSUE THREAD

**Issue by PSIN-dev** [Duskhaven/Bug-Reports#199]
Eranikus +8 can breath, melee and volley all in the same second, doing close to 10k damage. Not tested on lower keys. Overall boss is easily 3x more difficult than any other +8 boss.

**Comment by Duskhaven** [comment]
Time between abilities has been reduced, Poison Bolt Volley deals 30% less Damage, and some Spells are now used at a lower health percentage then before.

Fight should be much more manageable now.
