### ISSUE TITLE
S2 Ruby Tier Set for Warrior Tank 

### ISSUE THREAD

**Issue by Hammyys** [Duskhaven/Bug-Reports#1991]
There's two problems come along with the S2 Ruby Tier Set, it adds Cleave with 3 seconds Cooldown and remove the UI Berserker Rage Cooldown. However, the Berserker Rage Cooldown is still working but Cleave ability actually gained 3 seconds CD even though the set bonus doesn't mention any gain to Cleave Ability Cooldown and all these issues are removed once I stop wearing the Ruby S2 Tier set. I think it's from the 5th set bonus.

![image](https://github.com/Duskhaven/Bug-Reports/assets/131460518/7a35a77c-37ec-4972-ad20-76cb05e6272e)
![image](https://github.com/Duskhaven/Bug-Reports/assets/131460518/5702b61d-bcfb-4e9d-89a4-2829cda89884)
![image](https://github.com/Duskhaven/Bug-Reports/assets/131460518/8a889180-8ccf-4cca-b1e1-7e69bd7cf61e)

I don't know if these captures works but there you go.

**Comment by Duskhaven** [comment]
Fixed
