### ISSUE TITLE
Demon hunter t2.5 4/4 set bonus

### ISSUE THREAD

**Issue by 42343243242** [Duskhaven/Bug-Reports#1992]
Currently the fel demon only melees for 40 dmg, and upon explosion deals 1k dmg, is this intended? 1k dmg doesn't really scream "heavy damage" if so then I guess t2.5 is not worth using for demon hunters, and I would like to enjoy cool new bonuses as well.

**Comment by Duskhaven** [comment]
Damage increased after restart

**Comment by xAzeroth** [comment]
fel demon still doing melee dmg for  30-40 dmg
