### ISSUE TITLE
Tinker T1 2pc bugged

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#1995]
Tinker T1 2pc bugged.  Diffusing bomb does not strike the target second time for addition fire damage beyond 15yrd.  Please see attachment.

At 30yrd range:
![WoWScrnShot_061323_165335](https://github.com/Duskhaven/Bug-Reports/assets/127713434/9b1ec29f-e9dd-40cf-bb39-6bf1dee9ab32)

At 15yrd range:
![WoWScrnShot_061323_165350](https://github.com/Duskhaven/Bug-Reports/assets/127713434/a94ec251-97fe-46e9-9bee-47626e1a8d6e)

**Comment by Duskhaven** [comment]
Range increased after restart
