### ISSUE TITLE
fire mage 2.5 2p movement

### ISSUE THREAD

**Issue by Yuther2010** [Duskhaven/Bug-Reports#1997]
My apologies for prior ticket mistake, the reason behind the 2p dot not applying from blast wave was not due to the pyroblast being the first instance of damage but because the pyroblast was being cast while the mage was moving. So, the 2p dot applied from the hot streak pyroblast does not proc while the mage casts pyroblast while moving.

**Comment by Duskhaven** [comment]
Movement no longer supresses the proc after restart
