### ISSUE TITLE
Death knight 2.5 set still not working after issue being closed

### ISSUE THREAD

**Issue by BettyEvil** [Duskhaven/Bug-Reports#1998]
Raid bosses are still immune to the pustules exploding

![WoWScrnShot_061323_202709](https://github.com/Duskhaven/Bug-Reports/assets/136414049/d131a5b2-be83-4604-a8d6-ebd6d7106423)
![WoWScrnShot_061323_203010](https://github.com/Duskhaven/Bug-Reports/assets/136414049/ab8f6554-4a15-466c-8362-ef55138b5d4d)
![WoWScrnShot_061323_203313](https://github.com/Duskhaven/Bug-Reports/assets/136414049/17f35b5e-de1f-4922-b665-0405505755b6)
![WoWScrnShot_061323_203931](https://github.com/Duskhaven/Bug-Reports/assets/136414049/1849908e-410b-4eba-a3e2-dc72af97c946)
![WoWScrnShot_061323_204109](https://github.com/Duskhaven/Bug-Reports/assets/136414049/77d1bce6-dd39-49c1-88e1-dd840820ec2e)
![WoWScrnShot_061323_204112](https://github.com/Duskhaven/Bug-Reports/assets/136414049/d06a9dc7-502f-4c70-b5e7-12fff4b9bb6c)
the explosions.

**Comment by Duskhaven** [comment]
Restart hasn't happened yet
