### ISSUE TITLE
Survival Talent "Wilf Fire Infusion"

### ISSUE THREAD

**Issue by Lamaross** [Duskhaven/Bug-Reports#20]
Charcter Name: Themia
Zone/Area: Doen't matter for the Bug
Screenshot: Have none right now

Issue:
You can't Skill the Talent, even with 3/3 in the Talent "Resourcefulness"

**Comment by Duskhaven** [comment]
Duplicate Issue. Please refer to https://github.com/Duskhaven/Bug-Reports/issues/6 for more Information
