### ISSUE TITLE
Worgen Racial Running Wild cannot be cast while moving

### ISSUE THREAD

**Issue by Dredguard** [Duskhaven/Bug-Reports#2006]
Worgen Racial Running Wild Cannot be cast while moving the Tauren Racial Plainsrunning can be cast while moving one of the two of these abilities is not working as intended. both have a 60% and a 2nd rank at 100% but only one can be cast while moving

**Comment by Duskhaven** [comment]
Intended

**Comment by Dredguard** [comment]
Then why is Plainsrunning able to be cast while moving they are the same types of abilities both are non mount more like a Shapeshift if the Horde gets a moving mount why doesn't the Alliance?
