### ISSUE TITLE
Prot Paladin 2.5 Set 4p bonus not working

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#2008]
![image](https://github.com/Duskhaven/Bug-Reports/assets/52112645/9998d3c5-c39a-45a7-95a8-89a9c16626c3)

The buff shows up on my buff bar but it's not affecting the damage reduced at all. 

1. Judgement is not giving holy power
2. I had a paladin with consecration test it on me. (consecration does fixed damage unaffected by armor). I took the same damage (78 per tick) regardless of if i had consecration up or not. The buff does show up though

**Comment by Duskhaven** [comment]
Fixed after restart, tooltip adjsuted with the next patch update
