### ISSUE TITLE
t2.5 dps warrior 4pc and barbaric onslaught

### ISSUE THREAD

**Issue by thrashbeer** [Duskhaven/Bug-Reports#2014]
hello, when using barbaric onslaught it should grant you 5 rage with each strike as shown here: 

![image](https://github.com/Duskhaven/Bug-Reports/assets/128950992/19b3a862-604a-42f2-91fa-53f1e9e4f3ed)

however currently that is not the case

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/0586b499-06df-4467-9877-2683fcc742a7)
