### ISSUE TITLE
Worgen Racial Running Wild Cannot be cast while moving the Tauren Racial Plainsrunning can Same basic ability 

### ISSUE THREAD

**Issue by Dredguard** [Duskhaven/Bug-Reports#2015]
Worgen Racial Running Wild Cannot be cast while moving the Tauren Racial Plainsrunning can be cast while moving one of the two of these abilities is not working as intended. both have a 60% and a 2nd rank at 100% but only one can be cast while moving Plainsrunning able to be cast while moving they are the same types of abilities both are non mount more like a Shapeshift if the Horde gets a moving mount why doesn't the Alliance?

**Comment by Duskhaven** [comment]
Plainsrunning cannot be cast while moving
