### ISSUE TITLE
Jet Pack bugged

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#2020]
Tinker Jet Pack still does not give immunity to all stuns, fear and 30% dmg reduction.

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/90b4ea6d-36a5-4431-a2e6-e69d3f92fb2f)
![image](https://github.com/Duskhaven/Bug-Reports/assets/123925176/1bb44992-7446-4793-8919-77c284c573b6)
