### ISSUE TITLE
Tinker Shield Generator Still Bugged

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#2038]
Tinker Shield Generator still bugged.  The shield generator now spawns 8yard away from the tinker.  It also despawns my turret and My Greatest Invention.

**Comment by Duskhaven** [comment]
Intended

**Comment by nboytcl** [comment]
Before the change, Shield Generator spawns under the tinker.  How's this change intended?  So, you're telling me to walk 8 yrds to my shield that only lasts 5 sec?
