### ISSUE TITLE
Shadowy Tome

### ISSUE THREAD

**Issue by Vyntoras** [Duskhaven/Bug-Reports#2047]
Shadowy Plague procs the buff it requires to be put on the target on the next MB, which is 10s and the new Prot Pala buff that removes the CD of Holy Shield for 5s. If the Holy Shield buff runs after 5s, so does the Shadowy Plague buff, makingit almost impossible to apply if MB is fresh on CD.

**Comment by Duskhaven** [comment]
Fixed after restart
