### ISSUE TITLE
Oath of the silver hand bugged. 

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#2049]
It works with consecration damage but not when you block or parry. Unsure if dodge is also included. 

I would suggest also, that it removes the mana cost of avenger's shield.

Lastly, although I can't test it yet because the block and parry is not working, 2% chance might be a little too low. I would rather it be 10% and have an ICD.

**Comment by moonfirespammer** [comment]
I think the way its coded its bugged. It's proccing off if i get hit. and not block parry or dodge

**Comment by Duskhaven** [comment]
Procs correctly from blocks after restart

**Comment by moonfirespammer** [comment]
> Procs correctly from blocks after restart

Hi Noxx, is it just blocks or are dodges and parries included?
