### ISSUE TITLE
Druid T2 Set Bonus gives Priest passives

### ISSUE THREAD

**Issue by PSIN-dev** [Duskhaven/Bug-Reports#205]
(3) Set: Restores 25 mana per 5 sec. Increases the Effect of Power Word: Shield by 15%. Regrowth lasts 3 additional seconds.

**Comment by Duskhaven** [comment]
Some set bonuses are used for other sets/shared

**Comment by PSIN-dev** [comment]
@Duskhaven This is a leather set, so I assume it is unintended.
