### ISSUE TITLE
New BM Hunter changes dont work correctly

### ISSUE THREAD

**Issue by tornadax** [Duskhaven/Bug-Reports#2050]
Aspect of the cobra isnt triggering improved aspect of the hawk, its not benifiting from aspect mastery, its not increasing the pets attack Power Just the Hunters, and the cobras are not using their main damaging ability (the poison spit like 95% of their damage), the pets summoned from stampeed are horrificly undertuned, doing less then 5k damage for a 3 min CD (ither reduce the cd tô like 30 seconds or increase the damage It does)

**Comment by Colette00** [comment]
That is exactly what i reported with the Snakes dont do any of the Posion skills, its useless skill now.

Stampede is totally under-tuned compared to other hunter abilitlies that have 3 min cd.
Increase damage or make it shorter cd as mentioned.

the 2.5T set effect Stampede is not working either, and it does not show up even if my Pet has Frenzy.

BM aspect is not working and its not benefting from Aspect of the Hawk Talent / Mastery.
There is NO damage increase for pet.

**Comment by Duskhaven** [comment]
Cobra is now correctly using Poison Bolt again. Damage of Stampede increased.
Cobra Aspect benefits from Talents after restart

**Comment by tornadax** [comment]
What about the part where its not increasing the pets attack Power?

**Comment by Duskhaven** [comment]
> What about the part where its not increasing the pets attack Power?

Its only ranged attack power= no effects for the pet
