### ISSUE TITLE
Level 80 Mobs in Culling of Strat

### ISSUE THREAD

**Issue by Tartersaucee** [Duskhaven/Bug-Reports#2051]
You left some level 80 mobs in the gauntlet portion of culling of strat

**Comment by Xenbiotic** [comment]
![kii8k89o](https://github.com/Duskhaven/Bug-Reports/assets/67262624/bbb5fbff-7b71-4b2b-9e31-a9f81d5b2f9b)

This is the mob in question. Also spawns in heroic mode
