### ISSUE TITLE
Legplates of Eternal Guardian Effect doesnt work

### ISSUE THREAD

**Issue by FeralHeistxd** [Duskhaven/Bug-Reports#206]
The effect which should boost your consecration damage doesnt work. Tried the shield block works fine, but cant check the icebound fortitude cause dont have any DK with the item.
![image](https://user-images.githubusercontent.com/127445042/224648906-f5f57637-dfdd-45c6-b90f-faef1db14ef0.png)

**Comment by Duskhaven** [comment]
This Item shouldn't have other effects besides the defensive increase.
Fixed after restart.
