### ISSUE TITLE
Monk t2.5 2set bugged 

### ISSUE THREAD

**Issue by retclasslead** [Duskhaven/Bug-Reports#2072]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131426379/b2b71f14-1fee-4645-98a0-4a86682c29b4)
Piercing Jabs arent proccing Flowing fists.

T2 equivalent works just fine
![image](https://github.com/Duskhaven/Bug-Reports/assets/131426379/2236abbf-c16f-4bcc-8005-0a36da22e989)

**Comment by Duskhaven** [comment]
Fixed
