### ISSUE TITLE
[Karazhan] Terestian Illhoof is massively overtuned

### ISSUE THREAD

**Issue by cawilliamson** [Duskhaven/Bug-Reports#2083]
In short:

- He summons adds too frequently
- He applies a BRUTAL curse to everyone in the group dealing around 800 damage per 3 seconds
- He has around 200k HP more than other similar bosses in the "mega dungeon"

What really makes this thing hard is... he also drops the feral druid BiS weapon so I *need* to kill the guy but it's damn near impossible even with mostly T2 and T2.5 folks in the group.

**Comment by ryanportfolio** [comment]
I agree that the HP should be lowered by at least 100k

**Comment by cawilliamson** [comment]
@Duskhaven What (if anything) was actually changed here?
