### ISSUE TITLE
Demon Hunter  FEL RUSH 

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#2086]
Demon Hunter  cant use Fel RUSH  when raid bosses are too big , like nefarian, ragnaros , onyxia  and that ruined burst window

**Comment by Duskhaven** [comment]
Duplicate issue https://github.com/Duskhaven/Bug-Reports/issues/1322

**Comment by xAzeroth** [comment]
what do you mean by that Duplicate issue would you be more specific on this problem to explain
