### ISSUE TITLE
Demon Hunter PVP 

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#2094]
Cthun glaives  are bugged or something junk happening and our dmg is totaly trash and when I have those in pvp arena my dmg went red like I got debuff on ,  need to be FIXED ASAP!

**Comment by Duskhaven** [comment]
DH's are affected by the damage reduction debuff in PvP

**Comment by xAzeroth** [comment]
so with your answer ,  DH are kinda banned from PVP !! amazing !
