### ISSUE TITLE
Reins of the Corrupted Drake from Scavenger Larry

### ISSUE THREAD

**Issue by ryanportfolio** [Duskhaven/Bug-Reports#2100]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/d78ffb03-d93b-4ce5-a25a-5f115fc894f2)

This mount is not usable, gives the error "you can't use that here" 

![image](https://github.com/Duskhaven/Bug-Reports/assets/131197913/1075677e-6201-485c-b247-47c9a6269a0d)

**Comment by Duskhaven** [comment]
Useable after patch update
