### ISSUE TITLE
Culling of Stratholme reset mid run

### ISSUE THREAD

**Issue by Wheemix** [Duskhaven/Bug-Reports#2112]
We got into CoS hc via RDF right before the daily reset timer at 04:00 server time. When it hit, all of us got the message that we would be booted out in 1 minute. After teleporting out of the dungeon and then back in, the dungeon was reset and we had to start from scratch including the 5minute RP and all...

**Comment by Duskhaven** [comment]
Normal 3.3.5 reset behaviour
