### ISSUE TITLE
Survival hunter removing Serpent Sting

### ISSUE THREAD

**Issue by Xenbiotic** [Duskhaven/Bug-Reports#2119]
![456456](https://github.com/Duskhaven/Bug-Reports/assets/67262624/347904b4-86bd-49aa-a3f0-5f6e2a2f9a53)

I'm a MM ranged hunter and I NEED to have serpent sting on the boss. But a survival hunter is doing a skill to remove MY sting off.

Akin to how 2 ferals removing each otheers bleed stacks using pruverize (Fixed long ago)

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/2096
