### ISSUE TITLE
Fetish of Chitinous Spikes broken/dysfunctional interactions with combat and thorns buff

### ISSUE THREAD

**Issue by FatherSylla** [Duskhaven/Bug-Reports#2122]
No screenshots to help this one: When the Fetish of Chitinous Spikes is applied, it seems to (1) benefit from the druid thorn minor glyph to have a 60 minute buff, and (2) is overridden by thorns and (3) falls off immediately upon entering combat (possibly an interaction with bear brambles? Not sure on this)

Would be nice to make sure that thorns cast doesn't override the trinket buff, and to ensure that the buff remains on (no purge or other such effect took place) as intended.

**Comment by Yuther2010** [comment]
https://github.com/Duskhaven/Bug-Reports/issues/2033
