### ISSUE TITLE
Experience buffs not correctly giving exp

### ISSUE THREAD

**Issue by Pairadice78** [Duskhaven/Bug-Reports#2123]
![exp1](https://github.com/Duskhaven/Bug-Reports/assets/137776693/8ff786ee-b283-45db-b267-d61d9b9ee064)
![exp2](https://github.com/Duskhaven/Bug-Reports/assets/137776693/f0f83f63-171c-4ea3-a710-98eeeb53f789)

There seems to be a problem with the exp buffs not giving correct amount of exp.
In this example i had a quest to hand in for: 14.260 exp.
What it actually gave me was: 16.320 exp.
Which is nearly 15% increase as joyous journey buff is active this week.
What it does not take into account is the Dread pirate ring i have equiped which should give 5% more exp.
And also ignores the Call to arms exp buff i have which should give another 10% exp.
So by my calculations i should receive in this example: 18.538 exp

Please explain or resolve this issue.

Kind regards,
Happy gamer

**Comment by Duskhaven** [comment]
Joyous Journeys is already added and displayed before you accept the Quest (Which comes to the value of 14.260) Without it its roughly 12000 and Quest XP numbers are rarely uneven without it

Warmode and the Heirloom correctly granted you the 15% from 14.260 to 16.320
