### ISSUE TITLE
Demon Hunter Threat

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#2125]
asking for making more Threat in chaos strike becouse poison on demon hunter not working for adding up dmg what should usualy work and deadly poison is kinda bleed and holding threat but as DH is useless and while Thundefury is now complety wasted item on Demon Hunter as Tank than asking for more general threat and also  Glaive trow need to be AOE at least 3 targets without having Season 1 items

**Comment by Duskhaven** [comment]
Belongs in the suggestion channel
