### ISSUE TITLE
Enhancer - T2,5 2er Setboni 

### ISSUE THREAD

**Issue by Putz-Oesi** [Duskhaven/Bug-Reports#2128]
Hello there,

after transformation you get an Debuff - Shrink = Reduced Strengh, Stamina and Size and sometimes the offhand weapon is "missing".

**Comment by Duskhaven** [comment]
Intended

**Comment by Putz-Oesi** [comment]
You loose ap/stamina ( + your offhand), when the boni procs and this is intended? oO
