### ISSUE TITLE
Fire Mage 2.5 2 and 4 piece bonuses

### ISSUE THREAD

**Issue by Yuther2010** [Duskhaven/Bug-Reports#2131]
The dot provided from the 2 piece after casting pyroblast is dealing around 700 less per tick and the guaranteed critical strike to pyroblast from the 4 piece only brings the crit value up to around 90% and as well, the hot streak gained from Volatile Detonation no longer provides a critical hit pyroblast.

**Comment by Duskhaven** [comment]
2 Piece adjustion is intended. Cannot replicate 4 piece.
