### ISSUE TITLE
Feral 2.5 Set berserk after consuming predator's swiftness not proccing

### ISSUE THREAD

**Issue by FatherSylla** [Duskhaven/Bug-Reports#2137]
the 4set bonus for feral isn't proccing - which should, with the glyph be activating for 7 seconds (2+5). Tested on SW training dummies, doesnt show in combat log or buffs, spell ID isn't active. 30% damage increase doesn't seem to be applying to skills either.

**Comment by Duskhaven** [comment]
Fixed after restart

**Comment by Duskhaven** [comment]
Fixed after patch update
