### ISSUE TITLE
Striker's Garb (T2.5 Hunter) 2/5 Set Bonus does not work.

### ISSUE THREAD

**Issue by Rats4314** [Duskhaven/Bug-Reports#2141]
The first set bonus, "When your pet benefits from the Frenzy affect it stomps, dealing additional damage." does not work. I have tested on heroic dummy, regular dummy, dungeons and raids and the stomp has not gone off. Have also tested on different types of pets, cunning, ferocity, tenacity.

**Comment by Duskhaven** [comment]
2 set has been redesigned to grant increased damage during Cobra Strikes
