### ISSUE TITLE
Unholy dk 2.5 set bonuses not scailing with AP again.

### ISSUE THREAD

**Issue by BettyEvil** [Duskhaven/Bug-Reports#2142]
![WoWScrnShot_062923_001746](https://github.com/Duskhaven/Bug-Reports/assets/136414049/84df60ad-8242-4ce1-bc63-9ff391684a4e)

this was on maiden

**Comment by BettyEvil** [comment]
Even the bone sorcerer is doing barely any damage

**Comment by Duskhaven** [comment]
Scaling+Damage reduced to keep them in line with other spec bonuses
