### ISSUE TITLE
Demon Hunter  Scaling AQ40 Gear

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#2146]
2 set  Chaos Elemental 
4 set  Guardian 

they dont even scale with spell power or attack power  

Demon Hunter in T2.5 gear dont scale on dmg and gear is like playing tarzan  with  double jump out and in with fel rush with  800-1200 damage on Chaos elemental  so stacking spell power not working or agility / attack power  
soo while rest classes scales big time  Demon Hunter just got a bit more dmg from raw stats  agility + str   but... 

Equip :  big lost on expertise   
Equip : big lost on critical  

T2.5 gear big hit rating but no good dmg to be focused on T2.5   also ,  if you wana have expertise you need to have S2 (mythic )  ring to stay capped by that I see that downgrade than rather Upgrade on items while we doing progress

**Comment by Duskhaven** [comment]
Belongs in the suggestion channel

**Comment by xAzeroth** [comment]
you ok ? thats not bug ? the pets /guardian not scaling at all
