### ISSUE TITLE
Priest 2.5 (DPS) 4 set

### ISSUE THREAD

**Issue by retclasslead** [Duskhaven/Bug-Reports#2148]
![image](https://github.com/Duskhaven/Bug-Reports/assets/131426379/32031aeb-16e2-4db8-a26c-efc806868052)

Thrash kick / Piercing Jab dont hit twice and they dont heal you at all in either stance.
You dont gain 5% additional health in tank stance

**Comment by Duskhaven** [comment]
Fixed
