### ISSUE TITLE
Food Buffs

### ISSUE THREAD

**Issue by xAzeroth** [Duskhaven/Bug-Reports#2149]
![image](https://github.com/Duskhaven/Bug-Reports/assets/132115122/71304dcf-cc37-405b-b83c-44973d20855f)
![image](https://github.com/Duskhaven/Bug-Reports/assets/132115122/1c89e22b-dc8b-42a4-a21d-1fcf0c630fa0)

cant be stacked like before   

WHY ?

**Comment by Duskhaven** [comment]
Intended. Food buffs cannot be stacked.

**Comment by xAzeroth** [comment]
than make Dirge's Kickin duration of at least  1h

Reason : you need to farm 1 dungeon + alchemi+ cooking recipe  and all that for 15 min food buff ? looks to me its wasted time 
if its soo called  "EPIC COOKING RECIPE "
