### ISSUE TITLE
SFK M+ Spawns level 70 friendly bears

### ISSUE THREAD

**Issue by PSIN-dev** [Duskhaven/Bug-Reports#215]
Not sure how this happens but they spawn, spam taunt, are immobile, are friendly and only seem to spawn in proximity of the entrance (and in later parts of the map that are above the instance). They also apply a debuff to players that increases their damage taken by 10%.  I believe they have Zandalari in the name or something troll related, hope that helps.

**Comment by Duskhaven** [comment]
Fixed.
