### ISSUE TITLE
Protection Paladin Cannot Generate Holy Power

### ISSUE THREAD

**Issue by BS3-Dev** [Duskhaven/Bug-Reports#2150]
Hello since the latest patch (6/30), I am not able to generate Holy Power with Hammer of the Righteous, Holy Shield, nor Judgement.

Attached are two builds (both don't generate Holy Power):

- Down to Holy Shield in order to test Holy Shield and Judgement only
- Full Build - all abilities tested

Any help you can provide would be great!
Pajamalight

![ProtBuildToHolyShieldOnly-1](https://github.com/Duskhaven/Bug-Reports/assets/111845842/c8474838-5e58-4c1e-9d7f-04b0b2ffba2d)
![ProtBuildToHolyShieldOnly-2](https://github.com/Duskhaven/Bug-Reports/assets/111845842/7447af25-31b4-4261-955a-33cb8508825b)
![FullProtBuild-2](https://github.com/Duskhaven/Bug-Reports/assets/111845842/9fba597a-fee7-4ac4-952b-f928b72327b9)
![FullProtBuild-3](https://github.com/Duskhaven/Bug-Reports/assets/111845842/0e88869b-c032-44d3-ae4a-369b55e13c9b)
![FullProtBuild-1](https://github.com/Duskhaven/Bug-Reports/assets/111845842/12202dc5-32d0-4510-988b-bd937fca0158)

**Comment by Ramith-Zaeltir** [comment]
https://gyazo.com/50cc8242e70578e70d5d6a3361e1ffe9

https://gyazo.com/522516bfa76c100874f104a4f03b4509

https://gyazo.com/9f631167ba4cd7cb798f12513f1b9f94

same issue, unable to generate holy power.

tried swapping to primary/secondary a few times. restarted game, made sure i got latest patch etc still nada
