### ISSUE TITLE
Elemental Bulwark available to be learnt by Warriors.

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#217]
The (what should be an) Enhancement Shaman Spell Elemental Bulwark is available at Warrior Trainers under Protection. (Shamans can still learn it from Shaman Trainers.) It does not appear in their spell book, but it takes their money for it.

**Comment by harukaze3** [comment]
Further expanding on this: Elemental Bulwark is needed to learn Shield Slam (Rank 2) and subsequent Ranks.

**Comment by Duskhaven** [comment]
Fixed after restart
