### ISSUE TITLE
2.5T for elemental shaman partially doesn't work

### ISSUE THREAD

**Issue by qbawu** [Duskhaven/Bug-Reports#2171]
2/5 set bonus on tier 2.5 for elemental shaman should have 2 effects:
1) increase fire dmg by 10% while flametongue is active
2) cause lava burst to infuse next lighting bolt

Effect 1) **does not** work at all.
Effect 2) does work.

**Comment by Duskhaven** [comment]
Check your fire spell power after using flametongue weapon

**Comment by qbawu** [comment]
1) bonus wording suggest 10% increase of Fire Damage (not fire spell power), as in flat 10% increase of all fire dmg done
2) fire spell power after using flametongue weapon enchant is increased by flat +70, no matter my current spell power - additionally, it stays increased even after switching weapon buff or unequipping the 2.5T items.
