### ISSUE TITLE
Ret Paladin Conviction

### ISSUE THREAD

**Issue by TheAj40k** [Duskhaven/Bug-Reports#2180]
Paladin Retribution Talent Tree Conviction talent is also reducing the Paladin's damage by 5% once 5th point is put into Conviction.
https://www.youtube.com/watch?v=HthDFOvS-ys

**Comment by Duskhaven** [comment]
Intended,  check the changelog for aura debuffs

**Comment by TheAj40k** [comment]
> Intended, check the changelog for aura debuffs

So I'm guessing this is referring to the changelog post on 06.05.2023?
"Retribution Paladin
All damage dealt reduced by 5% at Level 60"
and is just coded to Conviction? No chance of getting tooltip updated to save confusion?
