### ISSUE TITLE
Ret Paladin Zeal

### ISSUE THREAD

**Issue by TheAj40k** [Duskhaven/Bug-Reports#2181]
Paladin Retribution Talent tree talent Zeal does not work as tool tip states. Tool tip says it should not work with two, one handed weapons. Currently it does not work with one, one handed weapon, nor a one handed weapon and shield, nor unarmed and shield, nor unarmed, only working with a single two handed weapon.
https://www.youtube.com/watch?v=fVazhbgbZP4
https://www.youtube.com/watch?v=t-bDQ2OfG8A

**Comment by Duskhaven** [comment]
Intended

**Comment by TheAj40k** [comment]
> Intended

Any chance of getting the tooltip updated then?
