### ISSUE TITLE
Balance druid Fury of Elune

### ISSUE THREAD

**Issue by LetThemCook69** [Duskhaven/Bug-Reports#220]
The custom Fury of Elune talent for balance druids is causing unintented pulls on packs of mobs due to the large range of the stellar flare that comes down from the talent, (seems to be pulling based on stallfall radius? have not been able to test) 
is this a bug or intended? 
Thank You

**Comment by Duskhaven** [comment]
This is intended.

**Comment by LetThemCook69** [comment]
Does glyph of focus help prevent this in some way or its just intended to be bad?
