### ISSUE TITLE
Oath of the Silver Hand

### ISSUE THREAD

**Issue by DaFiL33** [Duskhaven/Bug-Reports#226]
Oath of the Silver hand does not currently work, therefore does not scale dynamically 
![image_2023-03-13_110151130](https://user-images.githubusercontent.com/127772380/224758196-3d957a0f-0ae3-4894-9a98-1fc783cc02d2.png)
![image_2023-03-13_110236853](https://user-images.githubusercontent.com/127772380/224758422-2f791b95-181f-4583-a8e6-c0322388c7ec.png)

**Comment by Duskhaven** [comment]
Fiexd.
