### ISSUE TITLE
Enhancement Shaman m+ 4 set

### ISSUE THREAD

**Issue by MrSwedishh** [Duskhaven/Bug-Reports#227]
The 4 set from shaman m+ set ( Enhancement, Dreamwing ) does not stack with the talent Storm Infuser. The CD of Stormstrike should go down to 5.5 sec, but it stays at 6.5. CD is normaly 8 sec, Storm infuser brings it down to 6.5, then 4 set should bring it down another sec to 5.5 or 5 sec. 
Without talent / set bonus: https://gyazo.com/11c01938a59b84e242bce49de9c62095
With Storm Infuser: https://gyazo.com/a5b377fe3f4727689f58013bcf22a063
With 4set Bonus: https://gyazo.com/d44b9c79c47d9abe3220a456f705fead
With both 4set and storm infuser: https://gyazo.com/974607cd567799e0d49f3723122b2e96

If This is intended its kinda stupid to put reduced CD on the 4 set.

**Comment by Duskhaven** [comment]
It does not stack with the Storm Infuser passive.

**Comment by MrSwedishh** [comment]
Kinda useless set bonus then

**Comment by MrSwedishh** [comment]
If its for Enhancem, it should work for both 2h and dw

**Comment by MrSwedishh** [comment]
Should tell us on either the set or the talent that it dosnt stack with similar effects
