### ISSUE TITLE
Death knight Unholy BuG

### ISSUE THREAD

**Issue by Saddymosh** [Duskhaven/Bug-Reports#228]
Tallent "Commander of the Death" is broken. No Sudden Doom.And there is no Unholy pact also. So no ghouls...
Also seems like that multi coil while Death and Decay broken too. U can get buff but your coils are still solo target.

**Comment by Saddymosh** [comment]
Also Dancing Runic Weapon broken...

**Comment by Duskhaven** [comment]
Fixed after restart. Commander of the Death has been reworked.
