### ISSUE TITLE
Orgrimar ground blimp 

### ISSUE THREAD

**Issue by KamiNoEnd** [Duskhaven/Bug-Reports#23]
![image](https://user-images.githubusercontent.com/49670986/223283560-8311dadb-be7a-4e3b-b13f-4d1d829e4886.png)
Sometime a blimp spawn in the ground of orgrimar

Future "Tram" system?

**Comment by Duskhaven** [comment]
This Zeppelin was supposed to take you to Kargath from Orgrimmar. However custom Transports do not work correctly and will hopefully be fixed in the future. It is a rather badly documented process and not many know how to implement it properly.
