### ISSUE TITLE
Battle Shout + Commanding Presence tooltip

### ISSUE THREAD

**Issue by Wifejuggler** [Duskhaven/Bug-Reports#230]
When you talent into Commanding Presence the spell tooltip does update properly, but the buff tooltip itself (when applied to a player) displays the value as if you didn't have Commanding Presence. This is only a visual bug however. The player does gain the correct AP value.
At max level its 232 AP without the talent and 290 with the talent. When you hover your mouse over a buffed player it says 232 even though the character's Attack Power goes up by 290.

A minor issue but I thought it wouldn't hurt to mention.

**Comment by Duskhaven** [comment]
This is the case for similiar talents on the 3.3.5 client
