### ISSUE TITLE
invisible wall in hyjal and no currency at the quartermaster

### ISSUE THREAD

**Issue by lilpanodil** [Duskhaven/Bug-Reports#233]
There's an invisible wall at hyjal entrance so I cant leave and there's also no currency at the quartermaster.

I started and finished the questline before I updated the patches but those two problems persisted after I updated the patches.

**Comment by Duskhaven** [comment]
The currency will be visible with the next Patch Update. 
You can only leave Hyjal with your hearthstone at the moment.
