### ISSUE TITLE
Unable to turn in Onyxia's Head.

### ISSUE THREAD

**Issue by Sokks-Sturges** [Duskhaven/Bug-Reports#234]
Unable to turn in Onyxia's Head for Hit Neck. Provided both interaction with Quest Giver Varian to give Quest (7495) Victory for the Alliance and with Raid ID that encounter took place in.

![Onyxia Turn In One](https://user-images.githubusercontent.com/127478138/224809154-d68ac623-7527-47c5-bb61-010d45614600.png)
![Onyxia Turn In Two](https://user-images.githubusercontent.com/127478138/224809464-9fd8d11c-1f8e-4b4f-8dba-053f61c9bad2.png)

**Comment by Duskhaven** [comment]
This is now fixed. Speak with Bolvar in the Throne Room in Stormwind or near Thrall in Orgrimmar.
