### ISSUE TITLE
[Tinker] Scrap Bullet consumes 2ammo per use.

### ISSUE THREAD

**Issue by dmjohn0x** [Duskhaven/Bug-Reports#248]
Scrap Bullet is consuming 2 ammo per use.  I originally thought it was auto-shotting too, but I wasnt seeing the damage numbers. So I installed Details! and confirmed that autoshot wasnt being engaged or used. Only Scrap Bullet. Then To test if Auto Shot was registering, I fought more mobs opening the fights with auto shot. They registered fine.

So something in the coding of Scrap Bullet is causing it to consume two bullets per use. This is not reflected in the tooltip so im assuming this is a bug.

**Comment by Duskhaven** [comment]
Fixed
