### ISSUE TITLE
Deathstalker Lesh misplaced inside of wall

### ISSUE THREAD

**Issue by leiske** [Duskhaven/Bug-Reports#254]
![image](https://user-images.githubusercontent.com/4615743/224883897-3e0c5443-5a1d-418e-8a9d-802118f2e9f1.png)

I am here
![image](https://user-images.githubusercontent.com/4615743/224883932-a92a0a9c-e46a-4471-b144-69308c344fa3.png)

expected;
should be on top of the wall

**Comment by Duskhaven** [comment]
Fixed.
