### ISSUE TITLE
Dar'Khan's Lieutenants

### ISSUE THREAD

**Issue by Ehnyr** [Duskhaven/Bug-Reports#255]
Dar'Khan's Lieutenants https://www.wowhead.com/wotlk/quest=9170/darkhans-lieutenants 

The npc requiered to complete the mission  Borgoth the Bloodletter was not in any of the respawn points indicated on the map. There was no npc in the 30 minute time span that i checked in both positions. 

https://www.wowhead.com/wotlk/npc=16247/borgoth-the-bloodletter

**Comment by Duskhaven** [comment]
Fixed.
