### ISSUE TITLE
Master Enhancer Shaman Talent Bugged

### ISSUE THREAD

**Issue by wonderduck234** [Duskhaven/Bug-Reports#256]
Frost Brand/Windfury/Flametongue weapon not giving the increases it says they do.  No block rating increase, no 3% haste increase, no 5% block value increase.  Worked as of 3/12/2023, currently not showing increases on stat page.  Also able to pick Master Enhancer with less than 3 points in Elemental Weapons, not sure if this was meant to be working as intended?

**Comment by Duskhaven** [comment]
Works with no issues here. 
Some custom talents are intended to only require 2 points instead of 3 to pick.

**Comment by wonderduck234** [comment]
Very odd since it's not showing up on the stat pages.
