### ISSUE TITLE
Razormaw

### ISSUE THREAD

**Issue by Dustycloudy** [Duskhaven/Bug-Reports#258]
The quest Razormaw on Bloodmyst Isle, fails to make Razormaw land near the bonfire where you have to burn the dragon bones. The dragon instead flies far into the sky north of island and is impossible to pull.
![image](https://user-images.githubusercontent.com/127817864/224892145-305e316e-8eee-4b17-9768-4b87b3eb7dfb.png)

**Comment by Duskhaven** [comment]
Upon walking towards his location he will come to your postion.

**Comment by Sinnica** [comment]
Didnt work for me ... he was still flying gave up moved on .
