### ISSUE TITLE
[Shaman Spell Bug]  Stone Infusion

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#26]
Character Name: Aerqewyxc
Screenshot/Video: https://imgur.com/a/gFpu47U
Issue: Shaman spell Stone Infusion, doesn't give attack speed like tooltip says. Does increase armor.

**Comment by Duskhaven** [comment]
Cannot confirm. Works for other people.

**Comment by MadFlyingPanda** [comment]
Yeah, there is a window that pops up and it says that: ''performing this action will make this item non-tradeable''. Every. Single. Time. You. Cast.... it is really annoying. Anyway hope you fix it! Thx for the awesome work
