### ISSUE TITLE
My Greatest Invention (81169) - Doesn't give the 30% haste for the units duration.

### ISSUE THREAD

**Issue by WooshieBurr** [Duskhaven/Bug-Reports#261]
Instead, it applies 13533, for 10 seconds. While the unit itself lasts for 25 seconds. 
![image](https://user-images.githubusercontent.com/55280951/224893077-466ff9e6-48bc-43aa-8264-462d61ec48bc.png)
![image](https://user-images.githubusercontent.com/55280951/224893013-5209f73d-36de-45f2-854e-36e1b2008c3b.png)

**Comment by Duskhaven** [comment]
Fixed after restart.
