### ISSUE TITLE
Road Roller (81161) - Doesn't function trigger it's explosion/stun most of the time.

### ISSUE THREAD

**Issue by WooshieBurr** [Duskhaven/Bug-Reports#262]
Steps to reproduce: 
1) Cast Road Roller (81161).
2) Wait for the unit to charge at your target.

Expectation: The unit to charge at the target, collide with it, and suicide bomb into an AoE stun.
Reality: It awkwardly sits next to me, doing nothing, or charges the target but doesn't do anything.

Even using /petattack doesn't change the behaviour.

https://user-images.githubusercontent.com/55280951/224894041-c5e22431-c843-43e5-b2b6-bf52f911bb0f.mp4

**Comment by Duskhaven** [comment]
Road Roller doesnt work against Dummies.
