### ISSUE TITLE
Leather set-bonuses not working on Hunter

### ISSUE THREAD

**Issue by Karsenity** [Duskhaven/Bug-Reports#264]
Tried the 2-set for both Shadowcraft and Wildheart, didn't receive the bonuses from either. Mail-sets such as Beaststalker's is working

**Comment by Duskhaven** [comment]
Shadowcraft only has its original Set bonuses, this is a visual bug.

![image](https://user-images.githubusercontent.com/123925176/224895333-ca35b756-1031-4a9b-bb0e-44d33a3921c9.png)
Wildheart works on our side.
