### ISSUE TITLE
Set Bonus on Bluefang set Rogue, Druid does not work.

### ISSUE THREAD

**Issue by bowzef** [Duskhaven/Bug-Reports#267]
Playing a Demonhunter, currently the set-bonus for Demonhunter, the glaive throw doesn't hit 4 targets or apply any wounding/bleeding effect.
The +20 to hit Bonus does work though.
I don't know if the Lacerate and swipe , the Mangle and shred or tricks of the trade works, i have not personally tested it.
This is just what i know from a Demonhunter. also don't know if 4 set bonus works yet, i suppose you will need to test it all out.

**Comment by BAMFZone** [comment]
Im having the same issue as a DH. It doesnt bounce between 3 targets and doesnt apply a bleed for the 2 tier set piece bonus

**Comment by Duskhaven** [comment]
fixed
