### ISSUE TITLE
wont let me log in

### ISSUE THREAD

**Issue by deadimpulse57** [Duskhaven/Bug-Reports#272]
its currently 6:24am eastern and im trying to login and it says unable to connect
![Screenshot_20230314_062544](https://user-images.githubusercontent.com/127844853/224971833-dda52d06-45f0-4bcd-ace8-75d6c24c1f35.png)

**Comment by bowzef** [comment]
Don't check discord do you? server auth is down been posted /closed

**Comment by harukaze3** [comment]
This is not a bug. The login server is currently down, please, next time, wait for it to get fixed.

> GM Haruka
