### ISSUE TITLE
Oakheart quest unshareable, summoning stone by boss.

### ISSUE THREAD

**Issue by LVCJS** [Duskhaven/Bug-Reports#278]
The Oakheart quest is unshareable, therefore people summoned without the quest at the new stone by the boss have to run all the way down to get the quest and then run back up, effectively reducing the effectiveness of the summoning stone.

Boss shouldn't be 50000 yards from the quest givers, stone should either be down there with the NPC or another NPC added up there to remove wasted time when doing the world boss.

Thank you

**Comment by Duskhaven** [comment]
The Quest is now shareable
