### ISSUE TITLE
Shaman talent Master Enhancer not working

### ISSUE THREAD

**Issue by Shoro2** [Duskhaven/Bug-Reports#281]
Using frostbrand weapon does not increase my block

**Comment by Duskhaven** [comment]
Without Frostbrand 
![image](https://user-images.githubusercontent.com/123925176/225085345-729995f6-7a63-43c6-8012-ca3e45b01084.png)

With Frostbrand
![image](https://user-images.githubusercontent.com/123925176/225085476-f85d87e0-c273-44ef-b6f2-c72e41cc05df.png)


Works fine on our side.
