### ISSUE TITLE
Scholomance Bug's! Plz read

### ISSUE THREAD

**Issue by Zometthecomet** [Duskhaven/Bug-Reports#283]
Scholomance Last 6 Bosses not dropping the right loot! or any at all! And they were pulling from other rooms from above and below. Loot feel's like it's just missing from the table.

**Comment by LVCJS** [comment]
Loot is like that in post Vanilla version of the dungeon. Not sure if they want to customize it for this server, but it's the same as in accordance to 3.3.5 client.
