### ISSUE TITLE
Empyrean Demolisher

### ISSUE THREAD

**Issue by Lightsduty** [Duskhaven/Bug-Reports#285]
Empyrean Demolisher is not working/proccing. 
Tested on both target dummy and player. 0 procs in over 100k dmg done. Main hand and offhand tested.
Side note - have crusader enchant which worked fine.

**Comment by Lightsduty** [comment]
Ps. I just wasted my token on a broken weapon. And I think Alot of other players will too

**Comment by Duskhaven** [comment]
It does work, please refer to https://github.com/Duskhaven/Bug-Reports/issues/182
