### ISSUE TITLE
Sunken Temple Bugs

### ISSUE THREAD

**Issue by Dooby01** [Duskhaven/Bug-Reports#286]
Things like the fear effect on some bosses have unlimited range, so as you're respawning you get feared and just auto die repeatedly

Eranikus sleep can't be dispelled and thats bad

**Comment by LVCJS** [comment]
Eranikus sleep is a banish, which is mass dispellable, but yeah agreed.

**Comment by Duskhaven** [comment]
His deep slumber will be able to be dispelled with any dispell method. The range of the fears has been lowered.

**Comment by LVCJS** [comment]
This is still bugged. Undispellable in +8
