### ISSUE TITLE
Duskwood secret chest is not working

### ISSUE THREAD

**Issue by lorentzosa** [Duskhaven/Bug-Reports#287]
I have come accross the secret chest in Darkwood and it doesn't seem to be working
When you interact with it it shows the following dialogue in the attached picture.
It was also confirmed by an other player
![dialogue](https://user-images.githubusercontent.com/127891089/225112053-a6525125-340f-49c8-ac24-57043e68fc4b.png)

**Comment by Duskhaven** [comment]
Your Character has already completed that Quest so you may have found another location with the Chest.
