### ISSUE TITLE
(Tinker) Crafted Arclight Spanner does not register as weapon for Electrified Beaton

### ISSUE THREAD

**Issue by mastabagel** [Duskhaven/Bug-Reports#29]
Not the end of the world, but now I can't use my awesome weapon I engineered myself - which was also an upgrade.
![tinkerissues](https://user-images.githubusercontent.com/127183804/223349161-21f65f5a-0163-4ab4-825d-63ca2488d3cb.jpg)

**Comment by mastabagel** [comment]
![tinkerissues2](https://user-images.githubusercontent.com/127183804/223349434-64cf6afd-cec9-4d9c-9bad-56d8a0775784.jpg)

**Comment by Duskhaven** [comment]
Arclight Spanner does not have a Weapon Type which means it does not work with some melee abilities.
