### ISSUE TITLE
Empyrean Demolisher not proccing

### ISSUE THREAD

**Issue by Uhlrik** [Duskhaven/Bug-Reports#292]
I have killed countless mobs with this item since acquiring it and it has not procced once. I have checked my char stats page in case the buff is just invisible and my attack speed does not change. I was told in global that it just doesnt work on target dummies but i can assure you it is not working at all. Spent the mats to put crusader on this thing too, kinda a big F

**Comment by Necroticgorebeast** [comment]
I am also having this issue

**Comment by Flex13** [comment]
Big Win if they fix this. DW Pally with Ironfoe in Offhand 8-)

**Comment by Duskhaven** [comment]
Please refer to https://github.com/Duskhaven/Bug-Reports/issues/321
