### ISSUE TITLE
Removing debuffs from Ironman challenge

### ISSUE THREAD

**Issue by Feiros** [Duskhaven/Bug-Reports#293]
I have discovered a way to remove the debuff from ironman for damage healing and exp. When using the paladin skill Hand of Protection it removes the debuffs until you log off. They will return upon logging back in. The effects are effectively turned off and damage and healing numbers rise to their proper amounts, though the debuff for death still remains. Can not confirm if this is still functioning though.

**Comment by Duskhaven** [comment]
This is now fixed.
