### ISSUE TITLE
Disappearing weapon skills

### ISSUE THREAD

**Issue by spookyFrogirl** [Duskhaven/Bug-Reports#294]
Title says it all, but weapon skills will randomly disappear. I don't know what triggered it, but relogging on my BE warrior caused me to lose my sword skill and then miss every attack as a result. Negatively impacts lots of areas of play

**Comment by Duskhaven** [comment]
This is fixed with the next restart. Make sure to visit the Innkeeper in Stormwind or Orgrimmar

**Comment by spookyFrogirl** [comment]
Alright, was going to add you also can't re-purchase it, but I'll just play another toon for now
