### ISSUE TITLE
Character models flickering inside caves.

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#3]
Quest Name: Test Quest
Character Name: Magni
Zone/Area: Most of the caves and some buildings
Screenshot/Video: https://imgur.com/a/VhrWMIp
Issue: When you go inside of caves and some buildings, character models start to flicker and dissapear.

**Comment by Duskhaven** [comment]
We are aware of this Issue. Please report any more Caves/Buildings which have this Issue.
Locations that have been fixed by now: Blackrock Mountains, the Cave in Northshire and the building in Westfall.

**Comment by Chromie-the-gnome** [comment]
Cave that transitions from Coldridge Valley into Main zone of Dun Morogh and the one on south of Coldridge Valley too

**Comment by Chromie-the-gnome** [comment]
Will keep updating if I find more

**Comment by GRIMLEGION** [comment]
These have been fixed and will be included in the next update.

**Comment by QtipsQtips** [comment]
The following locations also flicker: Deep Elem Mine in the Worgen starting area, Caves along The Cauldron in the Searing Gorge.

**Comment by Vallithia** [comment]
The cave in northshire abby where you have to kill the kobalds.

**Comment by ShanaGartrex** [comment]
Building near the center of Westfall, where you pick up the Westfall Stew quest, which is shown in this clip from my stream: 
https://clips.twitch.tv/IgnorantInventiveDuckAMPTropPunch-peUZtoNHteZPW8_q

**Comment by Zathmar** [comment]
The cave complex in Searing gorge in the Cauldron area i believe its called the slag pits

**Comment by Shoro2** [comment]
coldridge pass (dwarfen starter area) has it too

**Comment by GRIMLEGION** [comment]
All fixed, awaiting next patch updates

**Comment by Duskhaven** [comment]
Marking as closed now, will reopen once more flickering issues are found
