### ISSUE TITLE
[Shaman Talent]  Improved Windfury Totem

### ISSUE THREAD

**Issue by svnthsn** [Duskhaven/Bug-Reports#30]
tooltip is increased to include the increase, however when the totem is placed it reverts to its base value.  
ex: i have one point in it and the tooltip windfury totem says 18% but when placed it goes to 16% and then only applies the latter.

**Comment by svnthsn** [comment]
Seems it is also same case for strength of earth and respective talent to enhance it

**Comment by Duskhaven** [comment]
This is a common Issue and does not show visually, but should have the correct Value once you check it in your Character Stats.
