### ISSUE TITLE
Crashing when loggin on char

### ISSUE THREAD

**Issue by Bixen23** [Duskhaven/Bug-Reports#31]
Hello.

I've just downloaded the Duskhaven server, and I have done exactly what the "How to connect" and the video showed, but when i log in on my newly created char and its loading, suddenly it crashing, its says something with a builing in SW in the crashreport.

I have also tryed to reinstall the file with the game in it.

So i hope someone might have an idea of what it causes to crash.

Cencerly.
Dennis

**Comment by Duskhaven** [comment]
Patch 5 has to be in your Data folder. Without it you will encounter crashes for custom/reworked Zones.
