### ISSUE TITLE
Warmode buff disappeares

### ISSUE THREAD

**Issue by Yurimir** [Duskhaven/Bug-Reports#313]
The Warmode buff disappears, seemingly at random - death, combat, change of zone, etc. 
The quest would remain active in the logbook, but the buff is gone.

**Comment by Yurimir** [comment]
![image](https://user-images.githubusercontent.com/35487260/225316972-aef011e9-96c6-437e-a69c-090bbf9d7346.png)
Here's what I mean.

**Comment by Duskhaven** [comment]
Warmode automatically dissapears if you do Dungeons via the Tool.

**Comment by Yurimir** [comment]
Shouldn't it then reappear once you leave the dungeon?

**Comment by Yurimir** [comment]
@Duskhaven Is it intended for the buff not to reappear after the dungeon is ready?
