### ISSUE TITLE
Mythic + balance

### ISSUE THREAD

**Issue by Jpar1** [Duskhaven/Bug-Reports#317]
Could some development time be spent on balancing mythic plus? Currently mythic +8's require you be play a specific class or have 2 healers to be completed.

Example:
Last boss in GY +8
Unholy Aura ticks for 700-1000 every 3 secs
Shadowbolt volley hits for 700 every 5 secs.
Instant frost forces you to move every 3 secs.

As more info is gathered I'll add to this report.

**Comment by ghost** [comment]
Thalnos also does an insta cast fire nova which I believe does a decent amount of damage too.

**Comment by Duskhaven** [comment]
Most M+ Dungeons are now in a good state
