### ISSUE TITLE
Lord Falconcrest falls through the mountain and becomes unlootable

### ISSUE THREAD

**Issue by ActualKeeghan** [Duskhaven/Bug-Reports#32]
Character name Keeghan
aprox 7pm realm time
Area: Arathi Highlands
Quest: Wanted! Otto and Falconcrest
Lord Falconcrest falls through the floor upon aggro, and while still killlable, once dead his body is covered by the ground, and cannot be seen or looted, thus making the quest uncompletable.

https://drive.google.com/file/d/1Z5z8ONYshCl89XwtOdDzrpe1OQAVeGa9/view?usp=share_link

**Comment by Duskhaven** [comment]
Fixed.
