### ISSUE TITLE
Human hunter can use one handed axes but will actually miss every single hit

### ISSUE THREAD

**Issue by Emeris-Hub** [Duskhaven/Bug-Reports#320]
I have made a ticket last night about this issue and apparently 15.03.2023 changelog should have fixed this. I did what was mentioned to fix it (talk to the innkeeper in Stormwind) and the problem is still present.

I have no idea if it's related to my character or to any human hunter.

**Comment by Duskhaven** [comment]
You have to get the skill book from the innkeeper.
