### ISSUE TITLE
Further proof of Empyrean Demolisher not working.

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#321]
I have done some exhaustive testing and I can confidently conclude that this weapon is NOT working at least on the openly available client since multiple people seem to agree with this.

I have done multiple of these tests on open world mobs to confirm what's said in thread #182 that the weapon does not proc from dummies and it has NOT procced once in about 30-40 minutes of combat.

To back this up I've used multiple addons and tools that would allow me to effectively track everything that's happening in combat with a similar tool that WarcraftLogs uses.

This is one example of it:
[Transcriptor.txt](https://github.com/Duskhaven/Bug-Reports/files/10980768/Transcriptor.txt)

You can see there that I was doing a similar rotation to what a real encounter would be to try and fish for procs as fast as possible but to no avail.

Further data here:

> Screenshot of Details!' aura tracker from the same sample from Transcriptor.txt file above.
![Details!](https://user-images.githubusercontent.com/122328217/225335176-8a26519b-d8f3-4359-9ecb-4a19feec4a0c.png)

> Weapon is equipped in the mainhand slot. (Ideally I would've liked to either use 2 of these or just 1 to isolate the weapon even further but I decided to use dualwield with something else to fish for flurry procs and swing faster for more chances in a smaller sample)
![Character Sheet](https://user-images.githubusercontent.com/122328217/225335648-41077eca-8f03-488d-9eb3-fa391ae7a349.png)

**NOTE: I was going to add this to the bug report mentioned above but decided to open a new one because the original one is closed and will likely be ignored.**

**Comment by Flex13** [comment]
thank you for your service :D My Bug-Report was like: Yea shiet doesn´t work. Where DPS?

**Comment by Yakisieras** [comment]
broski said fuck your data it works on my end. Okay then I guess we're not getting ED smh

**Comment by ghost** [comment]
> thank you for your service :D My Bug-Report was like: Yea shiet doesn´t work. Where DPS?

Lol yeah I try to be as exhaustive as I can for reporting so that they have to do minimal research for it and just straight up troubleshoot the problem. 
Hope it gets fixed soon tbh SMF is bad enough as it is

**Comment by Duskhaven** [comment]
A hotfix was just deployed and it should work again, please provide your results.
