### ISSUE TITLE
Weapon Proc doens´t work. Empyrean Demolisher

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#323]
Weapon proc doesnt work. Hitting target dummy for like 30 mins without proccing
![image](https://user-images.githubusercontent.com/127632931/225345833-c59ac0bd-7028-4a7e-b6e0-1913a05720f5.png)

**Comment by Duskhaven** [comment]
Duplicate Issue, refer to https://github.com/Duskhaven/Bug-Reports/issues/321
