### ISSUE TITLE
No spell from KSM after update

### ISSUE THREAD

**Issue by KamiNoEnd** [Duskhaven/Bug-Reports#327]
You guys said to do a ticket, here it is <3

![image](https://user-images.githubusercontent.com/49670986/225361705-3e08095a-1b28-4cb2-b0b1-1e7152339265.png)
![image](https://user-images.githubusercontent.com/49670986/225361783-7cdf6401-4421-4e67-8519-0d3c1f456f03.png)
![image](https://user-images.githubusercontent.com/49670986/225361917-b240c33b-897d-41d9-adaf-5ee29c874991.png)

**Comment by harukaze3** [comment]
This is a bugreport, not a ticket. The post meant open an in-game ticket.

> GM Haruka
