### ISSUE TITLE
Prayer of healing(rank 3)

### ISSUE THREAD

**Issue by sarkonthedad** [Duskhaven/Bug-Reports#329]
For priest's the prayer of healing(rank 3) spell heals for about 1/2 prayer of healing(rank 2), Screenshots provided.
![WoWScrnShot_031523_131541](https://user-images.githubusercontent.com/127152922/225405022-37ccd7bd-5ac9-441a-b632-3480d66a0d2a.jpg)
![WoWScrnShot_031523_131544](https://user-images.githubusercontent.com/127152922/225405028-91bea0a0-9681-46c1-a9f0-6e606efbf113.jpg)

**Comment by Duskhaven** [comment]
Fixed.
