### ISSUE TITLE
Demon Hunter "stances" disappearing

### ISSUE THREAD

**Issue by belongia** [Duskhaven/Bug-Reports#344]
I recently hit 55 on my Blood Elf Rogue named Nyeh.  I was doing the Demon Hunter questline, and noticed that every time I used my chaos strike ability 3 times, it would completely remove my Demon Hunter "stance."  I tried both the tanking and the dps stances and the both have the same issue where they are removed after 3 chaos strikes.  I am utterly unable to maintain my stances with this bug and I don't know how to solve it.  As you can imagine, this completely negates my ability to play the class effectively.

**Comment by Duskhaven** [comment]
Are you talented deep in the assassination tree? Demon Hunters only use the combat or sub tree
