### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by Stevo210154** [Duskhaven/Bug-Reports#345]
Just left Starter zone undead priest.
Game crashes as soon as try to move  is ok if stand still. other zones on other starter toons seem fine.
Unable to log in on priest at all now gets critical error

thanks

**Comment by Duskhaven** [comment]
Make sure to check your patch files

**Comment by Stevo210154** [comment]
Fixed it, patch 5 incorrectly labelled.
Thank you 
Cheers
