### ISSUE TITLE
Hunter pet issues regarding sizing and follow speed

### ISSUE THREAD

**Issue by adamjacobsjr** [Duskhaven/Bug-Reports#346]
When taming a pet not all of them should reduce in size. The cats for example instead of looking like a tiger or lion they look the size of a kitten in comparison to the character model. 
They also do not follow quickly enough. They should stay fairly close to the hunter.

**Comment by Duskhaven** [comment]
Once your pet has reached a certain Level (usually once they get Avoidance their speed is increased massively)

The size reduction is intended.
