### ISSUE TITLE
The Hinterlands Jintha' Alor Cave

### ISSUE THREAD

**Issue by Archaidas** [Duskhaven/Bug-Reports#347]
I was question through the Jintha' Alor cave and all the entities (Mobs, nodes, my character, etc. were flashing in and out of existence rapidly. It'd didn't stop me from completing the objectives, but it could be problematic for people with epilepsy.

**Comment by Duskhaven** [comment]
Please refer to https://github.com/Duskhaven/Bug-Reports/issues/3
