### ISSUE TITLE
8-Piece Hunter Set Molten Core

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#349]
The 2-Piece effect for Tinkers on the Hunter Molten Core Set is not working.
"Electrified Baton strikes a second time and adds 15% fire damage"

Since Tinker work with Nature and Lightning could this please be changed to Nature Dgm as well?

Btw alot of people are saying changes pressed by Mcdoubles have the highest priority is that really true?...

**Comment by Duskhaven** [comment]
Fixed.
