### ISSUE TITLE
Tinker cannot zone into Gnomer dungeon

### ISSUE THREAD

**Issue by Elasticsx** [Duskhaven/Bug-Reports#35]
leveling up a tinker and joined an RDF and zoned into Gnomer, but it keeps putting me into the "Tinker Gnomer" city instead of the gnomer dungeon

**Comment by Thickmonty** [comment]
Same

**Comment by Duskhaven** [comment]
This is intended. Tinkers cannot participate in the actual Dungeon since this is their "Class Hall"
