### ISSUE TITLE
Keystone Challenge Season 2 Weekly Quest --- SFK Issue

### ISSUE THREAD

**Issue by LVCJS** [Duskhaven/Bug-Reports#357]
SFK completion for the weekly gives Graveyard credit instead on +8, rather than SFK. 
Not sure yet if GY gives SFK credit in reverse.
Quest might be dead until resolved.

**Comment by LVCJS** [comment]
Cathedral gives SFK credit

**Comment by LVCJS** [comment]
ST gives Cathedral

**Comment by LVCJS** [comment]
and finally, Graveyard gives ST.

**Comment by Duskhaven** [comment]
Fixed.
