### ISSUE TITLE
Permanent Warmode Without Toggling it

### ISSUE THREAD

**Issue by PSIN-dev** [Duskhaven/Bug-Reports#358]
Merely standing near someone who triggers the Warmode quest will flag your character for Warmode. My DK Alt who has never even spoken to the NPC is now flagged perma for PvP after standing by the m+ vendor for 5m while I was AFK.

**Comment by Duskhaven** [comment]
Duplicate issue, refer to https://github.com/Duskhaven/Bug-Reports/issues/142
