### ISSUE TITLE
Divine purpose talent bugged

### ISSUE THREAD

**Issue by JulioFangio** [Duskhaven/Bug-Reports#359]
Just unlocked the talent and when two one-handed weapons are equipped could not hit a single auto attack for the past 20 mnts

**Comment by Duskhaven** [comment]
Make sure to visit the Innkeeper in Org/SW if you are a custom race/class combo

**Comment by JulioFangio** [comment]
Yes i am a tauren/paladin, just visited the innkeeper repurchased the one handed sword but still not working
