### ISSUE TITLE
Problem with dungeon finder

### ISSUE THREAD

**Issue by KamiNoEnd** [Duskhaven/Bug-Reports#36]
![image](https://user-images.githubusercontent.com/49670986/223581470-7c48e9a1-ee6e-49a0-9b42-dce285a0f342.png)
I have a macro to queue rdf but after a certain level between 55 60 it dissapear from the list

**Comment by Duskhaven** [comment]
This is a Visual Issue and will be fixed with a future patch. 
For now reloading/relogging will add the Roster back.
