### ISSUE TITLE
Frost Mage's 'Glacial Spike' and 'Snowstorm' talents are incapable of critting. 'Glacial Spike' also isn't reset by the 'Cold Snap' talent.

### ISSUE THREAD

**Issue by Scoliox** [Duskhaven/Bug-Reports#364]
https://imgur.com/a/9uqRv2x - Used Glacial Spike only while under the effects of Fingers of Frost for the +50% crit chance amp. It also seems like Glacial Spike isn't affected by the talent 'Ice Shards' (increases Frost crit damage by 100%) as it only crits for 40%~ extra damage, not double as it should with 'Ice Shards' talented, when it does crit.

I think the real bugs here are Glacial Spike and Snowstorm not being a part of 'Fingers of Frost', 'Shatter', and 'Ice Shards' their affected abilities lists. Could also be because Glacial Spike is listed under the General spellbook and not under any of the spec based spellbooks and that therefore it isn't seen as an actual mage ability? I did also test Glacial Spike on targets affected by Frost Nova which should also trigger Shatter's 50% increased crit chance bonus but it didn't work on those targets either which makes me think the ability is simply not flagged as a (frost) mage ability and therefore not affected by any of the mage talents. The 'Lonely Winter' ability for example does affect Glacial Spike's damage which I think is a general +15% increase to overall Frost damage done.

I'd still love to see Deep Freeze and Glacial Spike be on separate talent rows if possible, with Glacial Spike dealing reduced damage against players as a compensation nerf for PvP if the crit bug is ever fixed. Deep Freeze is a really fun ability to use in PvE due to how oomphy it hits and how you can use it back to back with Cold Snap. It also has uses in M+ and enables Frost mages to assist in stopping mob casts, which is something it currently lacks relative to other specs besides its 24s CD interrupt.

As it stands, Deep Freeze hits for 3.5k single target (ST) and has a 60%+ chance to crit for 7k+ on bosses every 30 seconds. Contrast to Glacial Spike which at most does 2.5k ST, or 5k on two targets, and is unaffected by FoF+Shatter, it's just not worth taking as a talent. Even if it were able to crit reliably, and  for 2x damage, Deep Freeze is a more fun ability to use since it's one that you rarely ever get to use in PvE since Frost has never been a viable PvE spec back when we had access to wotlk-style talents. So finally being able to play with it scratches a different itch to having access to Glacial Spike as a new ability. Hence why I'd love to see these two abilities on separate rows so that once Glacial Spike's biggest issue is fixed (not being able to benefit from FoF+Shatter), you can use both.

**Comment by Duskhaven** [comment]
Fixed.
