### ISSUE TITLE
Glyph of Windfury Weapon

### ISSUE THREAD

**Issue by Tribonius** [Duskhaven/Bug-Reports#365]
I am trying to apply Glyph of Windfury Weapon but it only gives an error message saying "That glyph is already inscribed in your spellbook". I already have another glyph allied to that slot, but it should normally replace it with the new one.
![WoWScrnShot_031523_230603](https://user-images.githubusercontent.com/128012463/225501998-278bd9b3-247b-4f8f-8618-2ebc2df859d7.jpg)

**Comment by Duskhaven** [comment]
The Glyph is already passively active as a Storm Infuser.
