### ISSUE TITLE
Trauma, Deep Wounds and Blood Frenzy.

### ISSUE THREAD

**Issue by Feardonald** [Duskhaven/Bug-Reports#378]
**Trauma**
Your melee critical strikes increase the effectiveness of Bleed effects on the target by 40% for 1 min.

**Deep Wounds**
Requires Melee Weapon
Your critical strikes cause the opponent to bleed, dealing 48% of your melee weapon's average damage over 6 sec.

**Blood Frenzy**
Increases your melee attack speed by 10%. In addition your Rend and Deep Wounds abilities also increase all physical damage caused to that target by 4%.

Trauma only ever applies to one target. All your targets are supposed to be affected.
Tested using Bladestorm versus 4 targets and without auto attacking (white hits).

Deep wounds and blood frenzy seem random. Sometimes cleave/sweeping strike do not apply these, but trauma is always missing for more than one target.
Bladestorm/whirlwind always apply deep wounds and blood frenzy, but always missing trauma for more than one target.

All warrior abilities are physical "melee".

Cleave, sweeping strikes, whirlwind, bladestorm, cleave and all our other abilities should always apply the debuffs with critical hits.

Please let me know if you need anymore information.

Best Regards
Genjuro

**Comment by ghost** [comment]
This is actually huge thank you for noticing and reporting it.

Do you happen to know if on-hit effects like fiery weapon, fiery plate gauntlets, etc. are fixed to not proc deep wounds?

I know for other 3.3.5 server that interaction is still there but I was wondering if they removed it here or it's just not working properly

**Comment by Duskhaven** [comment]
Bladestorm, Cleave and Whirlwind now correctly apply Trauma.
