### ISSUE TITLE
Issue with flying from Ironforge to Menethil Harbor

### ISSUE THREAD

**Issue by ironstag93** [Duskhaven/Bug-Reports#38]
Flying from Ironforge to menethil harbor glitches about halfway (when flying over IF Airport)

The gryphon will suddenly stop, fly backwards for a time, then will proceed to fly all the way out to WPL and then back to IF airport and then it corrects itself and continues to the harbor.

**Comment by Duskhaven** [comment]
Duplicate Issue, please refer to https://github.com/Duskhaven/Bug-Reports/issues/17
