### ISSUE TITLE
[Engineering] Exploding Sheep doesn't explode

### ISSUE THREAD

**Issue by tomdjh** [Duskhaven/Bug-Reports#390]
<img width="1178" alt="sheep" src="https://user-images.githubusercontent.com/128037096/225625010-0646e33a-7f7c-4002-8be6-c2bbd416655c.png">

After using 'Exploding Sheep' from Engineering, it stays (so far permanently, not the 3 minutes the tooltip suggests) and in addition it does not explode. 
'Exploding Sheep' just melee's any hostile mobs within it's aggro radius. Attached is a screenshot showing the combat log and damage on low-level enemies.

**Comment by Duskhaven** [comment]
Fixed.
