### ISSUE TITLE
Mage: Glacial Spike & Haste

### ISSUE THREAD

**Issue by Tzevy** [Duskhaven/Bug-Reports#395]
The Cast time of Glacial Spike does not change from 2.5 regardless of your haste or casting speed-altering mechanics (eg: icy veins, bloodlust/heroism, m+ 2 set proc haste bonus, druid light CD haste buff, etc.

I don't know if it's intended, but I think it should be affected by it.

**Comment by Duskhaven** [comment]
Fixed after restart
