### ISSUE TITLE
Shadowy Tome skips a tick of Mind Flay 

### ISSUE THREAD

**Issue by poggaming123** [Duskhaven/Bug-Reports#397]
Mind Flay only ticks twice with Shadowy Tome. You are losing 1/3rd of your damage and ramping slower since Shadow Weaving now requires an extra global.

EDIT: Mind Flay is supposed to tick 3 times, with Shadowy Tome and some haste you can almost get a 4th tick, but since this is bugged it ticks 2 times and then never again for the remaining duration.

**Comment by Duskhaven** [comment]
Fixed after restart
