### ISSUE TITLE
Feralas - wrong Fatigue Zone , beware people Hardcore characters - lost mine due to it lol XD

### ISSUE THREAD

**Issue by Denny2456** [Duskhaven/Bug-Reports#398]
![image](https://user-images.githubusercontent.com/128092451/225738652-d6a90c66-5c4d-4518-89f1-b8853fb2bc65.png)

https://clips.twitch.tv/SilkyRoundNarwhalPrimeMe-uJqi4AnLE7BU5rz4

R.I.P Arschbringer , maybe GM will restore it because technicly it wasnt my fault XD

**Comment by darkjesterr** [comment]
what do you mean wrong zone?
I see a fatigue zone there
![image](https://user-images.githubusercontent.com/81621780/225949672-cc56eec1-6056-4993-b23b-d668dfe3c841.png)
