### ISSUE TITLE
Scroll of Stamina isn't consumed

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#4]
Character Name: Magni
Zone/Area: Any (Not relevant)
Screenshot/Video: https://imgur.com/a/KchK5aF
Issue: When you use the low lvl scroll of stamina it doesn't get consumed and gives you the buff. Minor bug that only happens with this scroll so far.

**Comment by Duskhaven** [comment]
This is fixed with the next Server Restart
