### ISSUE TITLE
Alcor's Sunrazor Not Scaling with SP

### ISSUE THREAD

**Issue by Chad-CL** [Duskhaven/Bug-Reports#400]
![image](https://user-images.githubusercontent.com/32410028/225772865-c13bd808-0c06-49a5-b28d-acb761541110.png)

Report from another github mentioning Alcor's Scaling with Spellpower.

**Comment by Chad-CL** [comment]
It does not currently on this server.

**Comment by Duskhaven** [comment]
Fixed.
