### ISSUE TITLE
Chromaggus Bronze Dragonflight Debuff Refreshing Inducing PERMA STUN

### ISSUE THREAD

**Issue by Chad-CL** [Duskhaven/Bug-Reports#407]
Bronze Dragonflight Debuff lasts 7 seconds and refreshes at 3 seconds resulting in a permanent stun with no way to cleanse.

The duration of this buff should be 3 seconds.

Chromaggus is not possible at this time.

**Comment by Feardonald** [comment]
Hi Chad,

Maybe I am misunderstanding you, but isn't this the debuff players can remove themselves with hourglass sand?
Edit: Not possible to use the sand before first stun ever hits?

Best Regards
Genjuro

**Comment by LVCJS** [comment]
We were being chain-stunned. You can remove the 10 minute debuff, but the 10 minute debuff puts a stun that lasts about 7 seconds, but that overlaps refreshes after 3 seconds, so we're chain-stunned and unable to remove the 10 minute debuff that causes the chain reaction.

**Comment by Chad-CL** [comment]
We are unable to use the sand once stunned. The stun duration is typically
3 seconds. It is 7 currently.

**Comment by Duskhaven** [comment]
Fixed after restart. Also the intended stun duration is 4 seconds, not 3.
