### ISSUE TITLE
Death Knight runes being made Death Runes when they should not

### ISSUE THREAD

**Issue by zGlade** [Duskhaven/Bug-Reports#413]
Currently, as a Frost DK, using Obliterate while specced into 3/3 Blood of the North makes the Frost and Unholy runes consumed by Obliterate turn into Death runes. This should not be the case, it's only blood runes consumed by Blood Strike or Pestilence which should create Death runes when specced into this talent.

Tested with a DK specced into Blood of the North and one without.

**Comment by harukaze3** [comment]
Can't reproduce.

> GM Haruka
