### ISSUE TITLE
Mage: Diverted Energy

### ISSUE THREAD

**Issue by Sp4wNi** [Duskhaven/Bug-Reports#416]
Hey,

its says it GREATLY increases the mana reg, but it gives only 1 mana every second. thats 3 mana in total.
I think it is supposed to give 1 MAX MANA every second at least.
In best case it should give 3 max mana every second for 3 seconds

Cheers

**Comment by Duskhaven** [comment]
Fixed after restart.

**Comment by Duskhaven** [comment]
Fixed.
