### ISSUE TITLE
Freedom fighter/Holy paladin talent bug please fix 

### ISSUE THREAD

**Issue by Tatya97** [Duskhaven/Bug-Reports#420]
The custom talent freedom fighter in the holy paladin talent tree does not increase the movement speed of the target affected by the hand of freedom but increases the paladin movement speed always regardless of the target. This is contradicting the wording in the spell since there is no "Your movement speed " or "The paladin" and it just says"Your hand of freedom increases movement speed by 50% for 4 seconds".

**Comment by Duskhaven** [comment]
Description is updated with the next patch update
