### ISSUE TITLE
Arcane missiles not being cast.

### ISSUE THREAD

**Issue by Sylaria** [Duskhaven/Bug-Reports#421]
Hello,

On my mage arcane missiles sometimes will not cast.. It takes a gcd, mana and the arcane missile proc from arcane mage talent.

It does not get resisted. I have checked combat log everytime it happens but nothing shows.

The same was on another server and it got fixed there. Please have a look at this bug. 

Thank you!

Sylaria

**Comment by Duskhaven** [comment]
This happens when you are missing. Will be changed so it can no longer miss after restart
