### ISSUE TITLE
Tier 2 Wrath tank being Death Knight only

### ISSUE THREAD

**Issue by Ariavan** [Duskhaven/Bug-Reports#424]
![image](https://user-images.githubusercontent.com/128177824/225980728-b081c704-2ba5-4990-8bae-53d8621fa849.png)
 So, I believe that this isn't intended as these are quite literally warrior tier and I as a warrior can't equip them

**Comment by Duskhaven** [comment]
There are two different sets, one for warrior and one for Death Knights.
