### ISSUE TITLE
Skill Issue

### ISSUE THREAD

**Issue by Landengen** [Duskhaven/Bug-Reports#426]
Im pretty certain this is considered a bug. I cant tell if it actually effects the Herbalism skill because I dont have it on this character, all I know is I am no longer missing when I hit with a dagger.
![World of Warcraft_2023 03 17-14 25](https://user-images.githubusercontent.com/128180439/225988916-0ac53fbc-896a-42ff-a6a9-9d86adb5f026.png)

**Comment by Duskhaven** [comment]
The text is to be ignored, the actual effect of increasing the weapon skill works.
