### ISSUE TITLE
Balance Druid Bugs

### ISSUE THREAD

**Issue by onyxrain2882** [Duskhaven/Bug-Reports#429]
Wrath doesn't shoot thorns when close up. This made me opt out of questing as balance at all unfortunately. And Starfire with Fury of Elune is awesome! I love it! Except.. it pulls mobs that are not in combat so.. I don't use it in dungeons.. which is sad, it's my main damage and what makes the class fun. You can however take the "Glyph of Focus" to reduce it's range by 50% and you've less issues. Buuut when you go into raid and can't stand close enough etc, or dungeon pulls where you can't stand close enough.. you just lose all the fun and big numbies. Basically, as balance you have to stand far enough away that wrath procs thorns damage and close enough that starfire procs star damage and it's taking a lot of fun out of what could be! Oh uhm also, idk if it's meant to but increasing thorns damage with talent or with the druid set doesn't actually increase thorns from wrath. Thank's for letting me post my input! - Doc 

I suggest a Glyph system like Cata where once you learn the Glyph, you can take it out or swap it at any time. This would fix the issue of Starfire needing a glyph or not needing a glyph to be a button in balances rotation whilst also allowing for more creativity and flexability across all classes.

**Comment by Duskhaven** [comment]
Fixed
