### ISSUE TITLE
Blackblade of Shahram not working.

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#434]
The Epic sword dropped by the last Boss in Upper Blackrock Spire is not working.
The Sword is summoning Shahram but he grants no buffs ro the player deals no dgm to the mobs and just stands around.

This is from Wowhead about the proc effect:

The proc summons, a flamewaker who can cast the following spells:
[Curse of Shahram] AE Slow Enemies
[Might of Shahram]AE Stun Enemies (~5 sec)
[Fist of Shahram] Group Haste - 25% (~8 sec)
[Blessing of Shahram] Group restore life/mana (20 sec)
[Will of Shahram]  Self +50 all stats (20 sec)
[Flames of Shahram] Flamestrike enemies (~100-150 damage)

Please i have been farming UBRS for days to get this...its heart breaking it doesnt work.

From the bottom of my hearth please could you fix this Devs?

**Comment by Duskhaven** [comment]
Fixed.

**Comment by Colette00** [comment]
Thank you very much!

Its working but not quite yet please could we finish it up?

I have been hitting the Dummy for 1 Hour but never got the Group Haste buff.
If you add it could it be increased to 15 secs instead of just 8 secs?
