### ISSUE TITLE
Quest Bug - Totem of Tikti

### ISSUE THREAD

**Issue by Landengen** [Duskhaven/Bug-Reports#437]
Tested multiple times just to make sure. When you accept this quest you are supposed to be given a glide/slow fall effect to jump off the cliff with and land on the other side of the river you look down at.

**Comment by Landengen** [comment]
I should point out Ill be testing the rest of this quest line as well. At the moment it seems the follow up quest Totem of Yor also has the same issue.

**Comment by Landengen** [comment]
Final view of this quest, the Totem of Yor Quest also missing its effect "Embrace of the Serpent" which gives significant swim speed boost and water breathing. The last buff related quest does not have this issue. Totem of Vark gives you the invisible cat buff properly. In the dialogue there is an occasional speech error where the npc does not say your name properly and instead say $n or something similar.

**Comment by Duskhaven** [comment]
Fixed.
