### ISSUE TITLE
Frenzied Chimaera Mount

### ISSUE THREAD

**Issue by Simplest1012** [Duskhaven/Bug-Reports#441]
Frenzied Chimaera mount does not have a nameplate at all when targetted. Also pls let us ride the mount instead of transforming into it :)

https://imgur.com/a/puwiyTm

**Comment by Simplest1012** [comment]
Oh it also REALLY does not like water. Like the tiniest body of water will make it slow and make the camera think we're under water

https://www.youtube.com/watch?v=fwMOE7FmBio

**Comment by Duskhaven** [comment]
The mount is supposed to look like this 
![image](https://user-images.githubusercontent.com/123925176/226199444-c874d7c5-e91c-4c01-a957-5ebfb81fe87a.png)

Will be fixed with the next patch update
