### ISSUE TITLE
Quel'Serrar bug

### ISSUE THREAD

**Issue by FeralHeistxd** [Duskhaven/Bug-Reports#443]
![image](https://user-images.githubusercontent.com/127445042/226093821-cd027d3f-77f5-4098-913b-6ec9c806b2fc.png)
![image](https://user-images.githubusercontent.com/127445042/226093846-97ecf4ce-c168-4c61-bb8a-ca47105514e2.png)
Quel'Serrar doesnt add 20 defensive rating as is written on the item, but only gives 13 defensive rating
![image](https://user-images.githubusercontent.com/127445042/226093891-76c82f0f-ff02-4b22-9e3c-2397074d4010.png)

**Comment by Feardonald** [comment]
Hi Feral,

The conversion is not 1 to 1. 
You can test equipping any other items you have with defense.

There are still some wiki articles that go into further detail if you want to learn more.

Best Regards
Genjuro
