### ISSUE TITLE
flametougne stats aren't stacking

### ISSUE THREAD

**Issue by Phelp58** [Duskhaven/Bug-Reports#445]
Unsure if this is purposeful but Flametougne weapon when applied to 2 weapons is only increasing spellpower for 1 weapon, this is under normal circumstances wrong, and should apply for both weapons (Glyph is also bugged and should apply 2% crit per weapon enchanted with flametougne)

**Comment by Duskhaven** [comment]
This only works when using 2 different ranks.

**Comment by Phelp58** [comment]
i am using 2 seperate ranks it's still not working
