### ISSUE TITLE
Death Knight - Glyph of Obliterate causing Obliterate to create Death Runes

### ISSUE THREAD

**Issue by zGlade** [Duskhaven/Bug-Reports#449]
I have figured out what was causing issue #413, it's not the talent Blood of the North, but glyph of Obliterate that seems to be the culprit.

I've attached a video in which I reproduce the bug. The same talents were used for both specs and tests, the only difference being the glyphs used. I blood boil repeatedly using the death runes to show that it's not an issue with the WA, they are in fact death runes.

https://user-images.githubusercontent.com/128044333/226101456-793afe1d-32c8-49c3-8729-b008c4fe7944.mp4

**Comment by Duskhaven** [comment]
Fixed.
