### ISSUE TITLE
Human druids: Cat form size bug

### ISSUE THREAD

**Issue by Tekonaz** [Duskhaven/Bug-Reports#457]
When relogging while in cat form as a human druid u keep getting bigger (in the negative space so you are underground though)

**Comment by Tekonaz** [comment]
Example:
![image](https://user-images.githubusercontent.com/33176182/226118818-9e005955-5bcf-436b-b8fa-4a7911d89b94.png)

**Comment by Duskhaven** [comment]
Duplicate issue https://github.com/Duskhaven/Bug-Reports/issues/154
