### ISSUE TITLE
Journeyman riding and mount mail gold cost is incorrect

### ISSUE THREAD

**Issue by leiske** [Duskhaven/Bug-Reports#463]
I hit level 40 on my Undead and received the following mail:
![image](https://user-images.githubusercontent.com/4615743/226140119-ae721071-bccf-4e21-808f-d9012fb2586f.png)
![image](https://user-images.githubusercontent.com/4615743/226140122-85dd0d9a-cbb0-4fc9-b530-e481376ad0a6.png)

First paragraph, last sentence. 

> My fee is a modest fifty gold coins

Actual trainer shows 270:
![image](https://user-images.githubusercontent.com/4615743/226140050-da40de79-d2ed-4ae5-9ac5-d4756d87b8f2.png)

And the horses are also off by 1 gold:
![image](https://user-images.githubusercontent.com/4615743/226140060-01c58494-3f69-40c7-a941-896e68ad5fab.png)

**Comment by Duskhaven** [comment]
Fixed.
