### ISSUE TITLE
Earth Shock Rank 6 Damage

### ISSUE THREAD

**Issue by AlexandreBorges-GoFox** [Duskhaven/Bug-Reports#464]
It is doing lots of damage, way too much damage. Don't know if its intended, but doesn't  look  like

Skada
![image](https://user-images.githubusercontent.com/125302034/226141575-7d26db61-4c29-445e-ad26-1d43872e75e9.png)

![image](https://user-images.githubusercontent.com/125302034/226141587-eb26f680-63b1-4bba-8e68-6449bbc02f72.png)

My stats
![image](https://user-images.githubusercontent.com/125302034/226141596-fbf1022c-8cc4-48e5-b02e-05068f63f31d.png)

My talents

![image](https://user-images.githubusercontent.com/125302034/226141612-84eb716b-dc85-4f04-9c8e-6b829f6aff12.png)

![image](https://user-images.githubusercontent.com/125302034/226141618-34dbb5b6-b385-4e25-b55b-8149f124e780.png)

**Comment by AlexandreBorges-GoFox** [comment]
Oh, btw, the tooltip

![image](https://user-images.githubusercontent.com/125302034/226141663-d0d438dd-0728-4cc2-9aee-d0dccbfbd657.png)

**Comment by Duskhaven** [comment]
Fixed.

**Comment by AlexandreBorges-GoFox** [comment]
I've waiting and reloged, the numbers seem to be the same, is this a next server reset thing?
