### ISSUE TITLE
T2 Death Knight / Warrior Helmet off Onyxia is classified as Warrior only.

### ISSUE THREAD

**Issue by Chad-CL** [Duskhaven/Bug-Reports#466]
Hello,

The Helmet of Wrath off of Onyxia is only equipable by Warriors however the set is shared with DKs like prior sets.

The only way possible for DKs to get the helm is through tier turn-ins right now.

**Comment by Duskhaven** [comment]
Warrior and Death Knights have seperate T2 sets
