### ISSUE TITLE
Poisonous Shot Bugged 

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#467]
Hunter talent Poisonous Shot does not make Aimed Shot deal +10% nature dmg.  Aimed shot still does physical dmg after taking the talent.

**Comment by Duskhaven** [comment]
Cannot replicate, but it does not trigger while closer then 10 yards, range fixed after restart.
![image](https://user-images.githubusercontent.com/123925176/226198288-e34574a4-9aff-4169-bd2a-e9d10ab801df.png)
