### ISSUE TITLE
PvP Alli Mount Vendor

### ISSUE THREAD

**Issue by Highmoore** [Duskhaven/Bug-Reports#469]
The mounts are like 50,000 Honor when the horde mounts are like 25,000

**Comment by Duskhaven** [comment]
Cannot replicate 

Alliance: 
![image](https://user-images.githubusercontent.com/123925176/226802072-c68c551a-8bc7-4789-89bb-75431796710c.png)

Horde:
![image](https://user-images.githubusercontent.com/123925176/226802114-5275c355-3004-43d7-b0b2-2c8fa05c65da.png)
