### ISSUE TITLE
Hunter Kill Command and Aspects

### ISSUE THREAD

**Issue by Ffsallnamestaken** [Duskhaven/Bug-Reports#470]
Kill Command when the pet gains the buff all three charges are used up instead of 1 and Growl also uses up all three charges. 

When in a mythic+ I can't change aspects while in combat. I go from hawk to Viper and it just cancels them both and can't get into any aspect for remainder of thr fight.

**Comment by Duskhaven** [comment]
https://github.com/Duskhaven/Bug-Reports/issues/265
