### ISSUE TITLE
Winterspring Frostsaber Questline

### ISSUE THREAD

**Issue by Highmoore** [Duskhaven/Bug-Reports#471]
Not sure if this is a bug but it requires Exalted rep with them and then the mount is 900g... Horde have the 20 day daily then 80g for the venomhide raptor

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://user-images.githubusercontent.com/123925176/226241088-c53325af-5615-4ff3-9910-90ee3d1387c9.png)
