### ISSUE TITLE
Morbent Fel

### ISSUE THREAD

**Issue by Kygaz** [Duskhaven/Bug-Reports#477]
'Morbent Fel' is a quest in Duskwood at the Cemetary. It requires you to kill Morbent Fel, also you can use an item to remove his shield and weaken him. The item is not usable however, and upon killing Morbent Fel the quest does not complete.

**Comment by Duskhaven** [comment]
Fixed.

**Comment by TheSCREWEDSoftware** [comment]
> Fixed.

Sorry to comment on an old issue fixed. Are you able to share what was the fix you achieved for the NPC not completing upon being killed?
