### ISSUE TITLE
Wildfire Infusion

### ISSUE THREAD

**Issue by 7r3x92** [Duskhaven/Bug-Reports#478]
Good day,

The Survival hunter talent Wildfire Infusion is not able to be selected. I am a level 58 dwarf hunter named Tanin and have tried each level after level 38 to acquire this talent. I appreciate any insight into this issue.

Very Respectfully,

Tanin

**Comment by Duskhaven** [comment]
The Talent is passively active after spending point in resourcefullness but does not show as picked.
