### ISSUE TITLE
Warrior weapons skills drop

### ISSUE THREAD

**Issue by Truckergut1** [Duskhaven/Bug-Reports#479]
Blood Elf Warrior named Phoenix

One handed swords, axes, and daggers completely disappear from my skills.  The first couple times this happened, they relearned themselves at random. However, it occurred 12 hours ago and the havent returned. Cannot be re-learned at any weapon masters.

**Comment by Duskhaven** [comment]
It's just a visual bug, you still can equip all weapon types.

**Comment by Truckergut1** [comment]
I can equip any weapons i intend to use but i cannot hit any mobs regardless of level. Miss/dodge/parry, as if my weapons skill is literally zero
