### ISSUE TITLE
Blackblade of Shahram BUGGED

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#483]
This Sword got 1% Droprate in UBRS even after farming for weeks and finally getting it its not working right.

First the procc rate of the weapon effect is abysmal low like really low on compared to information on wowhead, your lucky to see it do anything for you during Dungeon run.

Is it not unfair when Empyrean Demolisher got buffed and now everyone can easily buy it and use this overpowered weapon compared to weird guy farming this sword like me getting it and seeing it doesnt work at all?....

To test the weapon effect summoning buffs i went and hit training dummy for 2 hours semi afk.

Procced around 17-18 times 

- Zero Group haste Buff 
- Zero Aoe Stun
- Stat Buff is not working for party only for sword wielder and it should work for whole party. 
- For some reason HP reg Buff is always appearing everytime not sure why

This darn thing used to be the best Sword you could get as Arms Warrior.....i wasted weeks on it just to get it.
And its just not working as it should ...major dissapointment.

**Comment by Duskhaven** [comment]
Fixed.
