### ISSUE TITLE
[The Real Threat] quest in Arathi Highlands

### ISSUE THREAD

**Issue by Beilog** [Duskhaven/Bug-Reports#484]
Quest https://classicdb.ch/?quest=680 is missing the boss mob Or'Kalar. Other mobs with the related quests are there ie Kill 3 Lords and Kill 7 Shamans. But Or'Kalar is not there. Could be added with the rest near the altar.

**Comment by Duskhaven** [comment]
Or'Kalar is in a new location outside of Stromgarde up on the Hill.
