### ISSUE TITLE
Tinker Scrap Bullet

### ISSUE THREAD

**Issue by xRunicTitan** [Duskhaven/Bug-Reports#486]
Once a mob gets close enough, my character stops casting Scrap Bullet. Very obnoxious.

**Comment by xRunicTitan** [comment]
Also pretty dumb how spamming Scrap Bullet just keeps resetting the cast timer...

**Comment by Duskhaven** [comment]
cannot replicate

**Comment by xRunicTitan** [comment]
If it helps, I use 
/startattack
/cast Scrap Bullet
