### ISSUE TITLE
Unique Cache M+

### ISSUE THREAD

**Issue by FeralHeistxd** [Duskhaven/Bug-Reports#488]
U cant get more than 1 unique cache from m+ of the same difficulty. So if u stack on keys to do later, and u get the same key u have in ur keyring, u are forced to either do the key in ur keyring next, so u can get it again, or delete the cache. Please change it so its not unique, and u can just spam dungeons, like its not even fun to be forced to do some content u dont really want to do now. I am spamming +2 rn so i can stock up on +4 then +6 etc. keys, but i was already forced to delete 2x cache cause i got same key. Either make it u are guaranteed to get key u dont have or make it not unique.

**Comment by Duskhaven** [comment]
Caches are no longer unique after the restart.
