### ISSUE TITLE
Scroll of Stamina (3 Stamina) Can be used infinite times, even if I only have 1 in my inventory.

### ISSUE THREAD

**Issue by Sebily0801** [Duskhaven/Bug-Reports#49]
Item: https://imgur.com/a/wCLEvvQ

I can use it infinite times without the item losing its quantity, its practically a spell at this point that gives me 3 free stamina.

**Comment by Chromie-the-gnome** [comment]
Already reported here https://github.com/Duskhaven/Bug-Reports/issues/4
