### ISSUE TITLE
Rogue quest bug not allowing stealth

### ISSUE THREAD

**Issue by Pinananas** [Duskhaven/Bug-Reports#490]
Klaven's Tower is a Rogue quest, in which it requires you to slay an undead outside said tower to retrieve a key, and then fighting your way up the tower to claim a book at the top to finish the quest.

Upon recieving the book, you get a debuffwhich doesn't allow stealth for 7 days. This is normal as later in the questline, you get the debuff removed.

The undead that is supposed to drop the key, is not dropping it. This is bad because I am now stuck with a 7 day debuff that doesn't allow stealth. I believe first aid Anti venom is a temporary fix until the quest is fixed.. but please fix, it can be frustrating for rogues questing in westfall.

**Comment by Duskhaven** [comment]
Fixed.
