### ISSUE TITLE
Heroic Molten Core tuning

### ISSUE THREAD

**Issue by midsu45** [Duskhaven/Bug-Reports#492]
Hello! Our raid team has cleared All of MC, Azshara, Onyxia,  heroic onyxia and up to chromaguss for the past 2 or more weeks, but heroic molten core seems to have some really overtuned mechanics. 

Most of the raid is fine, but Baron seems to be slightly overtuned especially with how fast the fire spirits spawn. The same issue is seen in rag. The fight goes pretty well up until 35% where he starts summoning fire spirits and he spawns them way too fast, especially with the ad that needs to be killed. The only clear that we have heard about so far was done by one group and thats because they used 3 healers and 1 tank. This seems like unintentional or even bad design because there shouldnt ever be a fight where you need 3 healers 1 tank, especially when 2 of their healers were disc priests. Our healers are pumping out 800-1k HPS but it doesnt seem enough, and we are pulling over 1k+ dps and bursting down the fire spirits but they still spawn in way too fast to where we cant focus on damaging the boss and have to tunnel them. Maybe nerf their spawn rate by half for both of those fights. 

In general, Molten core heroic is overtuned, especially for how little upgrade or gear you get for doing it as only off pieces drops and some dont even have a heroic equivalent. At least Onyxia still drops t2 helms and token.

**Comment by Duskhaven** [comment]
You already get a 10% buff. Other guilds were able to clear it.

**Comment by lolxd12345123** [comment]
> You already get a 10% buff. Other guilds were able to clear it.

are you retarded

**Comment by midsu45** [comment]
I have only heard of 1 other group clearing this and thats because they used 3 healers. Is that the intended way to do that fight then? Is this how future raids will be designed as well?

**Comment by midsu45** [comment]
The buff doesnt really do anything when it comes to the constant spawning of fire spirits (the draenei ghosts). Was this even tested by the dev before being released? I guess we will just go with the assumption that you want 10 man raids to have 3 healers and 1 tank only for certain fights, which is a bit of backward take.

**Comment by lolxd12345123** [comment]
> You already get a 10% buff. Other guilds were able to clear it.

btw one of the other guilds that cleared it has a tinker doing 3-4k ST dps because you (assuming Noxx) are beyond clueless when it comes to balance, you were just as brainless in 2021 and it clearly isnt any different now lmao
