### ISSUE TITLE
Leeching scoundrel

### ISSUE THREAD

**Issue by Calyxsys** [Duskhaven/Bug-Reports#493]
My post was closed, proof was shown this talent is working but seems to not work before 60 (as far as i know atm) as whoever posted the screenshot was definitely level 60, as they had the level 60 mutilate talent, but the leeching scoundrel is not currently working on my level 45 rogue.

![Screenshot_3323](https://user-images.githubusercontent.com/128289362/226216681-c4a62207-d336-4430-8809-dc4d9c9293f3.png)
![Screenshot_3324](https://user-images.githubusercontent.com/128289362/226216684-109b4ea3-2043-4161-b0c6-c187321be5a8.png)
![Screenshot_3326](https://user-images.githubusercontent.com/128289362/226216686-5af4b402-f764-4fca-ab2d-192c9f324aef.png)

I'm glad it starts working at least at some point, but trying to find the issue as to why it has not worked from 40-45 so far, can happily post messages when it starts working and at what level.

**Comment by Calyxsys** [comment]
![Screenshot_3327](https://user-images.githubusercontent.com/128289362/226217220-fd8390fe-7a9b-4e9b-a6eb-6d8a607e9915.png)

tested on another mob in my level range (lvl 42 hyena in tanaris and i'm still level 45)

**Comment by Duskhaven** [comment]
Fixed.
