### ISSUE TITLE
Demon Hunter problem

### ISSUE THREAD

**Issue by Azeroth94** [Duskhaven/Bug-Reports#494]
Give back  Demon Hunter "Poisons "  at least add 50 dmg on each poison becouse right now with  5-7 damage with poisons is very low and as DH Tank will help also with Threat as he is all around poison class also fix   Glaive trow AOE set mythic  + gear 2 set not working  its not AOE attack and not even bleed over time    

back to problem 1 ::   each tick of poison  5 -7   its just useless on DH  just make it 50 or at least some ok number around 25-30   for real  5-7 damage is just funny :D

**Comment by Duskhaven** [comment]
DH's can only use utility poisons.
