### ISSUE TITLE
Bonereaver's Edge proc

### ISSUE THREAD

**Issue by Feardonald** [Duskhaven/Bug-Reports#501]
Greetings,

I have only tested the normal version.

**Chance on hit:** You gain 75 armor penetration rating for 10 sec. This effect stacks up to 3 times.

It never goes above 2 stacks and why has it been lowered to 75 armor penetration? Intended to be 100 armor penetration per stack.
EDIT: Once it reaches 2 stacks, the duration gets only refreshed with 2 stacks instead of gaining 3 stacks.

Please let me know if you need any more information.

Best Regards
Genjuro

**Comment by Duskhaven** [comment]
This is a intended change (It might get readded back if the DPS gain is not as impactful)

**Comment by Feardonald** [comment]
@Duskhaven:
It is normally BiS for arms warrior with current content.
Right now it only stacks to 2 even though tooltip says 3.

You have to decide what is the best, but it used to be a very good item and would love to see it's return.
