### ISSUE TITLE
Tinker damage

### ISSUE THREAD

**Issue by midsu45** [Duskhaven/Bug-Reports#506]
Tinker is doing around 3k or more Single target dps which seems completely overtuned. Especially since 70% of that damage is just machine gun. The only people ive seen clear heroic Rag without 3 healers abused are using that tinker in their raid.

**Comment by poggaming123** [comment]
its 3k burst in opener, multiple classes can do 3k in opener, his damage was also boosted by 3 stack jabs, the other people who killed it didnt 3 heal they just had a monk full disc stacking jabs also. he ended the fight around 1.5k dps which is only like 15% higher than the 2nd which are 2 other hunters(full BM and melee BM).

**Comment by midsu45** [comment]
That is simply not true, he sustains a good 2.5-3k dps throughout most fights, as ive done runs with him.

**Comment by lolxd12345123** [comment]
![image](https://user-images.githubusercontent.com/127686417/226426479-e7e96803-2353-492f-8931-12a6b30b4885.png)

3k on opener btw LMAO
imagine lying

**Comment by poggaming123** [comment]
weird how much you guys know for not even being there, but somehow im lying

**Comment by midsu45** [comment]
This could not have been in your instance? Also he bursts for 4k+ so idk what you are talking about. 350k dmg with 3k dps is over 100s of that damage, not an opener.

**Comment by poggaming123** [comment]
its just funny that ur flaming us for "abusing" just cuz you cant kill it and youve been playing forever. boss damage doesnt even matter cuz hammers are timed, the only hard part about the fight is that he casts hammer while submerged so you cant see the target and we got him to 15% half of our pulls (about 10) across 2 days with people leaving cuz it was late so we filled with random people. the fight is not hard at all just the hammer is so incredibly bugged in multiple ways. so we made weakauras to minimize hammer bugs and even then it still bugged out

**Comment by midsu45** [comment]
No one is flaming anyone, just saying tinker either needs a nerf, or if they dont intend to do that, may as well just reroll to tinker.

**Comment by poggaming123** [comment]
Tinker is doing around 3k or more Single target dps which seems completely overtuned. Especially since 70% of that damage is just machine gun. The only people ive seen clear heroic Rag without 3 healers abused are using that tinker in their raid.

you said this, don't you remember?

**Comment by poggaming123** [comment]
"abusing"
as if anyone intended to abuse anything, our friend we'd never raided with joined, he was playing tinker, he did alot of damage, its happenstance.

**Comment by Duskhaven** [comment]
Fixed. Scaling was at 1,3 for Machine Gun and is now down to 0,5

**Comment by Chad-CL** [comment]
Abusing a broken class to deal double what most class' deal sustained to clear content that is currently difficult to kill is indeed still abuse. 

I rolled up a tinker last night after finding out how broken it was and almost had it 60. Get em next time.

**Comment by Chad-CL** [comment]
Good fix.

**Comment by poggaming123** [comment]
he made a tinker before anyone even knew how strong it was, literally everyone said it was dogshit and thought it was a melee class. no one abused anything. not sure why ur flaming anyone

**Comment by poggaming123** [comment]
we literally started playing a week ago, didnt know anything about this server and have done more than you, you've been playing for who knows how long. get shit on loser

**Comment by Chad-CL** [comment]
Good luck rekilling Rag without the bugged damage :)

**Comment by poggaming123** [comment]
you havent done rag at all, if anyone needs luck its you, the guy who actively plays this server and hasnt killed rag : ()

**Comment by Kromster** [comment]
i killed heroic rag with no tinker ???

**Comment by LVCJS** [comment]
> he made a tinker before anyone even knew how strong it was, literally everyone said it was dogshit and thought it was a melee class. no one abused anything. not sure why ur flaming anyone

Tinker got insane buffs 3 days ago, it wasn't good when he made it.

**Comment by midsu45** [comment]
> we literally started playing a week ago, didnt know anything about this server and have done more than you, you've been playing for who knows how long. get shit on loser

Idk like 90% of the people started when mcdoubles made the video or after, so idk who ur talking about.

Kromster, people saw ur vod and ur clear is impressive, but using 3 healers for a fight is a bit unreasonable for most groups who dont necessarily have a 3rd healer unless they want to pug one.

It can definitely be cleared easily tho. The issue here isnt Heroic rag, its that Tinker was busted and now it got fixed.

**Comment by poggaming123** [comment]
no the issue is that rag fucking throws hammers while submerged, you cant target him and the hammer range is either correct or 40 yards.

**Comment by poggaming123** [comment]
and yeah if we had a 2nd person playing priest then we just bruteforce disc + holy and no mechanics matter if you 3 heal.
