### ISSUE TITLE
Two-Ton Hammer

### ISSUE THREAD

**Issue by Bleuz** [Duskhaven/Bug-Reports#508]
Currently M+2 Two Ton Hammer is the best option for Feral. All other tiers have less bonus AP

Provides +75 and +189 feral attack power. I have 1265 with this equipped.

S2 version provides only +172 bonus feral atk power. I have 1152 with this equipped.

![two_ton_s2](https://user-images.githubusercontent.com/12867946/226339860-acd291d5-78d6-4616-8327-7a12551a4618.jpg)
![two_ton_m2](https://user-images.githubusercontent.com/12867946/226339864-fb50c11f-d3b8-4e2a-a379-662621ed8732.jpg)

**Comment by Duskhaven** [comment]
Fixed after restart
