### ISSUE TITLE
Melee hunter unable to hit

### ISSUE THREAD

**Issue by crazy2d** [Duskhaven/Bug-Reports#51]
Did a run trough SFK. could only hit mobs with wingclip. Raptor strike and auto attack did not work on any mob. after the instance, auto attack in open world works fine

**Comment by ashton1536** [comment]
I have similar problems on my Blood Elf Warrior. I was fine up until i logged in one day and now i can only hit with TS. but all auto attacks :( still is not working and my almost 60 character is unplayable :(

**Comment by Duskhaven** [comment]
Cannot replicate
