### ISSUE TITLE
Can enter Gazlowe's shredder

### ISSUE THREAD

**Issue by Arumas123** [Duskhaven/Bug-Reports#511]
You can enter Gazlowe's shredder in ratchet even after completing the questline.
It doesn't look like it has a distance where you are forced out of it,You can still loot the mobs you kill with the 800dmg attack but I didn't check if it gives quest completion for killing something.
Could be used to destroy Guns of Northwatch and other simple kill quests.

**Comment by Duskhaven** [comment]
Fixed
