### ISSUE TITLE
I cant log on characters logged out in Stormwind, please help

### ISSUE THREAD

**Issue by Abhraxxas242** [Duskhaven/Bug-Reports#517]
![image](https://user-images.githubusercontent.com/127543820/226449348-b6a30ca2-96be-49d0-ac12-0110dd164095.png)

**Comment by harukaze3** [comment]
Please don't open a bugreport for issues like this, just create a ticket in-game, or ultimately, ping me on Discord. Your character should be in Booty Bay after you give me your name.
> GM Haruka

**Comment by Abhraxxas242** [comment]
Well, the issue is that everytime i go into SW with a char it crashes no matter what

**Comment by harukaze3** [comment]
Remove Patch-Z/Patch-5/wow.exe, replace them as fresh files. That *may* fix the issue, but I don't guarantee it.

> GM Haruka

**Comment by Abhraxxas242** [comment]
Yeah, I removed the whole folder and re-unzipped a new one and the issue is still there

**Comment by Duskhaven** [comment]
Belongs in a ticket or in discord
