### ISSUE TITLE
Enchancing the Illidari Warglaives II

### ISSUE THREAD

**Issue by Swiftends** [Duskhaven/Bug-Reports#528]
Killed Nefarian and have gotten the quest complete but turn in is bugged.
![bugged](https://user-images.githubusercontent.com/128307710/226505084-da8a451a-bf9c-4537-a1c9-a28a78336be3.PNG)
![bugged2](https://user-images.githubusercontent.com/128307710/226505172-95051e31-2060-4ffa-b911-dd222e4b7dec.PNG)

**Comment by whieban** [comment]
https://cdn.discordapp.com/attachments/959165551467454504/1087563149286318141/image.png
Also have quest and can't turn in

**Comment by Duskhaven** [comment]
Fixed.
