### ISSUE TITLE
S2 Dragon's Demise vs +6 Dragon's Demise

### ISSUE THREAD

**Issue by LVCJS** [Duskhaven/Bug-Reports#529]
Not sure if reset has already happened for S2 items, but this one is still broken : 
S2 Dragon's Demise :
<img width="264" alt="S2 Ring" src="https://user-images.githubusercontent.com/55683228/226509933-72cebff0-8440-4696-8d08-0dab58a978b9.png">
+6 Dragon's Demise : 
<img width="263" alt="+6 Ring" src="https://user-images.githubusercontent.com/55683228/226509956-788204c4-843c-4c29-81fa-6200225a01e2.png">

**Comment by Duskhaven** [comment]
Fixed after restart
