### ISSUE TITLE
Priest Spirit Tap no longer working with mobk Abilites

### ISSUE THREAD

**Issue by Fubar96** [Duskhaven/Bug-Reports#53]
Before the server migration and the new patch Spirit Tap was triggering when i killed mobs using monk abilties. Now after the patch it is no longer triggering. This is a large part of monk's mana regen currently missing.

**Comment by Fubar96** [comment]
Edit: Spirit Tap is just flat not working at all. Both tests atm are inside of a dungeon.

**Comment by Duskhaven** [comment]
You must deal the killing blow to gain the Spirit Tap effect.

**Comment by Fubar96** [comment]
I was solo inside of Stockades at the time. Spirit Tap is working outside however
