### ISSUE TITLE
Level 70 Mob at Karazhan. [Low Prio]

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#530]
Unphased, most likely part of something WIP. People are getting Netherweave Cloth from it. Harmless, for the most part.

**Comment by harukaze3** [comment]
Addition: Level 68-70 Spectres and Shades are also in the Master's Cellar, can be farmed for Netherweave Cloth. Again, harmless, for the most part.

**Comment by Duskhaven** [comment]
Fixed.
