### ISSUE TITLE
M+8 Twine-Covered Bow (somewhat)worse than M+6.

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#531]
![image](https://user-images.githubusercontent.com/76977299/226550287-031ef34d-ed0d-45c4-994a-dc22abf77df6.png)
![image](https://user-images.githubusercontent.com/76977299/226550324-098b6959-7657-47f2-bf01-51e1fda81601.png)

**Comment by Duskhaven** [comment]
The S2 Bow offers additional shadow damage.
