### ISSUE TITLE
SFK+8 Completion notice Bugged

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#532]
After completing SKF+8 within the time limit no completion notice or rewards appear.
The timer keeps ticking after slaying the last boss.

This was run with the newest patch claiming to have this fixed.

Its not possible to get Keystone Mastery as well.

**Comment by Zuglifee** [comment]
This happened to me too.

No completion towards KSM Quest

**Comment by Duskhaven** [comment]
Cannot replicate
