### ISSUE TITLE
Single Minded Fury bugged

### ISSUE THREAD

**Issue by Kazzekk** [Duskhaven/Bug-Reports#539]
I've heard from multiple people that Single Minded Fury was bugged, and not granting what it actually says it grants. I've also heard that it is fixed, however after actually comparing with the stats that I have, I believe it to indeed be bugged. As for the damage and rage increase it gives, I'm not entirely sure, however the 4% haste bonus that the talent says that it gives does not apply(At least to my character sheet).

**Comment by Duskhaven** [comment]
Cannot replicate 

Without SMF 
![image](https://user-images.githubusercontent.com/123925176/226796851-f52035d5-e420-4c62-ba72-1c7a37317ca4.png)

With SMF 
![image](https://user-images.githubusercontent.com/123925176/226796884-9f47e666-85a3-44d1-82a7-9bf3865dd9f6.png)
