### ISSUE TITLE
Demon Hunter autoattack bug

### ISSUE THREAD

**Issue by DanskvandDH** [Duskhaven/Bug-Reports#542]
Demon Hunters seems to have autoattack issues since the new changelog. Cannot autoattack.
reload does not fix the issue

relog fixes the issue.

**Comment by Duskhaven** [comment]
Cannot replicate

**Comment by emilmajstro** [comment]
this is not a demon hunter issue, it happens on most melee characters, probably caused by a /startattack macro that is spammed or hit in the wrong timing/lag? making auto-attack to be stuck in attack animation and not working, relogging fixes it.
