### ISSUE TITLE
head slot appearance bug

### ISSUE THREAD

**Issue by clellbo96** [Duskhaven/Bug-Reports#543]
![WoWScrnShot_032123_213037](https://user-images.githubusercontent.com/128540472/226734358-a0568e19-582b-40df-abb3-32b266eb1356.jpg)

**Comment by LVCJS** [comment]
that's an item you're supposed to right click and learn. not sure if troll or just ..

**Comment by Duskhaven** [comment]
Fixed after restart. Make sure to update your patch.
