### ISSUE TITLE
Spark of Life

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#548]
Spark of Life does not Proc on Resto Shaman, I have spoken to a fellow healer (A holy Priest) and they said it procs and has 50%+ uptime.  Ive spent my entire mana bar on each spell (Chain Heal, Lesser healing wave, healing wave, tsunami, Lightning bolt, Lava burst, etc) and it has not procc'd once even though it clearly states it can proc on both Healing and Damage spells.

**Comment by Dova14** [comment]
An hpala has now confirmed they have a 98% uptime on it and even had another Rsham confirm it procc'd for them.  And an Rdudu also confirmed it doesnt proc for him

**Comment by Duskhaven** [comment]
Duplicate issue https://github.com/Duskhaven/Bug-Reports/issues/450
