### ISSUE TITLE
Warrior Rend and Trauma

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#549]
Thunderclap is applying rend without the Blood and Thunder talent acquired and Cleave is applying Trauma also without the talent acquired.

**Comment by Duskhaven** [comment]
Duplicate issue https://github.com/Duskhaven/Bug-Reports/issues/194

**Comment by ghost** [comment]
okay that was half of what i reported and you closed it, nice way to get me to not report bugs anymore.
