### ISSUE TITLE
Fire Elemental is immune to all Demon Hunter attacks

### ISSUE THREAD

**Issue by Kromster** [Duskhaven/Bug-Reports#55]
Hi so using Chaos strike and other Chaos attacks on the Entropic beast and Entropic Horror (Fire Elemental npcs) they are all immune to the damage 
![WoWScrnShot_030923_190235](https://user-images.githubusercontent.com/57280869/223972612-bbbcc79d-a6a0-4314-bf94-88ea95733dd0.jpg)

**Comment by Duskhaven** [comment]
Fixed.
