### ISSUE TITLE
Tank M+ Trinket

### ISSUE THREAD

**Issue by Calyxsys** [Duskhaven/Bug-Reports#553]
![Screenshot_3335](https://user-images.githubusercontent.com/128289362/226804214-9008dfce-34f3-42ab-9023-52f64e82bd53.png)
![Screenshot_3336](https://user-images.githubusercontent.com/128289362/226804221-9140cd6c-fdbe-4590-980e-ccf2e41fcc7a.png)

these are probably reversed, but woudlnt complain if the +8 was slightly better, 100 health that high to be fair

**Comment by Duskhaven** [comment]
Fixed.
