### ISSUE TITLE
Biznicks 247x128 Accurascope doesnt actually work

### ISSUE THREAD

**Issue by AdamLopez90** [Duskhaven/Bug-Reports#554]
Does not increased ranged hit rating at all.

**Comment by Duskhaven** [comment]
Cannot replicate 

Without
![image](https://user-images.githubusercontent.com/123925176/227700107-f37af7cc-44b9-49cc-afb3-c4bad63b0b13.png)

With
![image](https://user-images.githubusercontent.com/123925176/227700114-fc0c80c9-8327-4175-b856-fcff01d77ed6.png)
