### ISSUE TITLE
Hunter Bug

### ISSUE THREAD

**Issue by KhairianTV** [Duskhaven/Bug-Reports#555]
So, when you log into a fresh hunter you get books that will give you proficiencies in 1H Axes, Daggers, and Guns. When you learn these proficiencies, you are instead given plus to Herbalism, Specifically 451 +Herbalism.

Thank you for taking a look at this,
Khairian

**Comment by Duskhaven** [comment]
This is just a visual bug, your weapon skill is increased nonetheless
