### ISSUE TITLE
Mage-Talent: Precision/Arcane Focus wrong stats shown

### ISSUE THREAD

**Issue by Flex13** [Duskhaven/Bug-Reports#556]
![image](https://user-images.githubusercontent.com/127632931/226871034-60cf7ff7-6458-4252-ba67-138c2a32d0f4.png)
Changelog said 6%. It´s still the old value of 3%. Same for Arcane Focus I guess. Master of elements tooltip works.

**Comment by Duskhaven** [comment]
Fixed with the upcoming patch
