### ISSUE TITLE
Staff of the Explorer (S2) has a lower weapon damage than Staff of the Explorer +4

### ISSUE THREAD

**Issue by HipsterDragon42** [Duskhaven/Bug-Reports#561]
![staff +4](https://user-images.githubusercontent.com/128563963/226920693-447cc966-9a23-46e0-87a9-4df929de00a3.png)
![Staff S2](https://user-images.githubusercontent.com/128563963/226920696-afb0f550-1a7d-43fa-aec3-80414f0456c2.png)
As shown in screenshots, stats have properly scaled but the weapon damage has not, making it a worse weapon for monks despite being a 21 gear score and stat upgrade

**Comment by Duskhaven** [comment]
Fixed after restart.
