### ISSUE TITLE
Rogue Axe Proficiency Visual Bug

### ISSUE THREAD

**Issue by chtheiss** [Duskhaven/Bug-Reports#564]
My blood elf rogue does not have the axe proficiency trained but axes still show as if they are equipable. 
![image](https://user-images.githubusercontent.com/24509495/226973402-2de80df8-e423-4f52-889c-af8ec6496679.png)
![image](https://user-images.githubusercontent.com/24509495/226973737-c7913c3a-24ec-492e-9df1-4d4a6b496515.png)

**Comment by Duskhaven** [comment]
Cannot replicate 

![image](https://user-images.githubusercontent.com/123925176/227700064-0f86743e-888c-4f99-b78b-8f38d601bcbb.png)

**Comment by chtheiss** [comment]
It's not that you cannot train the axe proficiency. The issue is that the word `Axe` in the tooltip for the weapon should be red and not white to indicate that the proficiency is not trained yet.
