### ISSUE TITLE
Can't purchase druid T1 belt/bracer with Mark of the Raider

### ISSUE THREAD

**Issue by Blikey** [Duskhaven/Bug-Reports#567]
The only T1 druid belt/bracers you can buy from either T1 vendor are the custom ones that require base T1 items to buy

**Comment by Duskhaven** [comment]
This is intended. You can exchange the original t1 belts/bracers for the custom spec ones.

**Comment by Blikey** [comment]
The original t1 belt/bracers are not on the vendors is the point I'm trying to make
