### ISSUE TITLE
Improved Power Word: Shield talent 1/3

### ISSUE THREAD

**Issue by RaffClassic** [Duskhaven/Bug-Reports#568]
The Improved Power Word: Shield talent rank 1/3 shows that it buffs Power Word: Fortitude and increases stamina from 1 to 0%,
![image](https://user-images.githubusercontent.com/128628438/226984837-31bdec0f-55a1-4554-9349-e6f400e0bc99.png)

**Comment by Duskhaven** [comment]
Fixed with the next patch update
