### ISSUE TITLE
DH Form + Leeching Scoundrel

### ISSUE THREAD

**Issue by Calyxsys** [Duskhaven/Bug-Reports#570]
I've been doing a lot of testing trying to figure out why my DH form keeps getting removed, and i've narrowed it down to leeching scoundrel, whenever i get a deadly poison application, my character does a casting animation and my form is removed, I'm guessing the proc is considered "casting a spell called leeching scoundrel" which would also explain why my character has a casting animation when it procs.

**Comment by supxdz** [comment]
I believe DH is only supposed to use Combat or Sub spec

**Comment by Calyxsys** [comment]
might be true, but still wanna post and find out if this is intended

**Comment by Duskhaven** [comment]
Intended.
