### ISSUE TITLE
Legplates of Wrath

### ISSUE THREAD

**Issue by FeralHeistxd** [Duskhaven/Bug-Reports#571]
Legplates of Wrath should be also usable by warriors but they arent?
![image](https://user-images.githubusercontent.com/127445042/227003386-5f87ec36-197a-4cb3-80f5-d0d1ab1b281d.png)

**Comment by FeralHeistxd** [comment]
Also seems to be the problem with belt. Its probably the whole set.
![image](https://user-images.githubusercontent.com/127445042/227016740-608b3043-b4a4-4e63-8a02-8777b0ec7cd7.png)

**Comment by Chad-CL** [comment]
DKs and Warriors have separate "of Wrath" sets for some reason. This is different than the "of Might" T1 variants.

**Comment by Chad-CL** [comment]
My DK has a chestplate of Wrath just rotting because of that :(
