### ISSUE TITLE
monk currently has no s2 tier set

### ISSUE THREAD

**Issue by lolxd12345123** [Duskhaven/Bug-Reports#572]
if there is a monk set, neither myself or guildies who have been doing +8s weekly have seen a single piece drop

**Comment by poggaming123** [comment]
its demonfang s2 it just doesnt have monk included for some reason.

**Comment by poggaming123** [comment]
and im pretty sure the firestorm kick dot portion of demonfang s1 was a very very recent addition since it didnt even work until last week so that didnt even have anything for monk at first.

**Comment by lolxd12345123** [comment]
ye i have the s2 set atm aswell, rly hoping they just add monk to it instead of polluting the pool even more with a separate set

**Comment by Duskhaven** [comment]
Monk shares its T2 set with Shadow Priest

**Comment by lolxd12345123** [comment]
> Monk shares its T2 set with Shadow Priest

season 2, from +8. not t2 from ony and bwl
