### ISSUE TITLE
+8 Bow stats

### ISSUE THREAD

**Issue by PSIN-dev** [Duskhaven/Bug-Reports#578]
+8 Twine-covered bow needs its stats increased over +6 ty

**Comment by GoldWarr** [comment]
yeah the +6 Bow is better then the +8 Bow for some weird reason.

**Comment by Duskhaven** [comment]
The +8 bow makes up for it with the additional shadow damage

**Comment by PSIN-dev** [comment]
![kjbrah](https://user-images.githubusercontent.com/127295160/227700207-a298263c-dea8-44c8-9a2f-af52facffaca.PNG)
@Duskhaven my patch z is up to date and this is what i see
