### ISSUE TITLE
Flightpath from Ironforge to Menethil Harbor, Wetlands

### ISSUE THREAD

**Issue by Shqbruh** [Duskhaven/Bug-Reports#58]
So the gryphon starts flying backwards around the top of the icy mountain of ironforge. Then it starts flying in a straight line until it reaches Chillwind point, WPL. Then it turns around (180) and flies back into the mountain of ironforge before it then turns back onto the fp path to menethil harbor. This has happened twice now the two times ive flown to Menethil harbor.

**Comment by Duskhaven** [comment]
Duplicate Issue, please refer to https://github.com/Duskhaven/Bug-Reports/issues/17
