### ISSUE TITLE
Dh T2 3 peice 

### ISSUE THREAD

**Issue by BloodGH** [Duskhaven/Bug-Reports#581]
T2 3 set doesnt work for dh 
was able to get it to proc after removing my t1 then unequipping and reequipping my t2 without equipping any of my t1.
The problem is it procs the t1 dot and not a t2 one.
![35df895d3653894f205755379af8cf65](https://user-images.githubusercontent.com/128533810/227612003-0172ba55-ba33-44e6-b054-e91f8ce83880.png)

**Comment by Duskhaven** [comment]
It's the same bonus.
