### ISSUE TITLE
Giantstalker Set T1 Hunter/Tinker Bugged

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#582]
All of the Set piece effects are not working at the moment.

- 3 Piece Set effect: doesnt grant Wyvern Sting buff, Electrified Beacon doesnt strike two times
- 5 Piece Set effect : there is no increase in Pet Stamina also there is no 5% damage increase for Tinkers during Turret usage.
- 8 Piece Set effect : No damage increase for Volley or Multishots , no crit buff for poisoned harpoon no increase of bleed damage, no decrease of miss chance for Machine Gun.

Been darn long time had this set and still not working.

**Comment by AdamLopez90** [comment]
Wildfire cluster also does not empower your next raptor strike.

**Comment by Duskhaven** [comment]
Fixed.
