### ISSUE TITLE
Paladin skill "Charger" cannot be learned unless Journeyman Riding has been bought first

### ISSUE THREAD

**Issue by Buggyswires** [Duskhaven/Bug-Reports#583]
Learning the charger skill at level 40 costs 260G but it requires Journeyman riding to learn the skill
(the additional cost for Journeyman riding is 255g)

All other epic mounts are at 9G so i guess it was intended to get riding + the mount by learning the skill from the trainer.
Unfortunately it isn't possible to learn it because it requires the riding skill to learn the Charger skill.

Correct behaviour:
Either the cost should be comparable to the other epic mounts or the skill should be learnable and also give the Journeyman Riding

**Comment by elbrando91** [comment]
go do the quest chain, you get riding for free.. it should be an achievement to get the charger mount not just something you can buy from the trainer

**Comment by Buggyswires** [comment]
Ah, the quest chain works? I thought that one took even more gold 

Update: it does - for quest one 150G are needed

**Comment by Duskhaven** [comment]
Fixed after restart
