### ISSUE TITLE
Entangling Roots broken

### ISSUE THREAD

**Issue by ShukkaBogdi** [Duskhaven/Bug-Reports#590]
Entangling Roots are breaking every time I hit the mobs. I hit the mobs with a dagger, with a moonfire, with a wrath, with everything, everytime i have to cast wrath and then roots wrath and roots it's not normal. This bug is not present on retail or other servers! And don't tell me I have bad rng like in the in-game ticket, from 200 mobs damaged every time it breaks, I never saw it stay for 2 spells in a row not to mention more.

**Comment by Photonkannon** [comment]
Don't get mad. This is a work in progress. Try to report information so they can fix it. not feelings.

**Comment by ShukkaBogdi** [comment]
> Don't get mad. This is a work in progress. Try to report information so they can fix it. not feelings.

sry I got mad because of some GM vague response that I had bad RNG after doing some tests and writing in the ticket what I did.

**Comment by Duskhaven** [comment]
Cannot replicate
