### ISSUE TITLE
Leech Poison Crit Scaling bug. 100% crit chance at lvl 9.

### ISSUE THREAD

**Issue by gsagardia** [Duskhaven/Bug-Reports#592]
I'm an HC rogue, and I've died a few times. While leveling again, I got LP early and when questing noticed I crit A LOT when using it.

I checked with the Char sheet open and found I went from 2 Crit Rating to 48 Crit Rating, giving me an extra 89% chance to crit for a total of 100.70% Crit chance. (should be 15 + 89, but maths is hard)

I tried it again one level later and it was 100.32%

![WoWScrnShot_032323_153539](https://user-images.githubusercontent.com/10933340/227358067-2f515052-9649-43e2-b362-6b21ed41c4f5.jpg)

**Comment by Duskhaven** [comment]
Fixed after restart.
