### ISSUE TITLE
Power word shield ranking

### ISSUE THREAD

**Issue by ACFreeberg** [Duskhaven/Bug-Reports#599]
Power Word Shield: Rank 8 only offers 358 shielding as opposed to rank 7 that grants 573. Not sure about the actual value, if it might be weighted wrong or just a typo on the tooltip

**Comment by Duskhaven** [comment]
Rank 8 
![image](https://user-images.githubusercontent.com/123925176/227407823-1e1eb735-3a90-4d21-b73d-cecfed3d9997.png)

Rank 7
![image](https://user-images.githubusercontent.com/123925176/227407854-a2de249e-74ae-4cbf-a481-0e87f04a1a8b.png)

Make sure to update your patch
