### ISSUE TITLE
Wildfire Infusion not talentable

### ISSUE THREAD

**Issue by Karsenity** [Duskhaven/Bug-Reports#6]
Character Name: Fally
Talent ID: 81102
Issue: Within the survival hunter tree, even if you have the prerequisite talent Resourcefulness, you can't put points into Wildfire Infusion.

**Comment by Duskhaven** [comment]
There currently is a Visual Issue which does not show that you've picked the Talent.
Wildfire Infusion is still active nonetheless.  The Visual Issue will be fixed in a later patch.

**Comment by Karsenity** [comment]
This has continued to be referenced and I just wanted to comment and say this does not appear to be true. If you lock in this talent, it will immediately refund the point, and it can be spent elsewhere. HOWEVER, it is active for a singular trap (frost trap), even without having taken the talent. Other traps do not trigger it still.

**Comment by deadhill** [comment]
i havent even seen it active for 1 trap :D
