### ISSUE TITLE
Twine covered bow (S2) does not do 15-20 shadow damage even though tooltip says it should

### ISSUE THREAD

**Issue by martinus94** [Duskhaven/Bug-Reports#600]
It does not work on abilities or white hits. 
![image](https://user-images.githubusercontent.com/45718150/227421508-964ef177-78aa-4f02-8411-cd2ac372da75.png)

**Comment by Huntereye1** [comment]
This is a intended behaviour , the shadow damage is automaticly added towards the White hit. Please lookup next time intended client behaviour before embarrassing yourself.
