### ISSUE TITLE
Human Hunter Cannot Tame Beast

### ISSUE THREAD

**Issue by Fiffin** [Duskhaven/Bug-Reports#602]
I am a non-hardcore human hunter. I cannot tame lower level beasts after purchasing the Tame Beast ability from the hunter trainer - it simply says "Invalid Target" when I try.

![](https://cdn.discordapp.com/attachments/813092669848551505/1088711144149098557/image.png)

**Comment by Duskhaven** [comment]
Cannot replicate

**Comment by Fiffin** [comment]
I could make a video? What else do you need?

Cannot tame anything on my human hunter right now.

**Comment by Fiffin** [comment]
Think I've narrowed it down to some conflict with the Bartender4 addon.
