### ISSUE TITLE
New custom Elemental Shaman spells: increased crit dmg not applying (dealing 150% instead of 200%)

### ISSUE THREAD

**Issue by qbawu** [Duskhaven/Bug-Reports#604]
I am not sure if it's intentional or bug, but those spells could really use increased spell crit dmg from the ele spec. Elemental shaman rn is probably one of the least played spec in the game. 

Additionally, Great Sundering does not (ever) cause stun as per tooltip.

**Comment by Chromie-the-gnome** [comment]
Can Confirm

Great Sundering NEVER stuns and puts whole group/raid into combat bug.

Elemental Blast Is dealing 150% crit

**Comment by qbawu** [comment]
Both Great Sundering and Elemental Blast are dealing 150% crit.

I have not experienced combat bug for the raid so far when used in MC and BWL.

**Comment by Chromie-the-gnome** [comment]
Oh I def experienced that, ended up leaving the talent out till the bug is fixed.
Great sundering, soon to be earthquake, does combat bug to whole group/raid

**Comment by Duskhaven** [comment]
Fixed.
