### ISSUE TITLE
DH: When using Sprint, Fel Rush goes into CD as well, for the CD duration of Sprint (2 Minutes)

### ISSUE THREAD

**Issue by eteria27** [Duskhaven/Bug-Reports#605]
DH: When using Sprint, Fel Rush goes into CD as well, for the CD duration of Sprint (2 Minutes), instead of the 12 seconds CD.
In addition, using Fel Rush does not trigger the CD of Sprint.
Which of those is intended? Them both sharing CDs or not sharing? Either way, a fix is needed

**Comment by kskeensc** [comment]
Pretty sure this is intended to prevent abuse of mobility.  Especially since you have to drop stance to use sprint.  I do believe Fel Rush isnt intended to start sprint CD, but when you swap to use sprint it IS intended to give Fel Rush a cd.
