### ISSUE TITLE
shaman DW Flametongue weapon isnt working

### ISSUE THREAD

**Issue by th3spy** [Duskhaven/Bug-Reports#607]
shaman DW Flametongue weapon isnt working 

When DW and have flametongue one of them always doesnt work when it is ment too

**Comment by Phelp58** [comment]
i opened this last week and they said use seperate ranks, still doesn't work :/
it works on retail wotlk, and other p-servers but not here so idk if it's intentional or thought it was something else

**Comment by Duskhaven** [comment]
That's intended.

**Comment by Phelp58** [comment]
so u just killed an entire archetype...but support 2-handed enhance....WHY?!
