### ISSUE TITLE
Biznicks 247x128 Accurascope is bugged.

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#612]
This is an Engi item, it attaches a permanent scope on bow or gun and increases ranged hit rating by 30.

Put it on my Bow but my Hitrating didnt increase at all.

Please could i get a refund on this item?  i used it on my bow and this thing costed alot of gold for me.

**Comment by Duskhaven** [comment]
Works as intended.

Before 
![image](https://user-images.githubusercontent.com/123925176/227697383-de3a05ef-7908-4489-8540-3d27bdb9ca71.png)

After
![image](https://user-images.githubusercontent.com/123925176/227697401-ec1e8ee9-affd-475d-8fb8-dd0b5abd1628.png)
