### ISSUE TITLE
Might set (dps) set bonus missing damage

### ISSUE THREAD

**Issue by teachb02** [Duskhaven/Bug-Reports#614]
Warrior,dk t1 dps set Might 2 piece set bonus states 4% damage increase when runes are on cooldown but only provides 3%.
Also doesnt grant bonus damage for the full duration of the buff provided by set bonus( buff name: Advantage , duration:14 seconds) 3% damage drops around 7-8 second mark when buff is still up. Can see damage is lost in character damage tooltip    (Goes from 127% increased damage to 124% before buff ends )

**Comment by Duskhaven** [comment]
Fixed after restart.
