### ISSUE TITLE
Whale Insignia m+8 weak stats

### ISSUE THREAD

**Issue by Icebeam666** [Duskhaven/Bug-Reports#617]
For some reason whale insignia m+8 has same stats as whale insignia m+4, making it weaker than m+6 version
![image](https://user-images.githubusercontent.com/65196200/227664477-abefe18f-2c16-44d2-82e4-3e728e6e3297.png)

**Comment by Duskhaven** [comment]
![image](https://user-images.githubusercontent.com/123925176/227667026-eea33611-0063-4cf8-a5e5-6415cd1a6fdd.png)

Clear your cache
