### ISSUE TITLE
Paladin Issues

### ISSUE THREAD

**Issue by Jpar1** [Duskhaven/Bug-Reports#62]
- [x] Tauren Paladins don't get ress quest at level 10
- [x] Tauren Paladins have no weapon skill with any one-handed weapons (except for mace)
- [x] Tauren Paladins don't get Mass ress quest until level 60
- [x] Missing Paladin glyphs from vendors (Glyph of Flash of Light for example)
- [x] Tauren Paladin unable to leanr one-hand sword from Trainer (in Undercity) - See below for proof
- [x] Tauren Paladin's can't learn Seal of Corruption / Vengence from trainer  - See below for proof

**Comment by Jpar1** [comment]
![image](https://user-images.githubusercontent.com/52662978/224113378-1ae3164a-d225-4db4-aa4b-69e0e501496f.png)

**Comment by Duskhaven** [comment]
The Mass Quest is only available at Level 60, for any healing Class. 
They get their normal resurrection Spell upon character creation and from the Innkeeper in Orgrimmar.

**Comment by Jpar1** [comment]
![image](https://user-images.githubusercontent.com/52662978/224331584-21b43c4d-9483-4f88-b0dd-d80a1b618fa0.png)

For reference sake, Here is a pic while on a blood elf Paladin
![image](https://user-images.githubusercontent.com/52662978/224332719-fc8d3125-62de-4da1-b2ec-b02cd056ed4b.png)

**Comment by Duskhaven** [comment]
This is fixed with the next restart. Make sure to visit the Innkeeper in Stormwind or Orgrimmar.
