### ISSUE TITLE
Undead Hunter no weapon skill on some weapons

### ISSUE THREAD

**Issue by sergiulache** [Duskhaven/Bug-Reports#620]
For an undead melee hunter, using a weapon that's not in the weapon skills menu will result in missing all of your attacks.
Specifically, this seems to be a problem with the following weapons:

- 1H Axes
- Daggers
- Fist weapons

This basically means that the only usable 1H weapon is a sword. Every 2H weapon seems to work fine. Also, this may not be race specific, as by speaking to other hunters in-game it seems that the problem still occurs for other races.

**Comment by Duskhaven** [comment]
Use the weapon skill books from the innkeeper in org/sw
