### ISSUE TITLE
Tier 2 DPS Wrathful gear has same set bonuses as Tier 0

### ISSUE THREAD

**Issue by Kazzekk** [Duskhaven/Bug-Reports#621]
![image](https://user-images.githubusercontent.com/89116788/227689150-9e2af408-fa91-45c3-8b51-9c187eb7a70a.png)
![image](https://user-images.githubusercontent.com/89116788/227689162-7cf1f218-f183-434c-9045-9948f0fb38ab.png)

**Comment by Duskhaven** [comment]
visual bug. Tier 0 sets still offer the original bonuses
