### ISSUE TITLE
Quest: The Lich, Ras Frostwhisper

### ISSUE THREAD

**Issue by Buggyswires** [Duskhaven/Bug-Reports#625]
Problem:
Using the Soulbound Keepsake on Ras Frostwhisper doesn't transform him into human form

The quest ist not completeable.

**Comment by Duskhaven** [comment]
Visual Issue, head can still be looted 

![image](https://user-images.githubusercontent.com/123925176/227702051-57a5fcae-655e-420d-835b-4b288d19ba0c.png)

**Comment by Buggyswires** [comment]
Thanks for the info. I killed that guy 3 times using the Keepsake first and didnt check the loot once...
