### ISSUE TITLE
Tier 2 hunter set stats are scaled worse than tier 1 hunter stats and worse than other tier sets for other classes

### ISSUE THREAD

**Issue by AdamLopez90** [Duskhaven/Bug-Reports#626]
Tier 2 hunter set stats are sometimes worse than tier 1 hunter stats

Most other tier sets have around at 20-30% increase in stats and another 40-50% increase in 'green equipped ratings (crit/hit/etc)'

For tier 1 to tier 2 hunter set a lot of it is only 10% sometimes 5% or just straight up the same or worse (see tier 1 and 2 hunter boots for example)
![image](https://user-images.githubusercontent.com/9259615/227704878-d93f6aaf-4ddc-481a-b116-f22685152177.png)
![image](https://user-images.githubusercontent.com/9259615/227704885-5cdec439-bbdc-4764-b402-df576cc67eb3.png)

**Comment by Wafflfries** [comment]
I have noticed the same thing the gear is basically idenical with different set bonuses, I think the reason is because most BWL gear gives more INT taking up stat budges.
