### ISSUE TITLE
[Warrior T2] Wrath set is DK only, Warrior do not have a T2 tank set currently

### ISSUE THREAD

**Issue by Wheemix** [Duskhaven/Bug-Reports#627]
Item Name: Sabatons of Wrath
Zone/Area: Blackwing Lair
Screenshot/Video: 
![WoWScrnShot_032523_101608](https://user-images.githubusercontent.com/88062402/227708583-e6538b42-cd52-484e-84d6-512f6a981271.jpg)
Issue: The whole warrior tank set should be useable by warriors and death knights, for the DPS set this is actually the case. The tank set however can only be used by death knights so warriors currently do not have a full T2 set.

**Comment by Wafflfries** [comment]
Warrior tank have their own set i have seen the gear drop multiple times
