### ISSUE TITLE
Bonereaver's Edge's Armour Pen only stacks up to 2.

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#631]
https://youtu.be/_fp_12wHLT4

**Comment by Saddymosh** [comment]
@Duskhaven 
Why it was closed? 150 arpen is still far away from arpen cap, there is no items in game with arp except KSM trinkets. And even with this trinkets u can't go over 50%, arp works better at 90-100% cause low armor still gives a major of damage reduction. This two procs still loses to every weapon with decent damage and some dps stats like STR or AP. :c
