### ISSUE TITLE
Herioc BWL not open?

### ISSUE THREAD

**Issue by Wafflfries** [Duskhaven/Bug-Reports#632]
Last week and this week we have tried to enter Heroic BWL and could not (different errors depending on method), we tried many different solutions and after 2+hours of waiting for any GM help our tickets, we're ignored and in discord one GM said they didnt know if BWL H was open meanwhile Noxx told us it was. 
Solutions we tried, 
- running into BWL through UBRS (10herioc and 25herioc) this method kept tping us into Normal BWL 
- using the Orb (from attumement quest) the animation would happen on our bodies but we would not be TPed anywhere
-Reseting instances using ORB (this would sometimes take us to the instance on normal aswell)
-remaking party with someone with no lockout as the leader and reseting instances, (this made it so we could not interact with the orb)
-After remaking we also ran back to the raid through UBRS

**Comment by Duskhaven** [comment]
Fixed 
![image](https://user-images.githubusercontent.com/123925176/227770481-acb89460-71be-4ee8-a5b1-085a81085066.png)
