### ISSUE TITLE
Shadowstrike/Thunderstrike Proc/Transform missing

### ISSUE THREAD

**Issue by Huntereye1** [Duskhaven/Bug-Reports#637]
![WoWScrnShot_032523_225103](https://user-images.githubusercontent.com/109392926/227743945-8389f2c8-1568-4712-9fa0-6525e2a1eba4.jpg)

attempted over 1k hits, havent managed to get a proc. 
So missing onhit proc and missing transform to Thunderstrike.

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://user-images.githubusercontent.com/123925176/229314284-fd91d819-7781-4066-969d-149c5f3a8c89.png)

**Comment by Huntereye1** [comment]
u sure your using the Heroic version and not the Normal version? the normal version works fine, but not the Heroic.

**Comment by Huntereye1** [comment]
![WoWScrnShot_040323_100137](https://user-images.githubusercontent.com/109392926/229448208-37698050-adf5-4a97-8e68-2ef77e23d401.jpg)

Here again a retest, over 100 Autoattacks and 100 swipe/rake casts, still 0 procs, you have tested the "Normal version" not the shadow strike i posted aka Heroic. pls Recheck...
