### ISSUE TITLE
Launcher Crash report

### ISSUE THREAD

**Issue by Stvn-Johnson** [Duskhaven/Bug-Reports#639]
Launcher crashed while checking the patch 5 file for updates.
[crash.log](https://github.com/Duskhaven/Bug-Reports/files/11070345/crash.log)

**Comment by harukaze3** [comment]
Should be taken to the Launcher's GitHub. https://github.com/iraizo/duskhaven-loader/issues

> GM Haruka

**Comment by Stvn-Johnson** [comment]
Thought this was the github lol.  will  post there.
