### ISSUE TITLE
Quest: Rites of the Earthmother - missing Arra'chea

### ISSUE THREAD

**Issue by Donkey-ship** [Duskhaven/Bug-Reports#64]
Quest: Rites of the Earthmother - missing Arra'chea

The NPC Arra'chea is missing.

**Comment by Duskhaven** [comment]
![image](https://user-images.githubusercontent.com/123925176/224166427-142cd660-e06f-4f2b-aee0-f6740ce75b27.png)
The NPC wanders around in a huge Area.
