### ISSUE TITLE
Greataxe of the Warrior (S2) dps difference between OBSE (HC)

### ISSUE THREAD

**Issue by thrashbeer** [Duskhaven/Bug-Reports#643]
hello as the tooltip on greataxe of the warrior (s2) shows it is supposed to have an itemlvl of 73, these are the stats for that weapon.
![image](https://user-images.githubusercontent.com/128950992/227754620-03209f3b-8f81-466d-90a9-c243a8fec910.png)

now these are the stats of OBSE HC
![image](https://user-images.githubusercontent.com/128950992/227754651-84da15cc-2686-4cb8-88ff-d9315c1cfb33.png)

as you can see, even if s2 axe has 2 more ilvl then the obse sword, it has about 3 less dps then that sword which doesnt match at all, obse should have slightly lower dps or well the axe itself should have higher dps on it, quite a bit more infact

this is a weapon from BWL
![image](https://user-images.githubusercontent.com/128950992/227754700-dbb007cd-fab5-4b4c-8dd8-6b700b574be6.png)

it actually has the exact same itemlvl as the s2 mythic greataxe but it has significantly higher dps, so the mythic greataxe should either have its ilvl reduced or its dps increased if its supposed to match that itemlvl

**Comment by Icebeam666** [comment]
I noticed some of the mythic+ items have low weapon dps for their ilvl too, which is really strange considering wdps should follow ilvl in wrath. Great bug report hopefully this can be fixed.

**Comment by thrashbeer** [comment]
![image](https://user-images.githubusercontent.com/128950992/228396468-2b477f4d-a1b7-4b4d-a604-75d9957712b0.png)
![image](https://user-images.githubusercontent.com/128950992/228396500-f30d00da-db7d-4a08-bc6e-19864c570027.png)

yea there seems to be a dps discrepancy with custom-weapon dps and their ilvl in general if you look at these 2 weapons there from the mythic+ vendor

also again look at the difference between the +6 axe and the +8 variant and notice how little of a dps jump it is in comparison to its ilvl jump 

![image](https://user-images.githubusercontent.com/128950992/228396708-793961e4-97a6-480c-990f-3b4f7d2fdefb.png)
![image](https://user-images.githubusercontent.com/128950992/228396723-4074a196-b969-4703-915f-4ac896cd692a.png)
