### ISSUE TITLE
Whitename scarlet monastery won't revive

### ISSUE THREAD

**Issue by Rainwors** [Duskhaven/Bug-Reports#647]
I am shaman, set my totems on the boss fight. tremor totem - magma totem - mana spring totem - windfurry totem
We reduced the hp of whitename to start the sequence
She sleep our party
My magma totem still hitting Whitename and she stopped casting revive
We lost the effect of sleep and she was invencible because she didn't revived the knight
Then i exit the dungeon and she reset.

There is no big issue with this bug, but still exist and maybe is easy to solve.

**Comment by Duskhaven** [comment]
This happens when she is taking too much damage. Health increased with the next restart.
