### ISSUE TITLE
Dancing Rune Weapon still broken

### ISSUE THREAD

**Issue by Saddymosh** [Duskhaven/Bug-Reports#653]
Only appears a debuff on target, there is a screenshake and 0 damage :D Im not sure, but if we can do something about DPS Blood DK, we can just rework this tallent. Tanks don't need it at all and also u can't release its potential cause there is no Empower Rune Weapon as DPS . Even with glyph that makes it lasts 17 sec u can't do burst cause u have no runes, other classes can burst with all of their CDs.

**Comment by Saddymosh** [comment]
Tested in +8 keys

**Comment by Saddymosh** [comment]
Maybe make it passive like it have a chance to double your abillity which triggers effect. Idk what about a chance, probably 30% with normal damage or 40-45% with a half.

**Comment by Duskhaven** [comment]
Works fine on everything except training dummies

**Comment by Saddymosh** [comment]
It casts spells by its own rotation, like pet with skills, but it should copy cast on your cast

> Works fine on everything except training dummies

**Comment by KreepAK** [comment]
> Works fine on everything except training dummies

It is not working fine

**Comment by Saddymosh** [comment]
> > Works fine on everything except training dummies
> 
> It is not working fine
> 

They don't want blood live as dps, so i leaved server a month ago :D got pretty decent dk with +8 keys gear and Bonereaver Edge( Weapon is broken too,lmao)
