### ISSUE TITLE
full inventory opening things

### ISSUE THREAD

**Issue by valsekamerplant** [Duskhaven/Bug-Reports#654]
if you have a full inventory and open a clam it will remove the clam from your inventory and say your inventory is full. No return of the clam or its contents.

Also had that problem when trying to go kill a mob for a key to get a medalion out of a chest. The key was removed but my inventory was full so the contents of the chest was not transfered. After removing an item it said i did ot have te key to open it. So i had to wait for the mob to respawn to get the key to open the chest.

**Comment by Duskhaven** [comment]
Lost items should always be in the mailbox after a few hours
