### ISSUE TITLE
Holy Power Not Generating

### ISSUE THREAD

**Issue by Calyxsys** [Duskhaven/Bug-Reports#658]
sometimes if I use holy shield immediately after hammer of the righteous I do not get holy power, you can see in my screenshot i have 2 holy power, so hammer takes me to 3, and i proc the Holy nova, then Holy shield SHOULD put me back to 1 holy power, but you can see on my buff bar it does not. 
![Screenshot_3361](https://user-images.githubusercontent.com/128289362/227798446-d8c78b12-6212-433e-a92d-c8dd4e59c707.png)
![Screenshot_3362](https://user-images.githubusercontent.com/128289362/227798458-5c968e84-e410-443c-bad0-7e8743307339.png)
This isn't happening EVERY time, but its happening more often than not

**Comment by Duskhaven** [comment]
Holy Power has a ICD of 1 second.
