### ISSUE TITLE
Divine purpose 

### ISSUE THREAD

**Issue by Lightsduty** [Duskhaven/Bug-Reports#661]
On the website under paladin changes it states divine purpose in increases hit chance by 3% : 
"- Divine Purpose (Talent) Teaches you how to wield two-one handed Weapons and increases your hit chance by 3%. "
This is not the case and we are not received any hit % 
This is a very important change that should be included so that dual wield paladins can achieve soft hit cap.

**Comment by Duskhaven** [comment]
Hit Rating from talents are not visually shown in the character sheet.

**Comment by Lightsduty** [comment]
So you can confirm 100% we get 3% hit from DP and 2% from radiance aura ?
