### ISSUE TITLE
Holy Paladin and Unholy DK

### ISSUE THREAD

**Issue by midsu45** [Duskhaven/Bug-Reports#662]
Not sure if intended or not but Unholy DK is doing up to 3k ST DPS (not burst) and Hpaladin is healing for nearly 2k HPS. Im not sure if its some weird interaction with death coils for the DK, but it seems very buggy if other classes, especially ranged, do significantly less. Hpaladin seems to have a bug with beacon of light thats making them heal alot extra. If this intended then thats cool, but balancing content around 1-2 specs doing 3k DPS and 2k HPS seems a little bit crazy considering most classes cant do that, and we only have 10man raids. If these are not bugs and dont need fixing, then at least buff the other classes to be competitive. 

Beacon of light paladins are just basically auto attacking the boss and almost tripling other heals HPS. Its not a good design to basically be required to bring one and an unholy dk or generally a melee class to clear content. 

Most people have cleared heroic mc and such, but heroic bwl progression is literally dictated by which op classes u bring to the table, and it ruins the fun of the game especially when its unknown if thats bugged or those classes are meant to be significantly better.

**Comment by supxdz** [comment]
Why dont you losers bring those classes to HC BWL and stream it? Id love to see it!

**Comment by Bradeyxz** [comment]
You're in a 3.3.5 client where hpaladin always reigned paladin doesn't have any abusable bugs on holy atleast it has more bugs then anything

**Comment by midsu45** [comment]
> 

Why would I bring those when I can clear it without :)

**Comment by midsu45** [comment]
Keep acting like 2k HPS when other healers do like 1k or less is normal, id love to see you clear once without abusing something

**Comment by Wafflfries** [comment]
you are lost if u think hpal is OP

**Comment by supxdz** [comment]
Arth is such a salt lord lmfao, why don't you start clearing endgame content with the worst classes possible. Sounds like you are a pro already.

**Comment by Bradeyxz** [comment]
So disc priest and resto shaman are also broken by those standards right?

**Comment by midsu45** [comment]
Funny you assume who I am, and we are clearing without meta classes :), dont worry, dont need your permission. 

If you think beacon of light being bugged isnt broken, then ur literally delusional, same with tinker dmg pre-nerf, which is why it got nerfed ;) lmao

**Comment by supxdz** [comment]
How many bosses have you cleared in HC BWL?

**Comment by Wafflfries** [comment]
wait so the guy says that the content is required to bring those op classes, then says he clears it without them

**Comment by midsu45** [comment]
Damn did you ask the entire Effort guild to come shit post? Must be really desperate not to get nerfed

**Comment by Kromster** [comment]
no you just make stupid posts mate its not healthy for the game watch my vod for our first heroic Rag kill find any abuse there from my guild we dont raid till the weekend otherwise we would be in BWL H aswell just think about what you are posting about first my man....

**Comment by Wafflfries** [comment]
im just streaming the content as you know and my chat is doing what they want I have not said anything to chat to have them attack you there is no point

**Comment by supxdz** [comment]
Don't worry we have multiple classes geared at 60, we will always have the best comp possible.

**Comment by midsu45** [comment]
> no you just make stupid posts mate its not healthy for the game watch my vod for our first heroic Rag kill find any abuse there from my guild we dont raid till the weekend otherwise we would be in BWL H aswell just think about what you are posting about first my man....

I mean my first post was about tinker nerf and it got nerfed, so idk if its stupid or you just dont agree :)

**Comment by supxdz** [comment]
Nah your just a salty backseat gamer watching the real players clear content, and your so mad we are clearing it you just the top two people on the meters.

**Comment by midsu45** [comment]
> Nah your just a salty backseat gamer watching the real players clear content, and your so mad we are clearing it you just the top two people on the meters.

If that makes you feel important <3

**Comment by Wafflfries** [comment]
the only thing we argued about on the tinker post was u invalidated our kill saying we purposely abused tinker and its impossinble without it

**Comment by Bradeyxz** [comment]
it just had over scaling on their 1 ability and tinkers still do fine enough damage. Holy Paladin always has been a good healer in wotlk content and they have severe mana issues unless they have decent raid buffs and even then they still have issues they always been insane tank healers because of holy light beacon works as intended equal to any other client. There's around 3 to 4 talents in holy paladin doesn't even work even their best custom talent that's 5% dr and resistances doesn't work on anyone but the caster. Blasting healing into someone and especially on a fight like vael someone just spamming holy light is always gonna b insane especially as solo healing the fight when they have permanent resource gain

**Comment by Duskhaven** [comment]
There seems to be a Issue with the HC Sigil that increased the dmg by too much, it's fixed after the restart.
