### ISSUE TITLE
S2 Glaives (Nefarion) cause Demon Hunter to no longer generate Fury 

### ISSUE THREAD

**Issue by plasma-93** [Duskhaven/Bug-Reports#663]
My character is broken, I do not know what is causing it.

I cannot generate fury stacks and subsequently proc inner demon

I tried relogging, dying, and respeccing, changing dual specs, taking off all gear and putting it back on, and beating my head into a wall

Worked fine yesterday, not sure what happened, Noticed I was doing less damage today during raids and looked into it later in the day. 

Things I did before noticing it: Couple +8's, AOE farmed some dungeons, BWL, MC HC up until Rag
Character Name: Plas

**Comment by plasma-93** [comment]
Talked to some GM's, and they gave me the previous glaives, it's apparently because the Nefarion reward glaives don't allow you to generate Fury

**Comment by PlasmaPunch** [comment]
![image](https://user-images.githubusercontent.com/38546519/227814206-da190b06-7d3d-4687-b341-e4300497039a.png)

**Comment by plasma-93** [comment]
![image](https://user-images.githubusercontent.com/38546519/227814603-772f32b1-b0d3-4aa1-b22c-440b11b121c2.png)
![image](https://user-images.githubusercontent.com/38546519/227814621-48aac13d-ed39-43f7-a858-44effd28b510.png)
 These are the troublesome glaives

**Comment by Duskhaven** [comment]
Fixed.
