### ISSUE TITLE
Gnomish Battle Chicken never procs

### ISSUE THREAD

**Issue by Icebeam666** [Duskhaven/Bug-Reports#672]
As the title says, the item Gnomish Battle Chicken (https://www.wowhead.com/wotlk/item=10725/gnomish-battle-chicken) never procs. Some info:
I have engi at 315 (gnome bonus) which puts the chicken to level 63 since it scales with level
I have had it hit target dummy many, many times for its full 1.5 min duration.
I have also tried everything in this video https://www.youtube.com/watch?v=TSywF4MrPBQ&ab_channel=SimonizeShow
However, I am yet to see it ever proc its Battle Squawk aura (https://www.wowhead.com/wotlk/spell=23060/battle-squawk)

My suggestion would be to simply have it automatically proc the aura as soon as the chicken is used, as I have seen it work like that on other 3.3.5 private servers and it is way easier like that. Or, you could just give it a % chance to proc on hit when the chicken attacks. Either should be pretty easy to do I think (?). Either way, not having the item work really sucks.

**Comment by Duskhaven** [comment]
Fixed.
