### ISSUE TITLE
Holy Nova Rank 5 has less healing than Rank 4

### ISSUE THREAD

**Issue by AmphitheaterOfAnguish** [Duskhaven/Bug-Reports#676]
![image](https://user-images.githubusercontent.com/94326110/227852859-3d597cd6-64ab-460d-8aae-16ff1e5dfd9d.png)
Rank 5: 71-109 healing
![image](https://user-images.githubusercontent.com/94326110/227852937-e4ad782c-244a-4196-a125-d1958b170bc1.png)
Rank 4: 171-199 healing

currently I am using Rank 4 instead of rank 5 during dungeons because the healing is 100 more than the higher level version. I dont see how this could be intended.

**Comment by Duskhaven** [comment]
Fixed after restart
