### ISSUE TITLE
Cluck! Quest Bugged

### ISSUE THREAD

**Issue by Landengen** [Duskhaven/Bug-Reports#679]
The (somewhat) hidden quest of Cluck! has the issue of not letting you turn it in. You start the quest by repeatedly performing /chicken around a chicken and it eventually prompts you with "Chicken looks up at you quizzically. Maybe you should inspect it?" at which point it gives you the quest to return to it with Saldean's Chicken Feed (bought from the NPC Farmer Saldean). However, when performing it again several times to make the chicken into a quest giver/turn in, it does not turn into a turn in point. I did this several times and it only ever lets me accept the quest, and will not turn into a turn in point once I have it. Once it is turned in the chicken is supposed to lay an egg on the ground that you can loot for the pet "Westfall Chicken".

**Comment by Duskhaven** [comment]
There is another emote that has to be performed after you took the quest, this will instantly make him friendly.
