### ISSUE TITLE
Talisman of Binding Shard not dealing passive 25 nature damage to attacker for Demon Hunters

### ISSUE THREAD

**Issue by NwahDuskhaven** [Duskhaven/Bug-Reports#680]
Currently demon hunters do not benefit from the "when struck in combat inflicts 25 nature damage to the attacker." it seems to be overwritten by the damage caused by "fel energy" which isn't listed in that spells description.

**Comment by Duskhaven** [comment]
Intended.

**Comment by Khano11** [comment]
The fact this this is intended is a joke.
