### ISSUE TITLE
Prayer of Healing Ranking (same problem with Holy Nova)

### ISSUE THREAD

**Issue by KhairianTV** [Duskhaven/Bug-Reports#681]
![image](https://user-images.githubusercontent.com/128581470/227988544-6c111b2a-ddef-42a9-9f4b-ec85d82bcf98.png)
![image](https://user-images.githubusercontent.com/128581470/227988602-7461c0b0-36f2-4dd8-a118-5082a2ae2d22.png)
So the top image is Prayer of Healing rank 2 while the bottom one is rank 3. Rank 2 heals for quite a lot more than the 3rd.

**Comment by Duskhaven** [comment]
Update your patch
