### ISSUE TITLE
Hunter Pet "Evading"

### ISSUE THREAD

**Issue by Turtadray** [Duskhaven/Bug-Reports#683]
My pet wolf will "evade" buffs from myself gaining no benefit, these buffs range from Spirit Bond to Bestial Wrath. This buff is happening between multiple pets, within and outside of instances, and persists after dismissing and recalling a pet

**Comment by Duskhaven** [comment]
Duplicate issue, https://github.com/Duskhaven/Bug-Reports/issues/273
