### ISSUE TITLE
aspect of the beast does not properly give the AP to your tamed pets, 

### ISSUE THREAD

**Issue by SimplyCatt** [Duskhaven/Bug-Reports#685]
Also pets not not get affected by some raid wide buffs like kings, Bshout and etc. i do not know the full list of buffs that pet does not get affected by but it is quite abit. and its abit sad from a BM hunter's perspective, there is also just something going on with pet AP scaling in general i do again not know what exactly but my pet will at time have 390AP which is WAYY lower than it should compared to its scaling and other times have its normal 655AP even tho nothing has changed. at first i thought it was a pet happiness bug or something of the like. but it does not seem to be.

**Comment by Duskhaven** [comment]
It's only 10% for Pets, not 25%
