### ISSUE TITLE
Moonglade Set: (2) Set Bonus Bug

### ISSUE THREAD

**Issue by Trentmahalla** [Duskhaven/Bug-Reports#687]
For the restoration part of the set  `Rejuvenation ticks grant 3 Spell Power stackable up to 8.` It seems the Rejuvenation ticks are only granting 2 spell power each stack.

![image](https://user-images.githubusercontent.com/47612241/228117668-ec6b8508-b35c-4634-b87b-8e2a43c361d3.png)
![image](https://user-images.githubusercontent.com/47612241/228117715-631efb5a-849c-48b9-9350-2dc23c7fc2bf.png)
![image](https://user-images.githubusercontent.com/47612241/228117750-f1bb7914-6f06-4d18-889e-37df39daeefb.png)

**Comment by Duskhaven** [comment]
Fixed after restart
