### ISSUE TITLE
[Warrior Fury Talent] Single Minded Fury Slam does not hit with off-hand

### ISSUE THREAD

**Issue by Neverlight-Jyria** [Duskhaven/Bug-Reports#69]
Single Minded Fury when the Bloodsurge is active it does not trigger a off-hand attack

**Comment by Duskhaven** [comment]
![image](https://user-images.githubusercontent.com/123925176/224164760-8782df3e-0157-48f6-92b1-d4aeda1fc683.png)
Works without issues.
