### ISSUE TITLE
Pet Happiness

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#698]
Pet Happiness/Loyalty is supposed to be a deprecated feature on Duskhaven, however pets seem to lose damage the longer you "aren't feeding them". Using Feed Pet will prompt an error message, saying your "Pet doesn't like that Food", while using the correct food(in my case: meat for Cat).

**Comment by Duskhaven** [comment]
The Happiness/Loaylty System wasn't removed until cataclysm.
