### ISSUE TITLE
Tinker can not properly do Gnomeregan Dungeon

### ISSUE THREAD

**Issue by Thickmonty** [Duskhaven/Bug-Reports#70]
I qued up for random dungeon finder and though I was teleported to gnomregan I was not in phase with the gnomregan as a dungeon I was in phase with gnomer like I was still doing the quest line reclaime gnomregan . Though I could still get XP from the people my group killed and was able to roll on the items I was unable to see my group member also unable to see any foes along with unable to see any of the boxes I needed for the gnomeregan quest.

**Comment by Duskhaven** [comment]
This is intended, Tinkers cannot participate in the actual Dungeon as it is their "Class Hall"
