### ISSUE TITLE
Rogue Bloodfang 3set Not working

### ISSUE THREAD

**Issue by Kromster** [Duskhaven/Bug-Reports#700]
Hey so just noticed the 3set from my Bloodfang T2 says Increases your energy limit by 20 but in fact it only grants 10 energy
![WoWScrnShot_032923_063919](https://user-images.githubusercontent.com/57280869/228362272-8981d92b-591d-4158-a3bb-2cd35d742644.jpg)
![WoWScrnShot_032923_063934](https://user-images.githubusercontent.com/57280869/228362300-01d0daf6-ae53-4c80-a65a-25880058d777.jpg)

**Comment by Kromster** [comment]
Also the bonus energy doesnt stack with Vigor Glyph or Vigor Assassination talent

**Comment by Duskhaven** [comment]
Fixed
