### ISSUE TITLE
Alliance quest - The Attack!

### ISSUE THREAD

**Issue by Raulfin** [Duskhaven/Bug-Reports#702]
Quest 'The Attack!' (434)
-Only the person who starts the rp event, by talking to Tyrion (7766) and accepting it, gets credit for the 'Overhear conversation' objective. Anyone who accepts the quest via the 'n% is starting the quest, do you wish to join' popup will not get credit. -possible the player is marked as watching the meeting as soon as the rp starts, and only the starting player is on the quest at that time.
-If totems are out at the end of the conversation the 2 npcs will reset as soon as they become hostile.
-If the quest is started after the npc's despawn Lescovar (1754) takes longer to respawn than Spybot (8856), this causes the quest to softlock during the rp and the unspawned Lescovar doesn't begin to walk to the meeting area.
-The quest can be started before Spybot respawns, instantly softlocking the quest.

**Comment by Duskhaven** [comment]
Fixed after restart
