### ISSUE TITLE
Can't get the game to launch

### ISSUE THREAD

**Issue by Apocalyps0** [Duskhaven/Bug-Reports#703]
I downloaded (and later redownloaded) all files/patches and double checked that I followed all steps to connect. I am able to log in and create characters. However, when I click to launch after choosing my character, the launch screen sits there and stops responding as soon as the loading bar fills. I've tried redownloading everything, restarting my computer, and anything else I could think of and still am having the same issue.

**Comment by Duskhaven** [comment]
Please ask for support on our Discord
