### ISSUE TITLE
toggle stance macro command not working

### ISSUE THREAD

**Issue by Raulfin** [Duskhaven/Bug-Reports#706]
For stances that can be toggled on/off, like pally aura, druid forms, and war stances, macro's can use a not command '/cast **!**Cat Form(Shapeshift)' the ! tells it to cast the ability if it is not on and not to remove it if it is on. Currently the cat form macro example is both removing and recasting cat form when used while in cat.

**Comment by harukaze3** [comment]
This is easily solved by using the [nostance:x] conditional.

> GM Haruka
