### ISSUE TITLE
Runed Copper Bracer bug

### ISSUE THREAD

**Issue by Riecheck** [Duskhaven/Bug-Reports#707]
![wow bug 1](https://user-images.githubusercontent.com/129243121/228409507-8ecdb32e-553d-497d-9737-f17716bf541d.PNG)

Runed Copper Bracers doesn't show up in the Blacksmithing tradeskill window but becomes a general character skill instead

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/218

**Comment by Jalamin1** [comment]
Did they ever tell you what is the deal with this and what will be done about it, if anything?

**Comment by Riecheck** [comment]
No, still not resolved but he closed out my ticket
