### ISSUE TITLE
Flametongue ICD and improper stacking

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#708]
How its supposed to work:  Flametongue weapon is supposed to have 0 ICD (If we go off of other WoTLK cores) or a 0.01 ICD when using same spell rank flametongues (But the ICD is removed if you use 2 different spell ranks like in classic)

How its working:  Flametongue weapon has at least a 2 second ICD, resulting in missed Flametongue procs if your weapon speed goes below 2 seconds

This is harmful to enhancements as with procs my off hand can go as low as 1.3 speed, resulting in me missing multiple flametongue procs throughout a fight

https://imgur.com/a/CUbLNqP

Also Note:  Applying a 2nd Flametongue after applying your first, does nothing.  You do not gain the 2nd Flametongues SP nor will it proc.  This may be the cause of what I found above.  If you apply a rank 5 Flametongue after rank 6 (while dual wielding) only the last one you applied will take effect.

**Comment by Dova14** [comment]
My warcraft logs showing that my Flametongue is supposed to have 0 icd and stack together
https://classic.warcraftlogs.com/reports/8dDgq79AHxBCbPQa#fight=25&type=damage-done&source=20 (add together Stormstrike, lava lash, and melee connect hits, they will equal Flametongue hits, Flametongue uses was rank 9 + Rank 10 so downranking was used)

**Comment by Duskhaven** [comment]
Spellhance will receive a rework later on.
