### ISSUE TITLE
Feral Spirits + Magma totem hit

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#709]
How its supposed to work:  magma totem is supposed to go off your spell Hit and Feral Spirits are supposed to go off your melee hit for both their hit and expertise

How its working:  Both magma totem and feral spirits are not taking into account your hit resulting in magma totem having 17%+ miss rate and feral spirits getting missed 8%+ and dodged

https://imgur.com/a/J2cX4bg
In this imgur im melee hit capped, spell hit capped, and expertise capped but yet both are missing.  This is an issue as both are integral to an enhancements dps

**Comment by Dova14** [comment]
my logs from classic showing that they are affected by character sheet hit
https://classic.warcraftlogs.com/reports/8dDgq79AHxBCbPQa#fight=10&type=damage-done&source=20 (Shows feral spirits)
https://classic.warcraftlogs.com/reports/8dDgq79AHxBCbPQa#fight=25&type=damage-done&source=20 (Shows Both feral spirits and magma totem)

**Comment by Dova14** [comment]
Also Note Magma totem is not gaining your spell crit either

**Comment by Duskhaven** [comment]
This was related to the Dummy level beeing higher then intended.
