### ISSUE TITLE
Flurry grace period (Enhancement)

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#710]
How its supposed to work:  Flurry will only consume 1 stack per auto round if both autos connect within 0.5 of each other.  So as long as Auto 2 hits within 0.5 of the first auto, only 1 stack will be consumed

How its working:  No matter the speed you swing at, even if they are same speed.  Each auto will eat 1 stack of Flurry, severely reducing flurry uptime and nerfing dual wields dps.  

Proof:  Multiple guides state it, especially in classic wotlk "Due to [ Flurry](https://www.wowhead.com/wotlk/spell=16284/flurry) having a 0.5 seconds cooldown on being consumed, having weapons of matching speed is very important in order to minimize attack desynching and maximize your Flurry uptime. Most of the main-hand (MH) and off-hand (OH) weapons we list below have similar speeds and weapons with the same speed are meant to be used together, whenever possible."

https://www.wowhead.com/wotlk/guide/classes/shaman/enhancement/dps-bis-gear-pve-phase-2  (From here, at weapon section)

**Comment by Duskhaven** [comment]
Fixed.
