### ISSUE TITLE
Using Demonic Empowerment increases the cast time of Soul Fire

### ISSUE THREAD

**Issue by sfnjnz** [Duskhaven/Bug-Reports#715]
Using the talent Demonic Empowerment (did the test with Felguard out) makes Soul Fire go from 4.0s base casting time (with Bane talent for the 2s reduction in cast time) :
![image](https://user-images.githubusercontent.com/61242714/228577201-7bf5fa20-faab-4c17-9a9c-88813dae75d4.png)
to 4.4s base casting time : 
![image](https://user-images.githubusercontent.com/61242714/228577495-db99443b-6f3e-446c-a226-10da4a308224.png)
the cast time then stays at 4.4s for the rest of the play session.
the cast time goes back to 4.0s after a relog

**Comment by Duskhaven** [comment]
Bane (Rank 4) is passively activated if you use Demonic Empowerment. You do not need to spec into it as a Demo
