### ISSUE TITLE
Elemental shaman talent tree is broken!

### ISSUE THREAD

**Issue by vekras** [Duskhaven/Bug-Reports#717]
since the rework of the talent trees - ele shaman can not acces the the next row of each tier  even after spending talents on the ''new'' talents, this means that we can only place 1/5 points in shamanism affectly meaning we are 5 points short, a free talent respec/ reset the cost would be great to counter spending another 'x'g on a reset

**Comment by Darrendarle** [comment]
Ancestral knowledge still counts as Enhance atm. Meaning putting points in it actually opens up the 2nd row of Enhance talents instead.
