### ISSUE TITLE
Shaman talents broken

### ISSUE THREAD

**Issue by Sumsura** [Duskhaven/Bug-Reports#718]
I just did a respec on my dwarven shaman. now I can't put any talents into any tree and another note i only had 9 talent points at lv 21 before. I love this game but with the changes I worry about my other characters.

**Comment by Darrendarle** [comment]
It's just that the talents that got moved around are still counting toward their previous areas. like Ancestral Knowledge counting as Enhance and not Elemental. The restart coming up should fix it.

**Comment by Darrendarle** [comment]
Looks like the reset did fix it.
