### ISSUE TITLE
Holy Shock Healing Rank 2 stronger than Rank 3

### ISSUE THREAD

**Issue by XaanFX** [Duskhaven/Bug-Reports#719]
Holy Shock at rank 2 is stronger than the rank 3 version of this spell, but obviously rank 3 is supposed to be much stronger than rank 2. The damage has increased but the healing of rank 3 is less than rank 2.

Rank 2 of Holy Shock:
https://www.wowhead.com/wotlk/spell=20929/holy-shock ; 644-696 Healing

Rank 3 of Holy Shock:
https://www.wowhead.com/wotlk/spell=20930/holy-shock ; 845-915 Healing

![HolyShock3](https://user-images.githubusercontent.com/73441348/228608231-4798ebb4-ef48-4282-be19-88610eb038c6.PNG)
689-769 Healing (Rank 3)
![HolyShock2](https://user-images.githubusercontent.com/73441348/228608238-89ae8073-cf39-47bc-aaab-63db75ebe49c.PNG)
721-780 Healing (Rank 2)

**Comment by Duskhaven** [comment]
Fixed after restart
