### ISSUE TITLE
Hunter tier 2 gear not giving a 2/6 set bonus

### ISSUE THREAD

**Issue by AdamLopez90** [Duskhaven/Bug-Reports#725]
Tier two enhancement shaman gives shadowcraft 2 and 6 set bonuses and yet hunter tier gear doesnt get 2/6 set bonus? Is this a bug or intended? Hunters should probably gain the expertise from somewhere to not have to always wear low ilvl rare gear for the entire expansion ;).

**Comment by Duskhaven** [comment]
T2 Hunter only gives set bonuses at 3/5/8 pieces
