### ISSUE TITLE
Elemental Devestation 3/3 problem not giving 9% melee crit

### ISSUE THREAD

**Issue by N1V1** [Duskhaven/Bug-Reports#726]
Elemental Devestation 3/3 only grants 6% melee crit instead of 9%

**Comment by Dova14** [comment]
Note:  Elemental devestation DOES give 9% (went from 26% crit to 35% crit), I just tested it as dual wield, for 2h it may be bugged where you only receive the 6% from the 2h talent instead of the 9% from the actual talent
