### ISSUE TITLE
Fire Blast Buff and Master of elements bug

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#731]
Hey there!

Master of Elements isn't giving any hit chance at all. After testing on target dummy with effective 18% hit, some spells missed.

Also Fire Blast buff for 20% crit lasts 3 seconds instead of the 4 seconds its showing on the tooltip.

Thank you!

**Comment by Duskhaven** [comment]
Fixed.

The Fire Blast buff does last 4 seconds, however it can be increased to 4,5 if neccessary.
