### ISSUE TITLE
Engineering icon not showing

### ISSUE THREAD

**Issue by Mapox69** [Duskhaven/Bug-Reports#736]
Icon of engineering does not show. It is transparent in spellbook and actionbar.

**Comment by Duskhaven** [comment]
Update your patch
![image](https://user-images.githubusercontent.com/123925176/228680062-15ed0e05-4734-4335-8e4e-d1521b98ad57.png)

![image](https://user-images.githubusercontent.com/123925176/228680112-010b06e3-e07b-4470-8126-d0c41b672ddf.png)
