### ISSUE TITLE
Infernal Felfire

### ISSUE THREAD

**Issue by midsu45** [Duskhaven/Bug-Reports#745]
Not sure if intended, but it doesnt seem to factor for Ruin or Devastation talents after some testing. It currently does around 20-25% of incinerates damage (which is still pretty huge), but im not sure if thats intended since it was mentioned it would do about 60%. The current damage of it is more than fine though. If its not intended to factor Ruin and Devastation, thats fine too, but thought id point it out.

**Comment by Duskhaven** [comment]
Intended.
