### ISSUE TITLE
Red Curtain-ish visual bug; especially bad for Humans/in Elwynn Forest

### ISSUE THREAD

**Issue by takatakiful** [Duskhaven/Bug-Reports#75]
![Screenshot 2023-03-09 at 20 33 07](https://user-images.githubusercontent.com/127442920/224135442-1baa102b-511a-4714-9299-52db2007e146.png)
![Screenshot 2023-03-09 at 20 33 12](https://user-images.githubusercontent.com/127442920/224135447-45468775-6e82-4976-9bd0-89aa3111ee45.png)

You can see that in the first picture it is very visible;' in the second, I literally just turned the camera and it disappeared. I took all adding off without a change. I logged into a blood elf and there it was barely an issue. On my human, it appears outside in elwynn regularly, but never inside in buildings.

**Comment by GRIMLEGION** [comment]
This might be tied to a patch that is conflicting with ours, never seen this issue here.

Double check your patches and see if you forgot one
