### ISSUE TITLE
[Quest][Bloodmyst Isle] Razormaw spawning in wrong position

### ISSUE THREAD

**Issue by Ephyla** [Duskhaven/Bug-Reports#750]
Hello,
The end quest in Bloodmyst Isle razormaw elite (https://www.wowhead.com/wotlk/npc=17592/razormaw) spawning at the wrong position far away from the mountain. So its unkillable atm. No way to finish the quest. Can you guys check it out. Thanks a lot.
![WoWScrnShot_033023_091010](https://user-images.githubusercontent.com/129368300/228758956-fbbc0af9-e957-4ab8-b587-c66892fa9600.jpg)
![WoWScrnShot_033023_091338](https://user-images.githubusercontent.com/129368300/228758966-e7d00068-2c2c-4fee-9656-57385dbda733.jpg)

**Comment by Duskhaven** [comment]
Walking a few steps towards him makes him come to your position.
