### ISSUE TITLE
Stave of the Ancients Quest - Bugged Not working -

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#753]
in the Hunter Quest for Rhok'Delar   The quest has you kill 4 Demons and gather their heads. 

i have experienced the following problems in this quest.  

1. the demons don't patrol, they sit at a spot and don't move. 
2.  when you speak to one, a chat dialogue is supposed to happen. then they transform into a demon from their " shape shifted form ".  this does not happen, and you are unable to make them transform to kill them. 

The Quest giver in MC askes for the leaf, and black dragon sinew but does not give you anything in return.  you just lose your stuff. 
i had to go all the way to felwood to speak with the original quest givers. 

--HungryHippo

**Comment by Duskhaven** [comment]
Cannot replicate. The Demon version of them is already present and you do not need to trigger the dialogue.
