### ISSUE TITLE
Can't spent talant points

### ISSUE THREAD

**Issue by zeus9501** [Duskhaven/Bug-Reports#754]
Can't spent talant points.I just spent talants when sudontly stop working and i am stuck on only 3 points spent and i can't spent more i have curontly 5 unspent talents and i even try to reset talents.Help pls!!!

![WoWScrnShot_033023_174318](https://user-images.githubusercontent.com/129409180/228873569-c21248be-4bda-47f1-a09a-620db5b9cf0d.jpg)
![WoWScrnShot_033023_174319](https://user-images.githubusercontent.com/129409180/228873580-43466dee-67cb-47ef-b6b5-f4034c4d321b.jpg)
![WoWScrnShot_033023_174322](https://user-images.githubusercontent.com/129409180/228873599-42a47b32-7eec-41de-b82f-c3d43e4238a8.jpg)

**Comment by Duskhaven** [comment]
Update your patch
