### ISSUE TITLE
Quest: Bloodpetal Posion does not drop Gorishi Sting

### ISSUE THREAD

**Issue by Beepeherald** [Duskhaven/Bug-Reports#756]
Steps to Reproduce:
1. Have a druid of required level
2. Pick up quest "Bloodpetal Poison"
3. Go to Un'goro Crater and kill insects that are eligible to drop Gorishi Sting
4. Observe no insects drop Gorishi Sting

Observed Results:
Bloodpetal Poison does not drop Gorishi Sting

Expected Results:
Bloodpetal Poision does drop Gorishi Sting

**Comment by Duskhaven** [comment]
Cannot replicate
![image](https://user-images.githubusercontent.com/123925176/229314526-cecb688d-3c37-4e2e-a28c-a928ff160fc6.png)

Dropchance is low, has been increased to 50% now
