### ISSUE TITLE
Paladin Mounts Cost Double other Mounts

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#757]
[https://imgur.com/a/FvYYjT9](url)

Paladins mounts cost double what other mounts do, because you need to train journeyman riding before u can train it.

Back in classic, this mount was harder work than straight up buying an epic mount, but also cheaper. Also, when u get the mount, u get the required epic riding skill too. It doesn't make sense its more expensive on this server.

I think a good compromise is letting people buy the mount, OR removing all the gold costs and material costs from the questline

These are the mats and gold required for the questline in classic.

350 Gold
40 [ Runecloth]
6 [ Arcanite Bar]
10 [ Arthas' Tears]
5 [ Stratholme Holy Water]
20 [ Enriched Manna Biscuit]
1 [ Azerothian Diamond]
1 [ Pristine Black Diamond]

**Comment by Buggyswires** [comment]
I opened an issue for that some time ago, but there wasn't any reaction up to now:
https://github.com/Duskhaven/Bug-Reports/issues/583

**Comment by Duskhaven** [comment]
Fixed after restart

**Comment by Buggyswires** [comment]
One problem: you removed the journemyman requirement from buying the charger skill.

I have already bought the journeyman riding on my char (Vimes)
Now the requirement is removed - so every paladin who bought the riding skill still has to pay double the amount

**Comment by Buggyswires** [comment]
Did you fix the skill cost (nice) or the riding skill requirement (bad)?
Because every paladin who already bought the riding skill still has to pay double the amount then.
