### ISSUE TITLE
T2 hunter 8set not working for Mhunter

### ISSUE THREAD

**Issue by Wafflfries** [Duskhaven/Bug-Reports#761]
I made a ticket on github about how 8set T2 does not work on melee hunter, over the course of an entire raid the debuff proced 3 times, with over 40mins of combat.  After testing on a dummy for over 15mins last night same result about 1-2% debuff uptime. So then I Switched to MM and got between a 50%-70% uptime on the debuff. The ticket was closed earlier and the set hasnt seen any changes.

**Comment by Worgenpriest** [comment]
If this is looked at, please check if Tinker abilities work with it also.

**Comment by Duskhaven** [comment]
The Set Bonus would be too strong for melee hunters if it had the same procrate as on ranged. Set bonus might get reworked for melee.

Tinker set bonuses are working.
