### ISSUE TITLE
Assasianition bug/Bloodfang Set bonuses

### ISSUE THREAD

**Issue by ZoliZara** [Duskhaven/Bug-Reports#764]
Character Name: Zara
Issue: New talent Internal Bleeding is not working for me not doing damage after the buff, also my Mutilate ability is not doing any damage with my off hand, as you can see on the details.
Image: https://imgur.com/tUcRJ74
Also Bloodfang T2 3set bunos should increase my energy limit by 20 its not working tho.
Image: https://imgur.com/tpJKkTB
Please fix it both soon as possible, i think assa could take a place in top tier dps classes. 
Thanks for your hard work <3

**Comment by Duskhaven** [comment]
Internal Bleeding works for me (Perhaps use the highest rank?)

Energy Bonus is now fixed
