### ISSUE TITLE
The God Hakkar, no resummon after completing questline

### ISSUE THREAD

**Issue by FeralHeistxd** [Duskhaven/Bug-Reports#77]
After completing 'The God Hakkar' questline, u should be able to pick up 'Yeh'kinya's Scroll' which is item to resummon Avatar of Hakkar. But after talking to the NPC, i dont get anything.
![image](https://user-images.githubusercontent.com/127445042/224145063-537084f5-dbdd-479b-aed6-928ed60fc0a2.png)

**Comment by Duskhaven** [comment]
This is now fixed.
