### ISSUE TITLE
Muckshell Snapclaw Poison

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#770]
Muckshell Snapclaw's Poison DoT is ticking for too much. Most likely a scaling issue.

![image](https://user-images.githubusercontent.com/76977299/229230454-10c4abea-12f1-47ed-85ee-f9ccbbeca200.png)

**Comment by harukaze3** [comment]
Extension: the mob can spam this attack, and the poison can stack up to 5 times, making it deadly to any players, not just HCs.
![image](https://user-images.githubusercontent.com/76977299/229231331-738c9329-f4de-459b-9497-80b4414d5b68.png)

**Comment by Duskhaven** [comment]
Fixed
