### ISSUE TITLE
Agent of Nozdormu

### ISSUE THREAD

**Issue by Thickoatmeals** [Duskhaven/Bug-Reports#771]
Hey there Noxx!

So while my guild was farming for Scarab lord, we realized that during the quest The Hand of the Righteous, https://www.wowhead.com/classic/quest=8302/the-hand-of-the-righteous
You are unable to to "Deputize" a friendly player with Proxy Of Nozdormu properly. When you do Deputize them, they still cannot loot the needed Silithid Carapace Fragments.
 https://www.wowhead.com/classic/item=20384/silithid-carapace-fragment

My guild is really trying hard for this self made achievement, any and all help would be greatly appreciated!

**Comment by Duskhaven** [comment]
This will be fixed before AQ releases, as its not supposed to be available at the moment.
