### ISSUE TITLE
Improved Mark of the Wild not working as intended

### ISSUE THREAD

**Issue by mickyds33** [Duskhaven/Bug-Reports#773]
![image](https://user-images.githubusercontent.com/27994490/229256080-454824b0-b7bb-4525-8bbf-1152a3ecd662.png)

![image](https://user-images.githubusercontent.com/27994490/229256120-29934b10-5c57-42d1-a7dc-432395652d47.png)

**Comment by mickyds33** [comment]
Could be different for later ranks, currently level 24 on this toon

**Comment by Dova14** [comment]
This happens with ALL spells that is improved by a talent: I.E look at might/wisdom.  Its a normal thing that has been in all wrath servers, but in actuality it gives the improved version.  Test it yourself.  You will see your armor is being increased by 147 and not 105

**Comment by mickyds33** [comment]
You are right, thanks!
