### ISSUE TITLE
Depths of Despaire quest not clearing when hitting level 60

### ISSUE THREAD

**Issue by Kingdomofwar** [Duskhaven/Bug-Reports#774]
I hit lv 60 with (Depths of Despaire) quest  on my character (Sour) and the quest has not cleared. The debuff is still active and it seem i can't turn it in.
![Screenshot 2023-03-31 195301](https://user-images.githubusercontent.com/129566771/229260343-5e956c87-d767-412a-b391-c3e4eaac66ad.png)

**Comment by Duskhaven** [comment]
Open a ticket after reaching Level 60
