### ISSUE TITLE
Spending Maelstrom on Lightning Bolt Resetting Swing timer

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#776]
How maelstrom is supposed to work is if you have at least 1 stack of maelstrom, your auto swing timer will not be reset as long as your cast is finished before your swing finishes
So if your cast finishes 0.3 seconds your swing finishes, your auto isnt reset. but if your cast finishes 0.2 after your swing finishes, your auto is reset and you lose that round of auto attacks

How it actually is working is that either casting at 1 - 4 maelstrom or using 5 stack instant cast maelstroms is resetting your swing timer.  But if your maelstrom casts finish after your swing does, your auto does not reset.  

A very major bug that is messing up shaman dps by a lot due to all the lost auto attacks (as its resetting even on instant casts as stated previously)

https://www.youtube.com/watch?v=wZrjZe6PdHE
A video showing the above mentioned, my swing timer perfectly works and as I show in the video I show all that I mentioned: My auto resetting after an instant cast maelstrom, My auto resetting after a proper lightning weave, and my auto not resetting after an improper lightning weave

**Comment by Duskhaven** [comment]
A hackfix has been applied.
