### ISSUE TITLE
Searing Nightmares Shadow Priest Talent AoE Not Applying SWP Bug

### ISSUE THREAD

**Issue by Chad-CL** [Duskhaven/Bug-Reports#78]
![image](https://user-images.githubusercontent.com/32410028/224145177-2e115e91-b0e2-47ed-9389-27b595238ebc.png)

![image](https://user-images.githubusercontent.com/32410028/224145216-18e40c5a-47c4-4505-a187-9816998fc609.png)

![image](https://user-images.githubusercontent.com/32410028/224145239-22735075-d302-48a8-a45b-430ad90a3ab1.png)

Talent Searing Nightmares is not applying Shadow Word Pain to all enemies as described. It is only applying to the main target. It also overrides larger SWP on targets.

**Comment by Duskhaven** [comment]
Fixed
