### ISSUE TITLE
cannot remove the custom appearance for the Druid forms

### ISSUE THREAD

**Issue by Huntereye1** [Duskhaven/Bug-Reports#782]
as the title mentions , you do not have currently a way to remove the custom appearance from trial. Would be great to give player a option to either use standard apperance or the new one.

**Comment by Duskhaven** [comment]
This belongs in a suggestion post in the Discord, not on GitHub

**Comment by Huntereye1** [comment]
i was directed into Writing this into the Github. via the ingame ticket. but i guess ill rewrite this then into suggestion.
