### ISSUE TITLE
Enh Shaman Talent "Crash Lightning" not working.

### ISSUE THREAD

**Issue by dmjohn0x** [Duskhaven/Bug-Reports#784]
Enh Shaman Talent "Crash Lightning" not working. Cant even put a talent point in it anymore as of the Emerald Dream update.

Also, its pretty frustrating that you cant post screenshots anywhere in discord when you are having an issue to see if its actually a bug or not by showing others in chat. Thats probably not a bug, but intended. But regardless, its a stupid decision.

**Comment by Duskhaven** [comment]
Fixed with the next patch update. Putting 2 points into improved stormstrike passively teaches crash lightning
