### ISSUE TITLE
Priest "Greater Heal" Rank 3 stronger than Rank 4.

### ISSUE THREAD

**Issue by Salithri** [Duskhaven/Bug-Reports#787]
So Greater Heal rank 3 scales: 1617-1807
                          rank 4 scales: 1206-1437..

![greater](https://user-images.githubusercontent.com/127896721/229311214-a250d1c7-73aa-4c01-83d0-c4a386d1eda2.png)

**Comment by Duskhaven** [comment]
Fixed after restart
