### ISSUE TITLE
Expertise shows wrong rating

### ISSUE THREAD

**Issue by hardin017** [Duskhaven/Bug-Reports#794]
i have 17 expertise from my gauntlets and 14 expertise from shadowcraft 2 set on my shaman, plus 9 expertise from talent unleashed rage, Which means it should show up as 40, but it shows up as 22, Which is incorrect because that is not the correct math.

I shouldn't have to get so much expertise just to reach 22, my talent and the edgemaster's handguards should have been enough

**Comment by Worgenpriest** [comment]
I'm guessing the numbers you're stating are expertise "rating", not flat expertise.  It's the same as getting something with 14 critical strtike "rating" which doesn't give you 14% crit but only 1%.
