### ISSUE TITLE
Glacial spike range

### ISSUE THREAD

**Issue by Raulfin** [Duskhaven/Bug-Reports#796]
There seems to be no range limit on the extra target. 
During an SMGY+2 a couple times when fighting 1 mob our mage used spike and it would hit targets that were not in combat, were 40y+ away, and not in los.

**Comment by Duskhaven** [comment]
This is likely caused by the recent change to Glacial Spike benefitting from Frost Talents. Glacial Spike no longer initiates combat or pulls aggro. It's range and radius has also been lowered to 25 yards after the restart. If it's still not enough it will see further nerfs to both values.
