### ISSUE TITLE
Blacksmithing recipe is in my spellbook?!

### ISSUE THREAD

**Issue by Jalamin1** [Duskhaven/Bug-Reports#797]
![Screenshot 2023-04-02 155056](https://user-images.githubusercontent.com/129696278/229385494-8779601b-ec58-4125-84c7-63be7b590092.png)

**Is this supposed to be here?**

**Comment by Duskhaven** [comment]
Duplicate Issue, refer to https://github.com/Duskhaven/Bug-Reports/issues/218

**Comment by Jalamin1** [comment]
**So is there a fix coming?  Just asking.**
