### ISSUE TITLE
My character is lacking weapon skill for both Axes and Daggers even after training.

### ISSUE THREAD

**Issue by Tikersbtw** [Duskhaven/Bug-Reports#80]
https://i.imgur.com/aYvGA6w.png

Title. I have trained at all the trainers, and have the ability to equip both but will constantly miss/parry on mobs making these weapon types un-useable. IGN:Dog

**Comment by JeffDerDude** [comment]
Hey, I have the same problem on my Bloodelf Warrior. I am lacking 1h sword; 1h+2h axes and 2h maces, or rather the skills disappeared at some point.

**Comment by Duskhaven** [comment]
This is fixed with the next restart. Make sure to visit the Innkeeper in Stormwind or Orgrimmar.
