### ISSUE TITLE
Trial of Cenrius - Tank Ursoc Bug

### ISSUE THREAD

**Issue by Landengen** [Duskhaven/Bug-Reports#802]
There is a couple bugs with the Trial of Cenarius - Tank. One, he is supposed to have some time when you enter for him to survive and dps Xavius. This was only a case part of the time, but in none of the cases did the ranged dps do actual dps (though once it ran to melee), but the healer did nothing either to heal Ursoc, itself, or anyone else. 
The second bug is that he never dropped the Mind Control. I was able to kite him alone (without Xavius funny enough, he and the healer/dps npcs just had a staring contest) around the map, several buildings, and so on. 

Lastly, I have a suggestion. Even if this wasnt a bug and you could ignore Ursoc and the two supposed help npcs and you were just supposed to go circles with Xavius, his damage should be based on your stats for you to plan and rotate cooldowns around rather then just eating through you like wet toilet paper. I get that hes supposed to die, but makes less sense with that being the case if hes supposed only be dealt with until Ursoc loses his MC.

**Comment by Duskhaven** [comment]
Ursoc only loses his MC if you further damage Xavius.
