### ISSUE TITLE
Tristfal Glades - custom zep tower bugged

### ISSUE THREAD

**Issue by Mapox69** [Duskhaven/Bug-Reports#806]
The custom zeppelin tower in Tristfal Glades (the one with one ramp only) has bugged surface under the end of that ramp. Plus the zeppelin can not be entered.

(add - not bug related)
There is missing zeppelin master at the end to describe exactly the place the zeppelin is heading to. There is sign saying vengeance, but it says nothing to me.

**Comment by Duskhaven** [comment]
Bugged Surface has been fixed.
You cannot enter the Wotlk transportation ships/zeppelins.

**Comment by Mapox69** [comment]
Oh, did not know it is Wotlk related...then it is fine! Thanks for the work of fixing the bugs asap! Good luck.
