### ISSUE TITLE
Shaman Tank Stone Infusion

### ISSUE THREAD

**Issue by Davaerst** [Duskhaven/Bug-Reports#807]
The Shaman tanking ability 'Stone Infusion' from the 'Stone Warden' talent does not allow the shield, Aegis of the Scarlet Commander, from 'Scarlet Commander Mograine' in 'Scarlet Monastery: Cathedral' to be applied smoothly, giving the confirmation window that the item will become soulbound every time it is used.
No knowledge currently of any other weapons/shields that will cause this.

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/299
