### ISSUE TITLE
Warlock Tier 2 5 Piece Bonus

### ISSUE THREAD

**Issue by Davaerst** [Duskhaven/Bug-Reports#808]
The Warlock tier 2 set 5 piece bonus doesn't increase the duration of Immolate and Corruption at all when using Life Tap (all ranks tested).
![image](https://user-images.githubusercontent.com/36208013/229640413-6be566eb-562f-4d3b-9eeb-fb1d2d366d55.png)

**Comment by GoldWarr** [comment]
Can attest this too, its not increasing the duration when you use life tap.

**Comment by supxdz** [comment]
Its probably just baseline duration of Immolate and Corruption

**Comment by Duskhaven** [comment]
> Its probably just baseline duration of Immolate and Corruption

Correct
