### ISSUE TITLE
No Auto Attack

### ISSUE THREAD

**Issue by suppliedgm** [Duskhaven/Bug-Reports#810]
Sometimes your character won't auto attack
https://medal.tv/games/world-of-warcraft/clips/12P24HSSkqlTLW/d1337kpn6292?invite=cr-MSxKeXIsNjkwMDc5MjQs

**Comment by Mentilar** [comment]
same problem

**Comment by Duskhaven** [comment]
Related to bugged spawn positions, please report the affected creature.
Pulling the creature away should temporary fix the Issue
