### ISSUE TITLE
Eye of Divinity Heroic version

### ISSUE THREAD

**Issue by Shadzer** [Duskhaven/Bug-Reports#815]
Got the Eye of divinity on Heroic difficulty from Majordomo Executus. Rewarded with a NORMAL Benediction. Please make it so when you use the Heroic Eye of Divinity, that you get a heroic version of Benediction/Anathema. (Possibly for other item rewards too to buff heroic items)

It's technically not worth doing the quest with M+ gear if Benediction stays at its normal statrange.

**Comment by Duskhaven** [comment]
Belongs in Discord, not on bug reports.
