### ISSUE TITLE
Demo Warlock Imp Gang changes not working

### ISSUE THREAD

**Issue by GoldWarr** [Duskhaven/Bug-Reports#817]
"Demonology Warlock
Imp Gang: Summoned Imps now react slightly faster (Already live)
Imp Gang: Summoned Imps now explode for AoE damage before expiring (Already live)"

Neither of these two changes are working even tough it clearly states its already up on the live server.

**Comment by supxdz** [comment]
The explosion is working, does about 550 dmg per imp. 

The first imp summoned is attacking faster, but subsequent imps do not attack the target until you do.
