### ISSUE TITLE
Tanaris Infinite quest mob spawning

### ISSUE THREAD

**Issue by Davaerst** [Duskhaven/Bug-Reports#818]
The quest "Cuergo's Gold", that you get from combining 3 papers from the pirates in Tanaris, spawns 3 mobs everytime you click the flag on the ground, but can be clicked as many times as possible until you loot the key for the quest completion, potentially able to lag the server out.
https://youtu.be/rVpZnNZhMQI

**Comment by Duskhaven** [comment]
Fixed.
