### ISSUE TITLE
Hardcore character got revived heh

### ISSUE THREAD

**Issue by GooodGuyGreg** [Duskhaven/Bug-Reports#82]
Died during my hardcore challenge then didn't log on for a couple of hours cuz I was dead.... then my spirit was released after I logged back in and I could go revive at death location.
Idk if its cause my characters name is Chucknorris, or that even the Lich King couldn't hold Chuck Norris down or if its a bug

**Comment by Duskhaven** [comment]
Players that revive again during the Hardcore Challenge are not eligible for Rewards at Level 60.
