### ISSUE TITLE
Monk Tier2

### ISSUE THREAD

**Issue by BugStomper3000** [Duskhaven/Bug-Reports#824]
Tier 2 6set Fist of the tiger portion does not work, the others effects do

**Comment by eMalum** [comment]
Can confirm, the 60% additional damage over time effect from the 6-pc set bonus of the Dungeon 1 and Tier 2 sets does not appear to be working properly.

![image](https://user-images.githubusercontent.com/85034251/231280633-f56b17e0-c6ca-46e8-856e-38ea2a21972c.png)

**Comment by Duskhaven** [comment]
It strangely only procs on the 2nd application of Fist of the Tiger, not the first, after that it always applies when using the Skill. Will be added to the description after the next patch update.

**Comment by killersoxfan** [comment]
Also still broken. If you can fix all the monk tier sets and not close the tickets before they are fixed I will donate.
