### ISSUE TITLE
Smite Priest

### ISSUE THREAD

**Issue by BugStomper3000** [Duskhaven/Bug-Reports#826]
New Talent: Watchful Val'kyr - Call upon a Val'kyr to blast your enemies. The Val'kyr increases the Holy damage received by the target by 20% for 15 seconds.
The Valkyr doesnt do the 20% debuff on target

Also Watchful Val'kyr has 0 scaling, does same dmg naked as with full gear

**Comment by Duskhaven** [comment]
The 20% has been removed from the Description.
