### ISSUE TITLE
Pure Flame Essence trinket, not useable

### ISSUE THREAD

**Issue by Thickoatmeals** [Duskhaven/Bug-Reports#829]
![image](https://user-images.githubusercontent.com/129557110/229977202-ec65c1a8-c1af-4feb-855e-2095a9b151e4.png)
Unfortunately, whenever I tried to use the trinket, it says "You can't do that yet". Hopefully this can be fixed soon! I've been farming for this trinket for awhile! <3 thank you for all your hardwork!

**Comment by moonfirespammer** [comment]
Second on this. I could not use it too.

**Comment by Duskhaven** [comment]
Fixed after restart
