### ISSUE TITLE
Missile barrage / arcane barrage

### ISSUE THREAD

**Issue by Fallzi** [Duskhaven/Bug-Reports#830]
Missile barrage sometimes fails to fire, yet uses the proc.

Arcane barrage will pull entire rooms.

**Comment by harukaze3** [comment]
This can only happen, if you don't have enough hit-rating. Spell hit chance is 17%. As for the Arcane Barrage, that actually seems like a bug.

> Haruka

**Comment by Fallzi** [comment]
Okay, Thanks for letting me know about the hit cap problem w/ missile barrage.

Ya, Arcane Barrage will pull nearly the entire Cathedral of SM Cath when fighting mobs in the middle path.  Or, if you're fighting mobs too close to not-in-combat mobs like within 30 yards.

I'm not sure if Arcane barrage is supposed to fire additional Arcane missiles, but that is the animation that is firing, as well as the normal Arcane barrage animation.

> This can only happen, if you don't have enough hit-rating. Spell hit chance is 17%. As for the Arcane Barrage, that actually seems like a bug.
> 
> > Haruka
