### ISSUE TITLE
Improved Stormstrike is not giving mana. 

### ISSUE THREAD

**Issue by Feromone** [Duskhaven/Bug-Reports#831]
Title^ The mana regen is bugged and needs to be fixed.

**Comment by harukaze3** [comment]
![image](https://user-images.githubusercontent.com/76977299/230015178-4502e8e3-eb47-44f7-8b5a-84be7af5addb.png)

Works fine on our side.

> Haruka

**Comment by Feromone** [comment]
@harukaze3 Is there a Patch out new yet? Maybe I have to reset talents but it was 100% not working for me, any idea what interactions would be needed to make that so?

**Comment by Feromone** [comment]
> @harukaze3 Is there a Patch out new yet? Maybe I have to reset talents but it was 100% not working for me, any idea what interactions would be needed to make that so?

Reset Talent's and that fixed it -Edit
