### ISSUE TITLE
Survival hunter is broken (in a bad way)

### ISSUE THREAD

**Issue by Cavol315** [Duskhaven/Bug-Reports#843]
So currently the only thing that proc's Lock and Load is Freezing Trap and Frost Trap. 
Black arrow and explosive trap are never procing it. Not sure about immolation trap.

Expose Weakness never procs, currently on 2/3 and i never got the buff.

Playing range hunter, haven't tried melee, but since Lock and Load is essential for survival dmg, it makes the spec unplayable.

**Comment by Duskhaven** [comment]
Fixed.
