### ISSUE TITLE
Hardcore Quest. 

### ISSUE THREAD

**Issue by Healicious** [Duskhaven/Bug-Reports#848]
So I got my character "Scorn " up to lvl 60 on hardcore challenge. Yet the quest is still greyed out for me... Statisics says i have deaths but ive never died but i have taken the buggy flight to mithril harbor to get to the boat many times to go to other side of world  to quest and farm ore.

**Comment by whieban** [comment]
Ye my character "didnt complete the challenge". This is incredibly unfair.

![](https://cdn.discordapp.com/attachments/1083475381442576546/1093386103270146078/image.png)

![](https://cdn.discordapp.com/attachments/1083475381442576546/1093386689805819954/image.png)
![](https://cdn.discordapp.com/attachments/1083475381442576546/1093386912561115137/image.png)

**Comment by whieban** [comment]
![image](https://user-images.githubusercontent.com/77094224/230272642-13297989-451c-4b3b-aa3a-f7c71c654db4.png)
Confirmation that flying to Menethil Harbor kills you and revives.

**Comment by Duskhaven** [comment]
Open a ticket to be qualified for completion
