### ISSUE TITLE
Arcane Barrage - AoE and Combat Log

### ISSUE THREAD

**Issue by kasumee** [Duskhaven/Bug-Reports#852]
Arcane Barrage currently does not register the cleave/AoE damage it is doing in the combat log, so there is no way to track how much damage it is actually contributing - additionally it targets enemies that are currently not in combat with you in a GIGANTIC radius, makes it pretty unplayable in almost any real scenario.

**Comment by Duskhaven** [comment]
Should show in the combat log after restart. Range/radius can be increased but will not trigger if you are not at 30 yards max range for arcane barrage then
