### ISSUE TITLE
Tinker can't equip Dagger

### ISSUE THREAD

**Issue by nboytcl** [Duskhaven/Bug-Reports#853]
Tinker still can't equip Dagger after learning skill from SW innkeeper.

**Comment by Worgenpriest** [comment]
MG-X2 Turret still doing the same damage, and Master Engineering tooltip doesn't say anything about threat reduction.  Seems like 0 of the tinker changes went through.

**Comment by Duskhaven** [comment]
Cannot replicate. Buying the book from the Innkeeper teaches daggers
