### ISSUE TITLE
Enlist mode / War mode

### ISSUE THREAD

**Issue by wulfgarx** [Duskhaven/Bug-Reports#855]
This been happing a few times. I go to Org and Get Warmode aka inlist mode and i did a Dungeon and the buff is gone. Kinda suck. and i still have the quest. And now without the buff and quest still thinks im in Warmode but my pvp is off. but yet Other people can attack me and kill me

**Comment by Feromone** [comment]
@wulfgarx I believe this is intended, it reads in the quest description I think that it removes with RDF, just to keep in mind!
