### ISSUE TITLE
[Demonology] Wild Imps spawned via Soul Fire don't explode on expire

### ISSUE THREAD

**Issue by Krzywomordy** [Duskhaven/Bug-Reports#866]
![obraz](https://user-images.githubusercontent.com/50958510/230380825-41c4dd2f-fc89-4af6-a18c-d636703bbf36.png)
As said in the title and shown in the picture - no explosion from imps spawned via Soul Fire. Only ones spawned via Molten Core proc do explode on expiring. Also Imps sadly do not inherit hit chance of master (dunno if that's possible or not since they're guardians, but it's definitely very annoying).

**Comment by Duskhaven** [comment]
Cannot replicate (May just not work on dummies)

**Comment by Krzywomordy** [comment]
Tested on Oakheart, still no Explosions from Imps spawned via Soul Fire
![obraz](https://user-images.githubusercontent.com/50958510/230587180-1c0ccb16-e1ad-412d-b2bb-8961a8dbd729.png)
And I know I'm not the only one. Only Imps spawned from Molten Core explode

**Comment by Krzywomordy** [comment]
Here's another example from other warlock - no explosion at all (even tho he had only 4 imps spawned)
![obraz](https://user-images.githubusercontent.com/50958510/230588701-563a0e04-5dea-48f5-8b8c-38afffacafde.png)
