### ISSUE TITLE
Monk/Priest aggro range

### ISSUE THREAD

**Issue by LickMy4Head** [Duskhaven/Bug-Reports#869]
Didn't notice the same issue on my hunter and don't if it's a bug tbh. On my Priest aka Monk i'm getting the aggro many times, even when other people pull them. They just run off onto me.

**Comment by Duskhaven** [comment]
That is intended. Monks buffs replenishment/mystic touch etc generate threat

**Comment by LickMy4Head** [comment]
Even when i'm not attacking and just sitting there? I would understand in combat, but i'm talking outside of combat
