### ISSUE TITLE
Arcane Barrage now also hits a second time for AoE damage to multiple targets

### ISSUE THREAD

**Issue by Elylenai** [Duskhaven/Bug-Reports#871]
I really love it but the problem is the following:

The missiles pull mobs from far away, making it impossible to use in the following situations:
- CC'd mobs in some fights.
- Avoided pulls by tank, being pulled by the huge range those missiles have.
- Almost impossible to use in pug dungeons (you can do it tho if you want to be insulted, questioned or just showing how meme your spec is).

I'll attach file in a friendly environment for testing:

https://user-images.githubusercontent.com/129815753/230435348-a6d6f0c5-6734-4a5b-a72d-7ba547efe8f8.mp4

Any ideas I got:
The extra missile arcane barrage shoots could be a single target one but with some exploding radius (like arcane explosion for example)
Shoots enemies in a cone in x meters

**Comment by Duskhaven** [comment]
Range/Radius lowered to 20 after restart
