### ISSUE TITLE
Demon Hunter T1 (second) set bonus not working at all.

### ISSUE THREAD

**Issue by Thelendril** [Duskhaven/Bug-Reports#872]
Hello there, the Rogue/DH T1 (second) bonus which is "While demonic tatoos is active you now regnerate 2% health every 5 seconds" is not working at all, maybe you could fix it be implementing a buff kinda like the original T1 Hunter set, the buff goes on you and on the pet.
Thanks again for the server, and everything that you are doing for us <3

**Comment by Duskhaven** [comment]
Fixed after restart
