### ISSUE TITLE
Spirit of Eskhander bugged!

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#877]
Eskhander right/left claw chance on hit effect procs very rarely , this is because it has 1% chance on any "melee crit".
This means regular Hits arent even proccing it, please could this be changed to any "Crit" so non melee classes can use it too?

The main issue is that when i saw it procc once a few days ago, the summon did nothing.
Normaly it grants a debuff that is similar to 4 stacks of Sunder on the Target , this info is from old wow logs.

**Comment by Duskhaven** [comment]
Fixed
