### ISSUE TITLE
Troll (druid) regeneration not active after leveling

### ISSUE THREAD

**Issue by Madraddad** [Duskhaven/Bug-Reports#878]
I just made a new troll druid. Regeneration works properly from level 1. By the time I am level 8, regeneration is not ticking in combat anymore. 
Not sure the exact level it deactivates, but I think it may be after I learned starlight at level 5. Or maybe its after I picked up mining and engineering. Please let me know if this is acknowledged and will be addressed.

**Comment by Duskhaven** [comment]
Cannot replicate. HP/Mana regeneration is increased for the first Levels. So it might not be noticeable that much after reaching Level 8+
