### ISSUE TITLE
Troll riding Kodo Mount unable to run through certain horde buildings (such as orgrimmar flight master structure)

### ISSUE THREAD

**Issue by txion083** [Duskhaven/Bug-Reports#880]
Hello.

I have a troll character with a kodo mount and am unable to run through the entrance of the Orgrimmar flight master structure.  Another structure I cannot run through on a kodo is the zepplin structure (the one right outside orgrimmar that flies to Undercity and Grom Gol).

It seems like there is an invisible wall when riding on a kodo as a troll.  Dismounting obviously lets me walk right through them, but that isnt the point as just adds to the annoyance of having to dismount before entering these structures.

**Comment by Duskhaven** [comment]
This is normal for Kodo/larger sized Mounts
