### ISSUE TITLE
Different Chargers for factions.

### ISSUE THREAD

**Issue by harukaze3** [Duskhaven/Bug-Reports#883]
![image](https://user-images.githubusercontent.com/76977299/230538140-f4b4bf81-487d-4c0e-a11b-f9f29bec1851.png)

Courtesy of Domnall. Alliance has to pay ~300g, Horde has to pay ~6g for their lv 40 Charger.

**Comment by Duskhaven** [comment]
Alliance version also grants the Lvl 40 riding while the horde one requires lvl 40 riding to learn.
