### ISSUE TITLE
Dual wield specialization (enhancement shaman) does not appear to be giving spell hit.

### ISSUE THREAD

**Issue by Tikersbtw** [Duskhaven/Bug-Reports#884]
94 hit rating = 11.75% spell hit (Gear)
11.75%+6%=17.75% so should be over spell hit cap on the dummy.

Yet still missing on the heroic dummy.

Very odd for it to not give spell hit considering how tight the stat budget is already as enhancement.

**Comment by Duskhaven** [comment]
Heroic Dummies are now fixed. Their Level was higher then intended.
