### ISSUE TITLE
Alliance Paladin and Horde Paladin Mount quests differ in cost by 280g

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#885]
At the moment, alliance paladins have to pay almost 275 gold more than Horde paladins to get the class mount. Please see the picture as attached. 

https://cdn.discordapp.com/attachments/1083160617621393418/1093745372062568498/image.png

Please make it so alliance paladins also pay 5g only. Thank you!

**Comment by Duskhaven** [comment]
Once you learn the Alliance Version it grants you the Lvl 40 mount riding as well, the cost of both is roughly equal.
The Horde version can only be learned when having the lvl 40 mount riding skill
