### ISSUE TITLE
UD hunter autoshot

### ISSUE THREAD

**Issue by leplep2** [Duskhaven/Bug-Reports#887]
UD hunter's autoshot or any ranged skills do not work. Currently I'm at level 5, and both autoshot and serpent sting doesn't function due to "no ranged weapon equipped". I've learned the bow skill, and currently I managed to bug the whole character and now I'm unable to attack mobs even in melee autoattack and raptor strike.

**Comment by Duskhaven** [comment]
Cannot replicate
