### ISSUE TITLE
Trouble with launching wow.exe and dusk launcher

### ISSUE THREAD

**Issue by Asparag374** [Duskhaven/Bug-Reports#888]
Whenever i try to enter the game via the launcher, it sympli doesnt launch! I click on play and it shows me a black screen. I have done every step. Maybe there is something that my pc lacks, if you know, please tell me what it lacks. Ive had this issue on twow aswell but luckily they have two wow files: wow.exe(that didnt work) and wow.Fov.exe ir something like that( the one that worked).

**Comment by Duskhaven** [comment]
This should be posted on Discord, not GitHub.
