### ISSUE TITLE
Bindings of the Windseeker

### ISSUE THREAD

**Issue by FeralHeistxd** [Duskhaven/Bug-Reports#890]
So, after a few weeks of raiding, it came to my attention, that there is only 1 boss that actually drops right bindings? On the loot table it shows that Lord Rhannox, Baron geddon,HC Majordomo and Blue ragnaros from AC all drop Left bindings, while only Garr drops right bindings? is this a bug or its intended to be this way? If not, could we redistribute the bindings drop across more bosses, so its actually doable to get Thunderfury? I have had left bindings for 4 weeks already, and did only saw left bindings drop 3 times, but no right bindings.

**Comment by Duskhaven** [comment]
Majordomo on HC can drop both bindings.
