### ISSUE TITLE
Wildfire Infusion

### ISSUE THREAD

**Issue by Cptosm** [Duskhaven/Bug-Reports#899]
Wildfire Infusion is unable to be trained after putting 1 point into Resourcefulness even though Wildfire Infusion says it can be trained after only one point is put in. Even after 3 points are put into Resourcefulness I am unable to put a point into it, I am also level 54 and at this time I still can't train it either.

**Comment by Duskhaven** [comment]
This talent is passively active after spending 2-3 points into resourcefulness

**Comment by Cptosm** [comment]
As you can see in these files, I'm attempting to click on Wildfire Infusion after 1, 2, and 3 talent points in Resourcefulness, and none of them are allowing me to train Wildfire Infusion. Hopefully these screenshots work as this is my first time attempting to report bugs this way. If this is working for other people and just not me, maybe that could be noted in some way? (And yes, I'm left clicking on the talent. Hahaha.)

Thank you

![WoWScrnShot_040823_102541](https://user-images.githubusercontent.com/9252464/230726510-37ad0e46-763c-4f54-824b-5cefcd5da580.jpg)
![WoWScrnShot_040823_102557](https://user-images.githubusercontent.com/9252464/230726513-7438939b-358e-4320-b422-a7cb7d8fb658.jpg)
![WoWScrnShot_040823_102603](https://user-images.githubusercontent.com/9252464/230726515-445d6de0-61c1-40c6-ae2b-2db883d26695.jpg)

**Comment by Cptosm** [comment]
I understand now that this is a passive skill after spending at least one point in Resourcefulness. Please disregard my last post.
