### ISSUE TITLE
The Defias Traitor pathing issue

### ISSUE THREAD

**Issue by ActualKeeghan** [Duskhaven/Bug-Reports#9]
there appears to be a custom building in the middle of the path the defias traitor takes to leave Sentinel Hill. He managed to phase his way through it, but there were several moments where it looked like he would get stuck.

**Comment by GRIMLEGION** [comment]
Can you provide a screenshot of the building in question? Thanks

**Comment by ActualKeeghan** [comment]
https://drive.google.com/file/d/1Z5z8ONYshCl89XwtOdDzrpe1OQAVeGa9/view?usp=share_link
screenshots hate me but hopefully you can see it from this. the Traitor runs down from the right, through the wall of the building, and out to the left
