### ISSUE TITLE
Paladin charger (Ally side)

### ISSUE THREAD

**Issue by Vollaem** [Duskhaven/Bug-Reports#900]
I'd like to report something that is apparently only happening on ally side; The charger requires you to have apprentice riding and the cost is 270g (scaling with rep, weirdly) But for the blood elves it only cost 5g from what i've been told.

**Comment by Duskhaven** [comment]
Price cost makes no difference. The alliance version includes lvl 40 riding upon purchase while the horde version requires lvl 40 riding to learn

**Comment by Vollaem** [comment]
I forgot to specify, i couldn't learn it even with the gold.

**Comment by moonfirespammer** [comment]
I would like to verify you CANNOT learn it WITHOUT riding skill. I tested it as well.
