### ISSUE TITLE
Zul'Farrak BoE drop

### ISSUE THREAD

**Issue by Guessimboredagain** [Duskhaven/Bug-Reports#901]
While leveling through RDF we managed to get a Flurry Axe drop. Couple people greeded, Shaman needed on it and when I hit need it didn't say anything about a need confirmation. Afterwards, no one got it.

**Comment by Kerafyrmz** [comment]
can confirm, i was the shaman, playing under the character name 'Piaro'  the dungeon was Zul'Farrak though.

**Comment by Duskhaven** [comment]
Probably related to a full inventory or despawning creature.

**Comment by Kerafyrmz** [comment]
inventory had plenty of space, the roll just never happened after people hit the roll button.
