### ISSUE TITLE
Paladin charger cannot be learnt without riding skill

### ISSUE THREAD

**Issue by moonfirespammer** [Duskhaven/Bug-Reports#905]
I can verify this was the case 2 weeks ago at least. Has it been changed to fix it? Because back then, I could not learn it unless I trained Journeyman Riding. 

And I specifically remember this because I ran back and forth to try and train it at SW (could not) then had to go Elwynn to train it before it popped up. Definitely was some bug.

At this stage, just make it 5g and call it a done deal. I want the mount as it is iconic.

**Comment by Duskhaven** [comment]
Intended.
