### ISSUE TITLE
Atlas Loot not displaying on ElvUI

### ISSUE THREAD

**Issue by oidenn** [Duskhaven/Bug-Reports#909]
Hello! Atlas Loot is currently not showing at all, just the border and thats it, no functionality or graphic, I did try enabling and disabling it to see if that fixes and even reloaded and still nothing, its also noted that I am using ElvUI as well.

![Capture](https://user-images.githubusercontent.com/68927544/230750016-768bf3aa-60cd-4f49-ac76-97497af65d38.PNG)

**Comment by harukaze3** [comment]
This isn't a Duskhaven issue.

> Haruka
