### ISSUE TITLE
Bonereaver's Edge Chance on Hit ability does not stack to 3.

### ISSUE THREAD

**Issue by Righthander** [Duskhaven/Bug-Reports#91]
Bonereaver's Edge only stacks to 2, it should stack to 3. When a third stack is supposed to proc, only the 2 stack is refreshed. Video proof is attached.

![Screenshot (2324)](https://user-images.githubusercontent.com/127463505/224246861-4b370298-e2ff-4bd6-8630-7e2795b89ccf.png)

https://user-images.githubusercontent.com/127463505/224246893-dc3603ed-1b0c-41cf-9112-bb50252da365.mp4

**Comment by Duskhaven** [comment]
This is intended. Bonereaver's Edge has been limited to 2 stacks.
