### ISSUE TITLE
Launcher Spelling mistake

### ISSUE THREAD

**Issue by Helltul** [Duskhaven/Bug-Reports#911]
Spelling mistake on Launcher. Should be found instead of fonud
![Capture](https://user-images.githubusercontent.com/130282094/230765374-9118cd56-5737-4e77-86d9-24ff88b978ee.JPG)

**Comment by harukaze3** [comment]
The Launcher issues should be taken to https://github.com/laurensmarcelis/Duskhaven-Launcher.

> Haruka
