### ISSUE TITLE
Dragonstalker 8/8 Tier Bonus Doesn't work

### ISSUE THREAD

**Issue by Peks20** [Duskhaven/Bug-Reports#913]
The 8/8 tier bonus isn't proccing. I just attacked a dummy for 10 minutes and there was no expose weakness on the target. The only expose weakness was my own from the survival tree. Idk if thats interfering with the spell id and causing it not to proc.

**Comment by Duskhaven** [comment]
Low proc rate for melee hunters. Will get reworked later on.
