### ISSUE TITLE
Emerald Dream Raid - Issues and Bugs

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#923]
Druid Boss : Her Ring of ice got a greater hit range then visualised , people are getting hit even tough they ran out of it for certian.
Stone Lady Boss : Please reduce green fire effects its hard to see raid members also the Boss spawns Flowers right at the ghost healer if unlucky.
People cant ress because they die right away because of it.

**Comment by Duskhaven** [comment]
Radius of the Ice Ring has been lowered by 1 yard after the restart. Players should not release when fighting the Stone Lady.
