### ISSUE TITLE
The Ruby (S2) set have 2x Bugs - and is useless to use 5 set!

### ISSUE THREAD

**Issue by KingQurtz** [Duskhaven/Bug-Reports#924]
It seems The Ruby (S2) 5 set bonus don't work...

with 5 set on (shield block is 34sec CD)
![](https://cdn.discordapp.com/attachments/1095065389223903232/1095065709169619074/WoWScrnShot_040723_234449.png)
![](https://cdn.discordapp.com/attachments/1095065389223903232/1095065709815537765/WoWScrnShot_040723_234506.png)

without 5 set (shield block is 37sec CD) 
![](https://cdn.discordapp.com/attachments/1095065389223903232/1095065789826085025/WoWScrnShot_040723_234517.png)

Shield block is ment to have a 27 sec CD with 5 set.

And it Seem the 3 set bonus are working, but the 20% spell redu seems to be abit off the Shield block Buff timer (like 3sec)
![](https://cdn.discordapp.com/attachments/1095065389223903232/1095065990775181362/WoWScrnShot_040823_013047.png)
![](https://cdn.discordapp.com/attachments/1095065389223903232/1095065991400128602/WoWScrnShot_040823_013104.png)
![](https://cdn.discordapp.com/attachments/1095065389223903232/1095065992058638407/WoWScrnShot_040823_013608.png)

**Comment by Duskhaven** [comment]
Shield Block CD is only reduced by 3 seconds with the Ruby Set. The description be fixed in a later patch

**Comment by KingQurtz** [comment]
What about the 3 set not completely working yet ??

(The 3 set bonus are giving the 20% spell redu, but it also seems to be abit off the Shield block Buff timer, like 3sec)
