### ISSUE TITLE
Fix ignite munching if possible.

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#930]
Hey Noxx!
I don't know if you are aware of what the Ignite munching mechanic is but it's a penalty we even have here as fire mages in Duskhaven :( 

Blizzard never offered a fix, but I was wondering if you could make an adjustment to the fireball projectile speed so munching is WAY reduced and you don't need to use a Macro to delay your pyroblast spell so it doesn't munch (still happens sometimes since we don't have the WA from wotlk-classic working and even that WA makes fire feel clunky to play)

Solution? If possible, reduce fireball projectile speed to same as frostfire bolt or a bit slower even to avoid munching.

Thank you!!!!

**Comment by Duskhaven** [comment]
This belongs in the suggestion channel on discord.
