### ISSUE TITLE
Improved lone wolf seemingly not working

### ISSUE THREAD

**Issue by darkjesterr** [Duskhaven/Bug-Reports#931]
Lone wolf gives 25% damage
Improved is supposed to be 5% (tooltip says 3%)
Set bonus gives a further 3%

33% EXPECTED

-----------------------
Damage with lone wolf active

427-521
Mainhand dps 164.5
offhand dps 136.4

Damage without lone wolf

342-417
Mainhand dps 131.6
offhand dps 109.1

-------------------------
Damage
521 - 417 = 104 = 25%
427 - 342 = 85 = 25%

Mainhand
164.5 - 131.6 = 32.9 = 25%
Offhand
136.4 - 109.1 = 27.3 = 25%
(27.3/109.01 = 0.2502*100 = 25.02%)

EXPLOSIVE TRAP TICK
Lone Wolf active = 217
Without active = 174

217-174 = 43
43/174=0.2471*100 = 25 god damn %

Conclusion. 
Improved lone wolf buffs are not working

**Comment by Duskhaven** [comment]
Might not stack with the set bonus. (Intended)

**Comment by darkjesterr** [comment]
then the talent is still not working (Intended?)
