### ISSUE TITLE
Elemental Blast incorrect spellpower scaling (was fine last week)

### ISSUE THREAD

**Issue by qbawu** [Duskhaven/Bug-Reports#932]
Elemental Blast should scale 320% with spellpower before applying elemental shaman talents affecting fire dmg and lava burst modifications. It used to work correctly last week, now it got nerfed without any information anywhere to be found. 

My current testing suggest that AFTER all of the dmg increasing ele talents (concussion, fire power, shamanism), Elemental Blast spellpower scaling is at 290%, which is massive nerf (actual dmg output is lowered by aprox. 25%). 

Keep in mind that Elemental Blast baseline dmg is around 130, rest of the dmg comes from large spellpower scaling.

With this change, elemental shaman is ones again handicapped in dmg output in M+ and raids., since Elemental Blast was around 25% of all dmg output, not it dropped to around 18%, resulting in roughly 7-9% dmg output reduction.

**Comment by qbawu** [comment]
Additionally to poor spellpower scaling, it also show 5% haste in active buff instead of 10% haste after casting it.

**Comment by Duskhaven** [comment]
Visual bug. SP scaling has been adjusted to make up for the talents that synergizes with it.
