### ISSUE TITLE
Stone In silithus where you spawn elementals is bugged or taken out.

### ISSUE THREAD

**Issue by Nexios1** [Duskhaven/Bug-Reports#933]
So the stone where you spawn elementals for example ''Azure Templar'' In silithus twilight camp is bugged or taken out. Already talked to a gm, he said to bug report It. 
![1234](https://user-images.githubusercontent.com/130447861/231107025-bf71f3a7-c679-40af-b12a-4b1c845ead4c.PNG)

**Comment by Duskhaven** [comment]
Will be added before AQ is available.
