### ISSUE TITLE
[The Nightmare's Corruption] Not working as intended.

### ISSUE THREAD

**Issue by Thickoatmeals** [Duskhaven/Bug-Reports#936]
Hey there! So as the title says, the quest isn't working as intended in regards to the Duskwood portal. Usually there are mobs that drop the Nightmare Fragments. However, only the boss drops it here, and is not a 100% chance. is there anyway to implement a pack or two for the quest line? Every other portal has packs except Duskwood. Thank you for all the help y'all provide!

![image](https://user-images.githubusercontent.com/129557110/231227705-671f8a7e-0ada-468a-8a64-900fa3bc1e5b.png)
(edit for picture)

**Comment by Blikey** [comment]
Duskwood has never had dragonkin packs it's always just the saytr and the drop rate should be 100% but you might need it on FFA
