### ISSUE TITLE
Find Weakness not working

### ISSUE THREAD

**Issue by CovexVortex** [Duskhaven/Bug-Reports#937]
Find Weakness (Survival Hunter tree) sometimes simply doesn't work. I'll use the ability, and I'll then use Explosive Shot, but the buff will not be consumed nor the Black Arrow DoT applied.

I can't fully nail down the cause as I'm unable to replicate it on a dummy or raid boss, leading me to believe it is an issue involving m+ bosses.

**Comment by Duskhaven** [comment]
Fixed after restart
