### ISSUE TITLE
Monk DPS Tier 1 set bonus not functioning correctly.

### ISSUE THREAD

**Issue by eMalum** [Duskhaven/Bug-Reports#940]
The Tier 1 set bonus "Piercing Jab hits a second time for 25% of its original Damage." does not appear to be working properly, the effect just doesn't work.
![image](https://user-images.githubusercontent.com/85034251/231281013-cb5a4777-bf33-47ab-8879-efc6e718be4a.png)

In contrast, the same effect is present on the Scarlet Set, which does appear to be working properly. Another user offered this screenshot as evidence.
![image](https://user-images.githubusercontent.com/85034251/231281364-2e90f643-d686-4e85-978d-d527f963d621.png)

**Comment by killersoxfan** [comment]
I too was testing said issues. Monk bonuses were not active at all. Same for the Tier 2 / Devout set bonus. 6 pc was not working with extra 60% damage as dot from Fist of the Tiger

**Comment by Duskhaven** [comment]
Fixed
