### ISSUE TITLE
Chambermaid Pillaclencher Loot/Quest Drop

### ISSUE THREAD

**Issue by Landengen** [Duskhaven/Bug-Reports#941]
The NPC "Chambermaid Pillaclencher" in the Searing Gorge spawns as normal in the area next to the dwaven pillows for the quest "Kill'Em With Sleep Deprivation". This mob is not dropping a physical item on the ground called "Pillaclencher's Ornate Pillow" which starts a quick turn in quest to Thorium Point for a unique trinket that gives its user Slow Fall like abilities. For that matter, the mob doesnt even drop a bit of money when killed.

**Comment by Duskhaven** [comment]
Fixed.
