### ISSUE TITLE
Troll Druid boomkin walking animation/mount bug

### ISSUE THREAD

**Issue by LetThemCook69** [Duskhaven/Bug-Reports#942]
The walking animation of the new troll boomkin form is just downright bad, could you allow us an option possibly in the transmogrifier or something to allow us to switch between the different boomkin skins?
Also when this NEW boomkin form is used on mounts it makes you stand up ontop of the mount rather than sit on the mount, previous form didn't have this problem

Also it appears the troll boomkin form is also overwriting the celestial boomkin form from trial of cenarius, only way to use the empowered form is by phasing yourself into something e.g. hearthstone/zoning in

It also appears that the form is missing weapon animations too as my staff isn't appearing in said form

**Comment by Duskhaven** [comment]
Fixed with the next patch update
