### ISSUE TITLE
Scholomance bosses using BWL and MC spells

### ISSUE THREAD

**Issue by LundmarkJ** [Duskhaven/Bug-Reports#947]
Summary: Lorekeeper Polkelt and Alexei Barov use wrong spells in Scholomance

Description: I was in a group of five players doing Scholomance, a dungeon in World of Warcraft. We encountered Lorekeeper Polkelt, one of the bosses, and he killed my hardcore paladin with a spell called Corrosive Acid. However, this spell was not his normal ability, but a spell that belongs to Chromaggus, a boss in Blackwing Lair. We checked the combat logs and confirmed that he used the spell with ID 23313, which is Chromaggus' spell (https://www.wowhead.com/wotlk/spell=23313/corrosive-acid). He should have used a spell with ID 8245, which deals no damage (https://www.wowhead.com/wotlk/spell=8245/corrosive-acid).

![image](https://user-images.githubusercontent.com/82000605/231449878-5fbfed6f-9d00-42d3-9a65-374fc33ee96c.png)

We also noticed that another boss, Alexei Barov, using a wrong spell as well. The immolate he cast on us was not his normal Immolate spell but the spell belonging to Sulfuron Harbinger, a boss in Molten Core with spell ID 20294.(https://www.wowhead.com/wotlk/spell=20294/immolate) Instead of his intended spell with ID 15570 (https://www.wowhead.com/wotlk/spell=15570/immolate).

We suspect that there is a bug in the game that causes some bosses in Scholomance to use spells that belong to other bosses in different dungeons.

I hope for a resolution that allows me to continue playing my character, considering I died to a server bug similar to the wetlands flightpoint. I don't care too much about the hardcore rewards(even if they would be nice), I just want the debuffs removed so I can continue playing with my friends.

Best Regards, 
Empress

**Comment by Duskhaven** [comment]
Fixed.
