### ISSUE TITLE
Demonfang 3 set isn't working for mages.

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#948]
After acquiring the full demonfang set, went to test the (already super underwhelming 3set bonus that mages have on it) and it's not even working.

When a mage uses their mana ruby, it doesn't give any buff nor the spellpower increases.

(Would also get looking into adding hit into the s2 cloth set cause at this state its super useless for casters with all the vanilla itemization needed but that's not for a bug report)

**Comment by Duskhaven** [comment]
Fixed after restart
