### ISSUE TITLE
summoning pet in IF

### ISSUE THREAD

**Issue by dmk218** [Duskhaven/Bug-Reports#949]
i tryed summoning my pet in ironforge, said i did not have access to that spell. o turn off all addons and tryed again. left IF and summoned my pet. Think Hunters are not welcomed to IF

**Comment by ghost** [comment]
I think this is due to the Brawler's guild being underneath IF throneroom, in which pets aren't allowed into it for obvious reasons. This might affect pet summoning above.

Cheers

**Comment by dmk218** [comment]
i see locks get there pets but hunters can not?
