### ISSUE TITLE
Nemesis Set - 5p bonuses not working

### ISSUE THREAD

**Issue by Krzywomordy** [Duskhaven/Bug-Reports#951]
5p ser bonus says it grants:
![obraz](https://user-images.githubusercontent.com/50958510/231535303-08c48806-0143-425a-beee-16b354fd5c9b.png)
First thing - it DOESN'T increase pet's resistances. It applies the buff to the pet, but it doesn't increase pet's resistances (uploaded wrong picture, meant to upload one with pet's stats included, will do that when I have oportunity. Or just test that yourself, isn't too hard to check that) 
![obraz](https://user-images.githubusercontent.com/50958510/231537682-99973c47-39ef-4240-9975-6a4a2d35fd1e.png)
Second thing - it only increases Immolate and Corruption duration by 3 seconds instead of 6 seconds. Proof:
With set on corruption is 21 sec:
![obraz](https://user-images.githubusercontent.com/50958510/231536317-9f18e261-b41a-4035-8a9e-c782c5bc7789.png)
and immolate is 27 sec:
![obraz](https://user-images.githubusercontent.com/50958510/231536424-b366c37f-d81d-4f6c-84ff-0218bcece509.png)
Withous set bonus corruption lasts for 18 sec
![obraz](https://user-images.githubusercontent.com/50958510/231536635-5b496d8e-8e7a-445d-b3d1-a5f4f2c949c5.png)
and immolate lasts for 24 sec 
![obraz](https://user-images.githubusercontent.com/50958510/231536877-d9b2e7e3-a033-4e70-90b5-fa42880077e4.png)
NOT A VISUAL BUG, TESTED ON BOSSES. It should add 6 sec to the duration, it currently only adds 3 sec. And yeah, no extra resistances for pets sadly

**Comment by Duskhaven** [comment]
The resistance buff is not applied to the demon's stat page.  Duration fixed after restart.
