### ISSUE TITLE
[Warlock - Demonology] Wild Imps explosions inconsistency 

### ISSUE THREAD

**Issue by Krzywomordy** [Duskhaven/Bug-Reports#953]
Wild Imps rarely ever explode. Imps spawned via Soul Fire almost NEVER explode. Here's an example of a random boss fight.
I've spawned a minimum of 29 imps via Soul Fire as shown in the picture:
![obraz](https://user-images.githubusercontent.com/50958510/231556174-1bf688c7-640d-4602-9e2a-8886f4115d1b.png)
But only 4 of them exploded, also shown in the picture:
![obraz](https://user-images.githubusercontent.com/50958510/231556394-7cc8839d-51b2-4446-b2e7-92117fa15118.png)
Imps explosions are very inconsistent, from what I've tested only imps spawned via Molten Core seem to explode with higher consistency

**Comment by Duskhaven** [comment]
Threshold has been reduced by 2.5-3 seconds. If this isn't enough it will be reduced further.
