### ISSUE TITLE
Automatically passed on Mythic+ S2 Token.

### ISSUE THREAD

**Issue by Montana235** [Duskhaven/Bug-Reports#955]
3 of 5 people automatically passed on the Mythic + S2 Token at the end of a M+ run.
![Screenshot 2023-04-12 215938](https://user-images.githubusercontent.com/48023404/231571030-b8ab2ca1-4ff1-47bf-9801-f8cf31b7a0e3.png)

**Comment by Duskhaven** [comment]
Fixed after restart
