### ISSUE TITLE
Zero crit when i equip mr protection paladin gear

### ISSUE THREAD

**Issue by chickensorry** [Duskhaven/Bug-Reports#959]
I get zero crit when i equip my gear as a prot paldin, normally 8.4 naked but now zero when i go into my gear. not sure why, but its the actual number i think because i dont crit at all. attached is a photo of my gear and stats
![nocritbug](https://user-images.githubusercontent.com/130619139/231619078-b54cb16d-98f6-4898-83aa-f3ba27a9805f.PNG)

**Comment by Duskhaven** [comment]
Relog.
