### ISSUE TITLE
can't go back to random dungeon if you switch to specific at 60

### ISSUE THREAD

**Issue by EndingInfinity** [Duskhaven/Bug-Reports#96]
at 60 if i switch my dungeon finder to specific i cannot switch back to random classic dungeon without relogging
![wow_BS6beekmkD](https://user-images.githubusercontent.com/127152963/224365163-670b7a0c-d123-4de4-9f4b-74700a1f4d25.png)

**Comment by Duskhaven** [comment]
This is fixed with the next Patch update.
