### ISSUE TITLE
T1 Monk DPS 4-pc set bonus not working

### ISSUE THREAD

**Issue by eMalum** [Duskhaven/Bug-Reports#961]
The T1 Monk (DPS) 4-pc set bonus, "Fist of the Tiger causes your next 3 Piercing Jabs to deal 50% additional damage as nature damage", does not appear to be functioning problem. We've tested several times and have seen zero increase to damage.

![image](https://user-images.githubusercontent.com/85034251/231637215-3a001173-b4c5-43c1-9c86-83a2cbecab21.png)

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://user-images.githubusercontent.com/123925176/231905456-f8932ef3-60de-453f-a98f-7747028cec24.png)

**Comment by killersoxfan** [comment]
Yeah, still doesnt work. Not sure where you're finding that buff at for Divine fist.
idk how so many other monks haven't even noticed this or talked about it. Just msg me in game and I'll test this stuff for you on my end if its fixed or not. -Demias

**Comment by eMalum** [comment]
Divine Fist buff does **NOT** appear after using Fist of the Tiger with the T1 (DPS) 4pc set bonus.

**Comment by eMalum** [comment]
![image](https://user-images.githubusercontent.com/85034251/232096234-d8952b51-a0b6-4979-ba41-c62a75b996a0.png)
