### ISSUE TITLE
T1 Monk DPS 2-pc Set Bonus applying too many debuffs

### ISSUE THREAD

**Issue by eMalum** [Duskhaven/Bug-Reports#962]
We've tested the fixed T1 Monk DPS 2-pc Set Bonus, the damage appears to be working properly. However, now there's a 2nd armor debuff being applied to the target; in this image below, you can see two armor debuffs being applied by one Monk. 

![image](https://user-images.githubusercontent.com/85034251/231638649-50009a42-ed50-4643-9e69-a19ad3fa4bb8.png)

**Comment by Duskhaven** [comment]
Fixed.
