### ISSUE TITLE
Feral Spirits/Magma totem hit/crit problem (Reopening)

### ISSUE THREAD

**Issue by Dova14** [Duskhaven/Bug-Reports#963]
I am reopening this bug report due to the last one being closed with an unsatisfying answer.

Currently Feral Spirits and Magma totem do not taking into account your hit (Nor does magma totem take into account your Spell Crit)
Meaning Feral spirits miss 8% and dodge 6.5% of the time (They take your hit for both their hit and expertise)
and magma totem is missing 17 - 20% of the time nad has a 5 - 10% crit rate

Last bugreport was closed due to noxx stating that they were missing because custom bosses/training dummies are level 66, which is untrue as my spells wouldnt have 100% hit rate with spell hit cap on them, it would have a 33% miss rate with 17% spell hit.  

Here are screenshots from a heroic molten core I did that shows my magma totem/feral spirits missing even tho i have spell hit cap + melee hit cap in that raid
![image](https://user-images.githubusercontent.com/93952514/231641872-ff0c4348-2729-441b-ab1b-17d17c9f9c75.png)
![image](https://user-images.githubusercontent.com/93952514/231641897-09ffdb5c-df55-4e07-8c38-d6f6f8841f56.png)
![image](https://user-images.githubusercontent.com/93952514/231641918-34bfc1f1-5808-4de3-9027-da0013a21701.png)
![image](https://user-images.githubusercontent.com/93952514/231641932-bd1843ea-4f80-49a1-8891-988fb23a66b9.png)
![image](https://user-images.githubusercontent.com/93952514/231642010-25dd16ab-17f0-4ec4-b1e2-ed755990bada.png)

also my base stats with 0 buffs for reference, so you can see my spell crit is way higher than what the magma totem is critting for  (Spell hit was capped via a boomie in party giving 3% spell hit)

**Comment by Duskhaven** [comment]
Fixed after restart
