### ISSUE TITLE
Hunter Mythic + armour 4 set bonus doesn't work for Melee

### ISSUE THREAD

**Issue by ghost** [Duskhaven/Bug-Reports#967]
As title says, the 4 set "Freezing arrow" bonus doesn't proc off melee specs or attacks.
Not sure if intentional but tooltip is vague when explaining this. Instead of saying "Has a chance to fire..." perhaps something like "Ranged attacks have a chance to fire..." will rectify this.
Personally I think it's great to have a ranged only bonus to incentivise spec diversity in hunters.

Thanks.

**Comment by Duskhaven** [comment]
Only procs from ranged attacks
