### ISSUE TITLE
Broodlord Lashlayer didn't drop head

### ISSUE THREAD

**Issue by Halyeth** [Duskhaven/Bug-Reports#969]
My group killed Broodlord Lashlayer in BWL Normal but his head didn't drop for the quest Only One May Rise. I opened a ticket in game and on discord and haven't received a response yet. It's a bug after all so I am reporting it on here too.

**Comment by Duskhaven** [comment]
Cannot replicate 
![image](https://user-images.githubusercontent.com/123925176/231908648-43189227-32ff-42c9-aea8-2cb977d58385.png)

Head only drops if the Quest is in your log.
