### ISSUE TITLE
Hunter Focused Fire

### ISSUE THREAD

**Issue by TekBytes-Reimer** [Duskhaven/Bug-Reports#976]
As of right now, the Hunter talent, Focused Fire, states that when using a 2h weapon you gain 10% damage.

I am testing this right now and even though I swap between 2h and 1h weapons, damage is not changing at all. I don't know if this is a talent that just has weird wording and is only supposed to apply to the pet, or if this isn't functioning properly?

Thanks for looking into this.

**Comment by Duskhaven** [comment]
Cannot replicate
