### ISSUE TITLE
Heroic Ragnaros Bug

### ISSUE THREAD

**Issue by Chromie-the-gnome** [Duskhaven/Bug-Reports#980]
While fighting on his submerge face, Ragnaros becomes untargetable and he still drops hammers on people, it makes the fight rng, obnoxious and 0 counterplay.

I'm pretty sure its not intended for him to throw hammer while submerged since he's non targetable and such.

**Comment by Duskhaven** [comment]
Intended. If the main tank stands before him during add phase you will see a difference.
