### ISSUE TITLE
Demonology Imp Gang

### ISSUE THREAD

**Issue by Ashaemage** [Duskhaven/Bug-Reports#981]
The imps from the Imp Gang talent in the Demonology warlock tree for some reason do not attack Ragnaros or the Wrath of Azshara bosses. During the Ragnaros fight, the imps will stand by the side of the character and will not engage or move until the add during submerge spawns. During the Wrath of Azshara fight, the imps will run down the center staircase but will run back up. They continue to do this during their entire duration without attacking. I believe something with the pathing is off, as hunter pet's and the warlock felguard pet is able to path to Ragnaros/Wrath of Azshara and attack.

**Comment by Duskhaven** [comment]
Fixed.
