### ISSUE TITLE
Talisman of Troll Divinity buff not working as intended.

### ISSUE THREAD

**Issue by dkmnllth** [Duskhaven/Bug-Reports#988]
Talisman of Troll Divinity gives a buff that is supposed to cause direct healing spells to give a buff to the target that increases healing done to said target by 18, stacking up to 5 times. The buff lasts 20 seconds, and the effect it applies is supposed to last for 10 seconds. However, for some reason, the effect that the trinket's buff is supposed to apply does not apply to any recipient of a direct healing spell. Tested by Karol (shaman) with max ranks of Lesser Healing Wave, Healing Wave, and Chain Heal on a warrior in party. The trinket is known by many healers to be broken and thus is never used by anyone and considered a waste of a runestone. There is already another ticket made 3 weeks ago, however I figured I'd make a more detailed ticket in the hopes that this bug is able to be replicated and addressed instead of ignored/closed.

**Comment by dkmnllth** [comment]
https://github.com/Duskhaven/Bug-Reports/issues/610#issue-1639982845 previous less detailed ticket, for reference

**Comment by Duskhaven** [comment]
Duplicate Issue https://github.com/Duskhaven/Bug-Reports/issues/610
