### ISSUE TITLE
Hunter M+8 Token Set is bugged.

### ISSUE THREAD

**Issue by Colette00** [Duskhaven/Bug-Reports#989]
The 5-Piece Set effect has zero improvements for Rapid Fire, i cant tell if this was changed or nerfed prior to this odd "0" behind Rapid Fire.
The Issue is this set got no Bonus effects useable by Tinkers, none at all.

Since this is an endgame set could i recommend it having this two possible set effects for Tinkers?

5P :  Machine Gun last 3 seconds longer.
5P:   Machine Gun cooldown timer is reduced by 8 secs.

This Skill even after the nerfs is the bread and butter skill for Tinkers.

**Comment by Duskhaven** [comment]
It was reduced as it was broken.
