### ISSUE TITLE
Paladin 1 h Sword weapon skills are gone

### ISSUE THREAD

**Issue by Abhraxxas242** [Duskhaven/Bug-Reports#99]
Its litterally as the title explains, my 1 h sword skills are gone, and i cant relearn them at the trainer, what do i do??
![Uploading WoWScrnShot_031023_191314.jpg…]()

**Comment by Abhraxxas242** [comment]
So, i might aswell delete him then? what shall i do?

**Comment by bedle** [comment]
Confirming this issue.
1H Sword weapon skill is missing from Tauren Paladins.
I visited Sword weapon skill trainers in Undercity and Silvermoon, they are missing the skill too so there is currently no way for Tauren Paladins to learn 1H Sword skill at all.

**Comment by Duskhaven** [comment]
This is fixed with the next restart. Make sure to visit the Innkeeper in Stormwind or Orgrimmar.
