### ISSUE TITLE
Do you read the tickets you closed after?

### ISSUE THREAD

**Issue by killersoxfan** [Duskhaven/Bug-Reports#991]
actually curious. Just want to know the process to respond. I've tested a lot of the closed bugs which are indeed still in game. example like priest having to take off and reequip a wand to get the sp from it. 
v diff issues of broken priest tier sets
https://github.com/Duskhaven/Bug-Reports/issues/961#issue-1665607780

**Comment by Duskhaven** [comment]
Works fine on our side.

![image](https://user-images.githubusercontent.com/123925176/232178695-cac1ad0f-cbcc-4991-a396-be7cea1d0c7b.png)

**Comment by killersoxfan** [comment]
That doesn't mean its fixed? wth man. I've already stopped playing after getting my tier because of this shit. T1 and devout/t2 set

**Comment by killersoxfan** [comment]
(I see the t1 4 set is fixed)

**Comment by killersoxfan** [comment]
![image](https://user-images.githubusercontent.com/128938821/232192979-696d9e08-3b28-421c-a632-a134dee703a9.png)
T2 still broken though. This was my 2nd cast while still in combat. No dot both times, and I dont get the crit bonus from lightform either. 6 set. I'd imagine the 8 set is broken too, but I don't have that set just yet.
The tank monk bit works, but I think it's under performing a lot.
