### ISSUE TITLE
Enhance Shaman Mythic Set

### ISSUE THREAD

**Issue by FruitburstNZ** [Duskhaven/Bug-Reports#992]
Shamans Mythic set Dreamwing (4) does not stack with Storm Infuser.
The 1 second Cooldown.
![Wow_poVNduzLBi](https://user-images.githubusercontent.com/130805587/232171850-e8e84fcf-e2a5-418f-814b-e56088f98234.png)
![Wow_RGKTvqROxK](https://user-images.githubusercontent.com/130805587/232171855-7306c2ba-7332-4592-b8f1-fd468666dd41.png)

**Comment by Duskhaven** [comment]
Intended.
