### ISSUE TITLE
Bloodfang 8 Set

### ISSUE THREAD

**Issue by Slicerndicer** [Duskhaven/Bug-Reports#994]
8 set of Bloodfang armor reduces the energy cost of Mutilate by 8 energy and no tooltip or anything says so. (which I would like it to keep pretty cool),

**Comment by Duskhaven** [comment]
Fixed.

**Comment by Slicerndicer** [comment]
Fixed how if you don't mind me asking

**Comment by Slicerndicer** [comment]
> Fixed.
Fixed how if you don't mind me asking
