### ISSUE TITLE
Tauren Paladins unable to use polearms

### ISSUE THREAD

**Issue by Lujansh** [Duskhaven/Bug-Reports#999]
Paladins should be able to learn how to use polearms at lvl 20 for 90s iirc, not the case for the best race in the game.

**Comment by Duskhaven** [comment]
Taurens automatically start with the Polearm Skill

![image](https://user-images.githubusercontent.com/123925176/236578796-16910778-e0ea-4182-a1f9-248da7fc7d7c.png)
